[enhance] Provision to set default mode of payment for the POS in POS profile
frappe/erpnext pull request #10062
Opened 2017-07-24 12:23 UTC by rohitwaghchaure

2017-07-25 05:44 UTC, nabinhait requested changes

2017-07-25 05:44 UTC, nabinhait commented on erpnext/accounts/doctype/pos_profile/pos_profile.py
> +			default = [d.default for d in self.payments if d.default]
default is a python keyword, use 'default_mode_of_payment'?

2017-07-25 10:25 UTC, rohitwaghchaure commented on erpnext/accounts/doctype/pos_profile/pos_profile.py
> +			default = [d.default for d in self.payments if d.default]
Fixed!

2017-07-26 13:12 UTC, mbauskar approved these changes

2017-07-26 13:15 UTC, mbauskar requested changes
@rohitwaghchaure ,

Also add the documentation and test cases !!

2017-07-27 13:48 UTC, rohitwaghchaure commented
Fixed!

2017-07-28 15:40 UTC, merged