Fee redesign in school domain.
frappe/erpnext pull request #10087
Opened 2017-07-25 12:03 UTC by manassolanki

2017-08-02 09:41 UTC, nabinhait commented
Change the label of "Debit to" to "Academic Receivable Account" and "Credit To" to "Income Account"

<img width="461" alt="screen shot 2017-08-02 at 2 42 13 pm" src="https://user-images.githubusercontent.com/836784/28867400-a186753c-7793-11e7-9bb8-1991657611a5.png">

---

Change the  label to Total Amount per Student, now it is confusing.

<img width="299" alt="screen shot 2017-08-02 at 2 44 12 pm" src="https://user-images.githubusercontent.com/836784/28867398-a1818afe-7793-11e7-97d8-25fbee408b52.png">

---

If no contact email, while creating payment request from Fee, it gives error

<img width="770" alt="screen shot 2017-08-02 at 2 54 40 pm" src="https://user-images.githubusercontent.com/836784/28867397-a180f12a-7793-11e7-9486-ee332b262044.png">

---

While creating Payment from Fee, getting this error.

<img width="797" alt="screen shot 2017-08-02 at 3 01 45 pm" src="https://user-images.githubusercontent.com/836784/28867396-a17c6420-7793-11e7-8e72-9c98fda98795.png">

2017-08-02 10:05 UTC, nabinhait requested changes

2017-08-02 10:05 UTC, nabinhait commented on erpnext/schools/doctype/fees/fees.py
> +			pr = make_payment_request(dt="Fees", dn=self.name, recipient_id=self.contact_email,
It gives error if no contact_email

2017-08-02 10:05 UTC, nabinhait commented on erpnext/schools/doctype/fees/fees.py
> +							"account": self.debit_to,
extra indentation?

2017-08-02 10:05 UTC, nabinhait commented on erpnext/schools/doctype/fees/fees.py
> +def get_payment_entry(dt, dn, bank_account=None):
Can't it be commonfied with `https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/payment_entry/payment_entry.py#L667`?

2017-08-02 10:05 UTC, nabinhait commented on erpnext/schools/doctype/fees/fees.json
> +   "fieldname": "include_payment",
What is the use of this?

2017-08-02 10:08 UTC, manassolanki commented on erpnext/schools/doctype/fees/fees.json
> +   "fieldname": "include_payment",
This will be used to send the payment request if we are creating the fee records from the fee schedule.

2017-08-30 08:12 UTC, rmehta commented
@manassolanki please rebase and fix.

2017-09-08 11:07 UTC, manassolanki commented
- [ ] Field rename
- [ ] contact email
- [ ] send email input in schedule
- [ ] get query for student group
- [ ] Read only for child table

2017-09-19 11:53 UTC, nabinhait commented
Merged manually from console

2017-09-19 11:53 UTC, closed without merging