[ui-testing] added test for production order
frappe/erpnext pull request #10138
Opened 2017-07-27 13:20 UTC by codingCoffee

2017-07-28 09:04 UTC, rmehta requested changes

2017-07-28 09:04 UTC, rmehta commented on erpnext/setup/doctype/company/test_company_production.js
> +QUnit.test("Test: Company", function (assert) {
if you are writing multiple UI tests for a doctype, add it in a `tests` folder inside the doctype

2017-07-28 12:52 UTC, codingCoffee commented
created the tests folder inside the company doctype, since there were multiple tests!

2017-07-31 05:32 UTC, merged

2017-07-31 05:32 UTC, rmehta commented
- [ ] also test child table
- [ ] "Start" and "Finish" buttons -> Stock Entries