Allow Sidebar Menu search using text from Item Name of a record
frappe/erpnext pull request #10131
Opened 2017-07-27 09:36 UTC by creamdory

From PR in frappe repo https://github.com/frappe/frappe/pull/3798#pullrequestreview-52562113 as requested changes.

2017-07-27 10:05 UTC, rmehta commented
- [ ] Test Case
- [ ] Screenshots

2017-07-28 02:42 UTC, creamdory commented
Edited the code to automatically allow item_name search for doctypes with 'items' field.

2017-07-28 09:01 UTC, rmehta requested changes
Also write a simple test case to check this function works!

2017-07-28 09:01 UTC, rmehta commented on erpnext/controllers/website_list_for_contact.py
> +def get_trans_data_list(doctype, txt, filters, limit_start, limit_page_length=20, ignore_permissions=False,fields=None, order_by=None):
no shortnames like `trans_data` - use `get_list_for_transactions`

2017-07-28 09:04 UTC, creamdory commented on erpnext/controllers/website_list_for_contact.py
> +def get_trans_data_list(doctype, txt, filters, limit_start, limit_page_length=20, ignore_permissions=False,fields=None, order_by=None):
Ok sure @rmehta , I'll make the changes and make a simple test case. Thanks! I'll make update once ready.

2017-08-01 10:43 UTC, mbauskar commented
@creamdory,

Thanks for contributing,

Please check and fix travis build issues also please add a simple test case for the PR, Closing the PR for now but you can reopen it.

2017-08-01 10:46 UTC, creamdory commented
Sure @mbauskar , I am still preparing the test case for this. I'll let you know once ready and will re-open this one. Thanks!

2017-08-03 01:50 UTC, closed without merging