[Fix] Error in sales invoice and POS if customer group not defined in the customer
frappe/erpnext pull request #10148
Opened 2017-07-28 06:09 UTC by rohitwaghchaure

```
Traceback (most recent call last): File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/app.py", line 56, in application response = frappe.handler.handle() File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/handler.py", line 21, in handle data = execute_cmd(cmd) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/handler.py", line 52, in execute_cmd return frappe.call(method, **frappe.form_dict) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/__init__.py", line 922, in call return fn(*args, **newargs) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs doc.save() File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 230, in save return self._save(*args, **kwargs) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 263, in _save self.run_before_save_methods() File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 772, in run_before_save_methods self.run_method("validate") File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 666, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 887, in composer return composed(self, method, *args, **kwargs) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 870, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/frappe/benches/bench-2017-07-27/apps/frappe/frappe/model/document.py", line 660, in fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 56, in validate super(SalesInvoice, self).validate() File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/controllers/selling_controller.py", line 33, in validate super(SellingController, self).validate() File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate super(StockController, self).validate() File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/controllers/accounts_controller.py", line 47, in validate self.validate_due_date() File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/controllers/accounts_controller.py", line 125, in validate_due_date validate_due_date(self.posting_date, self.due_date, "Customer", self.customer, self.company) File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/accounts/party.py", line 302, in validate_due_date default_due_date = get_due_date(posting_date, party_type, party, company) File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/accounts/party.py", line 267, in get_due_date credit_days_based_on, credit_days = get_credit_days(party_type, party, company) File "/home/frappe/benches/bench-2017-07-27/apps/erpnext/erpnext/accounts/party.py", line 287, in get_credit_days frappe.db.get_value("Customer Group", customer_group, ["credit_days_based_on", "credit_days"]) TypeError: 'NoneType' object is not iterable
```

2017-07-28 06:24 UTC, nabinhait requested changes

2017-07-28 06:24 UTC, nabinhait commented on erpnext/accounts/doctype/sales_invoice/pos.py
> +	customer_doc.customer_group = frappe.db.get_single_value('Selling Settings', 'customer_group') or _("Government")
What if government does not exists?

I think we should force user to enter default customer group and territory in selling settings, even better if it is specified in POS Profile.

2017-07-28 06:24 UTC, nabinhait commented on erpnext/accounts/party.py
> +		due_date = today()
Today is not realistic if it's not a POS kind of sale. I think it should be entered manually.

2017-07-28 09:51 UTC, merged

2017-07-28 11:58 UTC, shanmukhasai6 commented
In this regard can we assign a default customer group, so that the new customers go into the default group

2017-07-31 16:40 UTC, Olawale1 commented
Hi,

Facing the same issue. Initially, invoices weren't getting synced from the POS at all and this error kept popping up. I then manually set the Customer Group in the Customer list. After this, the invoices got synced but the records are still in the Customer Queue!

Hope this will be rectified in the patch too

Thanks