[Fix] Timesheet Company Issue
frappe/erpnext pull request #10165
Opened 2017-07-28 12:28 UTC by rohitwaghchaure

2017-07-28 15:24 UTC, nabinhait requested changes

2017-07-28 15:24 UTC, nabinhait commented on erpnext/manufacturing/doctype/production_order/production_order.py
> +	timesheet.company = frappe.db.get_value('Production Order', production_order, 'company')
Pass the company as an argument, instead of getting from db.

2017-07-29 09:19 UTC, rohitwaghchaure commented on erpnext/manufacturing/doctype/production_order/production_order.py
> +	timesheet.company = frappe.db.get_value('Production Order', production_order, 'company')
Fixed

2017-07-29 12:50 UTC, nabinhait approved these changes

2017-07-29 12:50 UTC, merged