Advance payment patch
frappe/erpnext pull request #10178
Opened 2017-07-30 22:44 UTC by Olawale1

Hi @rmehta 

Trust you're doing great. I've added all the basic components for the Advance Payment functionality

Changes to PY file:

1. Added whitelist method for creating Advance Payment entry 
2. Added whitelist method for calculating Total Advance Paid 

Changes to JS file:

1. Added script and made relevant changes for Advance Payment button
2. Added script for calling Total Advance Paid method
3. Added script to auto-fetch Default Advance Account from Company master

Changes to JSON file:

1. Added field for Default Advance Account in Company master
2. Added field for Advance Payment Required in Expense Claim form
3. Added field for Total Advance Paid in Expense Claim form

Changes to Documentation

1. Added 'Managing Advance Payments' section to the Expense Claim documentation

Screenshots of End Results:

![company_advance_account](https://user-images.githubusercontent.com/9269337/28572672-e6dc877a-713f-11e7-9998-6328457dec8e.png)

![advance_payment_required](https://user-images.githubusercontent.com/9269337/28495539-b5e3d622-6f47-11e7-85ea-046c4c240d21.png)

![make_advance_payment](https://user-images.githubusercontent.com/9269337/28495544-c0a1a35a-6f47-11e7-820d-673a857f7ec9.png)

![advance payment patch2](https://user-images.githubusercontent.com/9269337/28495552-f8c7081a-6f47-11e7-96ed-c0465a687d7b.png)

![advance payment patch3](https://user-images.githubusercontent.com/9269337/28495553-0340cdbc-6f48-11e7-9134-3a20f54090a3.png)

Thanks

Kind regards,

2017-07-31 05:44 UTC, rmehta requested changes

2017-07-31 05:44 UTC, rmehta commented on erpnext/hr/doctype/expense_claim/expense_claim.js.save
> +// Copyright (c) 2015, Frappe Technologies Pvt. Ltd. and Contributors
Please remove this file!

2017-07-31 08:30 UTC, Olawale1 commented
I've removed the stray file... not sure how it got there in the first place :)

Thanks

2017-08-01 11:02 UTC, mbauskar commented
@Olawale1,

Thank you for contribution,

please check and fix the Travis issues? Closing the PR for now

2017-08-01 11:02 UTC, closed without merging

2017-08-01 11:58 UTC, Olawale1 commented
Hi @mbauskar 

Thanks for your feedback but I'm not sure the Travis issue had anything to do with my commits. I believe it had something to do with the Selling module

Thanks