[ui-test] completed tests for manufacturing
frappe/erpnext pull request #10218
Opened 2017-08-01 15:36 UTC by codingCoffee

- modified production_order to include child table assertions as requested for in pull request #10138 
- tested the entire production order process
- issue #9986 can be closed after this PR is merged

2017-08-02 09:03 UTC, codingCoffee commented
made the requested changes: 
- removed css selectors and used cur_frm

2017-08-02 11:42 UTC, rmehta requested changes

2017-08-02 11:42 UTC, rmehta commented on erpnext/manufacturing/doctype/production_order/test_production_order.js
> +	let required_source_warehouse = (i) => {
why put in a function?

2017-08-03 16:52 UTC, codingCoffee commented
@rmehta made the requested changes: 
- removed the functions

2017-08-04 05:20 UTC, merged