Advance Payment Patch
frappe/erpnext pull request #10220
Opened 2017-08-02 00:40 UTC by Olawale1

Hi

Trust you're doing great. I've added all the basic components for the Advance Payment functionality

Changes to PY file:

1. Added whitelist method for creating Advance Payment entry 
2. Added whitelist method for calculating Total Advance Paid 

Changes to JS file:

1. Added script and made relevant changes for Advance Payment button
2. Added script for calling Total Advance Paid method
3. Added script to auto-fetch Default Advance Account from Company master

Changes to JSON file:

1. Added field for Default Advance Account in Company master
2. Added field for Advance Payment Required in Expense Claim form
3. Added field for Total Advance Paid in Expense Claim form

Changes to Documentation

1. Added 'Managing Advance Payments' section to the Expense Claim documentation

Screenshots of End Results:

![company_advance_account](https://user-images.githubusercontent.com/9269337/28572672-e6dc877a-713f-11e7-9998-6328457dec8e.png)

![advance_payment_required](https://user-images.githubusercontent.com/9269337/28495539-b5e3d622-6f47-11e7-85ea-046c4c240d21.png)

![make_advance_payment](https://user-images.githubusercontent.com/9269337/28495544-c0a1a35a-6f47-11e7-820d-673a857f7ec9.png)

![advance payment patch2](https://user-images.githubusercontent.com/9269337/28495552-f8c7081a-6f47-11e7-96ed-c0465a687d7b.png)

![advance payment patch3](https://user-images.githubusercontent.com/9269337/28495553-0340cdbc-6f48-11e7-9134-3a20f54090a3.png)

Thanks

Kind regards,

2017-08-02 03:53 UTC, rmehta commented
@Olawale1 can you check the codacy issue?

2017-08-02 03:54 UTC, Olawale1 commented
There's only 1 Codacy error left (no unused vars) but the script needs that line in the code

Thanks

2017-08-02 03:59 UTC, rmehta commented
Just remove the `var doc =` part and let the sync remain

2017-08-02 05:00 UTC, Olawale1 commented
Thanks a lot @rmehta 

I've fixed it :)

2017-08-04 10:20 UTC, mbauskar requested changes
@Olawale1,

Thanks for the PR,

Please see my comments, Also can you please add simple tests cases ?

2017-08-04 10:20 UTC, mbauskar commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +					"docname": cur_frm.doc.name,
no need to use the `cur_frm.doc` just use the `doc.name`

2017-08-04 10:20 UTC, mbauskar commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +					cur_frm.set_value("total_advance_paid", r.message.amt);
`cur_frm` will deprecated, please use the `frm` instead

2017-08-04 10:47 UTC, Olawale1 commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +					cur_frm.set_value("total_advance_paid", r.message.amt);
Hi @mbauskar 

Thanks for the helpful review. Not sure how to add Test Cases. Could you give some guidance on this?

Kind regards,

2017-08-06 23:38 UTC, Olawale1 commented
Hi

I've updated the JS code by removing `cur_frm` which is soon to be deprecated. Would appreciate assistance with Test Cases

Thanks

2017-08-07 16:40 UTC, mhbu50 commented
Good Job @Olawale1  
you can do same as this : 
https://github.com/frappe/erpnext/blob/c54510660e8c7be232862f8175334c40de2e65df/erpnext/schools/doctype/instructor/test_instructor.js

2017-08-15 10:40 UTC, Olawale1 commented
Hi @mhbu50 

Sorry I missed replying this. Thanks for your encouragement and assistance :)

I've checked the reference but don't see how to adapt that for this PR. I'll require some more detailed guidance for this

BTW if the purpose is to confirm the feature works, won't it suffice to use screenshots or recording?

Thanks

2017-08-15 11:09 UTC, tundebabzy commented
No. The videos might prove that your code works right but it won't tell us when code in another part of the software breaks your code later.

2017-08-15 11:46 UTC, Olawale1 commented
Oh, I see... makes sense. In that case, this should actually be a kind of automated process

Still require some assistance here

Thanks

2017-08-22 05:43 UTC, rmehta commented
@nabinhait please clean and merge this...

2017-08-23 17:37 UTC, Olawale1 commented
Thanks plenty

2017-08-31 14:59 UTC, Olawale1 commented
Thanks a lot @nabinhait

2017-10-06 11:43 UTC, tundebabzy commented
#10632 reverted

2017-11-13 13:05 UTC, closed without merging