[Enhancement] Notify Expense Claim Approver whenever Expense Claim is created
frappe/erpnext pull request #10248
Opened 2017-08-02 12:14 UTC by KanchanChauhan

2017-08-03 05:29 UTC, nabinhait requested changes

2017-08-03 05:29 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +			self.notify_expense_claim_approver()
So, this email will go on every save of the Expense Claim, which is not so good. Add a button instead to send the email.

2017-08-03 05:29 UTC, nabinhait commented
Reopen after fixing.

2017-08-03 06:05 UTC, KanchanChauhan commented
Button added to notify approver.

<img width="454" alt="screen shot 2017-08-03 at 11 34 21 am" src="https://user-images.githubusercontent.com/16913064/28908180-bedd0bda-783f-11e7-95de-33227f6ce55a.png">

2017-08-03 06:08 UTC, nabinhait commented
@KanchanChauhan Please add a custom button in the toolbar, it will be shown only in draft mode and if status is Draft.

2017-08-03 07:10 UTC, KanchanChauhan commented
<img width="512" alt="screen shot 2017-08-03 at 12 39 44 pm" src="https://user-images.githubusercontent.com/16913064/28910073-d9967fac-7848-11e7-8411-b04f6139cc14.png">

2017-08-04 08:01 UTC, mbauskar commented
@KanchanChauhan,

Thanks for PR.

Travis checks failed please check and fix the test cases. Closing the PR for now but you can reopen it.

2017-08-07 12:20 UTC, rmehta commented
Why not Email Alert?

2017-08-08 09:16 UTC, nabinhait commented
@rmehta Email Alert will go every time on saving the Expense Claim, which is not desired.

2017-08-08 09:19 UTC, nabinhait requested changes
Also please add a screenshot of the email

2017-08-08 09:19 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +			frm.add_custom_button(__('Notify Expense Claim Approver'),
Can we change the label to "Notify Approver"?

2017-08-08 09:19 UTC, rmehta commented
@nabinhait I have added a feature to add a flag in Email Alert (like "Email Sent"). If its true, then it will not re-sent 😄

2017-08-08 09:19 UTC, closed without merging

2017-08-08 09:21 UTC, nabinhait commented
@rmehta Thats great 👍 But in this case, user can add more expenses after first saving, we really don't know when it is finalised.

2017-08-08 09:22 UTC, rmehta commented
Then set a property and trigger the email alert. the message should be configurable...