[Fix] Getting an error cost center is not defined in the purchase receipt, even if it's defined in the company
frappe/erpnext pull request #10320
Opened 2017-08-08 08:59 UTC by rohitwaghchaure

2017-08-08 09:28 UTC, nabinhait reviewed
The error message is coming while reposting GLE from landed cost voucher. Why it did not come on the first place on submission of PR?

2017-08-08 09:28 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +						"cost_center": d.cost_center or erpnext.get_default_cost_center(self.company),
Why setting default cost center here? Instead, in validate we should set default cost center if missing.

2017-08-08 09:28 UTC, nabinhait commented
closing, please reopen after fixing

2017-08-08 10:36 UTC, rohitwaghchaure commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +						"cost_center": d.cost_center or erpnext.get_default_cost_center(self.company),
Fixed!

2017-08-08 10:41 UTC, rohitwaghchaure commented
In Purchase receipt no entry has been made against the expense head.
During submission of landed cost voucher the amount has credited against expense account expenses_included_in_valuation and use has not defined the cost center in PR and therefore system not allowing to submit the landed cost voucher

2017-08-08 11:51 UTC, nabinhait requested changes

2017-08-08 11:51 UTC, nabinhait commented on erpnext/accounts/doctype/gl_entry/gl_entry.py
> +				self.cost_center = erpnext.get_default_cost_center(self.company)
I don't think it is a good idea to set a default cost center if not specified in the form. We should force users to set cost center in the transactions itself. We are already setting default cost center there while create a new transaction.

In current problem's context, we should edit the error message to direct user to take necessary action. In this case, PR should be amended and cost center should be entered there.

In the below message, we can change like:

```frappe.throw(_("{0} {1}: Cost Center is required for 'Profit and Loss' account {2}. Please edit/amend the {3} to set the Cost Center.")
  					.format(self.voucher_type, self.voucher_no, self.account, self.voucher_type))
```

2017-08-10 06:02 UTC, nabinhait approved these changes

2017-08-10 06:03 UTC, merged