While fetching items from another doctype create blank row at item child table in Material Request (#10339)
frappe/erpnext pull request #10378
Opened 2017-08-11 11:46 UTC by tundebabzy

![peek 2017-08-11 01-17](https://user-images.githubusercontent.com/818803/29211761-e3c10e70-7e92-11e7-8930-c527af8e6382.gif)

2017-08-14 11:38 UTC, rmehta requested changes

2017-08-14 11:38 UTC, rmehta commented on erpnext/public/js/controllers/buying.js
> +
why global functions? add the functions in the same scope

2017-08-14 13:16 UTC, tundebabzy commented on erpnext/public/js/controllers/buying.js
> +
Moved the function to the callback scope

2017-08-16 07:55 UTC, merged

2017-08-16 08:08 UTC, rmehta commented on erpnext/public/js/controllers/buying.js
> +				if (first_row_is_empty(frm.doc.items)){
inconsitent whitespace...