Getting Opportunity Items in Request for Quotation Document by Clicking "Get Items From" button
frappe/erpnext pull request #10546
Opened 2017-08-24 13:12 UTC by AravindPranera

In Request for Quotation document when we click Get items from button, it will show dropdown consists of Opportunity along with Material Request and Possible Supplier. By choosing Opportunity, it will display a dialog box of Opportunity List with Check box. We can select the Opportunity list and click on "Get Items" . We can get Opportunity list items in Request for Quotation Document.

2017-08-28 06:49 UTC, mbauskar commented
@AravindPranera ,

Thanks for contributing!

Our contribution guidelines require that you add a screenshot showing that your proposed change works with an example also can you please check the travis and codecy build. This pull request will be closed, but you can re-open it after adding the requested screenshot.

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

2017-08-28 11:11 UTC, AravindPranera commented
Here is a screenshots.

![image](https://user-images.githubusercontent.com/28756911/29771056-945752b0-8c0f-11e7-928f-cb224a523c1d.png)
![image](https://user-images.githubusercontent.com/28756911/29771087-b180b322-8c0f-11e7-98c6-f75e5a5f00f0.png)
![image](https://user-images.githubusercontent.com/28756911/29771093-b8d62166-8c0f-11e7-9fad-3bac9b9141c2.png)

2017-09-01 11:30 UTC, rmehta requested changes

2017-09-01 11:30 UTC, rmehta commented on erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
> -	get_suppliers_button: function (frm) {
why remove this?

2017-09-01 11:30 UTC, rmehta commented on erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
> +            this.frm.add_custom_button(__('Opportunity'),
whitespace!

2017-09-01 11:30 UTC, rmehta commented on erpnext/crm/doctype/opportunity/opportunity.py
> -		if not self.with_items:
why change this?

2017-09-01 11:37 UTC, AravindPranera reviewed
I have added comments for your review.

2017-09-01 11:37 UTC, AravindPranera commented on erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
> -	get_suppliers_button: function (frm) {
Sorry, Add this line.

2017-09-01 11:37 UTC, AravindPranera commented on erpnext/buying/doctype/request_for_quotation/request_for_quotation.js
> +            this.frm.add_custom_button(__('Opportunity'),
Remove the whitespace.

2017-09-01 11:37 UTC, AravindPranera commented on erpnext/crm/doctype/opportunity/opportunity.py
> -		if not self.with_items:
Add this line too.

2017-09-14 04:34 UTC, saurabh6790 commented
@AravindPranera Travis and Codacy are failing! Please fix them and reopen the PR.

2017-09-18 11:40 UTC, rmehta commented
@AravindPranera you still need to add back the functions you may have accidentally deleted. Can you fix this?

2017-09-18 12:12 UTC, AravindPranera commented
​I have committed the files with all functions, kindly merge it.

Thanks,
Aravind.​

Pranera Services & Solutions.
Tiruppur.


On Mon, Sep 18, 2017 at 5:10 PM, Rushabh Mehta <notifications@github.com>
wrote:

> @AravindPranera <https://github.com/aravindpranera> you still need to add
> back the functions you may have accidentally deleted. Can you fix this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/frappe/erpnext/pull/10546#issuecomment-330195048>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AbbLr0upuS8SzTfzU9OrflrqczqgZVHtks5sjlapgaJpZM4PBW_H>
> .
>

2017-09-21 10:22 UTC, merged

2017-09-21 11:39 UTC, AravindPranera commented
Thanks,
Aravind.

Pranera Services & Solutions.
Tiruppur.


On Thu, Sep 21, 2017 at 3:52 PM, Nabin Hait <notifications@github.com>
wrote:

> Merged #10546 <https://github.com/frappe/erpnext/pull/10546>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/frappe/erpnext/pull/10546#event-1259104952>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AbbLr0kTW0VnG9nCrY29B5fjarYLtkuzks5skjjugaJpZM4PBW_H>
> .
>

2017-09-21 11:45 UTC, rmehta commented
👍  for first PR 😄