[Enahance] Update variants fields defined in the Item Varianst Settings, if template updated
frappe/erpnext pull request #10595
Opened 2017-08-29 12:47 UTC by rohitwaghchaure

2017-08-31 09:49 UTC, GiorgioKN commented
Hi,
thank you very good news.
Could you please tell me when this will be available for the cloud version?

2017-08-31 10:01 UTC, rohitwaghchaure commented
Hi @GiorgioKN 

Currently it's under review and we'll release it once PR is merged!

2017-09-05 07:11 UTC, rmehta requested changes

2017-09-05 07:11 UTC, rmehta commented on erpnext/config/stock.py
> +					"name": "Item Variant Settings",
this should be in settings!

2017-09-05 07:12 UTC, rmehta commented on erpnext/config/stock.py
> +					"name": "Item Variant Settings",
also maybe add a button in Item (if it is a variant) for Variant Settings

2017-09-07 05:41 UTC, rmehta commented
patch + default settings on install.

2017-09-18 11:15 UTC, rmehta approved these changes

2017-09-21 10:12 UTC, nabinhait commented
merged from console

2017-09-21 10:12 UTC, closed without merging