feature/custom payroll frequency bimonthly 10 25
frappe/erpnext pull request #10660
Opened 2017-09-04 07:16 UTC by dualcnhq

- add dates for bimonthly payroll frequency but on month dates 10th of the month and 25th of the month

2017-09-18 11:18 UTC, rmehta commented
@dualcnhq Thanks for your interest in contributing!

Please check my comments

[ ] can we have the dates selectable for bi-monthly?
[ ] add a test case to see if your features work
[ ] update the documentation to reflect the new changes you are proposing.

Detailed contribution guidelines here: https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

2017-09-18 11:18 UTC, rmehta requested changes

2017-09-18 11:18 UTC, rmehta commented on erpnext/hr/doctype/process_payroll/process_payroll.py
> +	if payroll_frequency == "Bimonthly(10-25)":
there should always be a space before bracket.  `Bimonthly (10-25)`

2017-09-18 11:18 UTC, rmehta commented on erpnext/hr/doctype/process_payroll/process_payroll.py
> +		print 'relativedelta next month: ', nmd
print?

2017-11-13 13:14 UTC, nabinhait commented
@dualcnhq Closing the pull request for now, please reopen after fixing as per Rushabh's suggestion.

2017-11-13 13:14 UTC, closed without merging