[Feature] Item Variant Creation from Quick Entry
frappe/erpnext pull request #10775
Opened 2017-09-13 14:02 UTC by suyashphadtare

- Creation of item variants from quick entry(considering item template already created).

- Already sent frappe PR - [Enable overriding Quick Entry in custom app](https://github.com/frappe/frappe/pull/3519)

![out123](https://user-images.githubusercontent.com/10596607/27336869-77e063ee-55ee-11e7-8ceb-b9dd6e3b09b8.gif)

2017-09-13 15:16 UTC, mbauskar commented
@patilsangram,

Please check and fix the codecy issue, Closing the PR, for now, please reopen the PR once the issue s are fixed.

2017-09-14 06:59 UTC, mnatalia commented
please check that all your labels have possibility to be translated

2017-09-18 11:22 UTC, rmehta commented
@suyashphadtare thanks for the contribution!

Please fix translations

Can you also write a simple test case?

2017-09-18 11:22 UTC, rmehta requested changes

2017-09-18 11:22 UTC, rmehta commented on erpnext/public/js/templates/variant_attribute.html
> +			<td>Page No.</td>
make this translatable `{{ __("Page No") }}`

apply to all labels

2017-09-19 05:50 UTC, patilsangram commented
@rmehta , @mnatalia  Thanks for the suggestions, I have fixed translation. I will try test cases for Item variant creation from quick entry.

Thanks,

2017-09-20 13:55 UTC, patilsangram commented
1. Moved item UI test under stock 

2. Added UI tests for 

- Item Attribute

-  Item template

- Item variant from quick entry

2017-11-13 06:40 UTC, rmehta commented
https://github.com/frappe/erpnext/pull/11535

2017-11-13 06:40 UTC, closed without merging