Add Items Variants Attributes columns to Stock Balance Report
frappe/erpnext pull request #11048
Opened 2017-10-04 10:48 UTC by brownharryb

Show Item attributes in stock balance report for item variants if they exist.

![stock_balance_report](https://user-images.githubusercontent.com/17238907/31172016-d3985828-a8f9-11e7-9cca-726bc90a07bb.png)

2017-10-04 12:33 UTC, nabinhait commented
What if there are many attributes (lets say 50 or more)? The report will not look good. How about adding one single column which will show all the attribute values for that item.

2017-10-04 20:06 UTC, ckosiegbu commented
@brownharryb Or perhaps a filter at the top that lets us narrow down using select fields for the attribute and attribute value respectively.

2017-10-05 08:55 UTC, nabinhait commented
@brownharryb Let's make it optional by adding a filter checkbox "Show Item Variant Attributes". If checked, then add those columns, default should be unchecked.

2017-10-05 08:57 UTC, brownharryb commented
@nabinhait 
Valid point, but say a client wants to filter based on multiple attributes eg "I want to see all items in my warehouse with colour=blue and length=456m", putting all in a single column might not be that practical in terms of filtering

I have two proposals

- Add a single input box that displays attributes columns based on comma separated attributes
![comma_sep_attr](https://user-images.githubusercontent.com/17238907/31218738-29a4d124-a9b3-11e7-8d9b-00e82d9aa41f.png)
![comma_sep_attr2](https://user-images.githubusercontent.com/17238907/31218741-2d5c7cd6-a9b3-11e7-8201-83b1c2a8ddd7.png)

- Make it a frappe list style filtering
![comma_sep_attr3](https://user-images.githubusercontent.com/17238907/31218791-48be64c6-a9b3-11e7-8dd4-5043a12f6c0b.png)

Would appreciate a feedback
Regards

2017-10-05 09:19 UTC, nabinhait commented
@brownharryb I understand your point, basic purpose of those columns is filtering. So, keep separate columns for each attributes. But those columns will be added only if checked "Show Item Variant Attributes" filter.

2017-10-05 09:26 UTC, nabinhait requested changes

2017-10-05 09:26 UTC, nabinhait commented on erpnext/stock/report/stock_balance/stock_balance.py
> +		report_data += [get_variant_attr_val(item,i) for i in variants_attributes]
Doing a query for each row is not good. Instead create a dict for all item attribute values outside for loop and then use that dict to get attribute value.

```
{
  item1: {
    'color': 'blue',
    'size': 'XL'
  },
  item2: {
    'size': 'L',
    'pattern': 'Stripe'
  }
}
```

For example, check https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/report/sales_register/sales_register.py#L28

2017-10-22 22:09 UTC, brownharryb commented
Hi @nabinhait 
This has been redone 
https://github.com/frappe/erpnext/pull/11278

2017-10-22 22:09 UTC, closed without merging