Attendance check in
frappe/erpnext pull request #11054
Opened 2017-10-04 18:30 UTC by shridarpatil

Activate checkin / checkout in attendance control panel / HR settings.
On login, if not checked in, show popup to allow checkin

https://github.com/frappe/erpnext/issues/428

2017-10-05 05:48 UTC, rmehta commented
@shridarpatil nice! can you add some docs, screenshots?

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

2017-10-07 04:58 UTC, shridarpatil commented
@rmehta I will add the docs and screenshots once I complete the full flow.
I want some help to create a pop up on logout.

2017-10-15 18:16 UTC, shridarpatil commented
![attendance](https://user-images.githubusercontent.com/11792643/31587648-fe50442e-b202-11e7-8d22-4e22f5c03e0d.gif)

2017-10-18 05:41 UTC, rmehta requested changes

2017-10-18 05:41 UTC, rmehta commented on erpnext/hr/doctype/attendance/attendance.py
> +	employee_details = employee()
User the Frappe ORM

```
frappe.db.get_list('Employee', ['name', 'employee_name'], 
  or_conditions=dict(user_id=frappe.session.user, employee_mail=frappe.session.user))
```

It will also automatically check for permissions. Otherwise if you this will be open to exploit by anyother user who does not have rights on the employee

2017-10-18 05:41 UTC, rmehta commented on erpnext/hr/doctype/attendance/attendance.py
> +def employee():
try avoiding helper functions like these.. use the ORM - see below

2017-10-18 05:41 UTC, rmehta commented on erpnext/hr/doctype/attendance/attendance.py
> +		""".format(employee_details.name)
Never use .format for SQL queries, leaves it open to injection, again use ORM :)

```
from frappe.utils import nowdate
frappe.get_value('Attendance', dict(employee=employee_details.name, attendance_date=nowdate()))
```

2017-10-18 05:41 UTC, rmehta commented on erpnext/public/js/checkin_checkout_attendance.js
> +          {"fieldtype": "Button", "label": __("Check-In"), "fieldname": "check_in"},
use simpler labels `Mark Attendance`

2017-10-18 05:41 UTC, rmehta commented on erpnext/hr/doctype/hr_settings/hr_settings.json
> +   "description": "If checked Employee add use check-in and check-out to mark attendance",
avoid descriptions, keep the label as "Ask for Attendance on Login"

Also avoid the word "check in", you are basically marking attendance

2017-10-18 05:41 UTC, rmehta commented on erpnext/public/js/checkin_checkout_attendance.js
> +        title: __("Check-in Attendance "),
`"Mark Attendance"`

2017-11-10 08:54 UTC, rmehta commented
@shridarpatil are you still working on this?

2017-11-10 08:56 UTC, rmehta commented
A better design would be to add a hook on the `login` event and mark attendance if its an employee? Does that work?

Please fix and re-open

2017-11-10 08:56 UTC, closed without merging

2018-02-03 14:59 UTC, shridarpatil commented
I think on the`login` event we should not mark attendance, we should give an option to employee to mark his attendance.