[enhance] Added multi UOM feature in Material Request
frappe/erpnext pull request #11352
Opened 2017-10-26 10:19 UTC by rohitwaghchaure

2017-11-10 05:58 UTC, nabinhait requested changes

2017-11-10 05:58 UTC, nabinhait commented on erpnext/stock/reorder_item.py
> +						"uom":	uom,
Qty should be set based on purchase uom, `d.reorder_qty` is in stock_uom here.

2017-11-10 05:58 UTC, nabinhait commented on erpnext/stock/reorder_item.py
> +						"uom":	uom,
And purchase_uom should only be set if "material_request_type" is purchase

2017-11-10 05:58 UTC, nabinhait commented on erpnext/stock/get_item_details.py
>  			args.uom = item.purchase_uom if item.purchase_uom else item.stock_uom
set purchase_uom only if material_request_type is purchase

2017-11-10 05:58 UTC, nabinhait commented on erpnext/buying/doctype/purchase_order/purchase_order.py
> +			'source_field': 'qty',
Actually I think, `ordered_qty` should be maintained in stock_uom. Because purchase_uom can be changed in PO from MR.

2017-11-10 05:59 UTC, nabinhait commented
@rohitwaghchaure Closing now, please reopen after fixing.

2017-11-12 14:32 UTC, rohitwaghchaure commented
**Reorder level**

![screen shot 2017-11-12 at 8 01 10 pm](https://user-images.githubusercontent.com/8780500/32699967-50d5a382-c7e4-11e7-900d-7aba844a2905.png)


**Material Request**
![screen shot 2017-11-12 at 8 00 25 pm](https://user-images.githubusercontent.com/8780500/32699973-5a7db82a-c7e4-11e7-8525-1283a47449f2.png)

2017-11-12 14:32 UTC, rohitwaghchaure commented
@nabinhait Fixed!

2017-11-13 14:11 UTC, nabinhait commented on erpnext/stock/doctype/material_request/material_request.py
> +		target.transfer_qty = (qty * obj.conversion_factor)
repeated line

2017-11-13 14:11 UTC, nabinhait commented on erpnext/stock/doctype/material_request/material_request.py
> +		qty = d.qty - (d.ordered_qty / d.conversion_factor)
Production Order does not have multi uom / conversion factor. You only need to fix `if (d.stock_qty - d.ordered_qty) >0:`

2017-11-13 14:11 UTC, nabinhait commented on erpnext/stock/reorder_item.py
> +					conversion_factor = frappe.db.get_value("UOM Conversion Detail",
Conversion factor should not be fetched at all, if request_type is not 'Purchase'. It should be 1.

2017-11-13 14:12 UTC, nabinhait commented
@rohitwaghchaure Closing, please reopen after fixing.

2017-11-21 06:07 UTC, rohitwaghchaure commented
@nabinhait Fixed!

2017-11-21 10:47 UTC, merged