Employee loan fixes
frappe/erpnext pull request #11495
Opened 2017-11-09 07:14 UTC by rohitwaghchaure

- Added child table in salary slip to link salary slip and employee loan

- Fixed issue of interest amount, employee loan amount  not booked in respective interest account and employee loan account

- Added patch to update employee loan data in child table

2017-11-13 08:41 UTC, nabinhait requested changes
Add a gif file to show it is working

2017-11-13 08:41 UTC, nabinhait commented on erpnext/hr/doctype/employee_loan_detail/employee_loan_detail.json
> + "name": "Employee Loan Detail",
Why not "Salary Slip Loan"?

2017-11-13 08:41 UTC, nabinhait commented on erpnext/hr/doctype/salary_slip/salary_slip.json
> +   "fieldname": "loan_details",
why not "loans"?

2017-11-13 08:41 UTC, nabinhait commented on erpnext/hr/doctype/employee_loan_detail/employee_loan_detail.json
> +   "reqd": 0,
set required columns in this table

2017-11-13 08:41 UTC, nabinhait commented
closing it for now

2017-11-14 05:06 UTC, rohitwaghchaure commented
@nabinhait Fixed!

2017-11-14 12:28 UTC, nabinhait approved these changes

2017-11-14 12:29 UTC, merged