[fix] do not translate domains while creating db record
frappe/erpnext pull request #11616
Opened 2017-11-16 12:01 UTC by saurabh6790

- Import non-translated domain while installing fixtures
 - Patch to rename domain in English and to reset domain settings for activated domain
 - Moved **resave_domain_settings** and **revert_domain_settings** patch from frappe to erpnext. 
     - The domains specified in both patches only belongs to ERPNext. If ERPNext is not installed then these patches will break as they are not found the domain records.
     -  Handled patch re-execution by checking  into Patch Log table 
         ```if frappe.db.get_value("Patch Log", {'patch': 'frappe.patches.v9_1.resave_domain_settings'})```
   

Dependent PR: https://github.com/frappe/frappe/pull/4506

2017-11-16 13:29 UTC, nabinhait requested changes
If you move a patch from frappe to erpnext, it will run again. Lets keep those patches in frappe.

2017-11-17 04:10 UTC, saurabh6790 commented
@nabinhait they will only run if there is no entry for frappe's patches in Patch Log

```
if frappe.db.get_value("Patch Log", {'patch': 'frappe.patches.v9_1.revert_domain_settings'}):
```
---
```
if frappe.db.get_value("Patch Log", {'patch': 'frappe.patches.v9_1.resave_domain_settings'}):
```


```
if frappe.db.get_value("Patch Log", {'patch': 'frappe.patches.v9_1.resave_domain_settings'}):
```

2017-11-17 06:08 UTC, rmehta requested changes

2017-11-17 06:08 UTC, rmehta commented on erpnext/patches/v9_2/rename_translated_domains_in_en.py
> +
```
if language.startswith('en'): return
```

2017-11-17 06:08 UTC, rmehta commented on erpnext/patches/v9_2/rename_translated_domains_in_en.py
> +		if domain in ('Education', 'Healthcare', 'Hospitality'):
setup all active domains?

2017-11-17 06:59 UTC, merged