Employee tree
frappe/erpnext pull request #11667
Opened 2017-11-20 16:39 UTC by Zlash65

![employee-nested](https://user-images.githubusercontent.com/11695402/33029606-0a1af1ca-ce3f-11e7-8cb8-32a1383336d8.gif)
Without nestedset - [#11621 ](https://github.com/frappe/erpnext/pull/11621)

2017-11-24 14:46 UTC, Olawale1 commented
Hi,

Good job. Hope all branches will be expanded by default. Would be odd to open an Employee tree only to find the names of top management and then having to click each name to view subordinates 

Kind regards,

2017-11-25 05:43 UTC, Zlash65 commented
@Olawale1 No it does not by default as of now but it could be done, I'll ask around and see what majority has to say and will implement it 👍

2017-11-28 11:50 UTC, rohitwaghchaure commented
@Zlash65 
Patch is required to update lft and rgt of existing employee

2017-11-28 11:54 UTC, rohitwaghchaure commented on erpnext/hr/doctype/employee/employee.py
> +	if parent and company and parent!=company:
Why checked company with parent?

2017-11-28 12:38 UTC, rohitwaghchaure commented on erpnext/hr/doctype/employee/employee.py
> +		self.update_nsm_model()
Add in on_trash too!

2017-11-28 12:38 UTC, rohitwaghchaure commented
Closing PR, kindly make changes and reopen it

2017-11-29 08:38 UTC, nabinhait requested changes

2017-11-29 08:38 UTC, nabinhait commented on erpnext/hr/doctype/employee/employee.py
> +		self.update_nsm_model()
Instead of calling `update_nsm_model`, call super function (on_trash of NestedSet class)

2017-11-29 11:03 UTC, nabinhait requested changes
- Renaming of employee breaks
- Merging also breaks
The error comes from `before_rename` and `after_rename` function of nestedset.py

2017-11-29 13:14 UTC, merged