Letterhead in user progress
frappe/erpnext pull request #11679
Opened 2017-11-21 12:12 UTC by shreyashah115

#11163 
![letter](https://user-images.githubusercontent.com/17617465/33071850-35bd224a-cee3-11e7-90f5-61f7a0df9aaa.png)

2017-11-22 08:37 UTC, pratu16x7 requested changes

2017-11-22 08:37 UTC, pratu16x7 commented on erpnext/utilities/user_progress.py
> +					"description": _("Keep it web friendly 900px (w) by 100px (h)"),
Let's just skip the label and description altogether. Will also help in keeping the image control in the centre. Instead, we'll change help to "Upload your letter head (Keep it web friendly as 900px by 100px)". Once inside, they'll already be aware that things can be changed later on. (The edit line was while in the setup wizard).

2017-11-22 08:50 UTC, pratu16x7 commented
Also update `install_fixtures.py`.

2017-11-23 06:42 UTC, rmehta commented
Also update Setup Wizard test!

2017-11-24 09:34 UTC, pratu16x7 commented
@rmehta Agree, if we are also removing the brand info in this PR (right now there are no changes in Setup Wizard)

2017-11-28 10:39 UTC, merged

2017-11-28 10:40 UTC, nabinhait commented
@shreyashah115 Merged this PR. Remove brand slide from setup-wizard via a separate PR.