[feature] Shipping Rule Tax calculated based on Total Net Weight
frappe/erpnext pull request #11672
Opened 2017-11-21 07:39 UTC by vishdha

1. Currently Available for sales invoice only.
In Shipping Rule select calculate_based_on: Net Weight and Select condition from value to value.
In Sales Invoice Item Weight, total_weight and weight_uom field are added. 
based on qty weight are calculated for eg. weight=20 and qty = 5, total_weight = 100
In Sales invoice on select shipping rule, it will calculate tax based on total_net_weight.

2. WIP: Not work on multi UOM Currently, and need to implement it for buying module too.

2017-11-21 10:53 UTC, nabinhait requested changes

2017-11-21 10:53 UTC, nabinhait commented on erpnext/accounts/doctype/sales_invoice_item/sales_invoice_item.json
> +   "fieldname": "weight",
`weight_per_unit` will be more clearer

2017-11-23 09:14 UTC, vishdha commented
![anim](https://user-images.githubusercontent.com/6947417/33165431-d0ba76b0-d05c-11e7-8bf8-56a09efabd75.gif)

2017-11-28 11:08 UTC, rohitwaghchaure commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
> +cur_frm.add_fetch('item_code','weight_uom','weight_uom');
Wrote same code in every file. Add this code into transaction.js and check child table(sales order item) has field weight_per_unit

2017-11-28 11:16 UTC, rohitwaghchaure commented on erpnext/controllers/taxes_and_totals.py
> +				item.total_weight = flt(item.weight_per_unit * item.qty)
Total weight will calculate only if there is taxes? I think this has to be done on qty change trigger?

2017-11-28 11:17 UTC, rohitwaghchaure commented on erpnext/public/js/controllers/taxes_and_totals.js
> +				item.total_weight = flt(item.weight_per_unit * item.qty)
this has to be done on qty change trigger?

2017-11-29 05:39 UTC, rohitwaghchaure commented
Duplicate https://github.com/frappe/erpnext/pull/11770

2017-11-29 05:39 UTC, closed without merging