[fix] validate bom if order type is subcontracting
frappe/erpnext pull request #11705
Opened 2017-11-23 11:28 UTC by saurabh6790

https://github.com/frappe/erpnext/issues/11704

<img width="639" alt="screen shot 2017-11-23 at 4 54 33 pm" src="https://user-images.githubusercontent.com/3784093/33170769-87b54ae0-d06f-11e7-8b4d-36a02d1a0d8c.png">

2017-11-23 12:30 UTC, nabinhait requested changes

2017-11-23 12:30 UTC, nabinhait commented on erpnext/buying/doctype/purchase_order/purchase_order.js
> +					frappe.throw(__("BOM is not specified for subcontracting item {0} at row {1}",[item.item_code, item.idx]))
it should be in server side

2017-11-23 12:30 UTC, nabinhait commented
closing this

2017-11-24 06:47 UTC, saurabh6790 commented
@nabinhait Fixed!

2017-11-28 05:11 UTC, merged