Fetch items of item groups defined in the pos profile
frappe/erpnext pull request #11763
Opened 2017-11-28 13:47 UTC by rohitwaghchaure

2017-11-28 17:13 UTC, nabinhait requested changes

2017-11-28 17:13 UTC, nabinhait commented on erpnext/accounts/doctype/pos_profile/pos_profile.py
> +	return item_groups
return list(set(item_groups))

2017-11-29 06:00 UTC, rohitwaghchaure commented on erpnext/accounts/doctype/pos_profile/pos_profile.py
> +	return item_groups
Fixed!

2017-11-29 08:25 UTC, merged

2018-01-02 02:58 UTC, gbard commented
The issue is back in v10.0.4 (master)