Payment Entry Returned (#8659)
frappe/erpnext pull request #11896
Opened 2017-12-08 11:56 UTC by tundebabzy

This PR attempts to close #8659.

With this PR, users can have ERPNext automatically create a Journal Entry against a returned payment as well as a repayment.

When a Payment Entry is created, a "Return" button will be added. Behind the scenes, ERPNext will try to verify which button to display ("Return" or "Redeposit") or won't display the button at all if ERPNext is not sure.

![screenshot from 2017-12-08 11-01-49](https://user-images.githubusercontent.com/818803/33764358-6a27f5c6-dc14-11e7-9da7-f3860f434893.png)

![peek 2017-12-08 12-50](https://user-images.githubusercontent.com/818803/33764915-c1daba68-dc16-11e7-809f-c7abccd77c17.gif)

![peek 2017-12-08 11-41](https://user-images.githubusercontent.com/818803/33764418-99f1488e-dc14-11e7-96a3-aee9184ac7c5.gif)

2017-12-11 08:46 UTC, tundebabzy commented
requires frappe/#4569

2018-02-12 07:25 UTC, rmehta requested changes
Please add / update related documentation and add test cases.

2018-02-12 07:25 UTC, rmehta commented on erpnext/accounts/doctype/payment_entry/payment_entry.js
> +					fieldtype:'Date', reqd:1, label:'Posting Date',
label should be translatable

`__('Posting Date')`

Note: Fix all labels.

2018-02-12 07:25 UTC, rmehta commented
@tundebabzy please reopen after fixing the issues.

2018-02-12 07:25 UTC, closed without merging

2018-12-09 11:02 UTC, vrms commented
@tundebabzy does this feature satisfy the requirements for this open bounty? https://www.bountysource.com/issues/39242671-pdc-management-suggestion-full-feature-bounty
if so, I suggest to claim the funds, so the bounty can be closed.

2018-12-09 11:13 UTC, vrms commented
sorry, I was mislead. Thought this had been merged (as there was a reference on another PR for this being the better approach). So maybe my comment from above is irrelevant or is there a way to proceed with this and close both (this PR AND the bounty)?