[Enhance] New print format for UAE/KSA for vat/excise
frappe/erpnext pull request #12202
Opened 2017-12-27 10:39 UTC by rohitwaghchaure

2017-12-28 07:37 UTC, nabinhait requested changes

2017-12-28 07:37 UTC, nabinhait commented on erpnext/controllers/taxes_and_totals.py
> +	update_itemwised_tax_data(doc)
It should be "itemised"

2017-12-28 07:37 UTC, nabinhait commented on erpnext/regional/united_arab_emirates/utils.py
> +		row.tax_amount = flt((row.net_amount * tax_rate) / 100, row.precision("net_amount"))
Don't calculate `tax_amount` again, it can lead to mismatched data due to precision. "itemised_tax" already have "tax_amount".

2017-12-28 08:50 UTC, merged

2017-12-28 10:15 UTC, FlexsoftsTech commented
dear team, I got updates today in my client version but when i tried to print invoice i did not see the design above
i saw below design (i selected Detailed Tax Invoice)
[Test Detailed Tax Invoice.pdf](https://github.com/frappe/erpnext/files/1590996/Test.Detailed.Tax.Invoice.pdf)

2017-12-28 10:32 UTC, nabinhait commented
We just released the new print format. This print format is not yet deployed in client's account, will deploy it soon (by tomorrow).

2017-12-28 11:52 UTC, FlexsoftsTech commented
Thank you @nabinhait for clarification

2017-12-29 18:15 UTC, FlexsoftsTech commented
@nabinhait still I see separate table for items details and tax details, how i can print these above templates 
i am using V10