Set due date in purchase invoice based on suppler invoice date
frappe/erpnext pull request #12395
Opened 2018-01-09 10:19 UTC by rohitwaghchaure

2018-01-09 12:57 UTC, tundebabzy requested changes

2018-01-09 12:57 UTC, tundebabzy commented on erpnext/controllers/accounts_controller.py
> +		posting_date = self.get("biil_date") or self.get("posting_date") or self.get("transaction_date")
Typo. bill_date not biil_date

2018-01-09 12:57 UTC, tundebabzy commented on erpnext/controllers/accounts_controller.py
>  		due_date = date or posting_date
`bill_date` is overwritten here except `due_date` is not set.

2018-01-09 13:04 UTC, tundebabzy commented
PR doesn't work correctly:
![peek 2018-01-09 13-59](https://user-images.githubusercontent.com/818803/34722025-6de24500-f545-11e7-8feb-aa6ef5146ef0.gif)

2018-01-11 06:10 UTC, rohitwaghchaure commented on erpnext/controllers/accounts_controller.py
> +		posting_date = self.get("biil_date") or self.get("posting_date") or self.get("transaction_date")
Fixed

2018-01-17 10:53 UTC, merged

2018-02-06 20:52 UTC, cosimot commented
Hello! Any news on this?