Fixes issue #12512
frappe/erpnext pull request #12544
Opened 2018-01-18 14:10 UTC by vinayak--

It solves issue #12512

2018-01-19 03:28 UTC, Jacksoneasyway commented
Dear: Vinayak

is this how to fix our issue?  I'm not a programmer, would not able to understand how to do it.
please kindly give more deatails.

thanks

2018-01-19 12:33 UTC, Jacksoneasyway commented on erpnext/stock/dashboard/item_dashboard.js
> +		} else {
Dear: Vinayak
I think this is the right place for my question, I want to hide the (BTN-add) from 'sales user' and 'stock user'
please kindly help out how I can do that.
I've tried the perm level, set perm level to 'stock Manager' at 2, 'stock user' at 1, but still the the bth 'add' shows to everyone who has access to ITME.

2018-01-20 09:06 UTC, vinayak-- commented
Steps to replicate:-
>1. Login as Admin and give a certain user, permission for Stock User and Stock Manager or else any one of them.
> 2. Then login with that specified user and then you'll see that if either of the above permissions are given or both of them are given only then the buttons to "add" and "move" stock are visible else they are invisible.
> **Please check the gif below**

![solved-issue](https://user-images.githubusercontent.com/9364050/35181806-b2115d0e-fdee-11e7-9378-49c254ab6f16.gif)

2018-01-21 15:56 UTC, Jacksoneasyway commented
Dear: Vinayak

Thank you very much for your reply.
I’ve tried as your suggestion, I give one of the user only “sales user”, without “stock manager” nor “stock user”.

please check the below pictures.

maybe there are something more I should do? in the PDF is the documents the “sales user” has permission

Thanks, looking forward to your reply. 

Jackson Wu
EASY WAY TRD
Mobile: +968 97726911 (Oman)
            +971 566926835 (UAE)
            +86 15043291802 (China)
Add: Barka Sanaiya, Sultanat of Oman

2018-01-23 17:43 UTC, Jacksoneasyway commented
Dear: Vinayak

have you able to receive my last email?

just for this last point to finish all my questions, please kindly help on this.

Jackson Wu
EASY WAY TRD
Mobile: +968 97726911 (Oman)
            +971 566926835 (UAE)
            +86 15043291802 (China)
Add: Barka Sanaiya, Sultanat of Oman

2018-01-24 03:46 UTC, tundebabzy commented
Hi @vinayak-- 
Thanks for this fix. Please open the pull request to hotfix branch.

2018-01-24 04:02 UTC, tundebabzy requested changes
fix it on hotfix

2018-01-24 05:38 UTC, rohitwaghchaure commented on erpnext/stock/dashboard/item_dashboard.js
> +		if (frappe.user_roles.indexOf("Stock Manager") > -1 || frappe.user_roles.indexOf("Stock User") > -1){
Instead of checking hardcode roles, check user has write permissions for Stock Entry doctype
frappe.boot.user.can_write.indexOf("Stock Entry")

2018-01-24 05:38 UTC, rohitwaghchaure commented
@vinayak-- 
Closing the PR, make the changes in hotfix branch and create new PR

2018-01-24 05:38 UTC, closed without merging