Minor - Healthcare Desktop UI
frappe/erpnext pull request #12657
Opened 2018-01-25 15:42 UTC by system19

Minor - Healthcare Desktop UI
Spelling error, Links fixed

2018-01-26 05:35 UTC, nabinhait requested changes
Any specific reason for changing the colour of the icons?

2018-01-26 06:10 UTC, system19 commented
No not really. I don't actually like colour. I just returned them all to the same colour they were before the last healthcare icon related PR. I like the idea of the healthcare Module being mostly one colour though.
The main part of this PR is that I found several Icons that didn't link. Clicking them would do nothing.

2018-01-30 07:01 UTC, raghukamath commented
> No not really. I don't actually like colour. I just returned them all to the same colour they were before the last healthcare icon related PR. I like the idea of the healthcare Module being mostly one colour though.

Colour is subjective matter, some people like colours while others don't, however in this situation I guess we can keep different colour to make it a bit more consistent, because our desktop in other domains has various colours for icon background. adding color also makes it easy to spot icons and breaks the monotonous looks.

Can you please add a screenshot showing how it looks now. 

Thank you.

2018-01-30 07:46 UTC, ghost requested changes

2018-01-30 07:46 UTC, raghukamath commented on erpnext/config/desktop.py
> +			"color": "#FF888B",
Can you keep the colors as it is?

2018-01-30 07:53 UTC, raghukamath commented on erpnext/config/desktop.py
> +			"link": "List/Consultation",
thanks for adding the links

2018-01-30 08:18 UTC, nabinhait commented
@system19 As Raghu suggested, to keep consistency with other icons, I am merging this PR keeping the multiple colour.

2018-01-30 08:18 UTC, merged

2018-01-30 22:44 UTC, system19 commented
Sure, No problem :-)