[ADD] Feature to add multi images for single item and multi image zoo…
frappe/erpnext pull request #12709
Opened 2018-01-30 11:48 UTC by Solufyin

@revant, @manassolanki 
Feature to add multi images to a single item and multi-image zooming functionality.
![add_multiple_images_for_single_item](https://user-images.githubusercontent.com/34390782/35564736-2db8103e-05e1-11e8-8b91-8fd087ef1482.png)

![item_multi_image_zooming](https://user-images.githubusercontent.com/34390782/35564746-3b63bf58-05e1-11e8-8075-f9024c21b97f.png)

[ERPNext_product_muti_image_zooming.mp4.zip](https://github.com/frappe/erpnext/files/1677505/ERPNext_product_muti_image_zooming.mp4.zip)

2018-01-30 13:11 UTC, revant commented
I think the data on `Item Multi Image` is already captured on `Website Slideshow` DocType from frappe.
![screenshot from 2018-01-30 18-36-13](https://user-images.githubusercontent.com/1040161/35567903-afd94f78-05ec-11e8-834c-8226036c1b45.png)

`Website Slideshow` Feature needs update?

2018-01-31 04:53 UTC, Solufyin commented
Hello, @revant,
We keep both features when we configure "Item Multi Image" It will show the Item Multi Zooming and we configure item slideshow it will show the slideshow on e-commerce site.

The User can use two alternative choices:
1) If user added multiple images in "Item Multi Image" then user is able to see product multi 
zooming functionality on e-commerce site.

2) If the user added multiple images in "Slider" ( for slideshow ) then a user is able to see slideshow functionality on e-commerce site.

Thanks

2018-01-31 07:12 UTC, rmehta commented
"Multi Item Image" is a very bad name!

How about "Alternate Images" ?

2018-01-31 07:18 UTC, rmehta requested changes

2018-01-31 07:18 UTC, rmehta commented on erpnext/stock/doctype/item/item.js
> +//					fieldname = 'image'
remove commented code

2018-01-31 07:18 UTC, rmehta commented on erpnext/stock/doctype/item/item.js
> +				    image_dict = {
why this modal?

Also don't use variable names like `image_dict1` etc. This should just be one list of dicts?

2018-01-31 07:18 UTC, rmehta commented on erpnext/stock/doctype/item/item.js
> +			$("#myImg").css('display','block');
no absolute links please!

2018-01-31 07:18 UTC, rmehta commented on erpnext/templates/generators/item.html
> +		    {% if not list_all_image %}
whitespace

2018-01-31 07:18 UTC, rmehta commented on erpnext/stock/doctype/item/item.json
> +   "options": "Item Multi Image",
Item Alternate Image

https://github.com/frappe/erpnext/wiki/Naming-Guidelines

2018-01-31 07:19 UTC, tundebabzy commented
Hi @Solufyin 
I'm not sure if this is the right approach to this new feature (which I like). How does this affect POS?

2018-01-31 07:20 UTC, tundebabzy submitted a review, later dismissed
Fix codacy review also

2018-01-31 08:10 UTC, hda commented
@tundebabzy POS image and E-commerce image will not have conflicts as we are storing e-commerce alternate images in separate doctype. We are in discussion on this to use slideshow doctype instead of new doctype as suggested by @revant

2018-01-31 15:44 UTC, MichaelPinkowski commented
I strongly prefer the idea of storing e-commerce images separately from the slideshow.

2018-01-31 16:16 UTC, rmehta commented
I think we can keep images separate too.

2018-02-01 07:00 UTC, revant commented
Note : 

I've cases where some DocType need multiple images attached to it.

- Slideshow was separate (and part of framework), 
- Any DocType can have link to Website Slideshow,
- linked Slideshow will only contain "media" / images and not any non image files.

Cases.

- Merchandise posted by a user/seller on e-commerce Portal.
- List of previous Profile photos.

I feel better file upload, and file meta management is required to manage file backend (not UI).

I could achieve this using [whitelisted api](https://github.com/agrinext/agrinext/blob/develop/agrinext/api.py#L25):
(I'm testing the whitelisted api for permissions, eventually I'll send PR)

Multiple files attached images and other files.
![photo_2018-02-01_12-21-39](https://user-images.githubusercontent.com/1040161/35665061-7cf396f4-074a-11e8-9f1e-bb8aab36371c.jpg)

[Android App](https://github.com/agrinext/agrinext_mobile/tree/revant-dev) (UI) shows previous profile images
<img src="https://user-images.githubusercontent.com/1040161/35665142-c98f276c-074a-11e8-8849-d3ce1343660b.jpg" style="max-width:400;">

2018-02-01 09:29 UTC, rmehta commented
I also like @revant suggestion of making this generic.

We can rename "Website Slideshow" to "Media Group" and create a new Media Group object for each Item and link it to the Item.

In the template, the workflow will be the same, either you pull it from Item or Media Group?

2018-02-01 12:20 UTC, Solufyin commented
Hello @revant, @rmehta,
We did improvements as per your suggestion.

2018-02-13 05:09 UTC, rmehta commented
@Solufyin thanks for the fixes. I agree with @revant  that we can reuse "Website Slideshow" and link it in the Item instead of creating a new DocType. 

Just remove the Item Alternate table and link "Website Slideshow"

Bonus if you can rename "Website Slideshow" to "Media Group" in frappe.

2018-02-21 07:38 UTC, revant commented
@Solufyin,

> Just remove the Item Alternate table and link "Website Slideshow"

Can you do the suggested change?

We'll eventually rename `Website Slideshow` to `Media Group`. That refactor will have to be patched for old databases. Either you can attempt that on frappe/frappe, or just use `Website Slideshow` for now.

2018-02-21 09:42 UTC, Solufyin commented
**Dear @Revant and @rmehta,**

We are Improved Code for Item Alternate Zooming functionality using common doctype website slideshow.
We can use multiple choice as per user need using common doctype "Website Slideshow Item".

2018-03-04 06:23 UTC, revant commented
@Solufyin 

There seems to be a merge conflict with item.json

What I suggest this as a workaround:

- Note down fields added in item.json as a part of this PR
- pull latest item.json from upstream/develop
- `bench migrate`
- Add the fields noted down before (if not there in `Item` `DocType`)
- save Item DocType, commit as conflict resolved

2018-03-05 07:03 UTC, Solufyin commented
Hello @revant ,
We resolved conflict item.json.
Thanks.

2018-03-09 07:32 UTC, revant commented
@netchampfaris, can you help in review of CSS/HTML/JS?

@Solufyin I cleared the print statement do pull before you start making any changes. Also there seems to be merge conflict item.json again. :frowning_face:

2018-03-13 06:20 UTC, netchampfaris commented
@Solufyin 

After linking Website Slideshow in Item, I can see the slideshow on the website but don't know how to enable the zoom feature.

![image](https://user-images.githubusercontent.com/9355208/37325598-8ac6af12-26b4-11e8-9418-2014a800397f.png)

2018-03-13 06:25 UTC, netchampfaris requested changes
Why are we using another table when we can attach multiple images to the Item form itself?
Also, there are spaces in some files, please convert to tabs.

2018-03-13 06:25 UTC, netchampfaris commented on erpnext/templates/generators/item.html
> +                                div.list_all_images img:hover {
Why inline styles tags, we can put them in .less files

2018-03-13 06:25 UTC, netchampfaris commented on erpnext/templates/generators/item.html
> +                                #selectedImage{
id selectors are bad

2018-03-13 06:25 UTC, netchampfaris commented on erpnext/templates/generators/item.html
> +                            <script>
Move to .js file?

2018-03-13 06:25 UTC, netchampfaris commented on erpnext/templates/generators/item.html
> +                                function changeImage(image_src){
no camelcase

2018-03-13 06:25 UTC, netchampfaris commented on patches.txt
> +bench.patches.v3.deprecate_old_config
Remove file

2018-03-28 06:33 UTC, nabinhait commented
@Solufyin Closing this, please reopen after making changes as per @netchampfaris's suggestion.

2018-03-28 06:33 UTC, closed without merging