Removed sql and used orm
frappe/erpnext pull request #12755
Opened 2018-02-03 17:05 UTC by shridarpatil

Activate checkin / checkout in attendance control panel / HR settings.
On login, if not checked in, show popup to allow checkin

https://github.com/frappe/erpnext/issues/428

2018-02-03 17:45 UTC, shridarpatil commented
I think the build is getting failed because of this patch https://github.com/frappe/erpnext/blob/develop/erpnext/patches.txt#L492


![image](https://user-images.githubusercontent.com/11792643/35769866-d2f503f0-0937-11e8-9d4d-17b7f001de3e.png)

2018-02-12 12:30 UTC, nabinhait requested changes
- Add few screenshots
- Add documentation

2018-02-12 12:30 UTC, nabinhait commented on erpnext/hr/doctype/attendance/attendance.py
> +def employee():
`employee` is not a good method name, `get_employee()` ???

2018-02-12 12:30 UTC, nabinhait commented on erpnext/public/js/checkin_checkout_attendance.js
> +	var dialog = new frappe.ui.Dialog({
If user does not logged out till the next date, what will happen? May be check the server time every few minutes and if day changes, show the popup again.

2018-02-12 12:30 UTC, nabinhait commented
Closing this for now, please reopen after fixing.

2018-02-12 12:30 UTC, closed without merging