[fix] Fetch B2B limit from GST Settings
frappe/erpnext pull request #12808
Opened 2018-02-07 13:06 UTC by vishdha

2018-02-07 14:22 UTC, saurabh-bhosale commented
Fix for #12784

2018-02-12 06:13 UTC, rmehta commented
default value?

2018-02-12 08:59 UTC, nabinhait requested changes

2018-02-12 08:59 UTC, nabinhait commented on erpnext/regional/doctype/gst_settings/gst_settings.json
> +   "label": "B2B Limit",
This limit is not for B2B, it's for B2C. Also set a better descriptive label for this.

2018-02-12 08:59 UTC, nabinhait commented
Closing this for now, please reopen after fix.

2018-02-12 08:59 UTC, closed without merging