item balance report
frappe/erpnext pull request #12983
Opened 2018-02-17 14:49 UTC by PawanMeh

1. Simple Item Balance report to show minimal columns with stock quantity

![item balance report](https://user-images.githubusercontent.com/20460498/36342137-cbe591cc-141f-11e8-88e1-d7dee064c844.png)

2018-02-19 05:58 UTC, nabinhait requested changes

2018-02-19 05:58 UTC, nabinhait commented on erpnext/stock/report/item_balance/item_balance.json
> + "letter_head": "Nishal (Maharashtra)",
hard-coded letter head?

2018-02-19 06:46 UTC, PawanMeh commented on erpnext/stock/report/item_balance/item_balance.json
> + "letter_head": "Nishal (Maharashtra)",
removed with commit "358ffd7"

2018-02-19 07:18 UTC, nabinhait commented
@PawanMeh 
The name of the reports (Item Balance / Stock balance) can be confusing for the user. Even I was confused while checking the PR, until I check the description of the PR. So, may be in similar line, the report can be called "Item Balance (Simple)" or "Stock Balance (Simple)"

2018-02-20 05:14 UTC, maheshengg approved these changes

2018-02-20 05:17 UTC, maheshengg commented
@nabinhait @saurabh6790 

 Hi,  The report 'Item Balance (Simple)' hasn't been merged into the system, kindly reveiw and do the needful.

2018-02-20 06:47 UTC, merged

2018-02-20 07:55 UTC, maheshengg commented
@PawanMeh How do I see this new report in my instance ??

2018-02-20 08:13 UTC, PawanMeh commented
@maheshengg , this would be merged in master tomorrow end of day, so once it is available you can search by "Item Balance (Simple)" in search bar or reports and you should be able to view it.

2018-02-23 05:51 UTC, maheshengg commented
@PawanMeh Need to know why I am unable to find ""Item Balance (Simple)" Report in the search bar. Help would be appreciated.

2018-02-23 06:09 UTC, PawanMeh commented
@nabinhait , kindly confirm if it has been merged & updated in master branch or if there is an estimated timeline for it, you can let us know.