New Leaderboard
frappe/erpnext pull request #13001
Opened 2018-02-20 07:19 UTC by vishdha

2018-02-21 09:30 UTC, nabinhait requested changes

2018-02-21 09:30 UTC, nabinhait commented on erpnext/utilities/page/leaderboard/leaderboard.py
> +			`tabSales Invoice` as sales_invoice ON sales_invoice.sales_partner = sales_partner.name
Use `Sales Order` instead of `Sales Invoice`

2018-02-21 09:30 UTC, nabinhait commented on erpnext/utilities/page/leaderboard/leaderboard.js
> +		const company = frappe.defaults.get_default('Company');
why you are taking default company here? it should consider the select company

2018-02-21 10:11 UTC, vishdha commented
Changes Added :v:

2018-02-22 08:30 UTC, merged

2021-03-03 18:21 UTC, MrKovalski commented
How do we access it?
Right now I can't find it on the desk. I can find it in the search thou.