Manual to setup Multilingual Website
frappe/erpnext pull request #13105
Opened 2018-02-26 17:30 UTC by KanchanChauhan

Dependent on https://github.com/frappe/frappe/pull/5085

2018-03-18 15:45 UTC, ilyesderp commented
Hi @KanchanChauhan 
when will this be merged please?

2018-03-19 05:27 UTC, KanchanChauhan commented
@ilyesderp Most probably this week, there are some final changes happening.

2018-04-06 05:36 UTC, rmehta requested changes

2018-04-06 05:36 UTC, rmehta commented on erpnext/docs/user/manual/en/website/setting-multilingual-website.md
> +<img class="screenshot" alt="Webpage English" src="/docs/assets/img/website/jina-for-translatable-content.png">
please change the text in this screenshot

2018-05-16 06:17 UTC, closed without merging