Loan Management for the Members (Non Profit Module)
frappe/erpnext pull request #13149
Opened 2018-03-02 20:07 UTC by shreyashah115

Summary:

- Changes as per mentioned in #12822.
- Renamed Employee Loan Application to Loan Application and Employee Loan to Loan.
- Added field 'Applicant' and 'Applicant Type' for Employees and Members.
- 'Make Repayment Entry' button visible when Disbursement has been made.
- Added a field in Loan DocType to display the amount which has been repaid.
- Few fixes in the Loan DocType.
- Added a patch for renaming.

<img width="1073" alt="screen shot 2018-03-03 at 12 42 14 am" src="https://user-images.githubusercontent.com/17617465/36917626-59fceb74-1e7d-11e8-806d-71ab97437c75.png">

![loan](https://user-images.githubusercontent.com/17617465/36917597-49e16e04-1e7d-11e8-8429-c710b1e1c8e2.gif)

2018-03-03 07:41 UTC, olamide2 commented
Looks Cool

What about instances where members keep money with the NGO as invenstements and expect to get interest on such invenstements as well as pay back at a time in future?

Is that an itch you want to scratch?

2018-03-04 05:45 UTC, shreyashah115 commented
@olamide2 That needs some discussion, why don't you open a issue for it?

2018-03-20 09:52 UTC, kothagunda commented
Hello @umairsy , when will this feature get into Develop. We would like to test it out.

2018-03-20 09:56 UTC, umairsy commented
It has been merged already in the develop branch. In the master, you can expect with the release of ERPNext version 11, ETA two weeks (tentative).

2018-03-20 09:58 UTC, kothagunda commented
Cool. Thanks @umairsy .

2018-03-26 09:59 UTC, kothagunda commented
I installed the developer branch today. But still see Employee loan, instead of Loan docType. Am i missing something. 

![image](https://user-images.githubusercontent.com/30433779/37899873-45c196ba-310a-11e8-8f89-2216ee473282.png)


Installed Apps
ERPNext: v11.x.x-develop (061d912) (develop)
Frappe Framework: v11.x.x-develop (20052f0) (develop)

2018-03-26 11:45 UTC, shreyashah115 commented
@kothagunda Sorry about the confusion. Yes, it hasn't been merged into develop, yet.

2018-03-28 07:01 UTC, nabinhait requested changes
- Add Loan and Loan Application links in Non-Profit module page

2018-03-28 07:01 UTC, nabinhait commented on erpnext/patches/v11_0/rename_employee_loan_to_loan.py
> +
Patch is required for applicant, applicant_type, loan_application fields as well.

2018-03-28 07:01 UTC, nabinhait commented on erpnext/hr/doctype/loan/loan.py
> +			self.disbursement_date = nowdate()
Why nowdate? Ask user to enter.

2018-03-28 07:01 UTC, nabinhait commented on erpnext/hr/doctype/loan/loan.js
> +			frm.doc.repayment_schedule[0].payment_date = frm.doc.disbursement_date;
why so?

2018-04-24 06:48 UTC, nabinhait approved these changes

2018-04-24 06:49 UTC, merged

2018-05-05 06:50 UTC, nabinhait commented on erpnext/patches/v11_0/rename_employee_loan_to_loan.py
> +
Fixed via https://github.com/frappe/frappe/commit/3bb36344a6021d8edbe587bbf39c4a22f2d63dc7