Add Health Insurance Doctype and link to Employee
frappe/erpnext pull request #13257
Opened 2018-03-09 13:20 UTC by creamdory

Health Insurance is a generic information that should be added as an Employee information. In a company, it can be one Insurance provider or several.

In this case, I have added "Health Insurance" doctype and added "Health Insurance Provider" link field in Employee Doctype.

<img width="1190" alt="screen shot 2018-03-09 at 14 17 17" src="https://user-images.githubusercontent.com/21003054/37209285-08fc33e2-23a5-11e8-877b-94b51e43b542.png">

<img width="1179" alt="screen shot 2018-03-09 at 14 17 48" src="https://user-images.githubusercontent.com/21003054/37209289-0d9ce7a2-23a5-11e8-9406-046867952bcf.png">

2018-03-12 08:37 UTC, nabinhait requested changes

2018-03-12 08:37 UTC, nabinhait commented on erpnext/hr/doctype/health_insurance/health_insurance.json
> +   "fieldname": "name1",
Use `health_insurance_name` instead

2018-03-12 08:37 UTC, nabinhait commented on erpnext/hr/doctype/health_insurance/health_insurance.json
> +   "fieldname": "company",
Why is it required? It can be global records for every company.

2018-03-13 07:40 UTC, creamdory commented
@nabinhait I have edited request changes. Also, I have added it under "Set-up" in HR module.

<img width="267" alt="screen shot 2018-03-13 at 08 37 56" src="https://user-images.githubusercontent.com/21003054/37328345-281c95ee-269a-11e8-86b5-1f82d6e06503.png">

<img width="1016" alt="screen shot 2018-03-13 at 08 30 12" src="https://user-images.githubusercontent.com/21003054/37328340-1fcdb97c-269a-11e8-926e-97edfca7f967.png">

2018-03-20 07:07 UTC, merged