[fix] accounts receivable report fix
frappe/erpnext pull request #13669
Opened 2018-04-16 10:32 UTC by codingCoffee

Print pdf for accounts receivable report used to use the customer doc
name instead of the customer_name

2018-04-16 10:40 UTC, codingCoffee commented
![screenshot_20180416_160642](https://user-images.githubusercontent.com/13611153/38804485-28323d98-4190-11e8-8766-b6583db6ec1e.png)

![awesomescreenshot-2018-04-16t10-37-20-091z](https://user-images.githubusercontent.com/13611153/38804606-901888e0-4190-11e8-8a56-80807fecea6e.gif)

![screenshot_20180416_160959](https://user-images.githubusercontent.com/13611153/38804622-9dd7f86c-4190-11e8-9114-59f32eb4858a.png)

2018-04-17 06:56 UTC, nabinhait requested changes

2018-04-17 06:56 UTC, nabinhait commented on erpnext/accounts/report/accounts_receivable_summary/accounts_receivable_summary.js
> +				var customer = frappe.query_report_filters_by_name.customer.get_value();
This change should be in accounts_receivable.js

2018-04-17 06:56 UTC, nabinhait commented on erpnext/accounts/report/accounts_receivable/accounts_receivable.html
> +<h4 class="text-center">{%= report.context_data.customer_name || filters.supplier %}</h4>
if filters.customer then `(report.context_data.customer_name || filters.customer)`
And the same is applicable for supplier as well in accounts_payable report

2018-04-30 14:10 UTC, closed without merging