Leave Application - validate optional leaves
frappe/erpnext pull request #13736
Opened 2018-04-19 09:22 UTC by rkurungadam

https://github.com/frappe/erpnext/issues/13614

2018-04-24 09:23 UTC, nabinhait requested changes
- [ ] We have added a sudo test `test_optional_leave` in test_leave_application.py file. Please make the necessary changes to pass it.
- [ ] Add docs

2018-04-25 09:57 UTC, rkurungadam commented on erpnext/hr/doctype/leave_application/leave_application.py
> +	optional_leave = frappe.db.sql("select is_optional_leave from `tabLeave Type` where name = %s", leave_type)
found a smilar method is_lwp(), so thought db.sql is more optimal, change this too?

2018-04-25 10:03 UTC, rkurungadam commented on erpnext/hr/doctype/leave_application/leave_application.py
> +		while day <= getdate(self.to_date):
do we need holiday list in leave type? by this design leave types will have to be updated on period change. Holidays are fetched by get_holiday_list_for_employee in other places, let me know.

2018-05-04 13:00 UTC, nabinhait commented
Can you please rebase and fix conflicts?

2018-05-04 13:11 UTC, closed without merging