CRM dashboard
frappe/erpnext pull request #13816
Opened 2018-04-27 11:31 UTC by saurabh-bhosale

Second part of [Telephony services' Integration](https://github.com/frappe/erpnext/issues/13012).

1. Notifies an incoming call.
**Description:** Shows the notification of an incoming call to whoever the call is connected from the helpline/support team.
2. Updates the details on CRM Dashboard in realtime.

**Popup for an Incoming call:**
![incoming_call_popup](https://user-images.githubusercontent.com/25682214/39360564-6edf1d4c-4a3c-11e8-8824-37fd908f3ec2.gif)

- [ ] Gifs
- [ ] Docs

2018-05-25 06:34 UTC, rmehta commented
@saurabh-bhosale any update. Please add relevant documentation too

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

2018-06-25 06:21 UTC, rmehta requested changes

2018-06-25 06:21 UTC, rmehta commented on erpnext/crm/doctype/crm_settings/crm_settings.py
> +		open_issues = frappe.get_all("Issue", filters = {"contact":contact_doc.get("name")}, fields=["*"])
why select * ?

2018-06-25 06:21 UTC, rmehta commented on erpnext/erpnext_integrations/page/crm_dashboard/crm_dashboard.js
> +			method: "erpnext.erpnext_integrations.doctype.exotel_settings.exotel_settings.handle_outgoing_call",
why is this hard coded?

It should be able to call any calling service

2018-06-25 06:21 UTC, rmehta commented on erpnext/crm/doctype/crm_settings/crm_settings.py
> +def make_popup(caller_no, comm_details):
very large function

https://github.com/frappe/erpnext/wiki/Coding-Standards#break-functions--methods-more-than-10-lines-of-code

2018-06-25 06:21 UTC, rmehta commented on erpnext/crm/doctype/crm_settings/crm_settings.py
> +			comm_details.get("communication_exophone") +  "/" +
exotel hardcoding

2018-06-25 06:21 UTC, rmehta commented on erpnext/crm/doctype/crm_settings/crm_settings.py
> +		open_issues = frappe.get_all("Issue", filters = {"contact":contact_doc.get("name")}, fields=["*"])
also add a limit, limit to last 5 issues

2018-06-25 06:21 UTC, rmehta commented on erpnext/public/js/telephony/telephony_console.html
> +				<button id="new_lead" class="btn btn-sm btn-primary">Create Lead</button>
public facing strings must be translatable

https://github.com/frappe/erpnext/wiki/Coding-Standards#user-facing-messages-must-be-translated

2018-07-06 07:10 UTC, nabinhait commented
@saurabh-bhosale Closing the PR for now. Please reopen after finishing the pending tasks.

2018-07-06 07:10 UTC, closed without merging