[ADD] hr : Added functionality to calculate department, Employee and organization Age.
frappe/erpnext pull request #13838
Opened 2018-04-30 10:26 UTC by Solufyin

[ADD] hr: Added functionality to calculate department, employee and organization age.

![employee_age](https://user-images.githubusercontent.com/34390782/39423212-73ede332-4c8e-11e8-85bb-a1fb2b014255.png)

Calculates average age and total age of employees of the particular department and the total number of employees in particular department. see the below screenshot.

![department_age](https://user-images.githubusercontent.com/34390782/39423241-875ec404-4c8e-11e8-9605-cd2a7ef0e2ff.png)

Calculates average age and total age of employees of the organization and the total number of employees in the organization. see the below screenshot.

![company_age](https://user-images.githubusercontent.com/34390782/39423300-d7f0c2a0-4c8e-11e8-89c5-a4326d356307.png)

Thanks

2018-05-25 06:32 UTC, rmehta commented
Needs documentation an tests!

@Solufyin Appreciate your team taking lead in contributions 👍  Please make sure you read this carefully

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

Lets build awesome features :)

2018-05-25 06:32 UTC, rmehta requested changes

2018-05-25 06:32 UTC, rmehta commented on erpnext/hooks.py
> +			"erpnext.hr.doctype.employee.employee.age_calculation"]
this should be called from the controller itself!

2018-05-25 06:32 UTC, rmehta commented on erpnext/hr/doctype/employee/employee.py
> +		company_emps = get_employees_by_filter({'company': company,
Just use `frappe.get_all` !

```
frappe.get_all('Employee', dict(company = company, status = 'Active'), ['name', 'employee_age'])
```

2018-05-29 12:52 UTC, Solufyin commented
Hello @rmehta and @revant 

Thanks for appreciation.
We did improved code as per your suggestion.

Thanks.

2018-05-30 07:48 UTC, nabinhait commented
@Solufyin Thanks for the PR.

As per the implementation, the age values will be update on save of Employee records or on change of date-of-birth field's value. So, at any point of time, it will not give accurate age of department / company employees. If we maintain those age fields, we have to calculate and update the values regularly via scheduler.

But in my opinion, we don't need those fields inside the department / company at all. There should be a **Report** to show age of employees based on department / company.

Hence, closing this PR.

2018-05-30 07:48 UTC, closed without merging