[fix] Compounding error in task weight
frappe/erpnext pull request #13958
Opened 2018-05-08 08:56 UTC by vishdha

Failure rate
Sum of 2 numbers between 0.00 and 1.00
0.01 + 0.05 != 0.06
0.01 + 0.06 != 0.07
0.01 + 0.09 != 0.10
0.01 + 0.14 != 0.15
0.01 + 0.17 != 0.18
0.01 + 0.20 != 0.21
0.01 + 0.23 != 0.24
0.01 + 0.28 != 0.29
...
0.99 + 0.87 != 1.86
0.99 + 0.90 != 1.89
0.99 + 0.92 != 1.91
2106 failures (21%) out of 10000 sums
Failure rate: 21%

https://ge0ffrey.github.io/ge0ffrey-presentations/cornerCaseCheatSheet/CornerCaseCheatSheet.pdf

In our case, we have 86 task out of which 
72 contain weight 0.010 = 0.72
14 contain weight 0.020 = 0.28
the result should be 1.00
but it gives 1.0000000007
I have attached screenshot below
before 
![beforeweight](https://user-images.githubusercontent.com/6947417/39747492-16b3cf72-52cb-11e8-8e03-8f3e6fa42377.gif)

after:
![afterweight](https://user-images.githubusercontent.com/6947417/39747612-643dc48c-52cb-11e8-9792-7e261fe816f2.gif)

2018-05-08 09:50 UTC, nabinhait requested changes

2018-05-08 09:50 UTC, nabinhait commented on erpnext/projects/doctype/project/project.py
> +				sum = round(sum + task.task_weight, 3)
Don't hardcode, use precision of the field instead.

`flt(sum + task.task_weight, task.precision('task_weight'))`

2018-05-09 04:38 UTC, vishdha commented
Changes Added

2018-05-09 05:12 UTC, merged

2018-05-10 06:14 UTC, bhaveshjavar reviewed
this is work only one time if i add one task and save than try to add next task showing same error