add get leave period method
frappe/erpnext pull request #13985
Opened 2018-05-10 14:20 UTC by saurabh6790

```
ImportError: Module import failed for Leave Allocation (erpnext.hr.doctype.leave_allocation.leave_allocation Error: cannot import name get_leave_period)
```

2018-05-11 06:37 UTC, rkurungadam commented
Hi @saurabh6790 this would fix the import error, but the optional leave validation would still fail. issue came up with PR #13931 which had a dependancy on #13741 and I have mentioned too, and its not yet merged, jamsheer has closed and raised a new one #13951, would be great if you can review this.
Thanks

2018-05-11 15:45 UTC, nabinhait requested changes

2018-05-11 15:45 UTC, nabinhait commented on erpnext/hr/utils.py
> +def get_leave_period(from_date, to_date, company):
this missing function is defined in https://github.com/frappe/erpnext/pull/13951/files. Please copy it from there.

2018-05-12 12:16 UTC, saurabh6790 commented
Fixed!

2018-05-14 10:17 UTC, merged