[Feature] Managing Contracts in ERPNext
frappe/erpnext pull request #14205
Opened 2018-05-24 07:26 UTC by Alchez

**Overview:** You can create, view and manage Contracts between you and another entity, like Customers, Suppliers and Employees.

<hr>

New DocTypes:
- **Contract:** Contains the full details for a contract with the party (more details below).
- (Child Table) **Contract Fulfilment Checklist:** Displays the status and notes for each fulfilment requirement, if any, for the contract.
- **Contract Template:** Contains the template for all contract and contract fulfilment terms.
- (Child Table) **Contract Template Fulfilment Terms:** Stores the fulfilment terms for the contract template.

The **Contract** doctype currently allows:
- Creating contracts with Customers, Employees and Suppliers.
- Setting the period for which the contract is valid.
- Quickly setting the terms of the contract through existing **Contract Templates**, and editing them in the document.
- Recording the details of the person / entity signing the contract - name, user ID in the system (if any).
- Viewing the fulfilment status by the party, and add notes to each individual contract requirement.
- Linking the contract to a relevant document, such as Quotation, Sales Order, Project, etc.

<hr>

**Example Contract:**
![image](https://user-images.githubusercontent.com/13396535/38676763-b08373c0-3e79-11e8-990b-80eb4e53839c.png)

**Example Fulfilment Terms:**
![image](https://lh3.googleusercontent.com/QQ25RjaA1YS1kk40SgDRsEgwwq6cjF_JbKlLU93k6j25uQuTpZRZHZ221HHjYd1dUDw9cdMoIkjbHmqP7w5pQUcL6d-Be92h8oRzhzpdwBOF4KPwOh_J7vAt1rvzFx8dIF0-Wx3p)

<hr>

**Configuration:**

Each Contract needs:
- **Title:** the name of the contract
- **Party Type:** whether the contract is with a Customer, Supplier or Employee
- **Party Name:** the link to the record of the party in the system
- **Contract Terms:** the terms of the contract - these can be pulled from a template and edited manually

In addition to that, you can set some optional fields:
- **Start and End Date:** the active time range for the contract (if the end date is given, the system will automatically mark the contract as “Inactive” when it is past)
- **Signed:** this box indicates that the party has signed the contract (if checked, it will enable the “Signee Details” section with the following fields)
  - **Signee:** the name of the person who actually signed the contract
  - **Signed On:** the date on which the contract was signed
- **Contract Template:** link to a contract template in the system, allowing you to quickly pull up default terms for the contract
- **Requires Fulfilment:** check this box if the contract requires fulfilment terms / actions from the party (if checked, it will enable the following fields)
  - **Fulfilment Deadline:** the final date for all the fulfilment terms to be met
  - **Fulfilment Terms (table):** each row indicates an individual fulfilment term - you can add requirement details, mark a term as fulfilled and add notes for more information.
- **References:**
  - **Link Type:** link the contract with a document (must be one of Quotation, Project, Sales Order, Purchase Order, Sales Invoice, Purchase Invoice)
  - **Link Name:** link to the relevant record in the system

2018-05-24 09:45 UTC, Olawale1 commented
Great Job @Alchez !

This is a very helpful addition to ERPNext

Kind regards,

2018-05-24 12:02 UTC, OneiricIT commented
@Alchez awesome work! It would be great to eventually see this developed with charges which can be affiliated with contract and turned into draft invoice for example at each defined renewal or per setting! Also when alterations to charges need to be made, update the contract and subsequent invoices generated will have updated charges.

Well done!

2018-05-25 05:36 UTC, rmehta commented
Thanks for contribution, please add relevant documentation and tests

Might be a good idea to read this once!

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

2018-05-30 06:28 UTC, rmehta requested changes

2018-06-14 12:27 UTC, merged