Blanket order
frappe/erpnext pull request #14259
Opened 2018-05-28 14:40 UTC by manassolanki

Fixes https://github.com/frappe/erpnext/issues/13733

2018-05-31 04:00 UTC, nabinhait requested changes
- [x] Add tests
- [x] Add docs

2018-05-31 04:00 UTC, nabinhait commented
- [ ] Add screenshots / GIF

2018-06-11 12:18 UTC, manassolanki commented
@nabinhait Done

2018-06-13 09:50 UTC, nabinhait approved these changes

2018-06-13 09:56 UTC, nabinhait requested changes

2018-06-13 09:56 UTC, nabinhait commented on erpnext/controllers/stock_controller.py
> +					ordered_quantity = ordered_quantity + item.qty
Write this type function using `select sum(qty)` query, this helps to correct if goes wrong. For example, you forgot to call this function on STOP and UNSTOP events.

2018-06-14 10:30 UTC, nabinhait commented
merged from console

2018-06-14 10:30 UTC, closed without merging