[WIP Feature] Update Qty and Rate for PO and SO After Submit
frappe/erpnext pull request #14602
Opened 2018-06-20 06:44 UTC by creamdory

From this GH Issue https://github.com/frappe/erpnext/issues/13925 , we have this initial Design.

![po](https://user-images.githubusercontent.com/21003054/41641022-68f6daf8-7496-11e8-9248-92de8c478b10.gif)

![so](https://user-images.githubusercontent.com/21003054/41641353-98792ab4-7497-11e8-8dd5-2779ede06a09.gif)

As mentioned in the issue's comment, we have below issues:

Our team had started developing this for a month now and we have bumped into several challenges as follows that we need help from the frappe team.

- There is a dialog issue that was raised here frappe/frappe#5643.
- Update issue that is block by this general [validation](https://github.com/frappe/frappe/blob/9862619ca50e1d59907ae37c9c709673d2a7da24/frappe/model/base_document.py#L556). This is used by all submittable doctypes and if changed, might cause bigger problem. We really need help and enlightenment in this area.
- No Option to "Allow on Submit" for calculated fields in the doctype like amount and grand_total. If altered inside json file, still did not work.

These are the use cases that needs to be considered:

Update Qty

- Can be changed even with partial Delivery but cannot be less than the delivered Qty.
- Can be changed to Zero as long as no Delivery yet.
- Cannot be changed when PO is already invoiced.

Update Rate

- Can be changed during "To Received and Bill" Status (Means 1. no delivery and 2. with partial delivery)
- For Partial Deliveries, must lower the current line Qty to "Received Qty" then allow user to "Add" new line with the remaining Qty with the new rate.
- Cannot change rate when Invoice is already created.

2018-06-20 12:08 UTC, nabinhait commented
@creamdory I think the suggestion to set `doc.flags.ignore_validate_update_after_submit = True` should work. And then there will no requirement for those server side function to enable `allow_on_submit` property for child and parent table.

2018-06-21 07:12 UTC, creamdory commented
@nabinhait hey, need help. Getting this error every during `po.save()` but update is no working. Which is triggering this?

<img width="1056" alt="screen shot 2018-06-21 at 3 09 54 pm" src="https://user-images.githubusercontent.com/21003054/41703276-5c3b1d04-7565-11e8-933e-e2fc52da6626.png">

2018-06-21 08:13 UTC, snvora commented
> Cannot be changed when PO is already invoiced.

@creamdory Did you mean fully invoiced?

For partly delivered and invoiced it should work. Right?

2018-06-21 10:10 UTC, creamdory commented on erpnext/buying/doctype/purchase_order/purchase_order.py
> +			po.save()
@nabinhait we are getting a deadlock issue somewhere here.

```
Traceback (most recent call last):
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
    response = frappe.handler.handle()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/__init__.py", line 942, in call
    return fn(*args, **newargs)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 498, in update_child_qty_rate
    po.save()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in save
    return self._save(*args, **kwargs)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/model/document.py", line 310, in _save
    self.update_children()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/model/document.py", line 328, in update_children
    self.update_child_table(df.fieldname, df)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/model/document.py", line 337, in update_child_table
    d.db_update()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/model/base_document.py", line 343, in db_update
    ), list(d.values()) + [name])
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/apps/frappe/frappe/database.py", line 195, in sql
    self._cursor.execute(query, values)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/creamdoryy/Development/py2-frappe-dev/frappe-bench/env/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1213, u'Deadlock found when trying to get lock; try restarting transaction')
```

2018-06-21 10:12 UTC, creamdory commented
@snvora yes. We can do changes for partially delivered and partially invoiced PO's. Only those lines that are not invoiced and received can be updated.

2018-06-22 18:21 UTC, albertusgeyser commented
Great if this could be done as we constantly have to create another order when customers change their minds. 

Thank you

Albertus Geyser

2018-06-25 06:08 UTC, rmehta commented on erpnext/controllers/accounts_controller.py
> +    def __init__(self, *args, **kwargs):
you have replaced all tabs by spaces !

2018-06-25 06:10 UTC, rmehta requested changes

2018-06-25 06:10 UTC, rmehta commented on erpnext/controllers/accounts_controller.py
> +        throw(_("{0} is mandatory. Maybe Cur
please fix tabs

2018-06-25 10:27 UTC, nabinhait requested changes

2018-06-25 10:27 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +        throw(_("{0} is mandatory. Maybe Cur
**Purchase Order**
Following functions from validate should also be called.
1. Validate min_order_qty
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.py#L59
2. Set raw_materials_supplied table, as it's depends on qty
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.py#L61
3. Set status
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.py#L47

Also, I think most of the functions called in `on_submit` should be called while updating qty / rate.
- Update last pur rate
- update status updater if PO is created against SO
- Update previous doc's status
- Update requested qty in bin
- Update ordered qty in bin
- update reserved qty for subcontract
- Update blanket order
- Validate budget
- Validate approving authority
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.py#L205

2018-06-25 10:27 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +        throw(_("{0} is mandatory. Maybe Cur
Similarly, for Sales Order following functions should be called:
1. `set_status`
2. `make_packing_list`
3. `check_credit_limit`
4. `update_reserved_qty`
5. `validate_approving_authority`
6. `update_project`
7. `update_prevdoc_status`
8. `update_blanket_order`

And all these should be called after `calculate_taxes_and_totals `.

2018-06-25 10:30 UTC, nabinhait commented
Closing the PR as of now, please reopen after fixing requested changes.

2018-06-25 10:35 UTC, nabinhait commented
As you are working actively on the PR, reopening this. So that we can have comments on the PR.

2018-07-09 06:03 UTC, creamdory commented
hi @nabinhait ! Hope you can see my changes and send me some feedback if there are any. thanks!

2018-07-10 08:00 UTC, creamdory commented
@nabinhait here is the documentation https://github.com/erpnext/foundation/pull/238

2018-07-13 12:08 UTC, nabinhait commented
Merged the PR manually from console after fixes and cleanup. Closing this.

2018-07-13 12:08 UTC, closed without merging