Employee benefit - Last payroll period benefit
frappe/erpnext pull request #14634
Opened 2018-06-22 07:00 UTC by pjamsheer

- Employee Benefit - Last payroll period benefit calculation

2018-06-22 10:29 UTC, nabinhait requested changes

2018-06-22 10:29 UTC, nabinhait commented on erpnext/hr/doctype/employee_benefit_claim/employee_benefit_claim.py
> +def get_total_benefit_despensed(employee, sal_struct, sal_slip_start_date, payroll_period):
dispensed?

2018-06-22 11:33 UTC, pjamsheer commented on erpnext/hr/doctype/employee_benefit_claim/employee_benefit_claim.py
> +def get_total_benefit_despensed(employee, sal_struct, sal_slip_start_date, payroll_period):
Method name refactored

2018-06-22 11:57 UTC, nabinhait approved these changes

2018-06-22 11:57 UTC, merged

2019-11-05 15:07 UTC, fotocreaman commented
Is there a solution for this?