[Fix] 'To Bill' status even if the amount is zero
frappe/erpnext pull request #14784
Opened 2018-07-02 12:34 UTC by Alchez

Pull-Request

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you lint your code locally prior to submission?
- [ ] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

What type of a PR is this? 

- [ ] Changes to Existing Features
- [ ] New Feature Submissions
- [x] Bug Fix
- [ ] Breaking Change

--- 

- Motivation and Context (What existing problem does the pull request solve):

**Affected documents:** Sales Order, Delivery Note, Purchase Receipt

Due to an existing bug, sales and purchase documents that have a zero-amount show their status as "To Bill" even if invoices were made against them.

- The SQL query has been updated to include zero-amount documents to update their `per_billed` (which is what the status is compared against) appropriately.
- List view statuses have also been updated to reflect zero-amount orders correctly.

---

- Related Issue(s):

#5006
#12433

---

- Screenshots (if applicable, remember, a picture tells a thousand words):
![image](https://user-images.githubusercontent.com/13396535/42163778-72ba6f34-7e21-11e8-9b45-b36c27a8e6d0.png)

2018-07-17 11:46 UTC, nabinhait requested changes

2018-07-17 11:46 UTC, nabinhait commented on erpnext/controllers/status_updater.py
> +					SELECT IF(sum(abs(%(target_ref_field)s)) = 0, 100, ifnull(
Why setting `per_billed` as 100 directly, incase of zero grand total sales / purchase order? In those cases, we are already setting it based on `qty` using `update_billing_status_for_zero_amount_refdoc`?

2018-07-23 08:16 UTC, nabinhait commented
@Alchez Any comments on the review?

2018-07-24 06:56 UTC, Alchez commented
@nabinhait, sorry for the late reply.

I agree with your comment, but I can't think of a clean way to only update the DN ref field. Any suggestions on how to go about this?

2018-08-02 10:10 UTC, Alchez commented
@nabinhait - I've removed the SQL query update, and made the fix that only applies to Delivery Note documents. Can you please check and review?

CC: @agritheory

2018-08-30 09:45 UTC, vjFaLk commented
@nabinhait Sirji pls

2018-09-05 10:00 UTC, vjFaLk commented
@rmehta Sirji pls

2018-09-06 10:54 UTC, neilLasrado commented
@nabinhait @rmehta What is to be done here?

2018-09-06 12:57 UTC, merged