Modify renaming process of Account
frappe/erpnext pull request #14839
Opened 2018-07-08 08:11 UTC by shreyashah115

- Removed Allow Rename from Account master
- Account name and number could only be renamed by clicking on `Update Account Number` button.

![account number](https://user-images.githubusercontent.com/17617465/42418020-8c2a7e72-82b4-11e8-91a1-fa8ef4624149.gif)

2018-07-09 05:55 UTC, rohitwaghchaure commented
Hi @shreyashah115 

- If account number is on the form then set the account number as default in the popup.
- Rename update account number to Update Account Number / Account Name

2018-07-09 05:59 UTC, shreyashah115 commented
@rohitwaghchaure Done.

2018-07-17 12:50 UTC, nabinhait requested changes
- Still need to fix the original issue of splitting in `after_rename` method.
- Add some tests around renaming account

2018-07-17 12:50 UTC, nabinhait commented on erpnext/accounts/doctype/account/account.py
> +	def after_not(self, old, new, merge=False):
`after_not` ?

2018-07-23 08:24 UTC, nabinhait approved these changes

2018-07-23 08:45 UTC, merged