[Feature][Enhance] Healthcare Inpatient
frappe/erpnext pull request #14940
Opened 2018-07-17 13:37 UTC by pjamsheer

- Inpatient 
  - New DocTypes - Inpatient Record and Healthcare Service Unit Type
- Patient Appointment - Button - Get Prescribed Procedure - hide after save

2018-07-19 09:14 UTC, nabinhait requested changes
- Add screenshots
- Add tests

2018-07-19 12:57 UTC, pjamsheer commented
![screenshot from 2018-07-19 18 23 10](https://user-images.githubusercontent.com/20554466/42943765-4fecde7a-8b81-11e8-8259-0cfce9adc329.png)
![screenshot from 2018-07-19 18 23 48](https://user-images.githubusercontent.com/20554466/42943777-57ec0150-8b81-11e8-804a-f494844a63aa.png)

2018-07-19 12:59 UTC, pjamsheer commented
Added Tests and Screenshots
@nabinhait

2018-07-23 07:35 UTC, nabinhait approved these changes

2018-07-23 07:35 UTC, merged