Item Alternate Image Features in e-commerce site.
frappe/erpnext pull request #15044
Opened 2018-07-30 06:48 UTC by Solufyin

Hello @nabinhait
Added **Item Alternate Image Features** in e-commerce site.

As per your changed request #15015 We have developed Item Alternate Image Features.
We keep both features in single doctype. Slideshow and Item alternate image functionality shown in e-commerce site.

**The User can use two alternative choices:**

**1) If user is select slideshow option in slideshow drop down then user is able to see **slideshow functionality** in e-commerce site.**
![11](https://user-images.githubusercontent.com/34390782/43381406-328934f4-93f2-11e8-8d86-f353aa934d2f.png)
![12](https://user-images.githubusercontent.com/34390782/43381416-36678544-93f2-11e8-917b-502094d2a07e.png)

**2) If user is not select slideshow option in slideshow drop down then a user is able to see **Item Alternate Image** functionality in e-commerce site.**
![13](https://user-images.githubusercontent.com/34390782/43381437-44f6e24e-93f2-11e8-9618-9f719ebbaf1e.png)
![14](https://user-images.githubusercontent.com/34390782/43381441-48706dd2-93f2-11e8-8e80-a646e68323ed.png)
![15](https://user-images.githubusercontent.com/34390782/43381447-4b1a096c-93f2-11e8-8613-2560ae92dcfb.png)

**We configured images in slideshow item doctype in below snapshot:**

![con](https://user-images.githubusercontent.com/34390782/43381455-54a56724-93f2-11e8-9e58-7e870f77acb8.png)

**Please find attached video for more information:**

[item_alternate_image.mp4.zip](https://github.com/frappe/erpnext/files/2239954/item_alternate_image.mp4.zip)

Thanks.

2018-07-31 10:53 UTC, netchampfaris requested changes
I think we should replace the Image Slideshow altogether and set this mode as default.

2018-07-31 10:53 UTC, netchampfaris commented on erpnext/public/css/website.css
> +div.list_all_images img:hover {
Put these styles in website.less

2018-07-31 10:53 UTC, netchampfaris commented on erpnext/templates/generators/item.html
> +        <div class="row item-website-description" style="margin-top:30px; margin-bottom:20px">
Put these inline styles in website.less ?

2018-07-31 12:15 UTC, Solufyin commented
Dear @netchampfaris ,

We Improved code as per your suggestion.

2018-08-01 12:40 UTC, netchampfaris commented
@Solufyin Hey, as I mentioned in my review, we should remove the old item slideshow and replace it with the new browsing mode you have added. It should become the default mode of browsing multiple images of the item.

2018-08-02 01:01 UTC, gmplab commented
i think Solufyin's solution is better. The user can make their own decisions, use the new way or the old way.

2018-08-02 04:45 UTC, Solufyin commented
@gmplab, "i think Solufyin's solution is better. The user can make their own decisions, use the new mode or the old mode. You can set the new mode as default."

Yes, The user can make their own choice that's why we keep both functionality slide show and item alternate image in eCommerce site.

2018-08-02 09:44 UTC, Solufyin commented
Dear @netchampfaris , 

"@Solufyin Hey, as I mentioned in my review, we should remove the old item slideshow and replace it with the new browsing mode you have added. It should become the default mode of browsing multiple images of the item."

We removed old slideshow and added new item alternate image functionality set as default mode as per your review.

2018-08-07 09:47 UTC, netchampfaris commented
![item-alternative-image](https://user-images.githubusercontent.com/9355208/43768422-f0b5e28e-9a54-11e8-843c-44d7c0cd1cec.gif)

2018-08-07 09:49 UTC, netchampfaris approved these changes

2018-08-07 12:58 UTC, merged

2018-09-19 19:58 UTC, generare commented
This look awesome! All ok with it now?

2019-01-22 18:23 UTC, generare commented
Hello again! We were checking the Alternative Images functionality and it will be absolutely nice to have this functionality but it seems to have slightly many steps to input the alternate images if understood correctly. It would be nice if we would not need to jump to a Slideshow interface but rather upload the images on the same item interface page.

We borrowed the images from @Solufyin and edited those a bit to show what we mean.
![alternate-images-backend](https://user-images.githubusercontent.com/5984026/51556705-9a501780-1e83-11e9-826f-198e7ffdb2e0.jpg)