Adding "Include UOM" in Reports with Qty and Rates
frappe/erpnext pull request #15221
Opened 2018-08-26 06:07 UTC by SaiFi0102

**Prerequisite**: Pull Request at https://github.com/frappe/frappe/pull/6009 to allow adding total row (through frappe) on reports that result in list of dicts

**Problem**: Stock reports only show in stock UOM and does not show other UOMs
**Solution**: Include a filter field "Include UOM" and add extra columns for converted rate and qty columns using conversion_factor

**Thoughts for the future**: I once saw a field while using erpnext that allowed me to select multiple (comma separated) docs in one link field. I can't remember where it was otherwise I would have used such a field. I would suggest using that kind of a field to allow adding multiple UOMs.
**Missing out on**: Due to the complexity of getting conversion_factors from UOM Conversion Factor DocType, I did not consider those conversion factors. Should the reports also convert using UOM Conversion Factor?

**Implemented on reports**: Stock Ledger, Stock Balance, Stock Projected Qty 
**Further implementation**: Since qty and rate fields are included in many reports, I will continue updating reports to include the "Include UOM" field whenever the need arises. I would encourage the community to update the rest of the reports too.

2018-08-31 09:46 UTC, rmehta requested changes

2018-08-31 09:46 UTC, rmehta commented on erpnext/stock/report/stock_balance/stock_balance.py
> +		{"label": _("Opening Qty"), "fieldname": "opening_qty", "fieldtype": "Float", "width": 100, "convertible": "qty"},
+1 for using the new format, but why not refactor all the columns, so that it looks consistent

2018-08-31 09:46 UTC, rmehta commented on erpnext/stock/report/stock_ledger/stock_ledger.py
> +		for item in frappe.db.sql("""select item.name, ucd.conversion_factor from `tabItem` item
is this the same as above? (commonify)

2018-08-31 09:46 UTC, rmehta commented on erpnext/stock/utils.py
> +	for iCol in reversed(range(0, len(columns))):
snake_case in Python! `col_idx`

2018-09-17 12:12 UTC, closed without merging

2018-09-21 08:18 UTC, SaiFi0102 commented
@rmehta can you open the PR again? I've already completed the required changes.