[Enhancement] Email birthday reminder
frappe/erpnext pull request #15325
Opened 2018-09-05 13:23 UTC by Mangesh-Khairnar

Birthday reminder were not getting sent through email initially, since, recipients were not correctly selected. Also, the function was designed to send multiple emails, when multiple employees had their birthdays on the same day.
Now, Single email is sent for multiple birthdays. This includes sending a personalise email for the situation in which more than one person has a birthday on the same day. These personalise emails are designed in such a way that an employee celebrating a birthday on a particular day wouldn't get a email reminder for their own birthday but they would get a reminder for the birthday of their colleagues.

2018-09-06 09:54 UTC, netchampfaris requested changes

2018-09-06 09:54 UTC, netchampfaris commented on erpnext/hr/doctype/employee/employee.py
> +	return frappe.db.sql("""select name,personal_email, company, company_email, user_id, employee_name
Use ORM instead of raw sql

2018-09-06 09:54 UTC, netchampfaris commented on erpnext/hr/doctype/employee/employee.py
>  				reply_to=e.company_email or e.personal_email or e.user_id)
add header

2018-09-06 09:54 UTC, netchampfaris commented on erpnext/hr/doctype/employee/employee.py
> +			frappe.sendmail(recipients=filter(lambda u: u not in (e.company_email, e.personal_email, e.user_id), employee_emails),
move this logic into a function

2018-09-21 04:52 UTC, rmehta commented
👍  for first PR

2018-09-30 16:04 UTC, rmehta commented
Please add screenshots of the mail that will be sent.

2018-10-02 08:02 UTC, closed without merging