[Fix] Stock difference between gl entry and stock ledger entry booked in stock adjustment
frappe/erpnext pull request #15374
Opened 2018-09-10 09:40 UTC by rohitwaghchaure

2018-10-01 10:38 UTC, rmehta requested changes

2018-10-01 10:38 UTC, rmehta commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +					# Stock ledger value is not matching with the warehouse amount
move this to a separate function. Average function size should be 10 lines

2018-10-03 05:09 UTC, merged

2019-10-18 04:33 UTC, schilgod commented
@rohitwaghchaure @rmehta Possible to provide some explain why this change was necessary? We are having issues with PI having COGS entries, we cant figure out why COGS was credited with the difference amount. thanks.

2021-03-07 04:04 UTC, lxnow commented
I'd like to understand too, particularly in the Purchase receipt level

2024-04-17 07:29 UTC, A7medAbdin commented
The same here  too