Upgrade BOM Stock Report base with Qty to Produce
frappe/erpnext pull request #15697
Opened 2018-10-15 12:52 UTC by kickapoo

This a minor upgrade of BOM Stock Report with the addition of Qty to Produce (Similar to the report in source bom_stock_calculated)

Qty to Produce defualts to 1 and Report behaves as it used. With the other selection there is auto calculation for the other fields.

Also, some coloring added to Item Code for easy reference if BOM line has Enought Part to Produce.

![2018-10-15 15 39 45](https://user-images.githubusercontent.com/5064612/46951996-436fc080-d092-11e8-8567-1512854a916b.gif)

2018-10-16 11:40 UTC, rmehta requested changes

2018-10-16 11:40 UTC, rmehta commented on erpnext/manufacturing/report/bom_stock_report/bom_stock_report.js
> +					"fieldname": "qty_to_produce",
please fix indenting

2018-10-16 12:41 UTC, kickapoo commented on erpnext/manufacturing/report/bom_stock_report/bom_stock_report.js
> +					"fieldname": "qty_to_produce",
https://github.com/frappe/erpnext/pull/15697/commits/1547acdec8ced8a680affe12fe15ceb312844d02

2018-10-18 12:12 UTC, nabinhait commented
@kickapoo Can you please send the PR to staging-fixes branch?

2018-10-18 12:13 UTC, nabinhait commented
closing this

2018-10-18 12:13 UTC, closed without merging

2018-10-18 12:15 UTC, kickapoo commented
@nabinhait why this closed?