[New Feature]Scan Item Barcode label to quick create/update records in items child table
frappe/erpnext pull request #15731
Opened 2018-10-18 09:29 UTC by Zlash65

https://github.com/frappe/erpnext/pull/15329

Scan Barcode field added in
- Material Request
- Purchase Order
- Sales Order
- Delivery Note
- Stock Entry
- Purchase Invoice
- Sales Invoice

Code cleaned up.

2018-10-19 08:12 UTC, szufisher commented on erpnext/selling/page/point_of_sale/point_of_sale.py
> +	if serial_no_data:
Any reason why the searching sequence is serial number , then batch, finally barcode, not the other way around?
There is also barcode field in Item table, it is already obsolete and replaced by the Item barcode child table?

2018-11-08 07:28 UTC, rmehta requested changes

2018-11-08 07:29 UTC, rmehta submitted a review, later dismissed

2018-11-08 07:29 UTC, rmehta commented on erpnext/public/js/controllers/transaction.js
> +						show_description(child.idx, r.message.item_code, child.item_code);
this line is common, can be outside the `if` block !

2018-11-12 10:00 UTC, nabinhait requested changes

2018-11-12 10:00 UTC, nabinhait commented on erpnext/selling/page/point_of_sale/point_of_sale.py
> +	frappe.errprint([item_code, serial_no, batch_no, barcode])
remove `errprint`

2018-11-13 05:41 UTC, merged

2018-11-21 08:55 UTC, PawanMeh commented
Some possible gaps, scan field not available on Purchase receipt and also does the scanned bar code get updated in inventory?

2019-01-04 11:55 UTC, FinForceConsulting commented
@Zlash65 Zarrar, this PR merged only created field to capture Barcode number at the Item level and related docs.

Could you share a gif Screencast of how this will work for multiple items and the item table gets created automatically with scan. If this works like retail stores, it would be a great functionality