[fix] #14038-Std hours at company level to calculate timesheet hours
frappe/erpnext pull request #15819
Opened 2018-10-25 09:14 UTC by PawanMeh

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2018-10-25 09:18 UTC, PawanMeh commented
Before changes

![timesheet_before](https://user-images.githubusercontent.com/20460498/47489696-dc59c500-d864-11e8-924c-c3fb88ca869b.gif)

After changes

![timesheet_after](https://user-images.githubusercontent.com/20460498/47489720-e67bc380-d864-11e8-99c3-dd9783944c3a.gif)

2018-11-05 06:34 UTC, PawanMeh commented
Commenting to re-open for review comments

2018-11-08 06:53 UTC, rmehta requested changes

2018-11-08 06:53 UTC, rmehta commented on erpnext/projects/doctype/timesheet/timesheet.js
> +		var time_diff = (moment(child.to_time).diff(moment(child.from_time),"seconds")) / (60 * 60 * 24);
business logic should be server side!

https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#all-business-logic-and-validations-must-be-on-server-side

2018-11-12 11:10 UTC, merged