Absent on lwp
frappe/erpnext pull request #15823
Opened 2018-10-25 09:56 UTC by ashish-greycube

Solution to https://github.com/frappe/erpnext/issues/11435 and
https://github.com/frappe/erpnext/issues/5893

2018-10-25 16:08 UTC, jigneshpshah commented
Design : 

in HR Settings

There will be options for **_Salary Slip Based On_**
Leave Application
Attendance
Timesheet

if user will choose _Attendance_ , he will get an option to _Consider Absent as LWP_ or not, based on which Absent will be treated as LWP during Payroll processing.

Below is the gif explaining a scenario of an Employee having attendance as below
Working Days = 20

Absent Days = 3
Leave without Application = 1
1 Half Day = 0.5
Hence Total LWP = 4.5

Payment Days = 15.5

![salaryslip_absentaslwp](https://user-images.githubusercontent.com/4900815/47514267-91a86f00-d89d-11e8-86fd-666579a41691.gif)

2018-11-05 08:35 UTC, rmehta requested changes
please add tests

@ashish-greycube Thanks for contributing! Let me know if you need a call regarding tests.

2018-11-05 08:35 UTC, rmehta commented on erpnext/hr/doctype/salary_slip/salary_slip.py
> +                where t1.docstatus = 1
inconsistent indenting

2018-11-05 08:35 UTC, rmehta commented
Closing for now to reduce PR count. Please re-open after tests.

2018-11-05 08:35 UTC, closed without merging

2018-12-31 20:47 UTC, govindsmenokee commented
@rmehta I think a better approach would be to move the attendance required check to the employee doc level, that way we have more control over which set of employees should have attendance. Also having this check at any other place would not make sense with the current system.

2019-10-04 09:09 UTC, Olawale1 commented
Hi @ashish-greycube 

Trust you're doing well. Any chance of adding some tests so this can go through? It's still a much needed feature and quite frankly, it's surprising ERPNext doesn't have any link between attendance and payroll up till now!

Thanks

2019-10-04 09:22 UTC, flexy2ky commented
This will indeed be a brilliant addition to the Salary Module, whichever way it is implemented. We need this to reduce the number of processes required to confirm days worked. Right now, there are too many manual steps needed for organizations with a number of staff who may miss work without authorization, manually processing LWP for every single absence is a pain.

2019-11-22 01:10 UTC, AkramMutaher commented
> Design :
> 
> in HR Settings
> 
> There will be options for **_Salary Slip Based On_**
> Leave Application
> Attendance
> Timesheet
> 
> if user will choose _Attendance_ , he will get an option to _Consider Absent as LWP_ or not, based on which Absent will be treated as LWP during Payroll processing.
> 
> Below is the gif explaining a scenario of an Employee having attendance as below
> Working Days = 20
> 
> Absent Days = 3
> Leave without Application = 1
> 1 Half Day = 0.5
> Hence Total LWP = 4.5
> 
> Payment Days = 15.5
> 
> ![salaryslip_absentaslwp](https://user-images.githubusercontent.com/4900815/47514267-91a86f00-d89d-11e8-86fd-666579a41691.gif)

@jigneshpshah 

that's exactly what we need what happens for this feature?

2019-12-17 19:47 UTC, Olawale1 commented
Any update on this please?