update party_name and party_group
frappe/erpnext pull request #16017
Opened 2018-11-19 08:24 UTC by kalaisaranA

updating party_name and party_group in Report Payment Period Based On Invoice Date.

2018-11-26 07:05 UTC, kalaisaranA commented
By updating Party name and Party Group(customer/supplier group) gives detailed description on Party.kindly refer the snapshot
![screenshot_2018-11-26 payment period based on invoice date](https://user-images.githubusercontent.com/41562031/48997822-322cd000-f177-11e8-8b38-83cf37b6eb8c.png)

2018-12-24 09:37 UTC, rmehta requested changes
please use `frappe.db.get_value` instead of SQL

2018-12-24 09:37 UTC, rmehta commented on erpnext/accounts/report/payment_period_based_on_invoice_date/payment_period_based_on_invoice_date.py
> +			for i in frappe.db.sql("""
use the ORM

```
customer_name, customer_group = frappe.db.get_value('Customer', d.party, ['customer_name', 'customer_group'])
```

2019-01-07 10:45 UTC, sagarvora commented
Reopen after changes.

2019-01-07 10:45 UTC, closed without merging