Serial Number validation in stock entry
frappe/erpnext pull request #16020
Opened 2018-11-19 11:27 UTC by nxdevelopment

Stock Entry allows  same Serial Number items (duplication of serial no). Even though the product is sold (contain Delivery Note),again the  another product with same serial number is given it generate the new product with previous serial_no.In this Serial No list the creation document no is rewritten. So it allows repeation/duplication of serial number.In order to avoid the duplication the file is modified.

2018-11-26 06:51 UTC, nxdevelopment commented
kindly refer this in Issues  "Serial No : Validation in Stock Entry #15936 " where detailed description for Serial Number validation in stock entry is explained.

2018-12-10 12:13 UTC, rmehta requested changes

2018-12-10 12:13 UTC, rmehta commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +	def validate_serial_against_stock_entry(self):
please add test case

2018-12-10 12:14 UTC, rmehta commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		"""
such a docstring is meaningless because it is the function name

2018-12-10 12:15 UTC, rmehta requested changes

2018-12-10 12:15 UTC, rmehta commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +	def validate_serial_against_stock_entry(self):
there must be an empty line above the function

2019-01-07 10:44 UTC, sagarvora commented
Reopen after changes.

2019-01-07 10:44 UTC, closed without merging

2020-01-07 09:49 UTC, Olawale1 commented
Any update on this? Hope it's been fixed now