New reports : Stock Balance Multi-UOM
frappe/erpnext pull request #16136
Opened 2018-12-01 14:33 UTC by lelsheri

Report : Stock Balance Multi-UOM :
========================
to let customer view the balances with default UOM + Purchase UOM + Sales UOM
as my client request.

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2018-12-09 11:03 UTC, lelsheri commented
Any feedback.

2018-12-10 11:23 UTC, rmehta commented
@lelsheri 👍 for first contribution. How do we know if this works? Can you add a test case?

Also better to call the report "Stock Balance in Multiple UOMs"

2018-12-10 11:23 UTC, rmehta requested changes

2018-12-10 11:23 UTC, rmehta commented on erpnext/stock/report/stock_balance_multi_uom/stock_balance_multi_uom.py
> +	columns = [
please use the new API with JSON structures

2018-12-10 11:23 UTC, rmehta commented on erpnext/stock/report/stock_balance_multi_uom/stock_balance_multi_uom.py
> +                AND itm.name = sle.item_code
inconsistent indenting

2018-12-24 10:30 UTC, Mangesh-Khairnar requested changes

2018-12-24 10:30 UTC, Mangesh-Khairnar commented on erpnext/stock/report/stock_balance_multi_uom/stock_balance_multi_uom.py
> +		elif d.purchase_uom_conversion_factor != 0:
fix the indentations to match with the outer if conditions.

2018-12-24 10:30 UTC, Mangesh-Khairnar commented on erpnext/stock/report/stock_balance_multi_uom/stock_balance_multi_uom.py
> +		from `tabItem Variant Attribute` where parent in (%s)
Please follow the indentation guidelines:

https://github.com/frappe/erpnext/wiki/Coding-Standards#use-simple-indenting

2018-12-24 10:30 UTC, Mangesh-Khairnar commented on erpnext/stock/report/stock_balance_multi_uom/stock_balance_multi_uom.py
> +		else: qty_dict.bal_qty_s = 0
indentation doesn't match. Incorrect logic.

2019-01-07 10:42 UTC, sagarvora commented
Closing. Please reopen after making necessary changes.

2019-01-07 10:42 UTC, closed without merging