[Enhancement] Pending SO Items for Purchase Request Report
frappe/erpnext pull request #16188
Opened 2018-12-10 10:04 UTC by Mangesh-Khairnar

- Pending Sales Order Items for Purchase Request Report which was written as a query report didn't cover all the edge cases and was slower to read for larger datasets. This report refactor intends to solve that problem. 
- Sales Order for which a material request was  partially completed will only have remaining items listed and those sales order which don't have a corresponding material request will also be listed(For SO which are not "Completed").

![pendingsoitemsforpurchasereport](https://user-images.githubusercontent.com/14824451/49724491-69c76c00-fc8f-11e8-963c-b47020211ecc.gif)

2018-12-10 11:29 UTC, rmehta requested changes
please also add comments and a test case also a better name could be:

"Pending Sales Items to be Purchased"

2018-12-12 15:07 UTC, Mangesh-Khairnar commented on erpnext/selling/report/pending_so_items_for_purchase_request/pending_so_items_for_purchase_request.py
> +	sales_order_entry = frappe.db.sql("""select  so_item.item_code,
added indentation, comments and required tests

2018-12-24 08:55 UTC, merged

2018-12-24 10:09 UTC, djpalshikar commented
@Mangesh-Khairnar, is this going to cover items for Pending for  **Purchase** Only.
 
We manufacture our items, therefore we create Material Request for Manufacture.

2018-12-24 10:55 UTC, Mangesh-Khairnar commented
@djpalshikar this tracks Sales Order that have partial or no Material Request created. It has the same functionality as requested on issue #14953.

2018-12-24 11:21 UTC, djpalshikar commented
@Mangesh-Khairnar , in that case should not be renamed  as "Pending SO Items", as this will cover both items to be Purchased as well as items to be manufactured.