Rename BOM and Work order fields
frappe/erpnext pull request #16209
Opened 2018-12-13 12:04 UTC by rohitwaghchaure

2018-12-14 07:17 UTC, Alchez requested changes

2018-12-14 07:17 UTC, Alchez commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +		}[cstr(self.docstatus or 0)]
`cstr` seems unnecessary. Just use integers as the keys?

2018-12-14 08:48 UTC, rmehta commented
Patch breaks

2018-12-18 09:15 UTC, rohitwaghchaure commented
Fixed!

2018-12-24 09:08 UTC, rmehta commented
Merging for now, but next time #NoTestNoMerge

2018-12-24 09:08 UTC, merged