[Minor] Divide by zero exception fix in item wise purchase register
frappe/erpnext pull request #16247
Opened 2018-12-20 06:35 UTC by deepeshgarg007

Do not prepare row if stock quantity is zero

2018-12-26 05:11 UTC, saurabh6790 commented
Can you add screenshots (before/after)?

2018-12-26 05:12 UTC, saurabh6790 submitted a review, later dismissed
Can you add screenshots (before/after)?

2018-12-26 05:54 UTC, deepeshgarg007 commented
@saurabh6790 Done.

2019-01-07 10:08 UTC, sagarvora approved these changes

2019-01-07 10:11 UTC, sagarvora requested changes

2019-01-07 10:11 UTC, sagarvora commented on erpnext/accounts/report/item_wise_purchase_register/item_wise_purchase_register.py
> +		if d.stock_qty:
you can reduce indentation to increase readability by doing something like:

```
if not d.stock_qty:
    continue
```

2019-01-08 02:39 UTC, sagarvora approved these changes

2019-01-08 03:04 UTC, merged