fix: checks for status in employee and for date range in upload attendance.
frappe/erpnext pull request #16279
Opened 2018-12-25 16:54 UTC by sahil28297

1. Earlier the status of an amployee can be set to 'Left' even though other employees are reporting to this employee, added checks to prevent this behaviour.
2. Earlier the range of dates added to the template were not checked for date of joining and relieving date. Now the range of dates added in the template are between the date of joining and relieving date.

2018-12-25 17:21 UTC, netchampfaris requested changes

2018-12-26 07:16 UTC, Alchez requested changes

2018-12-26 07:16 UTC, Alchez commented on erpnext/hr/doctype/employee/employee.py
> +				employee_names = []
Use list comprehension for this as well.

2018-12-26 08:27 UTC, Alchez requested changes

2018-12-27 07:17 UTC, sahil28297 commented on erpnext/hr/doctype/employee/employee.py
> +				link_to_employees = [frappe.utils.get_link_to_form('Employee', employee_name) for employee_name in employee_names]
will get complicated from readability point of view

2018-12-27 07:22 UTC, Alchez commented on erpnext/hr/doctype/employee/employee.py
> +				link_to_employees = [frappe.utils.get_link_to_form('Employee', employee_name) for employee_name in employee_names]
`link_to_employees = [frappe.utils.get_link_to_form('Employee', employee.name) for employee in reports_to]`?

2018-12-27 07:31 UTC, sahil28297 commented on erpnext/hr/doctype/employee/employee.py
> +				link_to_employees = [frappe.utils.get_link_to_form('Employee', employee_name) for employee_name in employee_names]
yeah, this works.

2018-12-28 11:44 UTC, netchampfaris approved these changes

2018-12-28 11:45 UTC, merged