[FIX]:VALIDATED QUALITY INSPECTION FOR DELIVERY NOTE QUALITY INSPECTI…
frappe/erpnext pull request #16289
Opened 2018-12-26 10:30 UTC by Anurag810

…ON MUST BE SUBMITTED

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2018-12-26 15:59 UTC, FinForceConsulting commented
@Anurag810, did you also factor the validation for Item in QI report with Item line. I'm referring to the second bug I reported in my comment
https://github.com/frappe/erpnext/issues/16250#issuecomment-449849981

2018-12-31 06:18 UTC, nabinhait requested changes

2018-12-31 06:18 UTC, nabinhait commented on erpnext/controllers/stock_controller.py
> +					frappe.msgprint(_("Quality Inspection: {0} is not submitted for the item: {1} in row {2}").format(link, d.item_code, d.idx))
Use `frappe.throw` with exception class

2019-01-07 09:58 UTC, sagarvora commented
https://github.com/frappe/erpnext/wiki/Coding-Standards#commit-messages
please write PR title in lowercase.

2019-01-22 05:19 UTC, nabinhait approved these changes

2019-01-22 05:19 UTC, merged