GSTR3B Report json creation and print format
frappe/erpnext pull request #16595
Opened 2019-02-07 03:53 UTC by deepeshgarg007

Json Creation:
![screenshot 2019-02-07 at 9 16 07 am](https://user-images.githubusercontent.com/42651287/52389545-f6d54880-2ab9-11e9-8daa-1f233a77c975.png)
Print Format:
![screenshot 2019-02-07 at 9 16 15 am](https://user-images.githubusercontent.com/42651287/52389550-fb99fc80-2ab9-11e9-9541-fc144ae46781.png)

2019-02-22 04:58 UTC, sagarvora commented on erpnext/regional/doctype/gstr_3b_report/gstr_3b_report.html
> +<h5>GSTIN:&nbsp{{ data.gstin }}</h5>
One space can be added without using `&nbsp`.

2019-02-22 04:59 UTC, sagarvora commented on erpnext/regional/doctype/gstr_3b_report/gstr_3b_report.html
> +<h5>3.1&nbsp&nbspDetails of Outward Supplies and inward supplies liable to reverse charge</h5>
Better to use `&nbsp;`

And have a space after it too, helps with readability.

2019-03-07 09:12 UTC, karthikeyan5 commented
since the `invoice_type` field was removed in the patch can you please update the same in the following reports:

- gst_purchase_register

2019-03-07 09:16 UTC, karthikeyan5 requested changes

2019-03-07 09:16 UTC, karthikeyan5 commented on erpnext/patches/v12_0/set_gst_category.py
> +			frappe.db.sql("UPDATE `tabPurchase Invoice` SET eligibility_for_itc = replace(eligibility_for_itc, %s, %s)", (old, new))
```suggestion
			frappe.db.sql("UPDATE `tabPurchase Invoice` SET eligibility_for_itc = %s where eligibility_for_itc = %s", (new, old))
```
this query would be faster to execute and is more correct in this use case.

2019-03-08 13:13 UTC, test2a commented
yay...... finally after such a long time, GSTR 3B is finally here. Good job

2019-03-15 08:05 UTC, karthikeyan5 submitted a review, later dismissed

2019-03-18 07:43 UTC, netchampfaris approved these changes

2019-03-18 07:52 UTC, netchampfaris requested changes

2019-03-18 07:52 UTC, netchampfaris commented on erpnext/regional/doctype/gstr_3b_report/gstr_3b_report.html
> +	<h3 class="text-center">GSTR3B-Form</h3>
Add Translated Strings

2019-03-21 15:16 UTC, netchampfaris approved these changes

2019-03-21 15:17 UTC, merged