fix: Selling and buying amount precision fix
frappe/erpnext pull request #16764
Opened 2019-02-24 03:44 UTC by deepeshgarg007

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-02-25 06:15 UTC, sagarvora commented
Don't we want to fetch the float precision from `System Settings` instead?

2019-02-26 04:56 UTC, deepeshgarg007 commented
@sagarvora Yes, currency_precision and float_precision should be fetched form system settings.
I have made the requested changes.

2019-02-26 06:14 UTC, Alchez requested changes

2019-02-26 06:14 UTC, Alchez commented on erpnext/accounts/report/gross_profit/gross_profit.py
> +		currency_precision = cint(frappe.db.get_default("currency_precision")) or 3
Maybe set these as global constants in the file? You won't need to pass it as an argument.

2019-02-26 06:14 UTC, Alchez commented on erpnext/accounts/report/gross_profit/gross_profit.py
> +		new_row.gross_profit = flt(new_row.base_amount - new_row.buying_amount, currency_precision)
This is over-indented.

2019-03-04 07:26 UTC, netchampfaris approved these changes

2019-03-04 07:26 UTC, merged