fix: set warehouse from def_warehouse_for_sales_return in sales return
frappe/erpnext pull request #16783
Opened 2019-02-26 09:29 UTC by sahil28297

If defalut_warehouse_for_sales_return is set in Company doctype then in sales return, the value of warehouse will be fetched from it.

![default_warehouse_for_sales_return](https://user-images.githubusercontent.com/37302950/53401835-9e1d0f80-39d6-11e9-87f2-aace7862e3af.gif)

2019-02-28 10:50 UTC, neilLasrado commented
Please also take into consideration this PR merged to develop -> https://github.com/frappe/erpnext/pull/15491

2019-04-11 06:17 UTC, nabinhait requested changes
@sahil28297 Please fix the conflict

2019-04-12 05:39 UTC, nabinhait approved these changes

2019-04-12 05:39 UTC, nabinhait commented
@Anurag810 Please fix the conflict

2019-05-02 16:20 UTC, nabinhait submitted a review, later dismissed

2019-05-03 03:56 UTC, nabinhait approved these changes

2019-05-03 03:57 UTC, merged