LMS Feature
frappe/erpnext pull request #16810
Opened 2019-02-28 12:56 UTC by scmmishra

[WIP] Depends on https://github.com/frappe/frappe/pull/6872

This PR adds LMS Feature for ERPNext

## Home Screen
![screenshot 2019-02-28 at 6 19 37 pm](https://user-images.githubusercontent.com/18097732/53567753-31487780-3b86-11e9-95b2-ae4175bf9440.png)

## Program Page
![screenshot 2019-02-28 at 6 19 44 pm](https://user-images.githubusercontent.com/18097732/53567754-31e10e00-3b86-11e9-906b-00c34aa54de5.png)

## Course Page
![screenshot 2019-02-28 at 6 20 01 pm](https://user-images.githubusercontent.com/18097732/53567757-31e10e00-3b86-11e9-8511-e30f935cadcc.png)

## Article Page
![screenshot 2019-02-28 at 6 20 09 pm](https://user-images.githubusercontent.com/18097732/53567759-3279a480-3b86-11e9-8d66-f0d51e9e4edf.png)

## Student Profile Page
![screenshot 2019-02-28 at 6 20 56 pm](https://user-images.githubusercontent.com/18097732/53567760-3279a480-3b86-11e9-98eb-111827870b3d.png)

2019-03-01 11:39 UTC, DawnPol commented
Good work taking place here

2019-03-18 06:15 UTC, scmmishra commented
ToDo
- [ ] Better Quiz Tracking
- [ ] Program still shows in dashboard quiz section even if it has no quizzes
- [ ] Use word subscribe instead of enroll
- [ ] Default Program in case featured is not set
- [ ] Default LMS Titles if LMS settings not set
- [ ] Improve number of quiz attempt tracking
- [ ] Don't show all topics in course list view card. Make a separate page
- [ ] Make description mandatory for Program page
- [ ] Fix program page intro video
- [ ] Fix Layout of the hero image
- [ ] Add restricted mode to program
- [ ] Add Plyr for Vue, hence support for Vimeo, Youtube and self hosted videos
- [ ] Don't allow saving of a question without setting a correct answer
- [ ] Disable tracking for Teacher/Administrator etc.
- [ ] Make Profile page navigatatble
- [ ] Display score in profile page
- [ ] Atleast have two options question

Wishlist
- [ ] Certificates after completing exam
- [ ] Icons for each content type
- [ ] Rich text editor in question description
- [ ] Multiple correct answer questions in quiz

2019-04-22 06:13 UTC, rmehta requested changes

2019-04-24 07:20 UTC, rmehta approved these changes

2019-04-24 07:20 UTC, merged