feat(Support): Service Level Agreements
frappe/erpnext pull request #16828
Opened 2019-03-04 07:56 UTC by hrwX

Code refactor for SLA
[16268](https://github.com/frappe/erpnext/pull/16268)

2019-03-14 03:12 UTC, surajshetty3416 requested changes
@hrwX
`time_to_resolve` & `time_to_respond` seems redundant to save on DB since we are already saving resolution_time & response_time.
We can use `resolution_time`/ `response_time` to dynamically show (or even realtime) the `time_to_resolve_left` on client site. This will also remove the overhead of calculating `time_to_resolve` and `time_to_respond` on an hourly basis

2019-03-14 08:49 UTC, rmehta commented
@hrwX docs?

2019-03-15 09:06 UTC, hrwX commented
> @hrwX docs?

https://github.com/frappe/erpnext_com/pull/275

2019-03-18 10:58 UTC, surajshetty3416 submitted a review, later dismissed

2019-03-18 11:21 UTC, netchampfaris submitted a review, later dismissed

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/hr/doctype/employee_group/test_employee_group.js
> +/* eslint-disable */
remove file

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/hr/doctype/holiday_list/test_holiday_list.py
> +class TestHolidayList(unittest.TestCase):
pointless test

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/issue/issue.js
> +	const customer = $('div[data-fieldname="customer"]');
Don't use generic selectors, this can fail in cases where the field is hidden in another page. Use the `frm` api to get the element

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/issue/issue.py
> +		frappe.throw('{} parameter is invalid'.format(parameter))
Translated string

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/service_level/service_level.py
> +				frappe.throw(_("Start Time can't be greater than End Time for "+ support_and_resolution.workday +"."))
Translated string is incorrect. Use {0} placeholder

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/service_level/test_service_level.js
> +/* eslint-disable */
remove file

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/service_level_agreement/service_level_agreement.js
> +					frm.add_child("support_and_resolution");
```suggestion
					frm.add_child("support_and_resolution", data.message.support_and_resolution);
```

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/service_level_agreement/service_level_agreement.py
> +				frappe.throw(_("There can't be two Default Service Level Agreements."))
```suggestion
				frappe.throw(_("A Default Service Level Agreement already exists."))
```

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/service_level_agreement/service_level_agreement.py
> +	service_level_agreements = frappe.get_list("Service Level Agreement", filters=[{"agreement_status": "Active"},{"default_service_level_agreement": "0"}])
```suggestion
	service_level_agreements = frappe.get_list("Service Level Agreement", filters={
		"agreement_status": "Active",
		"default_service_level_agreement": "0"
	})
```

2019-03-18 11:21 UTC, netchampfaris commented on erpnext/support/doctype/service_level_agreement/test_service_level_agreement.js
> +/* eslint-disable */
remove file

2019-03-19 11:12 UTC, surajshetty3416 approved these changes

2019-03-19 11:17 UTC, merged