feat(regional | India): auto-generate e-Way Bill JSON from Sales Invoice
frappe/erpnext pull request #16907
Opened 2019-03-12 19:02 UTC by sagarvora

**Screenshots**

**Transporter Info** section in Delivery Note (order changed):

![Screenshot from 2019-03-13 00-04-05](https://user-images.githubusercontent.com/16315650/54227017-03b7e280-4525-11e9-999c-6474928d9715.png)

**e-Way Bill No.** field in Sales Invoice (allowed on submit):

![Screenshot from 2019-03-13 00-02-44](https://user-images.githubusercontent.com/16315650/54227015-031f4c00-4525-11e9-8405-d821c1880c36.png)

**Generate e-Way Bill JSON** button in Sales Invoice:

![Screenshot from 2019-03-13 00-02-56](https://user-images.githubusercontent.com/16315650/54227016-03b7e280-4525-11e9-8922-f3a931018cb0.png)

**Transporter Info** section in Sales Invoice (custom fields in regional module):

![Screenshot from 2019-03-13 00-05-08](https://user-images.githubusercontent.com/16315650/54227018-03b7e280-4525-11e9-9add-8816367e2fcb.png)

**Bulk Action** for generating e-Way Bills from List View:

![Screenshot from 2019-03-13 00-05-33](https://user-images.githubusercontent.com/16315650/54227019-04507900-4525-11e9-925f-e23f9600d9f4.png)

E-waybill JSON Spec and Example (latest):
https://docs.ewaybillgst.gov.in/Documents/bulkewb/EWB_Attributes1611.xlsx

Example Output JSON File:
https://jsonbin.io/5c880189adeb832d3ec6e5cf

Tested working on ewaybillgst.gov.in

2019-03-17 08:09 UTC, sagarvora commented
Documentation PR: https://github.com/frappe/erpnext_com/pull/280

2019-03-19 08:52 UTC, nabinhait requested changes
- Write a patch to make new custom fields
- Test cases

2019-03-19 08:52 UTC, nabinhait commented on erpnext/regional/india/utils.py
> +def generate_ewb_json(dt, dn):
split into smaller function

2019-03-19 08:52 UTC, nabinhait commented on erpnext/accounts/doctype/sales_invoice/regional/india.js
> +			frm.add_custom_button('Generate e-Way Bill JSON', () => {
Put it under "Make" button

2019-05-01 14:37 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/sales_invoice/regional/india.js
> +			frm.add_custom_button('Generate e-Way Bill JSON', () => {
Fixed

2019-05-02 16:24 UTC, nabinhait approved these changes

2019-05-02 16:25 UTC, merged