fix: Make Customer and lead field dynamic
frappe/erpnext pull request #17097
Opened 2019-04-01 12:47 UTC by deepeshgarg007

There are two seperate fields for Customer and Lead which causes permission issues.
Using dynamic link to resolve this.

2019-04-02 09:03 UTC, Alchez requested changes

2019-04-02 09:03 UTC, Alchez commented on erpnext/selling/doctype/quotation/quotation.py
> +		if self.quotation_to == "Lead":
Also check if `self.customer_lead` is entered, otherwise `get_doc` will break.

2019-04-08 07:13 UTC, Alchez submitted a review, later dismissed

2019-04-08 07:13 UTC, Alchez commented on erpnext/selling/doctype/customer/customer.py
> +		for d in frappe.get_all('Opportunity', {'lead': self.lead_name}):
This should be inside the if check. If there is no lead name, the `get_all` will return ALL opportunities.

2019-04-25 06:44 UTC, netchampfaris requested changes

2019-04-25 06:44 UTC, netchampfaris commented on erpnext/crm/doctype/opportunity/opportunity.js
> +			frm.set_df_property("customer_lead", "label", "Customer");
```suggestion
			frm.set_df_property("customer_lead", "label", frm.doc.opportunity_from);
```

2019-04-25 06:44 UTC, netchampfaris commented on erpnext/crm/doctype/opportunity/opportunity.py
> +		if not self.opportunity_from:
Make the field mandatory, no need to check here.

2019-04-25 06:44 UTC, netchampfaris commented on erpnext/crm/doctype/opportunity/opportunity.py
> +			self.customer_name = frappe.db.get_value("Customer", self.customer_lead, "customer_name")
Use fetch_from

2019-04-25 06:44 UTC, netchampfaris commented on erpnext/crm/doctype/opportunity/opportunity.py
> +			if not self.customer_lead:
Make the field mandatory, no need to check here

2019-04-25 06:44 UTC, netchampfaris commented on erpnext/crm/doctype/opportunity/opportunity.py
> +		party_account_currency = get_party_account_currency("Customer", quotation.customer_lead,
Check if Quotation is from Customer

2019-04-25 06:44 UTC, netchampfaris commented on erpnext/selling/doctype/customer/customer.py
> +		for d in frappe.get_all('Opportunity', {'customer_lead': self.lead_name}):
Why exclude Quotation?

2019-04-28 15:11 UTC, netchampfaris approved these changes

2019-04-28 15:16 UTC, merged