fix(India): run patch for GST custom fields
frappe/erpnext pull request #17149
Opened 2019-04-05 12:16 UTC by hrwX

run patch for newly added GST custom fields

2019-04-18 02:34 UTC, deepeshgarg007 requested changes
@hrwX please check if the country of the the company is India and then only create the custom field

2019-05-01 05:34 UTC, nabinhait requested changes

2019-05-01 05:34 UTC, nabinhait commented on erpnext/patches/v10_0/gst_hsn_fixes.py
> +def execute():
The patch should only run if any of the company belongs to India

2019-05-02 16:26 UTC, nabinhait approved these changes

2019-05-03 03:56 UTC, merged