feat(accounts): validate Bank Account's IBAN
frappe/erpnext pull request #17316
Opened 2019-04-22 02:51 UTC by barredterra

Add validation of IBAN to Bank Account. 

Validation algorithm:

1. Cut off the first four characters and append them

    `DE91100000000123456789` becomes `100000000123456789DE91`

2. Replace all characters with their position in the alphabet + 9

    `100000000123456789DE91` becomes `100000000123456789131491`

3. Check if this integer mod 97 equals 1.

    `100000000123456789131491 % 97 == 1`

![screencast](https://user-images.githubusercontent.com/14891507/56480364-09a4ca00-64ba-11e9-90e1-419c5d816289.gif)

2019-04-22 10:07 UTC, nabinhait requested changes
Check travis, it' failing in case IBAN is missing.

2019-04-22 10:40 UTC, barredterra commented
@nabinhait thanks, fixed it.

2019-04-24 15:20 UTC, barredterra commented
@nabinhait works, finally. Sorry about the failing tests, next time i will check them before opening a PR.

2019-04-24 17:26 UTC, nabinhait approved these changes

2019-04-24 17:27 UTC, merged