PR for Statement of Accounts
frappe/erpnext pull request #17356
Opened 2019-04-24 06:07 UTC by jiloysss

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-04-24 10:39 UTC, deepeshgarg007 requested changes

2019-04-24 10:39 UTC, deepeshgarg007 commented on erpnext/accounts/report/statement_of_accounts_receivable/statement_of_accounts_receivable.py
> +                print("XXXXXXXXXXXXXXXXXXXXXXXXXXx")
Please remove print statements

2019-04-24 10:39 UTC, deepeshgarg007 commented on erpnext/accounts/report/statement_of_accounts_receivable/statement_of_accounts_receivable.py
> +                    print("ROOOOOOOOOOOW")
Remove print statements

2019-04-24 10:39 UTC, deepeshgarg007 commented on erpnext/accounts/report/statement_of_accounts_receivable/statement_of_accounts_receivable.py
> +                    #if self.filters.get(scrub(args.get("party_type"))):
Remove commented code

2019-06-12 09:17 UTC, jaywks commented
What is needed to merge this?

2019-06-21 04:00 UTC, rmehta requested changes

2019-06-21 04:00 UTC, rmehta commented on erpnext/accounts/report/statement_of_accounts_receivable/statement_of_accounts_receivable.py
> +    def prepare_conditions(self, party_type):
Indentation using tabs

https://github.com/frappe/erpnext/wiki/Coding-Standards#use-simple-indenting

2019-06-21 04:00 UTC, rmehta commented on erpnext/accounts/report/statement_of_accounts_receivable/statement_of_accounts_receivable.py
> +        columns = [_("Posting Date**") + ":Date:80",
please use new JSON format for column definitions

2019-07-22 07:19 UTC, jaywks commented
@jiloysss please address the changes requested thank you very much for your effort.

2019-10-10 10:16 UTC, closed without merging