adds ability to have zero quantity items on transactions
frappe/erpnext pull request #17401
Opened 2019-04-28 03:21 UTC by tukutela

Includes ability to alter turn it on or off via the Account Settings page.

2019-05-01 06:15 UTC, nabinhait reviewed
Can you please explain the use case?

2019-05-01 06:16 UTC, nabinhait requested changes

2019-05-01 06:16 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +			if cint(self.allocate_advances_automatically):
It should not be changed

2019-05-01 21:45 UTC, tukutela commented
Hi Nabin, thanks for reviewing! 

As for use-cases we have a few, but the main reason is that one of my clients is a language translation company in Chicago, a client uploads a document and they translate it. In order to quote for the work (and eventually invoice for it) they run it through a process of collating the number of words, duplicates, previous matches, and something close called a fuzzy match. Essentially you run the file through a database of something you've done for that client previously, saves a bit of money as the translation tool does the work. So the lines on a transaction is the number of words, then the different types of matches the importation process found which are the discounts. Giving you a price per language for a group of documents. (Hope all this makes sense). 

But to answer your question a little more succinctly, we need to show that the files provided by the client had zero repetition and/or fuzzy matches for some languages (eg. we haven't done any work for them in this language, but others we have). Zero line quantities are pretty important to this particular business, for new clients they appear more often, and even for long-term existing ones working in a new language, or with new subject matter.  

Re: As soon as I figure out how to do an update of accounts_controller.py within this context, I'll update it :) Thanks for picking that up, I didn't intend for that edit.

2019-05-01 21:46 UTC, tukutela commented on erpnext/controllers/accounts_controller.py
> +			if cint(self.allocate_advances_automatically):
you are absolutely right! my apologies.

2019-05-13 03:03 UTC, tukutela commented
Hi Nabin, could I ask that you review this again? Thankyou.

2019-05-22 04:09 UTC, tukutela reviewed
Hoping this gets reviewed again, please....

2019-06-21 04:38 UTC, tukutela commented
keeping this from being 'stale'

2019-07-15 21:09 UTC, CVSaritama commented
> Includes ability to alter turn it on or off via the Account Settings page.

In V10 we added products with zero amount for offers, but now it is impossible. We need an alternative.

2019-07-23 09:44 UTC, closed without merging

2020-05-11 16:25 UTC, iMoshi commented
Anyone has a version for v12, or v13? :) 

Allowing quantity of 0 item on transactions should be allowed. Many times users import and export quotations, opportunities etc from branches, on spreadsheets, that have no internet access. For example, from mining field.

2023-08-30 12:56 UTC, zoharyExponent commented
is this now included in V14 ?

2024-01-19 07:49 UTC, jcagbay commented
No, I just tested V14.