feat(regional): Bank remittance report
frappe/erpnext pull request #17524
Opened 2019-05-08 11:07 UTC by Mangesh-Khairnar

- Allow creation of payment order based on payment entry
![creating_payment_entry_from_payment_order](https://user-images.githubusercontent.com/14824451/57370310-7b189400-71ad-11e9-8068-57d0942a4f36.gif)

- Add a generate txt report for bank remittance for Indian clients and this will generate and attach the text file to the doc and also, initiate download.
![Screenshot 2019-05-08 at 4 30 03 PM](https://user-images.githubusercontent.com/14824451/57370817-a9e33a00-71ae-11e9-9312-70e33a602e0e.png)

- Text report generated according to the multiband format followed by banks
![Screenshot 2019-05-08 at 4 28 04 PM](https://user-images.githubusercontent.com/14824451/57370668-5113a180-71ae-11e9-8858-b5c680185e9f.png)

- custom fields in company added for india specific client
![Screenshot 2019-05-06 at 4 16 27 PM](https://user-images.githubusercontent.com/14824451/57370556-085be880-71ae-11e9-9c41-68a0b9db9370.png)

2019-05-13 11:20 UTC, netchampfaris requested changes

2019-05-13 11:20 UTC, netchampfaris commented on erpnext/regional/india/bank_remittance_txt.py
> +		amount=str(format(ref_doc.amount, '.2f'))[:13],
Dont clip amount

2019-05-13 11:20 UTC, netchampfaris commented on erpnext/regional/india/bank_remittance_txt.py
> +
validate mandatory values from payment order

2019-05-14 13:05 UTC, Mangesh-Khairnar commented on erpnext/regional/india/bank_remittance_txt.py
> +		amount=str(format(ref_doc.amount, '.2f'))[:13],
fixed

2019-05-15 06:31 UTC, netchampfaris requested changes

2019-05-15 06:31 UTC, netchampfaris commented on erpnext/regional/india/bank_remittance_txt.py
> +		frappe.throw(_("Amount for a single transaction is more than maximum allowed amount, create a separate payment order by splitting the transactions"))
Specify how much is the maximum amount in the message

2019-05-15 06:31 UTC, netchampfaris commented on erpnext/regional/india/bank_remittance_txt.py
> +		frappe.throw(_("%s is mandatory for generating remittance payments, set the field and try again" % attr))
Use {0} placeholder in translated strings

2019-05-15 06:31 UTC, netchampfaris commented on erpnext/regional/india/bank_remittance_txt.py
> +		frappe.throw("%s field is limited to size %d" % (label, max_size))
Add translated string

2019-05-15 06:31 UTC, netchampfaris commented on erpnext/regional/india/bank_remittance_txt.py
> +	print(batch)
Remove print

2019-05-20 08:14 UTC, netchampfaris approved these changes

2019-05-20 09:30 UTC, merged