feat: Call Popup
frappe/erpnext pull request #17763
Opened 2019-05-27 10:51 UTC by surajshetty3416

2019-06-17 04:56 UTC, surajshetty3416 commented
[WIP] docs https://github.com/frappe/erpnext_com/pull/392

2019-06-17 07:46 UTC, netchampfaris requested changes

2019-06-17 07:46 UTC, netchampfaris commented on erpnext/crm/doctype/utils.py
> +	number = number[-10:]
Why only 10 digit phone numbers?

2019-06-17 07:46 UTC, netchampfaris commented on erpnext/crm/doctype/utils.py
> +		employee_emails += [e.user_id for e in frappe.get_doc('Employee Group', group.employee_group).employee_list]
why not query the child table directly?

2019-06-17 07:46 UTC, netchampfaris commented on erpnext/erpnext_integrations/exotel_integration.py
> +	numbers = 'some number'
?

2019-07-01 06:53 UTC, netchampfaris requested changes

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/crm/doctype/utils.py
> +	available_employee_groups = frappe.db.sql_list("""SELECT `employee_group`
`frappe.get_all` ?

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/erpnext_integrations/exotel_integration.py
> +def handle_incoming_call(*args, **kwargs):
`*args` unused

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/erpnext_integrations/exotel_integration.py
> +	elif create_new_if_not_found:
put this part in `create_call_log`

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/erpnext_integrations/exotel_integration.py
> +def get_call_log(call_payload, create_new_if_not_found=True):
`get_call_log` should not create a call log

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/public/js/call_popup/call_popup.js
> +		wrapper.append('<div class="text-muted"> Loading... </div>');
translation

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/public/js/call_popup/call_popup.js
> +					title="Make New Contact">
translation

2019-07-01 06:53 UTC, netchampfaris commented on erpnext/public/js/call_popup/call_popup.js
> +			const comm_field = this.dialog.fields_dict["last_communication"];
`this.dialog.get_field('last_communication')`

2019-07-01 11:04 UTC, netchampfaris approved these changes

2019-07-01 11:06 UTC, merged