feat: Custom configurable accounting dimensions
frappe/erpnext pull request #17769
Opened 2019-05-28 06:53 UTC by deepeshgarg007

2019-05-30 12:03 UTC, rmehta requested changes

2019-05-30 12:03 UTC, rmehta commented on erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py
> +			frappe.enqueue(delete_accounting_dimension, doc=self)
show progress

2019-05-30 12:03 UTC, rmehta commented on erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py
> +			df.update({
break into smaller function `add_to_budget`

2019-05-30 12:03 UTC, rmehta commented on erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py
> +def get_doclist():
`get_doctypes_with_dimensions`

2019-06-03 11:30 UTC, rmehta approved these changes

2019-06-03 11:30 UTC, merged

2019-06-06 12:19 UTC, jaichavan commented
Awesome!!!

2020-10-04 00:54 UTC, Muhammadinaam commented
Very nice feature. I have a small question. If we use the dimension feature for different branches of a company then what will be the effect on inventory valuation. We want the inventory valuation (Perpetual FIFO of Moving Average) of each branch to be separate. Is it possible with the current feature?