fix: Dashboards for doctypes in accounts module
frappe/erpnext pull request #17801
Opened 2019-05-30 06:45 UTC by deepeshgarg007

2019-05-30 12:07 UTC, rmehta requested changes
Add report link in dashboard (general feature)

2019-05-30 12:07 UTC, rmehta commented on erpnext/accounts/doctype/pos_profile/pos_profile_dashboard.py
> +				'label': _('Sales Invoices'),
heading not required for single entries

2019-06-03 08:44 UTC, nabinhait requested changes

2019-06-03 08:44 UTC, nabinhait commented on erpnext/accounts/doctype/bank/bank_dashboard.py
> +				'items': ['Bank Account', 'Bank Statement Transaction Entry', 'Bank Guarantee']
Remove 'Bank Statement Transaction Entry', it is not used anymore. I will write a patch to delete all related docs.

2019-06-12 11:45 UTC, merged