fix: Usability fixes to Serial No and batch selector
frappe/erpnext pull request #18071
Opened 2019-06-26 05:53 UTC by deepeshgarg007

Port Of: https://github.com/frappe/erpnext/pull/18070

2019-06-27 09:33 UTC, rmehta requested changes

2019-06-27 09:33 UTC, rmehta commented on erpnext/selling/sales_common.js
> +			{
`{` on the same line as if

2019-06-27 09:34 UTC, rmehta requested changes

2019-06-27 09:34 UTC, rmehta commented on erpnext/selling/sales_common.js
> +				if (doc.doctype === 'Sales Invoice' && (!doc.update_stock))
please add comments

2019-06-28 08:37 UTC, nabinhait approved these changes

2019-06-28 08:38 UTC, merged