patch: reloads all newly created docs in v12
frappe/erpnext pull request #18148
Opened 2019-07-03 12:25 UTC by Mangesh-Khairnar

- Fixes migration from v11 to v12
- On migrating from v11 to v12 certain doctypes are not reloaded, which is breaking the migration on adding custom fields.

2019-07-03 13:43 UTC, Thunderbottom approved these changes

2019-07-03 17:51 UTC, Thunderbottom requested changes

2019-07-03 17:51 UTC, Thunderbottom commented on erpnext/patches/v12_0/make_custom_fields_for_bank_remittance.py
> +    reload_doc("accounts", "doctype", "tax_category")
`frappe.reload_doc()` and not `reload_doc()`

same goes for the next line as well

2019-07-04 07:20 UTC, nabinhait approved these changes

2019-07-04 07:20 UTC, merged