fix: enable track changes for issue doctype
frappe/erpnext pull request #18260
Opened 2019-07-11 13:12 UTC by DeeMysterio

**Additions:** Enabled "Track Changes" for Issue DocType

2019-07-11 13:26 UTC, Anurag810 requested changes

2019-07-11 13:26 UTC, Anurag810 commented on erpnext/support/doctype/issue/issue.json
> + "track_changes": 1,
No need to change this on the doctype level. You track changes by using ```customize form``` in **Menu Dropdown**
![Screenshot 2019-07-11 at 6 53 26 PM](https://user-images.githubusercontent.com/32095923/61054515-38717300-a40d-11e9-9423-a7f5090e98c3.png)

2019-07-14 07:06 UTC, hrwX commented
@DeeMysterio You can use customize form to do the same. "Track Changes" should be enabled by the user if he/she wants to see it.

2019-07-14 07:06 UTC, hrwX commented
If you have any other views, feel free to reopen it

2019-07-14 07:06 UTC, closed without merging