feat: added default dashboard fixtures
frappe/erpnext pull request #18360
Opened 2019-07-16 10:33 UTC by scmmishra

Create default account dashboards when installing ERPNext.

**Preview:**
<img width="1440" alt="Screenshot 2019-07-16 at 4 02 35 PM" src="https://user-images.githubusercontent.com/18097732/61287720-257eea00-a7e3-11e9-80d8-cd47fea5e422.png">

2019-07-16 11:12 UTC, adityahase requested changes

2019-07-16 11:12 UTC, adityahase commented on erpnext/setup/setup_wizard/data/dashboard_charts.py
> +				"owner": "Administrator",
Can we get rid of this?

2019-07-17 15:05 UTC, adityahase approved these changes

2019-07-17 15:05 UTC, adityahase commented on erpnext/setup/setup_wizard/operations/install_fixtures.py
> -				return doc
Were you high?

2019-07-18 05:09 UTC, scmmishra commented on erpnext/setup/setup_wizard/operations/install_fixtures.py
> -				return doc
Someone else probably was.

2019-07-18 06:54 UTC, scmmishra commented on erpnext/setup/setup_wizard/data/dashboard_charts.py
> +				"owner": "Administrator",
The empty fields? Removed them!

2019-07-19 12:57 UTC, adityahase approved these changes

2019-07-22 11:42 UTC, nabinhait approved these changes

2019-07-22 11:42 UTC, merged