feat(Contacts): Multiple Emails in a Contact
frappe/erpnext pull request #18675
Opened 2019-08-08 18:22 UTC by hrwX

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-09-02 01:01 UTC, surajshetty3416 requested changes

2019-09-02 01:01 UTC, surajshetty3416 commented on erpnext/communication/doctype/call_log/call_log.py
> +		numbers = [nos.phone for nos in doc.phone_nos]
```suggestion
		numbers = [d.phone for d in doc.phone_nos]
```

2019-09-02 01:01 UTC, surajshetty3416 commented on erpnext/crm/doctype/opportunity/test_opportunity.py
> +		d = frappe.get_doc({
```suggestion
		contact = frappe.get_doc({
```

2019-09-02 01:01 UTC, surajshetty3416 commented on erpnext/public/js/templates/contact_list.html
> +				{%= __("Email ") %}: {%= contact_list[i].email_id %}<span class="text-muted"> ({%= __("Primary") %})</span><br>
```suggestion
				{%= __("Email") %}: {%= contact_list[i].email_id %}<span class="text-muted"> ({%= __("Primary") %})</span><br>
```

Not good for translation

translation for `__('Email')` will not be equal to `__('Email ')`

please fix `__('Phone ')` as well

2019-09-02 07:08 UTC, surajshetty3416 submitted a review, later dismissed

2019-09-02 07:45 UTC, surajshetty3416 commented
Fix needed in pos.py (line 224) as well

2019-09-02 08:06 UTC, surajshetty3416 approved these changes

2019-09-02 10:27 UTC, merged

2019-09-05 07:46 UTC, muchai commented
There's a minor bug on this, handling apostrophes (') in emails: https://github.com/frappe/erpnext/issues/18927