feat: Added 'barcode' field in BOM and 'BOM barcode' field in Work Order
frappe/erpnext pull request #18721
Opened 2019-08-13 17:35 UTC by marination

- **BOM** now includes a barcode field to register barcodes pertaining to that BOM

![image](https://user-images.githubusercontent.com/25857446/62961182-e65fab00-be19-11e9-8170-60b3789a5e0a.png)

- **Work Order** has an additional **BOM Barcode** field wherein the barcode number can be inserted and the concerned BOM No. and Item code will be fetched

![bom](https://user-images.githubusercontent.com/25857446/62963031-cb8f3580-be1d-11e9-9786-5ac525fd6f17.gif)

- Inappropriate barcodes will also be taken care of
![errorbom](https://user-images.githubusercontent.com/25857446/62963474-b2d34f80-be1e-11e9-8372-e5feeaf146df.gif)

2019-08-14 11:39 UTC, deepeshgarg007 requested changes

2019-08-14 11:39 UTC, deepeshgarg007 commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +		if bom == None :
```suggestion
		if not bom :
```

2019-08-14 11:39 UTC, deepeshgarg007 commented on erpnext/manufacturing/doctype/work_order/work_order.js
> +				frm.set_value("production_item","");
```suggestion
				frm.set_value("production_item", "");
```
add single space after comma everywhere

2019-08-14 11:39 UTC, deepeshgarg007 commented on erpnext/manufacturing/doctype/work_order/work_order.js
> +			if (r.message){
```suggestion
			if (r.message) {
```

2019-08-14 11:39 UTC, deepeshgarg007 commented on erpnext/manufacturing/doctype/work_order/work_order.py
> +	def get_item_bom_from_barcode(self,barcode):
Make this function a whitelisted function
There is no need to pass the work order doc since it it not used anywhere in this function

2019-08-21 11:44 UTC, nabinhait commented
@marination Does not look like a generic requirement, make it part of custom app

2019-08-21 11:44 UTC, closed without merging