Immutable ledger v3
frappe/erpnext pull request #18740
Opened 2019-08-14 13:09 UTC by deepeshgarg007

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-11-26 02:40 UTC, deepeshgarg007 commented
Do not close

2019-12-27 15:24 UTC, Don-Leopardo commented on erpnext/patches/v12_0/update_is_cancelled_field.py
> +from erpnext.regional.india.setup import make_custom_fields
Unused import? And maybe you should print the exception in te execute. None should be pass? isn't it more clear?

2020-04-07 11:49 UTC, nabinhait requested changes
Travis failing

2020-04-09 06:19 UTC, nabinhait requested changes

2020-04-09 06:19 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +				advance['amount'] = - advance['amount']
What does it mean?

2020-04-09 06:19 UTC, nabinhait commented on erpnext/stock/stock_balance.py
> +def repost_all_stock_vouchers():
remove this function

2020-04-09 06:19 UTC, nabinhait commented on erpnext/patches/v12_0/update_is_cancelled_field.py
> +		None
pass

2020-04-09 06:23 UTC, nabinhait requested changes
Simplify `build` method in stock_ledger.py

2020-04-09 06:23 UTC, nabinhait commented on erpnext/controllers/stock_controller.py
> -				update_gl_entries_after(self.posting_date, self.posting_time, warehouses, items,
remove update_gl_entries_after function

2020-04-30 05:08 UTC, nabinhait approved these changes

2020-04-30 05:08 UTC, merged