fix: leave balance reports
frappe/erpnext pull request #18984
Opened 2019-09-10 10:16 UTC by Mangesh-Khairnar

Fixes
- opening leave balance was fetching the leave allocation. This change fetches the leave balance based on the leave application.
- Checks for leave approvers in employee leave balance summary and display only those records for which user is a leave approver(department approver).

2019-09-11 04:58 UTC, surajshetty3416 requested changes

2019-09-11 04:58 UTC, surajshetty3416 commented on erpnext/hr/report/employee_leave_balance_summary/employee_leave_balance_summary.py
> +	return frappe._dict(frappe.db.sql('''
Use ORM.

For child departments use `get_descendants`

2019-09-11 05:15 UTC, nabinhait requested changes

2019-09-11 05:15 UTC, nabinhait commented on erpnext/hr/report/employee_leave_balance/employee_leave_balance.py
> +		leave_approvers = department_approver_map.get(employee.department_name, [])
Also consider `leave_approver` set on Employee master (introduced last week).

2019-09-11 05:15 UTC, nabinhait commented on erpnext/hr/report/employee_leave_balance_summary/employee_leave_balance_summary.py
> +			if (len(leave_approvers) and user in leave_approvers) or (user in ["Administrator", employee.user_id]) \
Also consider leave_approver set on Employee master (introduced last week).

2019-09-11 13:43 UTC, nabinhait requested changes

2019-09-11 13:43 UTC, nabinhait commented on erpnext/hr/report/employee_leave_balance/employee_leave_balance.py
> +		leave_approvers = employee.leave_approver or department_approver_map.get(employee.department_name, [])
Leave Approver mentioned in Employee is default approver. All the other approvers for the department should also be able to view the report.

You should just add employee.leave_approver to department_leave_approvers list, if not exists.

2019-09-12 04:33 UTC, surajshetty3416 requested changes

2019-09-12 04:33 UTC, surajshetty3416 commented on erpnext/hr/report/employee_leave_balance_summary/employee_leave_balance_summary.py
> +	department_list = frappe.db.sql_list(''' SELECT name FROM `tabDepartment` WHERE disabled=0{0}'''.format(conditions)) #nosec
This also can be converted to ORM. Why raw query?

2019-09-12 19:03 UTC, Mangesh-Khairnar commented on erpnext/hr/report/employee_leave_balance_summary/employee_leave_balance_summary.py
> +	department_list = frappe.db.sql_list(''' SELECT name FROM `tabDepartment` WHERE disabled=0{0}'''.format(conditions)) #nosec
no equivalent ORM with similar functionality

2019-09-12 19:05 UTC, Mangesh-Khairnar commented on erpnext/hr/report/employee_leave_balance/employee_leave_balance.py
> +		leave_approvers = employee.leave_approver or department_approver_map.get(employee.department_name, [])
I assumed leave approver in employee was overriding leave approver in the department. Added corrected changes.

2019-09-13 05:37 UTC, nabinhait approved these changes

2019-09-13 05:37 UTC, merged

2019-09-18 07:10 UTC, muchai commented
An error on these two reports: https://github.com/frappe/erpnext/issues/19100