feat: Loan management and accounting
frappe/erpnext pull request #19035
Opened 2019-09-13 04:22 UTC by deepeshgarg007

PR for the feature request: https://github.com/frappe/erpnext/issues/18997

Documentation PR: https://github.com/frappe/erpnext_com/pull/573

2019-09-18 04:37 UTC, rmehta requested changes
Great work, needs a lot of commenting!

2019-09-18 04:37 UTC, rmehta commented on erpnext/loan_management/doctype/loan_disbursement/loan_disbursement.json
> + "autoname": "LD-.#####",
Let all loan series start with **LM**, since loan management is now a module. example: `LM-DIS-.###`

2019-09-18 04:37 UTC, rmehta commented on erpnext/loan_management/doctype/loan_interest_accrual/loan_interest_accrual.py
> +	open_loans = frappe.get_all("Loan",
function is too big (try 10 LOC)

2019-09-18 04:37 UTC, rmehta commented on erpnext/loan_management/doctype/loan_interest_accrual/loan_interest_accrual.py
> +
Add a comment with example and real numbers, so its easier to debug / review. Say loan is worth 1000, date of disbursement is X, accrual date is Y, so interest accrued should be Z)

2019-09-18 04:37 UTC, rmehta commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +				"against_voucher_type": "Loan",
last 4 properties are common, commonify the code?

2019-09-18 04:37 UTC, rmehta commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +def get_amounts(amounts, against_loan, loan_type, posting_date):
add comments with an example

2019-09-18 04:37 UTC, rmehta commented on erpnext/loan_management/doctype/loan_interest_accrual/test_loan_interest_accrual.py
> +	pass
tests?

2019-12-24 04:46 UTC, rmehta commented
@nabinhait please review overall functionality, since I have been part of design not the best person to review

2020-01-30 10:23 UTC, nabinhait reviewed
- GL entry against party
- Penalty % label (per day)
  - Status cannot be changed after creation of Loan against loan application
- Hide “Repayment Period in Months” if method = Repay Fixed Amount per Period
- Penalty Interest Rate description
- Filter “Payment Account” based on Bank/Cash
- Fetch payment account based on mode-of-payment
- Disabled field - allow on submit
- Accounts editable in loan
- posting date <= disbursement date <= Repayment start date
- Accrue interest on last date of the month
- Calculate principal and interest (of EMI) based on last months interest
- Pass posting date in disbursement GL entry
- Post party in loan gle
- Naming series for Process Loan Interest Accrual
- On cancel for Process Loan Interest Accrual
- Calculate Payable Principal Amount
- Create loan repay button after partial disbursement
- Prepare schedule after extra repayment
- Rename “Total Payment” to “Total Payable Amount”

2020-02-25 10:02 UTC, nabinhait requested changes

2020-02-25 10:02 UTC, nabinhait commented on erpnext/config/loan_management.py
> +					"description": _("Loans provided to customers and employees."),
Application of loans from customer and empoyees

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.js
> +		frm.set_df_property("repayment_method", 'reqd', frm.doc.is_term_loan);
`toggle_reqd` and `toggle_display` is better functions for this

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.js
> +                    "loan_application": frm.doc.loan_application
indentation?

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.js
> +						frm.set_value("is_secured_loan", r.message.is_secured_loan);
Instead of writing `set_value` so many times, use a list of fields and use `set_value` inside for loop.

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.py
> +			frappe.throw("Repayment Start Date is mandatory for term loans")
```suggestion
			frappe.throw(_("Repayment Start Date is mandatory for term loans"))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.py
> +			frappe.throw("Loan Security Pledge is mandatory for secured loan")
```suggestion
			frappe.throw(_("Loan Security Pledge is mandatory for secured loan"))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.py
> +			msg = _("Loan amount cannot be greater than {0}".format(self.maximum_loan_value))
```suggestion
			msg = _("Loan amount cannot be greater than {0}").format(self.maximum_loan_value)
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.py
> +			frappe.throw("Loan amount is mandatory")
```suggestion
			frappe.throw(_("Loan amount is mandatory"))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan/loan.py
> +		frappe.throw("Repayment Method is mandatory for term loans")
```suggestion
		frappe.throw(_("Repayment Method is mandatory for term loans"))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_disbursement/loan_disbursement.py
> +			frappe.throw("Disbursed Amount cannot be greater than loan amount")
```suggestion
			frappe.throw(_("Disbursed Amount cannot be greater than loan amount"))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_disbursement/loan_disbursement.py
> +		frappe.db.set_value("Loan", self.against_loan, "disbursed_amount", disbursed_amount)
```suggestion
		frappe.db.set_value("Loan", self.against_loan, {"disbursement_date": self.disbursement_date, "disbursed_amount": disbursed_amount})
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_interest_accrual/loan_interest_accrual.py
> +				"remarks": "Against Loan:" + self.loan,
```suggestion
				"remarks": _("Against Loan:") + self.loan,
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_interest_accrual/loan_interest_accrual.py
> +				"remarks": "Against Loan:" + self.loan,
```suggestion
				"remarks": _("Against Loan:") + self.loan,
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +				"remarks": "Against Loan:" + self.against_loan,
```suggestion
				"remarks": _("Against Loan:") + self.against_loan,
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +				"remarks": "Against Loan:" + self.against_loan,
```suggestion
				"remarks": _("Against Loan:") + self.against_loan,
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +				"remarks": "Against Loan:" + self.against_loan,
```suggestion
				"remarks": _("Against Loan:") + self.against_loan,
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +		gle_map.append(
`if self.penalty_amount:`?

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_security_pledge/loan_security_pledge.js
> +		frappe.model.set_value(cdt, cdn, 'post_haircut_amount', cint(row.amount - (row.amount * row.haircut/100)));
Should it be `flt` instead of `cint`?

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_security_pledge/loan_security_pledge.js
> +			maximum_amount += item.post_haircut_amount;
```suggestion
			maximum_amount += flt(item.post_haircut_amount);
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_security_price/loan_security_price.py
> +			frappe.throw("Loan Security Price overlapping with {0}".format(existing_loan_security[0][0]))
```suggestion
			frappe.throw(_("Loan Security Price overlapping with {0}").format(existing_loan_security[0][0]))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_security_price/loan_security_price.py
> +		frappe.throw("No valid <b>Loan Security Price</b> found for <b>{0}</b>".format(loan_security))
```suggestion
		frappe.throw(_("No valid Loan Security Price found for {0}").format(frappe.bold(loan_security)))
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_security_shortfall/loan_security_shortfall.py
> +		ltv_shortfall.save()
```
if existing_shortfall:
	ltv_shortfall = frappe.get_doc("Loan Security Shortfall", existing_shortfall)
else:
	ltv_shortfall = frappe.new_doc("Loan Security Shortfall")
	ltv_shortfall.loan = loan
ltv_shortfall.shortfall_time = get_datetime()
ltv_shortfall.loan_amount = value["loan_amount"]
ltv_shortfall.security_value = value["security_value"]
ltv_shortfall.shortfall_amount = value["loan_amount"] - value["security_value"]
ltv_shortfall.process_loan_security_shortfall = process_loan_security_shortfall
ltv_shortfall.save()
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_security_unpledge/loan_security_unpledge.py
> +				frappe.throw("Cannot unpledge more than {0} qty of {0}".format(frappe.bold(pledged_qty),
```suggestion
				frappe.throw(_("Cannot unpledge more than {0} qty of {1}").format(frappe.bold(pledged_qty),
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/loan_type/loan_type.py
> +				frappe.throw(_("Account {0} does not belongs to company {1}").format(frappe.bold(self.get(fieldname)),
```suggestion
				frappe.throw(_("Account {0} does not belong to company {1}").format(frappe.bold(self.get(fieldname)),
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/doctype/sanctioned_loan_amount/sanctioned_loan_amount.py
> +			frappe.throw("Sanctioned Loan Amount already exists for {0} against company {1}".format(
```suggestion
			frappe.throw(_("Sanctioned Loan Amount already exists for {0} against company {1}").format(
```

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/report/loan_repayment_and_closure/loan_repayment_and_closure.json
> +   "role": "System Manager"
Set proper roles

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/report/loan_repayment_and_closure/loan_repayment_and_closure.py
> +			"currency": frappe.get_cached_value("Company", filters.get("company"), "default_currency")
Keep it outside for loop

2020-02-25 10:02 UTC, nabinhait commented on erpnext/loan_management/report/loan_security_status/loan_security_status.py
> +		row["currency"] = frappe.get_cached_value("Company", filters.get("company"), "default_currency")
outside for loop

2020-02-25 10:02 UTC, nabinhait commented on erpnext/patches/v11_0/rename_employee_loan_to_loan.py
> +	frappe.reload_doc("loan_management", "doctype", "loan")
If we are not doing patch for existing loan to new loan, then this patch also does not make any sense.

2020-02-26 05:14 UTC, nabinhait approved these changes

2020-02-26 05:14 UTC, merged