feat: Stock Quick Balance
frappe/erpnext pull request #19123
Opened 2019-09-20 00:13 UTC by marination

- It will display the stock balance and stock value given the date and warehouse
- Item code can be fed or barcode can be scanned to retrieve the values

![_0](https://user-images.githubusercontent.com/25857446/65289635-29bfde80-db69-11e9-8f27-5d7785237430.gif)

![_1](https://user-images.githubusercontent.com/25857446/65289649-32181980-db69-11e9-818e-07e228aa4d5e.gif)

2019-09-27 10:57 UTC, nabinhait requested changes

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.js
> +				frm.trigger('warehouse_check');
check_warehouse

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.js
> +	make_custom_button: (frm) => {
add context

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.py
> +	out["item_barcode"] = [x[0] for x in barcodes]
don't fetch

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.py
> +	out["image"] = frappe.db.get_value(
fetch_from

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.py
> +def get_item_stock_details(item, warehouse, date):
get stock_balance

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.js
> +				method: 'erpnext.stock.doctype.stock_quick_balance.stock_quick_balance.get_barcode_stock_details',
get_barcode_stock_details should also return stock balance as well

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.json
> +   "label": "Item Name"
read only

2019-09-27 10:57 UTC, nabinhait commented on erpnext/stock/doctype/stock_quick_balance/stock_quick_balance.json
> + "permissions": [
add permissions for stock user and stock manager roles

2019-09-30 06:01 UTC, rmehta requested changes
Bad naming! There must be a way to define such names.
 `Get Quick Stock Balance` will be a better name.

2019-10-09 09:54 UTC, merged

2019-10-09 09:55 UTC, nabinhait approved these changes