feat(Sales Order): Allow to skip delivery note creation
frappe/erpnext pull request #19222
Opened 2019-09-30 19:37 UTC by Mangesh-Khairnar

- Allow users to skip delivery note creation from sales order
![Screenshot 2019-10-01 at 1 05 20 AM](https://user-images.githubusercontent.com/14824451/65910112-abc0ca80-e3e7-11e9-9361-8a7f04080965.png)

- added Skip delivery note creation in list view
![Screenshot 2019-10-01 at 1 05 55 AM](https://user-images.githubusercontent.com/14824451/65910146-be3b0400-e3e7-11e9-8083-e18ec1b70f20.png)

2019-10-04 09:18 UTC, nabinhait requested changes

2019-10-04 09:18 UTC, nabinhait commented on erpnext/selling/doctype/sales_order/sales_order.json
> +   "label": "Skip Delivery Note Creation",
Rename it to "Skip Delivery Note"

2019-10-10 09:58 UTC, Mangesh-Khairnar commented on erpnext/selling/doctype/sales_order/sales_order.json
> +   "label": "Skip Delivery Note Creation",
added changes

2019-10-12 14:01 UTC, nabinhait approved these changes

2019-10-12 14:03 UTC, merged