feat: Enhancement in landed cost voucher
frappe/erpnext pull request #19252
Opened 2019-10-05 04:28 UTC by deepeshgarg007

![image](https://user-images.githubusercontent.com/42651287/66249806-9be21700-e756-11e9-88d3-98f2ee1d1237.png)

2019-10-12 12:35 UTC, olamide2 commented
@deepeshgarg007 , can we add parties to the additional charges item list? eg a vendor when an accounts payable account is chosen.

2019-10-21 08:19 UTC, nabinhait commented
> @deepeshgarg007 , can we add parties to the additional charges item list? eg a vendor when an accounts payable account is chosen.

@olamide2 Can you please give an example when we will select accounts payable as additional charges

2019-10-21 08:59 UTC, olamide2 commented
@nabinhait  let me give a real life example that we encounter in my company

We buy some goods from China from our Chinese supplier.

These goods are cleared by a clearing agent who gives us 60 days payment terms

The landing cost of the goods is the cost from China plus the clearing fees, we use the landing cost voucher for these.

We will like to be able to add the cost of clearing to the account of the clearing agent by choosing accounts payable and the agents name in the other charges section. This will automatically update the clearing agents account and we can then make payment as contracted.

Regards

2019-10-21 09:18 UTC, nabinhait commented
> @nabinhait let me give a real life example that we encounter in my company
> 
> We buy some goods from China from our Chinese supplier.
> 
> These goods are cleared by a clearing agent who gives us 60 days payment terms
> 
> The landing cost of the goods is the cost from China plus the clearing fees, we use the landing cost voucher for these.
> 
> We will like to be able to add the cost of clearing to the account of the clearing agent by choosing accounts payable and the agents name in the other charges section. This will automatically update the clearing agents account and we can then make payment as contracted.
> 
> Regards

For the above example, you should add "Clearing charges" account in additional charges. And at the same time, you should create a Purchase Invoice where supplier is clearing agent and expense account is "Clearing Charges".

2019-10-21 09:44 UTC, olamide2 commented
Thanks @nabinhait 

That is a viable work around, but it adds one more step to the process, this extra step of raising the PI could be avoided if the party option is available, just like we have in the journal entries.

2019-10-21 10:26 UTC, nabinhait commented
> Thanks @nabinhait
> 
> That is a viable work around, but it adds one more step to the process, this extra step of raising the PI could be avoided if the party option is available, just like we have in the journal entries.

I believe this is not a work-around, but appropriate way to do it. Because we will be able to track of invoices sent by clearing agents with other details like supplier-invoice-no etc.

2019-11-07 12:05 UTC, nabinhait requested changes

2019-11-07 12:05 UTC, nabinhait commented on erpnext/stock/doctype/landed_cost_voucher/landed_cost_voucher.js
> +		this.frm.set_query("expense_account", "taxes", function() {
Use following for filtering accounts with account type = ["Tax", "Chargeable", "Income Account", "Expenses Included In Valuation", "Expenses Included In Asset Valuation"]

https://github.com/frappe/erpnext/blob/develop/erpnext/controllers/queries.py#L131

2019-11-07 12:05 UTC, nabinhait commented on erpnext/stock/doctype/stock_entry/stock_entry.js
> +					"account_type": "Expenses Included In Valuation",
Use following for filtering accounts with account type = ["Tax", "Chargeable", "Income Account", "Expenses Included In Valuation", ""Expenses Included In Asset Valuation""]

https://github.com/frappe/erpnext/blob/develop/erpnext/controllers/queries.py#L131

2019-11-08 07:22 UTC, nabinhait approved these changes

2019-11-08 07:22 UTC, merged