feat: Disable CWIP Accounting checkbox added in Company and Asset Category
frappe/erpnext pull request #19262
Opened 2019-10-07 12:54 UTC by marination

- **Asset Settings** is removed completely
- **Disable CWIP Accounting** checkbox will be present in **Company** under **Fixed Asset Depreciation Settings**

![Screenshot 2019-10-07 at 6 13 55 PM](https://user-images.githubusercontent.com/25857446/66312510-6ee85c80-e92e-11e9-942e-f4fc3c5baf3a.png)

- Also in **Asset Category** under **Depreciation Options**

![Screenshot 2019-10-07 at 6 16 05 PM](https://user-images.githubusercontent.com/25857446/66312678-ba9b0600-e92e-11e9-974b-938500a13ece.png)

- It's value in Asset Category will be given preference in cases of Purchase Invoice and Receipt
- Removed some non-functional code

2019-10-09 08:27 UTC, nabinhait requested changes
- Rename `disable cwip accounting` to `Enable Capital Work in Progress Accounting`
- Make "Enable Capital Work in Progress Accounting" a Select field with options "Yes", "No" and "", default is "No". Patch for existing accounts

2019-10-09 08:27 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +			asset_category = frappe.db.get_value("Item", item.item_code, "asset_category")
get_cached_value

2019-10-09 08:27 UTC, nabinhait commented on erpnext/accounts/general_ledger.py
> +	if not is_cwip_accounting_disabled(gl_map[0].company, None) \
Check if CWIP is enabled for any of the asset category

2019-11-07 12:33 UTC, nabinhait requested changes

2019-11-07 12:33 UTC, nabinhait commented on erpnext/patches/v12_0/set_cwip_and_delete_asset_settings.py
> +		if company:
Always set enable_cwip_accounting value for all companies

2019-11-07 12:33 UTC, nabinhait commented on erpnext/patches/v12_0/set_cwip_and_delete_asset_settings.py
> +				company_doc.save()
Use `set_value` instead of doing `get_doc` and `save`

2019-11-07 12:33 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +			if item.item_code:
```
if item.item_code and item.is_fixed_asset:
	asset_category = frappe.get_cached_value("Item", item.item_code, "asset_category")
	if is_cwip_accounting_enabled(self.company, asset_category):
		return 1
```

2019-11-07 12:33 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +			if item.item_code:
`if item.item_code and item.is_fixed_asset:`

2019-11-07 12:33 UTC, nabinhait commented on erpnext/accounts/general_ledger.py
> +	enable_cwip_in_company = cint(frappe.get_cached_value("Company",
The code should look like this:

```
cwip_enabled = cint(frappe.get_cached_value("Company", gl_map[0].company, "enable_cwip_accounting"))

if not cwip_enabled:
	cwip_enabled = any([cint(ac.enable_cwip_accounting)
		for ac in frappe.db.get_all("Asset Category", "enable_cwip_accounting")])

if cwip_enabled and gl_map[0].voucher_type == "Journal Entry":
```

2019-11-12 12:57 UTC, nabinhait submitted a review, later dismissed

2019-11-12 13:47 UTC, merged

2019-11-12 16:52 UTC, MorezMartin commented
Hello
Little problem with it when trying to migrate 
<pre>Traceback (most recent call last):
  File &quot;/usr/lib/python3.5/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/usr/lib/python3.5/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py&quot;, line 97, in &lt;module&gt;
    main()
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py&quot;, line 18, in main
    click.Group(commands=commands)(prog_name=&apos;bench&apos;)
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py&quot;, line 764, in __call__
    return self.main(*args, **kwargs)
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py&quot;, line 717, in main
    rv = self.invoke(ctx)
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py&quot;, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py&quot;, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py&quot;, line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py&quot;, line 555, in invoke
    return callback(*args, **kwargs)
  File &quot;/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/decorators.py&quot;, line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py&quot;, line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py&quot;, line 233, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py&quot;, line 48, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py&quot;, line 41, in run_all
    run_patch(patch)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py&quot;, line 30, in run_patch
    if not run_single(patchmodule = patch):
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py&quot;, line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File &quot;/home/frappe/frappe-bench/apps/frappe/frappe/modules/patch_handler.py&quot;, line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + &quot;.execute&quot;)()
  File &quot;/home/frappe/frappe-bench/apps/erpnext/erpnext/patches/v12_0/set_cwip_and_delete_asset_settings.py&quot;, line 17, in execute
    enable_cwip_accounting = cint(not cint(cwip_value[0][&apos;value&apos;]))
IndexError: list index out of range
</pre>

2019-11-13 13:46 UTC, marination commented
@MorezMartin https://github.com/frappe/erpnext/pull/19576

2019-11-25 18:19 UTC, MorezMartin commented
Thanks a lot, i disabled the patch