fix(HR):adding is_compensatory as default in setup
frappe/erpnext pull request #19307
Opened 2019-10-15 07:21 UTC by hereabdulla

2019-10-20 13:24 UTC, karthikeyan5 approved these changes

2019-10-21 08:09 UTC, Mangesh-Khairnar requested changes

2019-10-21 08:09 UTC, Mangesh-Khairnar commented on erpnext/setup/setup_wizard/operations/install_fixtures.py
> +			'allow_encashment': 0, 'is_carry_forward': 0, 'include_holiday': 1, 'is_compensatory':1 },
```suggestion
			'allow_encashment': 0, 'is_carry_forward': 0, 'include_holiday': 1, 'is_compensatory': 1 },
```

2019-10-21 08:12 UTC, nabinhait approved these changes

2019-10-21 08:12 UTC, merged