refactor: Expense Claim Cost Center
frappe/erpnext pull request #19326
Opened 2019-10-16 08:44 UTC by jiloysss

* There is a cost center field added to the table (Expense Claim Detail)
* Changed Script in Expense Claim (python) where the cost center in GL Entry is based on the cost center field on each row (Expense Claim Detail)
* Filtered Cost Center in Expense Claim Detail where it will only fetch child account
* Hid Cost Center in Expense Claim
* Added Deferred Expense Accounts checkbox in Expense Claim Type

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-10-16 08:45 UTC, jiloysss commented
EXPENSE CLAIM
Added field Cost Center in table

![expense_claim](https://user-images.githubusercontent.com/31837156/66903018-46e6b080-f034-11e9-83de-5e7e574def77.gif)

EXPENSE CLAIM TYPE
Added check box Deferred Expense Accounts
If checked, Default Account in table will be filtered with Asset Accounts. Expense Accounts if otherwise

![Expense_claim_type](https://user-images.githubusercontent.com/31837156/66903020-46e6b080-f034-11e9-83b8-f7d542096056.gif)

2019-10-17 06:12 UTC, sammish approved these changes

2019-11-06 15:28 UTC, sammish commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +			"is_group": "child"
"is_group": 0

2019-11-08 07:22 UTC, nabinhait requested changes

2019-11-08 07:22 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +	cur_frm.set_df_property("cost_center", "hidden", true);
- Don't hide cost_center field, remove it entirely. And write a patch to update child cost centers based on parent.

- Copy cost center from first row on addition of new row. And on entering cost_center in any row, it should get copied to all rows with blank cost_center.

Refer following code for example:
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.js#L458
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.js#L556

2019-11-22 06:15 UTC, sammish commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +	cur_frm.set_df_property("cost_center", "hidden", true);
@nabinhait It has updated kindly check  #19663

2019-11-26 07:35 UTC, sammish commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +	cur_frm.set_df_property("cost_center", "hidden", true);
@nabinhait It has updated again #19663 

Please check and verify.

2019-12-04 09:33 UTC, closed without merging