refactor: Expense Claim Cost Center
frappe/erpnext pull request #19325
Opened 2019-10-16 08:38 UTC by jiloysss

* There is a cost center field added to the table (Expense Claim Detail)
* Changed Script in Expense Claim (python) where the cost center in GL Entry is based on the cost center field on each row (Expense Claim Detail) 
* Filtered Cost Center in Expense Claim Detail where it will only fetch child account
* Hid Cost Center in Expense Claim
* Added Deferred Expense Accounts checkbox in Expense Claim Type

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2019-10-16 08:39 UTC, jiloysss commented
EXPENSE CLAIM
Added field Cost Center in table

![expense_claim](https://user-images.githubusercontent.com/31837156/66902537-69c49500-f033-11e9-841e-75d9e307b896.gif)
EXPENSE CLAIM TYPE
Added check box Deferred Expense Accounts
- If checked, Default Account in table will be filtered with Asset Accounts. Expense Accounts if otherwise

![Expense_claim_type](https://user-images.githubusercontent.com/31837156/66902538-69c49500-f033-11e9-9d05-fd504cf9fc32.gif)

2019-10-17 06:13 UTC, sammish approved these changes

2019-11-01 09:23 UTC, deepeshgarg007 commented
@jiloysss Can you tell us a use case for this. Why do you need Asset Accounts in Expense Claim Type and Cost Center on Each expenses.

2019-11-02 06:05 UTC, sammish commented
@deepeshgarg007 **Expense Claim Type:** we can claim **Prepaid expense** via expense claim module. (Debit in **Prepaid asset account** Credit in the ****bank or cash**) this is more flexible to HR Department claim their  **Prepaid expense** without purchase invoice.
**Cost Center on each Expenses:** it will help Employee to claim multiple cost center  expense via single expense claim get approval from management.
for example : Employee  business trip for both projects ( project1 and project2). He got expense 100. Here he can share that amount to **Projcet1** 50 and **Project2** 50 from single expense claim.

2019-11-04 10:10 UTC, deepeshgarg007 commented
> @deepeshgarg007 **Expense Claim Type:** we can claim **Prepaid expense** via expense claim module. (Debit in **Prepaid asset account** Credit in the ****bank or cash**) this is more flexible to HR Department claim their **Prepaid expense** without purchase invoice.

How will you select Cash or Bank Account in Expense Claim only Payable Accounts are allowed in Explain Claim. There is already a mechanism available for this use case.

1. Create Employee Advance
2. Create Payment Entry against Employee Advance
3. You can then use that Employee Advance to allocate it against a Expense Claim

 
> **Cost Center on each Expenses:** it will help Employee to claim multiple cost center expense via single expense claim get approval from management.
> for example : Employee business trip for both projects ( project1 and project2). He got expense 100. Here he can share that amount to **Projcet1** 50 and **Project2** 50 from single expense claim.

Why the parent cost center at parent level is hidden. And cost center in expenses table should not be mandatory. What if someone does n't want to tag expense wise cost centers.

2019-11-04 11:12 UTC, sammish commented
**How will you select Cash or Bank Account in Expense Claim only Payable Accounts are allowed in Explain Claim. There is already a mechanism available for this use case.** ////  we will not select payable account  like **cash** or **bank** we will select "Prepaid Account" under Asset.
![image](https://user-images.githubusercontent.com/12432802/68116557-2e1f3b80-ff0c-11e9-881b-8b6a793219c3.png)

**Empoyee advance is other type of senario** I am not talking about that. I am talking about **Prepaid ExpenseI** have well knowlege of that


**Why the parent cost center at parent level is hidden. And cost center in expenses table should not be mandatory. What if someone does n't want to tag expense wise cost centers.** ////// current expense cost center also not support **Parent Cost Center** regarding **Cost ceneter mandatory** if you assign company master default **cost ceneter** it will not ask expense claim.

2019-11-06 13:09 UTC, nabinhait requested changes

2019-11-06 13:09 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +		   "is_group": "child"
"is_group": 0

2019-11-06 15:31 UTC, sammish commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +		   "is_group": "child"
@nabinhait I will Update Kindly migrate version12  Pull request https://github.com/frappe/erpnext/pull/19325

2019-12-04 09:33 UTC, closed without merging