Fixed asset refactor
frappe/erpnext pull request #19369
Opened 2019-10-21 09:47 UTC by thefalconx33

- Item Master & Asset
  - Serial No, Serial Number Series is now disabled for Fixed Asset Item
  - Auto Create Asset on Purchase Checkbox for Fixed Asset Item
  - Mandatory Asset Category & Naming Series for auto creation
  - Manual Asset creation should be linked with a purchase document

- Asset Movement
  - Has table for list of assets
  - List has Make Asset Movement Action for a selected no. of assets
  - Employee is linked to Asset Custodian field

- Purchase Receipt
  - Asset are created based on qty when auto create checked in item. Initial Asset Movement is created
  - Cancelling of PR requires deletion of Asset Movement and cancelling of Linked Asset

- Purchase Invoice
  - Asset are created based on qty when auto create checked in item & update stock is checked on PI. Initial Asset Movement is created 
  - Cancelling of PI is same as Purchase Receipt

- Landed Cost Voucher for Asset
  - Validates assets created is same as purchase receipt/invoice item quantity
  - Removed Serial no rate update for Asset Items
  - Asset gross amount are updated when GL Entries are created

2019-11-06 09:03 UTC, thefalconx33 commented on erpnext/assets/doctype/asset_movement/asset_movement.js
> -	select_serial_no: function(frm) {
removed serial no from asset movement

2019-11-07 11:41 UTC, nabinhait requested changes

2019-11-07 11:41 UTC, nabinhait commented on erpnext/assets/doctype/asset/asset.js
> +	purchase_receipt: function(frm) {
Write `set_query` for purchase receipt and invoice link fields. it should only show the receipts/invoices where item used.

2019-11-07 11:41 UTC, nabinhait commented on erpnext/assets/doctype/asset/asset.py
> +			# should this be hard coded ?
remove naming series from asset movement

2019-11-07 11:41 UTC, nabinhait commented on erpnext/assets/doctype/asset/asset.py
> +
remove entire `make_purchase_invoice` functionality

2019-11-07 11:41 UTC, nabinhait commented on erpnext/assets/doctype/asset_movement/asset_movement.py
> +			elif self.purpose in ['Transfer', 'Receipt']:
Refactor this function. On cancellation, ensure atleast one movement entry always exists

2019-11-07 11:41 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +			if d.is_fixed_asset and d.meta.get_field("asset") and d.asset:
move function to sales_invoice.py

2019-11-07 11:41 UTC, nabinhait commented on erpnext/controllers/buying_controller.py
> +		purchase_amount = flt(row.rate + row.item_tax_amount)
base_rate

2019-11-07 11:41 UTC, nabinhait commented on erpnext/controllers/buying_controller.py
> +	def make_asset_movement(self, assets):
Only do asset movement on submission of assets

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/item/item.js
> +		frm.set_df_property('asset_naming_series', 'reqd', frm.doc.auto_create_assets);
Hide asset_naming_series if auto_create_assets unchecked

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/item/item.js
> +		frm.set_df_property('asset_category', 'reqd', frm.doc.auto_create_assets);
you can use `toggle_reqd` as well

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/landed_cost_voucher/landed_cost_voucher.py
> +							frappe.throw(_('Purchase Document {0} has submitted assets.').format(receipt_document.get('name')))
Don't fetch submitted asset's rows

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +		return gl_entries
no need to return gl_entries

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +		return gl_entries
no need to return gl_entries

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +		return gl_entries
no need to return gl_entries

2019-11-07 11:41 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +			doc = frappe.get_doc("Asset", asset.name)
doc is not used

2019-11-07 11:41 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +					if self.update_stock:
and item.landed_cost_voucher_amount

2019-11-14 09:06 UTC, nabinhait requested changes

2019-11-14 09:06 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +		if is_cwip_accounting_enabled(self.company, item.asset_category):
if not is_cwip_accounting_enabled?

2019-11-14 09:06 UTC, nabinhait commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +				if not is_cwip_accounting_enabled(self.company, item.asset_category):
if is_cwip_accounting_enabled?

2019-11-14 10:26 UTC, nextchamp-saqib commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +		if is_cwip_accounting_enabled(self.company, item.asset_category):
fixed

2019-11-14 10:26 UTC, nextchamp-saqib commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +				if not is_cwip_accounting_enabled(self.company, item.asset_category):
fixed

2019-11-18 06:16 UTC, nabinhait approved these changes

2019-11-18 06:16 UTC, merged