fix: Sales Invoice Status and Payment Reconciliation
frappe/erpnext pull request #19388
Opened 2019-10-22 12:42 UTC by marination

1) **Unpaid Sales Invoice** Status showed **'Paid'** after Credit note was made against it 
     - Fix: Status is now **'Credit Note Issued'**

2) **Payment Reconciliation** will only show standalone **Debit/Credit Notes** in 'UNRECONCILED PAYMENT DETAILS' section or **Payments** Table

2019-10-23 05:36 UTC, Anurag810 requested changes

2019-10-23 05:36 UTC, Anurag810 commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		if self.outstanding_amount < 0 or (self.paid_amount == 0 and self.outstanding_amount == 0):
please write comment for this check. ``` (self.paid_amount == 0 and self.outstanding_amount == 0) ```

2019-10-23 05:38 UTC, marination commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		if self.outstanding_amount < 0 or (self.paid_amount == 0 and self.outstanding_amount == 0):
theres more changes required, on it

2019-10-31 10:37 UTC, nabinhait requested changes

2019-10-31 10:37 UTC, nabinhait commented on erpnext/controllers/status_updater.py
> +		 "eval:self.outstanding_amount <= 0 and self.docstatus==1 and self.is_return==0 and get_value('Purchase Invoice', {'is_return': 1, 'return_against': self.name, 'docstatus': 1})"],
frappe.db.get_value ?

2019-11-01 06:30 UTC, marination commented on erpnext/controllers/status_updater.py
> +		 "eval:self.outstanding_amount <= 0 and self.docstatus==1 and self.is_return==0 and get_value('Purchase Invoice', {'is_return': 1, 'return_against': self.name, 'docstatus': 1})"],
![Screenshot 2019-11-01 at 12 00 08 PM](https://user-images.githubusercontent.com/25857446/68006601-2ad34800-fc9f-11e9-9a4d-38affc1bf6ee.png)

2019-11-07 07:22 UTC, nabinhait approved these changes

2019-11-07 07:22 UTC, merged