fix: incorrect balance qty in stock ledger if batch filter set
frappe/erpnext pull request #19479
Opened 2019-11-01 11:56 UTC by rohitwaghchaure

**Issue**

<img width="1194" alt="Screenshot 2019-11-01 at 5 22 39 PM" src="https://user-images.githubusercontent.com/8780500/68023237-a4355f80-fccc-11e9-9800-bd5b43dcefa8.png">

**After Fix**

![image](https://user-images.githubusercontent.com/8780500/68023250-a8fa1380-fccc-11e9-99ca-5e7dae63e64f.png)

2019-11-06 13:00 UTC, nabinhait requested changes

2019-11-06 13:00 UTC, nabinhait commented on erpnext/stock/report/stock_ledger/stock_ledger.py
> +
```
if sle.voucher_type == 'Stock Reconciliation':
     actual_qty = sle.qty_after_transaction
     stock_value = sle.stock_value
```

2019-11-08 08:29 UTC, rohitwaghchaure commented on erpnext/stock/report/stock_ledger/stock_ledger.py
> +
Done

2019-11-08 09:20 UTC, nabinhait approved these changes

2019-11-08 09:20 UTC, merged