fix: performance issue of sales invoice while save/submit
frappe/erpnext pull request #19598
Opened 2019-11-17 17:25 UTC by rohitwaghchaure

2019-11-18 06:19 UTC, nabinhait requested changes

2019-11-18 06:19 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +		# if self.doctype != 'Material Request':
Should it be commented?

2019-11-19 11:57 UTC, rohitwaghchaure commented on erpnext/controllers/accounts_controller.py
> +		# if self.doctype != 'Material Request':
Fixed

2019-11-19 13:17 UTC, nabinhait approved these changes

2019-11-19 13:17 UTC, merged