feat(Contacts): select billing contact for sales invoice
frappe/erpnext pull request #19610
Opened 2019-11-19 03:30 UTC by ronelvcabrera

Most of the time, point of contact are different from sale, invoicing and on different aspect/phase of the transaction. This feature is to have contacts that are identified for billing.

Therefore, as seen below, when creating a sales invoice, the priority to retrieve a contact for Sales invoice are tagged as `is Billing Contact` contacts.

In connection with this PR https://github.com/frappe/frappe/pull/8840

### Usage:

Billing contact will be retrieved during creation of Invoice as point of contact at this stage is different from sale or other aspect/stage of the transaction.

![core is billing contact new contact](https://user-images.githubusercontent.com/44422325/69043125-69059100-0a2d-11ea-9f68-ca11fe6e8f70.gif)

2019-11-20 06:56 UTC, ronelvcabrera commented
Build error is related to this PR https://github.com/frappe/frappe/pull/8840 where function has been aded a parameter.

2019-12-02 01:51 UTC, ronelvcabrera commented
In relation to the linked PR (https://github.com/frappe/frappe/pull/8840/files), changes here will be moved in ERPNext.

2019-12-02 13:51 UTC, ronelvcabrera commented
Been having unrelated error on Travis CI and is the same with the another PR https://github.com/frappe/erpnext/pull/19612. 

Checked out `develop` branch and ran `bench run-tests --app erpnext` and still having the same error.

2019-12-24 08:32 UTC, deepeshgarg007 requested changes

2019-12-24 08:32 UTC, deepeshgarg007 commented on erpnext/accounts/party.py
>  def set_contact_details(party_details, party, party_type):
```suggestion
def set_contact_details(party_details, party, party_type, doctype=None):
```

2019-12-24 08:32 UTC, deepeshgarg007 commented on erpnext/accounts/party.py
>  def set_contact_details(party_details, party, party_type):
Travis is failing because of this. Fix and reopen closing this for now.

2019-12-24 08:33 UTC, closed without merging