fix: Training Event Email Template
frappe/erpnext pull request #19652
Opened 2019-11-21 11:48 UTC by Anurag810

**Before**
![image](https://user-images.githubusercontent.com/32095923/69335324-b0d12600-0c82-11ea-8e01-e0eb401ddd6d.png)
**After**
![Screenshot 2019-11-21 at 5 17 46 PM](https://user-images.githubusercontent.com/32095923/69335400-e4ac4b80-0c82-11ea-9eb2-24b62c9bf184.png)

2019-11-26 12:39 UTC, scmmishra requested changes
Format the code with indentations

2019-12-02 12:07 UTC, scmmishra requested changes
Add event link to the list of details and set the description as a separate div outside the list without indentation

2019-12-04 07:20 UTC, Anurag810 commented
> Add event link to the list of details and set the description as a separate div outside the list without indentation

Done Please merge

2019-12-04 12:27 UTC, scmmishra approved these changes

2019-12-18 06:13 UTC, merged