fix: tax templates from all companies fetching in receipt
frappe/erpnext pull request #19682
Opened 2019-11-25 10:09 UTC by nextchamp-saqib

2019-11-26 02:28 UTC, deepeshgarg007 requested changes

2019-11-26 02:28 UTC, deepeshgarg007 commented on erpnext/stock/doctype/purchase_receipt/purchase_receipt.js
> +				filters: {'company': cur_frm.doc.company }
```suggestion
				filters: {'company': frm.doc.company }
```

2019-11-26 02:29 UTC, deepeshgarg007 commented
@nextchamp-saqib also rasie a PR for v11 as well

2019-11-29 11:25 UTC, nabinhait approved these changes

2019-11-29 11:25 UTC, merged