feat(employee): make a configurable birthday email template
frappe/erpnext pull request #19709
Opened 2019-11-27 14:07 UTC by DeeMysterio

**previous system:**
It sent a birthday reminder email to all the employees except the one celebrating their birthday.

**The new system:**

- It sends out an email to all the employees including the one celebrating their birthday.

- It sends out an email per birthday guy. 

- Added a field in "HR Settings" saying "Birthday Email Template" to select an Email Template which if set, is used by the system to send out an email and has the required context about the employee otherwise a hard coded email message and subject is used.
 
![hr](https://user-images.githubusercontent.com/13060550/69727509-b1693100-1148-11ea-9473-050c484b8089.gif)

- The Email Template that is used to be used by existing(patches) and new sites(install_fixtures):

![Screenshot 2019-11-22 at 5 40 26 PM](https://user-images.githubusercontent.com/13060550/69727250-2851fa00-1148-11ea-8e82-fe5fc8660862.png)

- A birthday email sent using a template designed with the available employee context in the Email Template:

![Screenshot 2019-11-22 at 3 33 04 PM](https://user-images.githubusercontent.com/13060550/69727323-52a3b780-1148-11ea-942c-2e2005da49a2.png)

2019-12-24 08:12 UTC, Anurag810 requested changes

2019-12-24 08:12 UTC, Anurag810 commented on erpnext/hr/doctype/employee/employee.py
> +		recipients_list = frappe.get_all('Employee', filters={'status': 'Active'})
Get the recipients from the company where the birthday boys/girls belong. 
You can also handle multi-company Employee birthdays. where two employees having birthday belongs to two different companies, then they should have different recipients for different companies.

2019-12-24 08:12 UTC, Anurag810 commented on erpnext/hr/doctype/hr_settings/hr_settings.json
> + "modified_by": "diksha@digithinkit.com",
Change modified_by to "Administrator"

2019-12-24 08:15 UTC, Anurag810 commented
Resolve Conflicts and update your Pull Request

2020-10-07 15:54 UTC, DeeMysterio commented
@nabinhait This PR was closed after a discussion with @rmehta

2020-10-07 16:36 UTC, nabinhait commented
@DeeMysterio okay, can you summarize the discussion?

I thought it got closed by bot automatically. 
And I was thinking that there might be separate emails for the birthday boy/girl and their colleagues.

2020-10-13 08:29 UTC, DeeMysterio commented
> @DeeMysterio okay, can you summarize the discussion?
> 
> I thought it got closed by bot automatically.
> And I was thinking that there might be separate emails for the birthday boy/girl and their colleagues.

We can give different messages to the birthday guy/girl and their colleagues but they can anyway send personal wishes to the former if they want to. Anyway, the reason why this system got rejected is that I think he didn't like this design as it's sending automated birthday wishes and it can be annoying😶. Not sure as the discussion happened long back. You can confirm with him.

2021-01-06 07:58 UTC, Anurag810 requested changes
please resolve conflicts. and changes requested

2021-01-13 10:36 UTC, closed without merging