feat(marketplace): allow user to un-publish item
frappe/erpnext pull request #19815
Opened 2019-12-04 20:26 UTC by Mangesh-Khairnar

![Screenshot 2019-12-05 at 12 06 04 AM](https://user-images.githubusercontent.com/14824451/70178488-6334ce80-1702-11ea-951c-970236c4e50a.png)

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2019-12-24 11:10 UTC, netchampfaris requested changes

2019-12-24 11:10 UTC, netchampfaris commented on erpnext/hub_node/api.py
> +			hub_tracked_items.save()
Looks like you haven't tested this code. Please test these workflows before sending a Pull Request.

```suggestion
			hub_tracked_item.save()
```

2019-12-24 11:10 UTC, netchampfaris commented on erpnext/public/js/hub/pages/Home.vue
> +			this.get_items();
This will be called on every route change. Shouldn't this be called only on the `Home` route? Add a check for it.

2019-12-24 11:10 UTC, netchampfaris commented on erpnext/public/js/hub/pages/Item.vue
> +					const saved_items_link = `<b><a href="#marketplace/saved-items">${__(
Translated strings on multiple lines won't work. They must be on a single line.

https://frappe.io/docs/user/en/translations#3-blocks

2019-12-24 11:10 UTC, netchampfaris commented on erpnext/public/js/hub/pages/Item.vue
> +					const featured_items_link = `<b><a href="#marketplace/featured-items">${__(
Translated strings on multiple lines won't work. They must be on a single line.

2019-12-24 11:10 UTC, netchampfaris commented on erpnext/public/js/hub/pages/Item.vue
> +			frappe.confirm(__(`Unpublish ${this.item.item_name}?`), () => {
Interpolated Strings don't work with translations. https://frappe.io/docs/user/en/translations#2-variables

2019-12-27 09:15 UTC, netchampfaris requested changes

2019-12-27 09:15 UTC, netchampfaris commented on erpnext/patches/v12_0/set_published_in_hub_tracked_item.py
> +	''')
If there is a row in Hub Tracked Item then the SQL statement won't run. Is this the intended behavior?

2019-12-27 09:17 UTC, Mangesh-Khairnar commented on erpnext/patches/v12_0/set_published_in_hub_tracked_item.py
> +	if frappe.db.a_row_exists("Hub Tracked Item"):
```suggestion
	if not frappe.db.a_row_exists("Hub Tracked Item"):
```

2019-12-27 09:21 UTC, netchampfaris approved these changes

2019-12-28 12:22 UTC, merged