feat: provision to select the custom fields in the online POS
frappe/erpnext pull request #19876
Opened 2019-12-09 12:39 UTC by rohitwaghchaure

**Set the fields in the POS Settings**

![image](https://user-images.githubusercontent.com/8780500/70435675-73a3cb00-1aad-11ea-8e2c-db641a909f09.png)

2019-12-10 21:43 UTC, olamide2 commented
Pretty good @rohit

But more importantly we need to brainstorm on how to resolve this missing invoices issues in offline pos.

2019-12-24 08:17 UTC, nextchamp-saqib requested changes

2019-12-24 08:17 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_settings/pos_settings.js
> +				frappe.meta.get_docfield("POS Field", "fieldname", frm.doc.name).options = [""].concat(fields);
Is it necessary to set options on every "refresh" event and when user toggles offline pos? Maybe set once in "onload" event?

2019-12-24 08:17 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_settings/pos_settings.js
> +	use_pos_in_oflfine_mode: function(frm) {
typo: use_pos_in_oflfine_mode -> use_pos_in_offline_mode

2019-12-24 08:17 UTC, nextchamp-saqib commented on erpnext/selling/page/point_of_sale/point_of_sale.js
> +				if(r.message) {
Set this as `r.message.length` otherwise "More Information" section shows up even when there are no custom fields to be shown.

2019-12-24 08:17 UTC, nextchamp-saqib commented on erpnext/selling/page/point_of_sale/point_of_sale.py
> +		"fieldtype", "default_value", "reqd", "read_only", "options"], debug=1)
debug mode

2019-12-26 08:10 UTC, merged

2020-06-27 20:58 UTC, michaeleino commented
Were this merged to v12 ? if not will it be merged??
if yes, I have 12.10.0 and I can't find it !