feat: allow adding & deleting of items in submitted SO & PO
frappe/erpnext pull request #19911
Opened 2019-12-11 11:43 UTC by nextchamp-saqib

2019-12-20 06:46 UTC, deepeshgarg007 commented
@nextchamp-saqib Add some basic test cases for it

2019-12-24 07:43 UTC, nabinhait requested changes

2019-12-24 07:43 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +	if len(parent.items) > len(data):
- remove this condition
- move deletion functionality to a new function
- deleted_children

2019-12-24 11:12 UTC, nabinhait approved these changes

2019-12-24 11:12 UTC, merged