feat: Capture return amount against Employee Advance via Journal Entry
frappe/erpnext pull request #19955
Opened 2019-12-16 08:21 UTC by deepeshgarg007

When some part of Employee Advance is unused and returned back and a Journal Entry is made for the same even then the return amount is not reflected in Employee Advance and the same gets fetched in Expense Claim. 

![Screenshot 2019-12-16 at 1 46 33 PM](https://user-images.githubusercontent.com/42651287/70890272-a77d7400-200a-11ea-9515-9b87751f4156.png)

2019-12-16 09:38 UTC, rushikesherp commented
@deepeshgarg007 , Is there  any functionality to return the return amount against this advance? Does it automatically pass journal entry for return and mark the advance entry as returned so that it cannot be adjusted against another claim?

2019-12-16 09:46 UTC, deepeshgarg007 commented
> @deepeshgarg007 , Is there any functionality to return the return amount against this advance? Does it automatically pass journal entry for return and mark the advance entry as returned so that it cannot be adjusted against another claim?

@rushikesherp Within Journal Entry itself you'll have to mention the reference type and reference name and the return amount will be updated in Employee Advance and  it won't be considered in Expense Claim

![image](https://user-images.githubusercontent.com/42651287/70896489-d13c9800-2016-11ea-96cf-799f66665190.png)

2019-12-23 12:26 UTC, nabinhait requested changes

2019-12-23 12:26 UTC, nabinhait commented on erpnext/hr/doctype/employee_advance/employee_advance.json
> +   "label": "Return Amount",
Returned Amount?

2019-12-24 06:22 UTC, merged