feat: appointment Letter
frappe/erpnext pull request #20104
Opened 2019-12-27 06:14 UTC by Anurag810

**Appointment Letter Template:**

![image](https://user-images.githubusercontent.com/32095923/71504009-9bf93b00-289d-11ea-8e21-cdead2ff4e40.png)

**Appointment Letter: **

![image](https://user-images.githubusercontent.com/32095923/71504046-ccd97000-289d-11ea-8430-ada8bc0b8f95.png)
![image](https://user-images.githubusercontent.com/32095923/71504057-dc58b900-289d-11ea-9fd2-07eb86e46a14.png)
![image](https://user-images.githubusercontent.com/32095923/71504074-eb3f6b80-289d-11ea-875f-be9ac8f8b14a.png)

**Print Format:**
![image](https://user-images.githubusercontent.com/32095923/71504135-3e192300-289e-11ea-91f0-93df73febc85.png)

2019-12-27 06:22 UTC, Anurag810 commented
@nabinhait please suggest changes.

2019-12-31 12:01 UTC, nabinhait requested changes
- Add Docs

2019-12-31 12:01 UTC, nabinhait commented on erpnext/hr/doctype/appointment_letter_template/appointment_letter_template.json
> +  "content"
Why not closing_note?

2019-12-31 12:01 UTC, nabinhait commented on erpnext/hr/doctype/appointment_letter_template/appointment_letter_template.json
> +   "role": "System Manager",
It should be HR Manager

2019-12-31 12:01 UTC, nabinhait commented on erpnext/hr/doctype/appointment_letter/appointment_letter.py
> +	print(template)
remove print

2019-12-31 12:01 UTC, nabinhait commented on erpnext/hr/doctype/appointment_letter/appointment_letter.py
> +	fields = ['title', 'description'],
indent?

2019-12-31 12:01 UTC, nabinhait commented on erpnext/hr/doctype/appointment_letter/appointment_letter.json
> +   "role": "System Manager",
Should be HR User and HR Manager

2020-01-07 07:47 UTC, nabinhait requested changes
- Add link in HR home page

2020-01-21 07:52 UTC, Anurag810 commented on erpnext/hr/doctype/appointment_letter_template/appointment_letter_template.json
> +  "content"
Done

2020-01-21 07:53 UTC, Anurag810 commented on erpnext/hr/doctype/appointment_letter/appointment_letter.py
> +	print(template)
Done

2020-01-21 07:53 UTC, Anurag810 commented on erpnext/hr/doctype/appointment_letter_template/appointment_letter_template.json
> +   "role": "System Manager",
Done

2020-01-21 07:55 UTC, Anurag810 commented on erpnext/hr/doctype/appointment_letter/appointment_letter.json
> +   "role": "System Manager",
Done

2020-01-21 09:46 UTC, Anurag810 commented
> * Add link in HR home page

done

2020-01-21 12:20 UTC, Anurag810 commented
docs  https://github.com/frappe/erpnext_com/pull/655

2020-02-03 12:21 UTC, nabinhait approved these changes

2020-02-03 12:22 UTC, merged