fix: incorrect batch fetched for the serialized items
frappe/erpnext pull request #20119
Opened 2019-12-27 10:03 UTC by rohitwaghchaure

**Issue**
Steps to replicate the issue

1. Create an Item and enabled has serial no and has batch no

1. Make 2 purchase receipts of quantity 10, so that system will create 20 serial nos and 2 batches

1. Now make stock entry with purchase as Material Transfer and select the serial nos of second batch and keep the batch no field blank. System will fetch the 1st batch which is not belongs to the selected serial no

**After Fix**

System will fetch the batch based on the serial nos. If system found more than one batch then user has to manually select the batch also system which check the selected batch is belong to selected serial nos or not

2019-12-27 11:31 UTC, nabinhait requested changes

2019-12-27 11:31 UTC, nabinhait commented on erpnext/controllers/stock_controller.py
> +					frappe.throw(_("The batch {0} does not belog to serial no {1}")
The reverse validation should be added, as batch is superset.
"Row #{0}: Serial No {1} does not belong to Batch {2}"

2019-12-30 06:13 UTC, nabinhait submitted a review, later dismissed

2019-12-30 07:56 UTC, nabinhait approved these changes

2019-12-30 07:56 UTC, merged

2020-04-23 14:53 UTC, Alchez commented
@rohitwaghchaure @nabinhait 

Can we port this to hotfix branches as well please?

The fix made at

https://github.com/frappe/erpnext/blob/92b933f4acd14520a35ca80c395b1c682278a14e/erpnext/controllers/stock_controller.py#L50

is required to avoid problems in the validation for Sales Order documents, which doesn't have the `batch_no` field.

For reference, the current v12 branch has the following code:

https://github.com/frappe/erpnext/blob/7ed7c3237a523e219f25d347033ee89d7e3a1613/erpnext/controllers/stock_controller.py#L50

The other changes made in this PR might be relevant as well.