feat: Validity for Item taxes
frappe/erpnext pull request #20135
Opened 2019-12-29 05:33 UTC by deepeshgarg007

![image](https://user-images.githubusercontent.com/42651287/71552882-cf1d0500-2a2a-11ea-917e-c211835df666.png)

2019-12-30 11:15 UTC, nabinhait requested changes

2019-12-30 11:15 UTC, nabinhait commented on erpnext/stock/get_item_details.py
> +			if args.get('bill_date') and tax.valid_from >= getdate(args.get('bill_date')):
tax.valid_from <= getdate(args.get('bill_date'))

2019-12-30 11:15 UTC, nabinhait commented on erpnext/stock/get_item_details.py
> +		taxes = taxes_with_validity
`taxes_with_validity` should be ordered by `valid_from` desc and while filtering based on `tax_category` it should take latest one.

2019-12-30 11:16 UTC, nabinhait requested changes
- In transactions
    - item_tax_template link field's value should be filtered based on validity
    - Validate in server side

2019-12-31 09:29 UTC, deepeshgarg007 commented
Working on changes in docs. Will update the PR link in description soon

2020-01-02 10:17 UTC, nabinhait requested changes
- tests

2020-01-02 10:17 UTC, nabinhait commented on erpnext/public/js/controllers/transaction.js
> +				'valid_from': doc.posting_date
transaction_date in sales/purchase order

2020-01-02 10:17 UTC, nabinhait commented on erpnext/controllers/queries.py
> +	if not item_doc.taxes:
if no taxes in item, check in item_group. if not there as well return all.

2020-01-02 10:17 UTC, nabinhait commented on erpnext/controllers/taxes_and_totals.py
> +					if not item_doc.taxes:
if taxes not in item, check for item_group

2020-01-02 10:17 UTC, nabinhait commented on erpnext/controllers/taxes_and_totals.py
> +						'posting_date': self.doc.get('posting_date'),
posting_date or transaction_date?

2020-01-06 06:49 UTC, nabinhait requested changes

2020-01-06 06:49 UTC, nabinhait commented on erpnext/controllers/queries.py
> +		return frappe.db.sql(""" SELECT name FROM `tabItem Tax Template` where name
Why are we doing this query? We already have list of valid tax templates.

2020-01-06 10:04 UTC, nabinhait approved these changes

2020-01-06 10:04 UTC, merged

2021-02-16 03:33 UTC, casesolved-co-uk commented on erpnext/public/js/controllers/transaction.js
> +			frappe.throw(__("Please enter Item Code to get item taxes"));
Purchase and Sales Invoice lines should never need an item code for anything, to support one-off manually typed lines