feat: Repay advance from salary
frappe/erpnext pull request #20366
Opened 2020-01-21 08:53 UTC by Anurag810

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2020-01-22 07:14 UTC, Anurag810 commented
Docs: https://github.com/frappe/erpnext_com/pull/657

2020-02-17 10:25 UTC, nabinhait requested changes

2020-02-17 10:25 UTC, nabinhait commented on erpnext/hr/doctype/employee_advance/employee_advance.js
> +		console.log("Working");
remove console.log

2020-02-24 12:18 UTC, Anurag810 commented
Please merge

2020-02-26 10:19 UTC, nabinhait requested changes
- Don't add `payroll_date` and `salary_component` fields in Employee Advance. It will be difficult to enter accurate data in this field for the user while creating advance.
Instead, it should be decided while creating Additional Salary record. So, instead of submitting additional salary record automatically on click of button, it should open Additional Salary record after  mapping data. Then HR User will select payroll date and salary component and submit it.
- Also, add "Reference Document Type" and "Reference Document" fields in Additional Salary to track linked employee advance ID. Same should be implemented for "Leave encashment" and "Employee Incentive" and "Retention Bonus", currently those are reversed linked.

2020-02-27 12:46 UTC, closed without merging