feat: Added popup to 'Get Items from Open Material Requests' in Purchase Order
frappe/erpnext pull request #20371
Opened 2020-01-21 11:56 UTC by marination

Depends on https://github.com/frappe/frappe/pull/9281 and https://github.com/frappe/frappe/pull/9334

- 'Get Items from Open Material Requests' directly fetched and mapped all Material Requests from the supplier.
- Often it timed out for large number of Material Requests

**After change:**
- Popup with filtered Material Requests on button click
- More control on the number of Material Requests mapped at once

![GETITEMS](https://user-images.githubusercontent.com/25857446/72802263-631c6e00-3c71-11ea-87ec-ee68fab981d9.gif)

2020-01-21 11:57 UTC, marination commented
Working on optimisation

2020-02-03 11:43 UTC, nabinhait reviewed
@marination Is this ready to merge?

2020-02-05 13:31 UTC, sahil28297 requested changes
https://github.com/frappe/erpnext/pull/20371/commits/b395bb979c912fc3ab9e628e2b23beeaac85d578 why though?

2020-02-06 05:29 UTC, marination commented
> [b395bb9](https://github.com/frappe/erpnext/commit/b395bb979c912fc3ab9e628e2b23beeaac85d578) why though?

@sahil28297 accidental

2020-02-17 10:27 UTC, nabinhait approved these changes

2020-02-17 10:28 UTC, merged