fix: don't allow territory creation via quick entry
frappe/erpnext pull request #20435
Opened 2020-01-27 10:11 UTC by 0Pranav

fix: don't allow territory creation via quick entry
fix: set "All Territories" as default value for parent_territory

2020-01-27 10:21 UTC, nabinhait requested changes

2020-01-27 10:21 UTC, nabinhait commented on erpnext/setup/doctype/territory/territory.json
> +   "default": "All Territories",
You cannot hard-code "All Territories" here. It can be renamed or have different value based on translation.

2020-01-27 10:21 UTC, nabinhait commented on erpnext/setup/doctype/territory/territory.json
> +   "default": "All Territories",
To set it as default use `get_root` function

2020-01-28 07:12 UTC, nabinhait requested changes

2020-01-28 07:12 UTC, nabinhait commented on erpnext/setup/doctype/territory/territory.py
> +		if not self.parent_territory:
You cannot set parent territory forcefully, this way none will be able to create multiple root territories. You can set only default value.

2020-01-28 08:32 UTC, 0Pranav commented
extending this change to other doctypes in https://github.com/frappe/erpnext/pull/20452

2020-01-28 08:32 UTC, closed without merging