Fixed purchase order backflush qty hotfix
frappe/erpnext pull request #20658
Opened 2020-02-18 10:47 UTC by rohitwaghchaure

Backport https://github.com/frappe/erpnext/pull/20285

2020-02-18 13:14 UTC, nabinhait requested changes

2020-02-18 13:14 UTC, nabinhait commented on erpnext/controllers/buying_controller.py
> +		group_by = "item_code")
`having qty > received_qty`

2020-02-18 13:46 UTC, rohitwaghchaure commented on erpnext/controllers/buying_controller.py
> +		group_by = "item_code")
Done

2020-02-26 06:21 UTC, nabinhait commented
@rohitwaghchaure Closing this, let's redesign this as per our discussion.

2020-02-26 06:21 UTC, closed without merging