fix: Handle rows with same item code from Purchase Receipt to Invoice.
frappe/erpnext pull request #20724
Opened 2020-02-25 11:31 UTC by marination

- Consider a Purchase Receipt with multiple rows in the items table all having **the same Item Code**.
- A Purchase Return exists against this receipt for the first row in the items table.
- While creating invoice via Purchase Receipt, it shows the following:
  ![Screenshot 2020-02-25 at 4 47 56 PM](https://user-images.githubusercontent.com/25857446/75242917-00c60880-57ef-11ea-9c7f-8f5f3a56ea4f.png)

- It fetches the return details of the item code. Since all rows have same item code it assumes all rows have been returned.

**After Fix:**
- Added 'purchase_receipt_item' field in Purchase Receipt Item. The return document will have exactly which row was returned.
- Rows that are returned will not be mapped to Purchase Invoice.

2020-03-31 15:02 UTC, nabinhait requested changes
Resolve conflicts

2020-03-31 15:41 UTC, marination commented
> Resolve conflicts

@nabinhait  done

2020-04-28 12:51 UTC, marination commented
![Screenshot 2020-04-28 at 6 14 10 PM](https://user-images.githubusercontent.com/25857446/80489151-08d02f00-897d-11ea-92c0-dcccc45bffa3.png)

2020-05-05 09:07 UTC, nabinhait approved these changes

2020-05-05 09:07 UTC, merged