refactor: POS workflow
frappe/erpnext pull request #20789
Opened 2020-03-02 07:51 UTC by nextchamp-saqib

2020-03-31 15:02 UTC, nabinhait requested changes
Fix conflict

2020-03-31 16:20 UTC, mhbu50 commented on erpnext/public/js/utils/serial_no_batch_selector.js
> +							frappe.msgprint(`Fetched only ${records_length} avialable serial numbers.`);
Make the text translatable

2020-04-12 10:46 UTC, mhbu50 commented on erpnext/selling/page/point_of_sale_beta/pos_payment.js
> +		const label = change ? 'Change' : 'To Be Paid';
Make label translateable

2020-05-25 14:22 UTC, rohitwaghchaure commented on erpnext/accounts/page/pos/pos.js
> +				method: "erpnext.accounts.page.pos.pos.make_invoice",
remove offline POS

2020-05-29 07:35 UTC, nabinhait requested changes

2020-05-29 07:35 UTC, nabinhait commented on erpnext/patches/v12_0/rename_pos_closing_doctype.py
> +		frappe.reload_doc('Selling', 'doctype', 'POS Closing Entry')
Move these documents to accounts module

2020-05-29 07:35 UTC, nabinhait commented on erpnext/patches/v13_0/replace_pos_payment_mode_table.py
> +				pos_payment_method.save()
db_insert()

2020-05-29 07:35 UTC, nabinhait commented on erpnext/selling/doctype/pos_closing_entry/pos_closing_entry.py
> +					'period_end_date': ('between', [self.period_start_date, self.period_end_date])
or self.period_start_date between period_start_date and period_end_date

2020-05-29 07:35 UTC, nabinhait commented on erpnext/selling/doctype/pos_closing_entry_details/pos_closing_entry_details.json
> + "name": "POS Closing Entry Details",
Name should be singular "POS Closing Entry Detail"

2020-05-29 07:35 UTC, nabinhait commented on erpnext/selling/doctype/pos_invoice/pos_invoice.py
> +		if cint(self.is_pos):
Put the below code inside a function

2020-05-29 07:35 UTC, nabinhait commented on erpnext/selling/doctype/pos_opening_entry_details/pos_opening_entry_details.json
> + "name": "POS Opening Entry Details",
POS Opening Entry Detail

2020-05-29 10:20 UTC, nabinhait requested changes
- Error during migrate:
1.
```
Executing execute:frappe.reload_doc("selling", "doctype", "POS Payment Method") #2020-05-28 in develop (_01c2b3de3a80a4dd)
/Users/nabinhait/projects/develop-bench/apps/erpnext/erpnext/selling/doctype/pos_payment_method/pos_payment_method.json missing
```
2. 
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/commands/site.py", line 260, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/migrate.py", line 70, in migrate
    frappe.model.sync.sync_all(verbose=verbose)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/sync.py", line 19, in sync_all
    sync_for(app, force, verbose=verbose, reset_permissions=reset_permissions)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/sync.py", line 70, in sync_for
    reset_permissions=reset_permissions, for_sync=True)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/modules/import_file.py", line 70, in import_file_by_path
    ignore_version=ignore_version, reset_permissions=reset_permissions)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/modules/import_file.py", line 143, in import_doc
    doc.insert()
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/document.py", line 264, in insert
    self.run_post_save_methods()
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/document.py", line 948, in run_post_save_methods
    self.run_method("on_update")
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/document.py", line 815, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/document.py", line 1101, in composer
    return composed(self, method, *args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/document.py", line 1084, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/model/document.py", line 809, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 291, in on_update
    self.run_module_method("on_doctype_update")
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 357, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/Users/nabinhait/projects/develop-bench/apps/frappe/frappe/modules/utils.py", line 206, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for POS Closing Entry (erpnext.accounts.doctype.pos_closing_entry.pos_closing_entry Error: No module named 'erpnext.selling.doctype.pos_invoice_merge_log.pos_invoice_merge_log')
```

2020-05-29 12:43 UTC, olamide2 commented
Hi @nextchamp-saqib 

While we are doing this can we work on item variants? 

1. I noticed that their is a problem selecting items with variants into the shopping cart. Error log is as follows 


![erroimage](https://user-images.githubusercontent.com/23294026/83260751-385b9c80-a1b2-11ea-9e70-470f4c23a3fd.jpg)

Also can we change the workflow for selecting items with variants to follow the sequence in the gif image below ? This is assuming it is not been scanned in with barcode. 

![pos2](https://user-images.githubusercontent.com/23294026/83260817-54f7d480-a1b2-11ea-8bdf-089de7829e18.gif)

2020-05-29 12:54 UTC, nextchamp-saqib commented
@olamide2 Send me the item form view for the item with variants.

2020-05-29 13:01 UTC, olamide2 commented
> @olamide2 Send me the item form view for the item with variants.

The item view in ERPNext or in the app I used as an example above?

2020-05-29 13:03 UTC, nextchamp-saqib commented
> > @olamide2 Send me the item form view for the item with variants.
> 
> The item view in ERPNext or in the app I used as an example above?

In ERPNext

2020-05-29 13:25 UTC, nextchamp-saqib commented
@olamide2  The item description is faulty. Please send only the item description screenshot.

2020-05-29 13:38 UTC, olamide2 commented
![image](https://user-images.githubusercontent.com/23294026/83265681-bd967f80-a1b9-11ea-9cfa-9efecdc8dcff.png)
![image](https://user-images.githubusercontent.com/23294026/83265718-cc7d3200-a1b9-11ea-9ca0-5f4451cfe32b.png)
![image](https://user-images.githubusercontent.com/23294026/83265751-dd2da800-a1b9-11ea-8783-635f164a138a.png)

2020-05-29 14:01 UTC, olamide2 commented
I do not think it I'd faulty,

It is auti generated by the system

2020-05-29 14:09 UTC, nextchamp-saqib commented
@olamide2 I cannot replicate with the same configuration as yours. However I will make changes to account for such descriptions.

2020-05-29 14:36 UTC, olamide2 commented
I will test this.

Thank you

2020-06-01 09:59 UTC, nabinhait requested changes
- [x] POS link in desk page
- [x] Delete old pos and point-of-sale page
- [x] Me is not defined (onload of pos beta) - pos_controller.js - 517
- [x] /Users/nabinhait/projects/develop-bench/apps/erpnext/erpnext/selling/doctype/pos_payment_method/pos_payment_method.json missing in migrate
- [x] In recent orders page, on change of order type, clear selected form view
- [x] “Error: Data missing in table: Items” coming from recent orders page, on click of “save as draft”
- [x] “jinja2.exceptions.TemplateNotFound: erpnext/selling/doctype/pos_closing_entry/closing_voucher_details.html” on click of “Close the POS”
- [ ] Global search using "pos" term --- No provision in framework for this
- [ ] “Tax template” naming and style -- Fixed naming
- [ ] POS Opening Entry - “01-06-2020 un11fin11” in period start date field -- Unable to replicate
- [x] On saving POS Closing Entry - “Payment Reconciliation” table is getting blank

2020-06-08 10:17 UTC, olamide2 commented
Hello Guys

Any update on this? We are all waiting for it to be merged so we can start adding our own pull requests to this 

We fully intend to make this the best PoS in the market. No joke.

2020-06-12 08:06 UTC, olamide2 commented
Opening and Closing Entry

When carrying out the "Close the PoS" function I noticed that the system does not show the difference amount when the closing amount is keyed in

![image](https://user-images.githubusercontent.com/23294026/84480067-e162c680-ac8b-11ea-825a-d812d54c22b9.png)

It also does not show the opening amount as keyed in when the cashier started the day.

Kindly look into this 

Regards

2020-06-12 08:29 UTC, nextchamp-saqib commented
Opening amount should be set while creating an opening entry, so as to fetch it while closing.
Difference amount will be calculated automatically based on keyed Closing amount.

2020-06-12 09:02 UTC, olamide2 commented
> Opening amount should be set while creating an opening entry, which will be auto fetched while closing.
> 
> Difference amount will be calculated automatically based on keyed Closing amount.

I know all this already, I am telling you that the system is not behaving that way.

I also pasted an image where the difference amount is not calculating see the image above, the closing amount and the Expected Amount are not the same yet the difference amount is zero.

Also in the case above I keyed in an opening amount and yet it shows zero above.

Please check

2020-06-12 12:03 UTC, olamide2 commented
Another issues you might want to look at. This is a process issue.

Consider a case where the company does not allow negative stock.

I see that at Point of Sale the cashier gets a warning when an item that will go into negative is in the shopping cart.

However the sales transaction is still allowed to be completed.

However this negative stock situation will not allow the PoS closing entry to be concluded at end of day. It will ask that this negative situation be corrected first.

In my opinion if the organisation chooses not to allow negative stock then the transaction should not go through at PoS. It will be troublesome for the end of day team to be the one to worry about negative stock.

What do you think?

2020-06-16 13:06 UTC, olamide2 commented
By the way please do not remove offline PoS

The two must still  be able to live side by side

2020-06-19 10:05 UTC, nabinhait requested changes
Travis is failing

2020-06-22 15:57 UTC, Olawale1 commented
> In my opinion if the organisation chooses not to allow negative stock then the transaction should not go through at PoS. It will be troublesome for the end of day team to be the one to worry about negative stock.
> 
> What do you think?

Hi @olamide2 

I think it might be better for the end of day team to deal with it rather than the cashier in front of queueing customers

Cheers

2020-07-23 13:17 UTC, nabinhait approved these changes

2020-07-23 13:21 UTC, merged

2020-07-29 16:31 UTC, muchai commented
Hi, hope this addresses this bug: https://github.com/frappe/erpnext/issues/20889

2020-08-11 09:31 UTC, ptdas commented
Hi,

please add function to allow print before submit just like the older version... 

that will help customer that need a pre print receipt for task checking (for F&B)

Thanks

2020-08-11 10:06 UTC, dexterhussain commented
anyway to add sale person in this ?

2020-11-07 16:42 UTC, Botanium commented
Do we have a weight scale feature in the POS?

2021-04-16 00:56 UTC, Labyrinth-00 commented
the item selector is not showing the full price.  Just the integer part of the decimal price.

2021-05-15 21:25 UTC, RiyadhAltayib commented
Hello Frappe team

I'm so excited for the release of the new UI and After testing the POS; I've got some points I wish to raise to your kind consideration. I hope this would be the right place to write my request.

1- **Partial payment through POS view:**
[Case#1] combined payment that is paid partially by cash and reminder paid by other mode of payment.
[Case#2] partial payment, and upon confirming the invoice (the user can re-open same invoice from POS view) to be able to update collection of remaining payment.

2- **Payment on Credit through POS view:**
[Case#1] customer has loyalty points or a credit which will be deducted fully from upon invoice confirmation.
[Case#2] customer has loyalty points or a credit which will be deducted partially from and reminder paid by other mode of payment.
[Case#3] customer is provided with the completed invoice with zero payment and is allowed to pay later.

3- **Print Invoice (before submit - with note of Unpaid) through POS view**

4- **write-off invoice (completely or partially) from POS view**

5- **Ability to edit and customize the POS view** 
To add additional fields such as (barcode reader for quick item select).