feat: Allow PI creation without PO
frappe/erpnext pull request #20864
Opened 2020-03-06 13:29 UTC by deepeshgarg007

Allow to create a Purchase Invoice against a supplier even though Purchase Order Required is set as "Yes" in Buying Settings

2020-03-09 12:57 UTC, nabinhait requested changes
Why is it only for allowing PI without PO?
The same thing is required for PR without PO, DN without SO and SI without SO.

2020-03-09 12:58 UTC, nabinhait requested changes

2020-03-09 12:58 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +						{1} as {2} in {3}""").format(frappe.bold(d.item_code), frappe.bold('Purchase Order Required'),
```suggestion
						{1} as {2} in {3}""").format(frappe.bold(d.item_code), frappe.bold(_('Purchase Order Required')),
```

2020-03-09 12:58 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +						{1} as {2} in {3}""").format(frappe.bold(d.item_code), frappe.bold('Purchase Receipt Required'),
```suggestion
						{1} as {2} in {3}""").format(frappe.bold(d.item_code), frappe.bold(_('Purchase Receipt Required')),
```

2020-04-02 15:41 UTC, marination approved these changes

2020-04-02 15:41 UTC, marination commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py
> +						frappe.bold('No'), get_link_to_form('Buying Settings', 'Buying Settings', 'Buying Settings')))
`get_link_to_form ('Buying Settings', 'Buying Settings')` works too

2020-04-06 06:45 UTC, merged

2020-08-06 02:17 UTC, Ponyooooo commented
Is it possible if we could also include this feature on the Items? Because sometimes there are suppliers with mixed items which means the item can be received or items are for billing only. Also, if possible to have a checkbox on the item record if it will be included in the printing of the transactions so that it will be automatically not included on the print but still be included or visible on the transaction?