feat: Refactor additional salary
frappe/erpnext pull request #20936
Opened 2020-03-13 12:58 UTC by Anurag810

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2020-05-01 11:25 UTC, nabinhait requested changes

2020-05-01 11:25 UTC, nabinhait commented on erpnext/hr/doctype/additional_salary/additional_salary.py
> +			emp_adv.save()
why not frappe.db.set_value?

2020-05-01 11:25 UTC, nabinhait commented on erpnext/hr/doctype/employee_advance/employee_advance.js
> +				console.log("Helloxs")
remove console.log

2020-05-01 11:27 UTC, nabinhait requested changes
Patch is missing to migrate additional salary reference leave encashment, employee incentive and salary slip.

2020-05-02 14:42 UTC, nabinhait requested changes
Travis is failing

2020-05-04 07:01 UTC, Anurag810 commented on erpnext/hr/doctype/additional_salary/additional_salary.py
> +			emp_adv.save()
done

2020-05-04 07:01 UTC, Anurag810 commented on erpnext/hr/doctype/employee_advance/employee_advance.js
> +				console.log("Helloxs")
done

2020-05-05 10:29 UTC, merged

2020-05-05 10:30 UTC, nabinhait reviewed
Merged manually after fixing tests and patch