refactor: Upload Attendance
frappe/erpnext pull request #20947
Opened 2020-03-16 06:45 UTC by Anurag810

Upload attendance does not show Holidays in the template.

**Please check once locally**

2020-03-16 06:48 UTC, deepeshgarg007 requested changes

2020-03-16 06:48 UTC, deepeshgarg007 commented on erpnext/hr/doctype/upload_attendance/upload_attendance.py
> +			print(data)
Remove print

2020-03-16 06:48 UTC, deepeshgarg007 commented on erpnext/hr/doctype/upload_attendance/upload_attendance.py
> +		pprint(rows)
remove print

2020-03-16 06:48 UTC, deepeshgarg007 commented on erpnext/hr/doctype/upload_attendance/upload_attendance.py
> +		for row in rows:
remove print

2020-03-16 06:48 UTC, deepeshgarg007 commented on erpnext/hr/utils.py
> +			}, debug = 1)
remove debug

2020-03-16 06:49 UTC, deepeshgarg007 commented
@Anurag810 Why refactor?

2020-04-23 10:45 UTC, nabinhait approved these changes

2020-04-23 10:45 UTC, merged