Check order as delivered
frappe/erpnext pull request #20966
Opened 2020-03-17 10:04 UTC by Dharmraj-48

Added Condition to check if order is already delivered then prompt the error message

![Screenshot from 2020-03-17 14-48-28](https://user-images.githubusercontent.com/60173537/76845261-a0ae0980-6864-11ea-8e0b-b146177f73ea.png)

2020-03-17 12:05 UTC, gavindsouza commented
@Dharmraj-48 how many commits are supposed to be a part of this PR?

2020-03-19 11:36 UTC, Dharmraj-48 commented
commits are fixed for
https://github.com/frappe/erpnext/pull/20966

2020-03-20 05:36 UTC, gavindsouza commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +					debugger;
cleanup required?

```suggestion
```

2020-03-20 05:37 UTC, gavindsouza requested changes

2020-03-20 05:37 UTC, gavindsouza commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +					console.log(doc.docstatus);
```suggestion
```

2020-03-31 11:01 UTC, marination commented
1) I think a better approach to avoiding mapping delivered sales orders would be hiding the **Pick List** button under **Create** in a Sales Order if the order is 100% delivered.
2) When it comes to fetching Sales Orders into a Pick List, it can be done from a new **Pick List** itself. A filtered list of Sales Orders is fetched to select so you don't have to check for delivery status again.
3) Adding only a creation provision for Pick List in the List View makes the other actions seem less important. Invoice, Delivery Note, Work Order creation from Sales Order are very frequent uses too. So i wouldn't handle this through List View.

2020-03-31 11:06 UTC, closed without merging