Error message changes
frappe/erpnext pull request #21038
Opened 2020-03-24 06:52 UTC by anupamvs

Adding Better error message when user change rate in sales invoice, delivery note.
![image](https://user-images.githubusercontent.com/20715976/77396565-000e9b00-6dca-11ea-994d-c3d8a2991085.png)

2020-03-24 14:46 UTC, deepeshgarg007 requested changes

2020-03-24 14:46 UTC, deepeshgarg007 commented on erpnext/utilities/transaction_base.py
> +							.format("<b>Maintain Same Rate Throughout Sales Cycle</b>", get_link_to_form("Selling Settings","Selling Settings","<b>Selling Settings</b>")))
```suggestion
							.format(frappe.bold("Maintain Same Rate Throughout Sales Cycle"), 
 get_link_to_form("Selling Settings", "Selling Settings", frappe.bold("Selling Settings"))))
```

2020-03-25 12:54 UTC, anupamvs commented on erpnext/utilities/transaction_base.py
> +							.format("<b>Maintain Same Rate Throughout Sales Cycle</b>", get_link_to_form("Selling Settings","Selling Settings","<b>Selling Settings</b>")))
@deepeshgarg007 Done the changes.

2020-03-26 06:26 UTC, deepeshgarg007 approved these changes

2020-03-26 06:26 UTC, merged