fix: Validate Serial/Batch No naming series in Item itself
frappe/erpnext pull request #21167
Opened 2020-04-06 08:29 UTC by marination

- Invalid Serial / Batch No naming series breaks elsewhere (while doing a stock transaction). The user has to navigate back to the Item to fix it.
![image](https://user-images.githubusercontent.com/25857446/78538005-f9424800-780d-11ea-9aaa-b3b32912ed8e.png)

- Validate In Item itself.
![Screenshot 2020-04-06 at 1 58 41 PM](https://user-images.githubusercontent.com/25857446/78538237-50e0b380-780e-11ea-9632-0c39014807a0.png)

2020-04-06 13:45 UTC, nabinhait requested changes

2020-04-06 13:45 UTC, nabinhait commented on erpnext/stock/doctype/item/item.py
> +			if self.get(field) and "." not in self.get(field):
```suggestion
			series = self.get(field)
			if series and "#" in series and "." not in series:
```

2020-04-07 08:00 UTC, marination commented on erpnext/stock/doctype/item/item.py
> +			if self.get(field) and "." not in self.get(field):
done

2020-04-07 08:46 UTC, nabinhait approved these changes

2020-04-07 08:46 UTC, merged