feat: Razorpay subscription for Non profit memberships
frappe/erpnext pull request #21187
Opened 2020-04-07 09:22 UTC by scmmishra

This PR makes the following changes
1. Integrates razorpay with Non Profit Membership
1. Added membership settings DocType
1. Added webhook for subscription activated and charged

2020-04-13 09:06 UTC, surajshetty3416 requested changes

2020-04-13 09:06 UTC, surajshetty3416 commented on erpnext/non_profit/doctype/membership_settings/membership_settings.json
> +   "fieldtype": "Data",
```suggestion
   "fieldtype": "Int",
```

2020-04-13 09:06 UTC, surajshetty3416 commented on erpnext/non_profit/doctype/membership/membership.py
> +
delete...

2020-04-13 09:06 UTC, surajshetty3416 commented on erpnext/non_profit/doctype/member/member.py
> +		}
spaces and tabs...
<img width="906" alt="Screenshot 2020-04-13 at 2 33 18 PM" src="https://user-images.githubusercontent.com/13928957/79108315-b9420e80-7d93-11ea-8d26-7347683b18c3.png">

2020-04-13 09:06 UTC, surajshetty3416 commented on erpnext/non_profit/doctype/membership_settings/membership_settings.js
> +		// }
remove commented code if not required.

2020-04-16 12:48 UTC, scmmishra commented
@nabinhait can you review this?

2020-04-20 15:31 UTC, merged