feat(Healthcare): Rehabilitation Module
frappe/erpnext pull request #21216
Opened 2020-04-09 07:28 UTC by ruchamahabal

Rehab / Physiotherapy sub-module in ERPNext Healthcare
![rehabilitation](https://user-images.githubusercontent.com/24353136/78866479-1751b780-7a5d-11ea-9df8-0110c54a4daa.png)

- **Exercise Type**:

    The heart of rehab is mapping exercises.
    1. Template for prescribing exercises
    2. Set Healthcare Service Units (will be marked occupied when therapy sessions for this type are 
         booked)
    3. Attach Videos or PDF for Exercise Steps
    4. Add or edit steps in cards (images, title, desc)

    ![exercise_type](https://user-images.githubusercontent.com/24353136/78867207-5a605a80-7a5e-11ea-8af0-07d4e671e4ad.png)

<details>
<summary>Therapy Type</summary>

1. Template for Therapies
2. Item created automatically for billing
3. Configure exercises, rates and duration

![rehab_therapy_type](https://user-images.githubusercontent.com/24353136/78868309-49b0e400-7a60-11ea-8bb3-a7581d582674.png)

</details>

<details>
<summary>Therapy Plan</summary>

1. Add Therapies
2. Track progress according to sessions
3. Automatically created on Patient Encounter submission

![therapy_plan](https://user-images.githubusercontent.com/24353136/78868400-8086fa00-7a60-11ea-946c-1a38a16ab370.png)

</details>

<details>
<summary>Therapy Session</summary>

1. Therapy Type wise Sessions
2. Number of therapies updated in Therapy Plan on submit
3. See counts progress

![therapy_session](https://user-images.githubusercontent.com/24353136/78868485-a3b1a980-7a60-11ea-97b9-85eafec4cb97.png)

</details>
<details>
<summary>Therapy Plan from Encounter</summary>

![therapy_plan_from_encounter](https://user-images.githubusercontent.com/24353136/78868563-c6dc5900-7a60-11ea-9811-e6e56e2c811c.png)
</details>

</details>
<details>
<summary>Appointment Booking from Therapies</summary>

![app_rehab](https://user-images.githubusercontent.com/24353136/78868812-30f4fe00-7a61-11ea-8a00-8946b7a3a5b5.png)

</details>

<details>
<summary>Invoicing</summary>

![get_healthcare_services](https://user-images.githubusercontent.com/24353136/78868878-4702be80-7a61-11ea-81de-15b3c0a6509c.png)

</details>

- [ ] Tests
- [ ] Documentation

2020-04-21 06:46 UTC, nabinhait requested changes
- Fix permissions in all doctypes
- Set columns for editable grid via docfield property, it will add flexibility to user to customize.

2020-04-21 06:46 UTC, nabinhait commented on erpnext/healthcare/doctype/patient_encounter/patient_encounter.js
> +		frm.get_field('therapies').grid.editable_fields = [
Why columns are not defined through docfield property?

2020-04-21 08:11 UTC, ruchamahabal commented
> * Set columns for editable grid via docfield property, it will add flexibility to user to customize.

Actually 2 child tables are being re-used:

- **Exercise** Child Table 
  - Therapy Type

     Here Counts Completed is not shown since it is a template:
     ![therapy_type_table](https://user-images.githubusercontent.com/24353136/79841143-9c7d8a80-83d4-11ea-8301-a3fc0adb6889.png)

  - Therapy Session

      Here Counts Completed is shown and Difficulty Level is visible on row expansion:
      ![therapy_session_table](https://user-images.githubusercontent.com/24353136/79841155-a0a9a800-83d4-11ea-8d43-47d95b8e7ff6.png)

- **Therapy Plan Detail** child table
   - Therapy Plan
       
      Here the Sessions Completed column is shown
      ![therapy-plan-table](https://user-images.githubusercontent.com/24353136/79841821-9805a180-83d5-11ea-9db1-ea653eff2b8e.png)

   - Patient Encounter

     The Sessions Completed column is irrelevant here, hence it is hidden
     ![patient-encounter-table](https://user-images.githubusercontent.com/24353136/79841945-c4b9b900-83d5-11ea-9f46-e390da04f557.png)

2020-04-22 07:37 UTC, nabinhait approved these changes

2020-04-22 07:37 UTC, merged