fix: bom update cost is not working
frappe/erpnext pull request #21348
Opened 2020-04-20 21:11 UTC by rohitwaghchaure

**Issue 1**

```
{'method_name': 'erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.update_latest_price_in_all_boms', 'log': <function log at 0x7fbeaf7c2ae8>, 'retry': 0, 'is_async': True, 'user': 'Administrator', 'kwargs': {}, 'job_name': 'erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.update_latest_price_in_all_boms', 'event': 'daily_long', 'method': <function update_latest_price_in_all_boms at 0x7fbeb4420400>, 'site': 'hspl18.erpnext.com'}
Traceback (most recent call last):
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/utils/background_jobs.py", line 102, in execute_job
    method(**kwargs)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/erpnext/erpnext/manufacturing/doctype/bom_update_tool/bom_update_tool.py", line 90, in update_latest_price_in_all_boms
    update_cost()
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/erpnext/erpnext/manufacturing/doctype/bom_update_tool/bom_update_tool.py", line 103, in update_cost
    frappe.get_doc("BOM", bom).update_cost(update_parent=False, from_child_bom=True)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 244, in update_cost
    self.save()
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/model/document.py", line 325, in _save
    self.update_children()
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/model/document.py", line 351, in update_children
    self.update_child_table(df.fieldname, df)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/model/document.py", line 360, in update_child_table
    d.db_update()
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/model/base_document.py", line 363, in db_update
    ), list(d.values()) + [name])
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/database/database.py", line 125, in sql
    self.check_transaction_status(query)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/database/database.py", line 261, in check_transaction_status
    frappe.throw(_("Too many writes in one request. Please send smaller requests"), frappe.ValidationError)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/__init__.py", line 377, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable)
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/__init__.py", line 356, in msgprint
    _raise_exception()
  File "/home/frappe/benches/bench-version-12-2020-04-17/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Too many writes in one request. Please send smaller requests
```

**Issue 2**

```
{'method_name': 'erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.update_latest_price_in_all_boms', 'log': <function log at 0x7fdaefb31c80>, 'retry': 0, 'is_async': True, 'user': 'Administrator', 'kwargs': {}, 'job_name': 'erpnext.manufacturing.doctype.bom_update_tool.bom_update_tool.update_latest_price_in_all_boms', 'event': 'daily_long', 'method': <function update_latest_price_in_all_boms at 0x7fdaf485d268>, 'site': 'hspl18.erpnext.com'}
Traceback (most recent call last):
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/utils/background_jobs.py", line 102, in execute_job
    method(**kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/erpnext/erpnext/manufacturing/doctype/bom_update_tool/bom_update_tool.py", line 90, in update_latest_price_in_all_boms
    update_cost()
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/erpnext/erpnext/manufacturing/doctype/bom_update_tool/bom_update_tool.py", line 103, in update_cost
    frappe.get_doc("BOM", bom).update_cost(update_parent=False, from_child_bom=True)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 244, in update_cost
    self.save()
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 934, in run_post_save_methods
    self.run_method("on_update_after_submit")
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 794, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 1065, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 1048, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 788, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 86, in on_update_after_submit
    self.manage_default_bom()
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/erpnext/erpnext/manufacturing/doctype/bom/bom.py", line 304, in manage_default_bom
    item = frappe.get_doc("Item", self.item)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/__init__.py", line 752, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 71, in get_doc
    return controller(*args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/website/website_generator.py", line 16, in __init__
    super(WebsiteGenerator, self).__init__(*args, **kwargs)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/model/document.py", line 147, in load_from_db
    d = frappe.db.get_value(self.doctype, self.name, "*", as_dict=1)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/database/database.py", line 401, in get_value
    order_by, cache=cache)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/database/database.py", line 592, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/benches/bench-version-12-2020-03-19/apps/frappe/frappe/database/database.py", line 150, in sql
    if (frappe.conf.get("logging") or False)==2:
  File "/home/frappe/benches/bench-version-12-2020-03-19/env/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/frappe/benches/bench-version-12-2020-03-19/env/lib/python3.6/site-packages/werkzeug/local.py", line 309, in _get_current_object
    return getattr(self.__local, self.__name__)
  File "/home/frappe/benches/bench-version-12-2020-03-19/env/lib/python3.6/site-packages/werkzeug/local.py", line 72, in __getattr__
    return self.__storage__[self.__ident_func__()][name]
  File "/home/frappe/benches/ [...]

2020-04-21 06:01 UTC, nabinhait requested changes

2020-04-21 06:01 UTC, nabinhait commented on erpnext/manufacturing/doctype/bom/bom.py
> +			self.db_update()
Test case?

2020-04-22 10:50 UTC, rohitwaghchaure commented on erpnext/manufacturing/doctype/bom/bom.py
> +			self.db_update()
Done

2020-04-23 04:18 UTC, nabinhait approved these changes

2020-04-23 04:18 UTC, merged