feat: Default Dashboard for Healthcare Workspace
frappe/erpnext pull request #21414
Opened 2020-04-25 17:05 UTC by ruchamahabal

![dashboard](https://user-images.githubusercontent.com/24353136/80285788-eeac0c00-8744-11ea-935a-f7c4351d0cdc.png)

2020-04-28 22:01 UTC, rohitwaghchaure commented on erpnext/patches.txt
> +erpnext.patches.v12_0.add_default_dashboards # 2020-04-25
travis is failing for the patches, need to add frappe.reload_doc("healthcare", "doctype", "patient_appointment") before this patch

2020-05-01 13:01 UTC, nabinhait submitted a review, later dismissed

2020-05-04 08:11 UTC, nabinhait requested changes
Please add `frappe.reload_doc("healthcare", "doctype", "patient_appointment")` in `add_default_dashboards` patch

2020-05-05 10:32 UTC, nabinhait approved these changes

2020-05-05 10:32 UTC, merged