Update in field type
frappe/erpnext pull request #21420
Opened 2020-04-26 08:56 UTC by wojosc

Warranty Period (in Days) changed from "Data" to "Int".

2020-04-27 03:14 UTC, deepeshgarg007 requested changes
@wojosc Please update the modified time in json as well so that the changes take effect on migrate

2020-04-27 06:48 UTC, wojosc reviewed
added time stamp

2020-04-30 06:06 UTC, deepeshgarg007 approved these changes

2020-05-01 06:08 UTC, merged

2020-05-01 06:33 UTC, deepeshgarg007 commented
Reverting this, will require patch