feat(Cost Center): Distributed Cost Center
frappe/erpnext pull request #21531
Opened 2020-04-30 14:19 UTC by karthikeyan5

This feature enhances the Cost Center dimension to allow the distribution of the tagged value to a set of Cost Centers.

A distributed cost center can be created out of different ratios of ordinary cost centers and it can be tagged against the GL entries.

Financial statement reports are also accordingly modified when cost center filter is added.

**Screenshot of Cost Center with Distributed Cost Center**
![image](https://user-images.githubusercontent.com/4847317/80720803-10c5d580-8b1b-11ea-824f-d4141f6f92c7.png)

2020-05-29 15:40 UTC, sammish commented
@nabinhait Thanks

2020-06-01 13:15 UTC, nabinhait requested changes
- The actual amount column in Budget Variance Report should also be updated based on distribution cost center.
- docs is pending

Otherwise, the PR is good to go.

2020-06-02 10:26 UTC, KaviyaPeriyasamy commented
> * The actual amount column in Budget Variance Report should also be updated based on distribution cost center.
> * docs is pending
> 
> Otherwise, the PR is good to go.

Hello @nabinhait ,
This https://github.com/frappe/erpnext/pull/21531/commits/84f863fdee2af9afece0f6a257e03806d444fb45 commit will update the actual amount column based on the distributed cost center.

2020-06-03 06:26 UTC, KaviyaPeriyasamy commented
> @KaviyaPeriyasamy thanks for the dedicated support.

It's my pleasure.

2020-06-03 06:44 UTC, KaviyaPeriyasamy commented
@nabinhait 
Corresponding docs were updated in this PR https://github.com/frappe/erpnext_documentation/pull/85

2020-06-04 06:51 UTC, nabinhait requested changes

2020-06-04 06:51 UTC, nabinhait commented on erpnext/accounts/report/general_ledger/general_ledger.py
> +			is_opening {select_fields_with_percentage}
```suggestion
			is_opening, `tabGL Entry`.creation {select_fields_with_percentage}
```

2020-06-04 06:51 UTC, nabinhait commented on erpnext/accounts/report/general_ledger/general_ledger.py
>  			remarks, against, is_opening {select_fields}
```suggestion
			remarks, against, is_opening, creation {select_fields}
```

2020-06-04 12:37 UTC, KaviyaPeriyasamy commented
@nabinhait 
Suggested changes were applied.

2020-06-08 06:50 UTC, nabinhait approved these changes

2020-06-08 06:50 UTC, merged

2020-06-08 08:47 UTC, sammish commented
@nabinhait thanks for your great support 

@karthikeyan5 @Vigneshsekar @KaviyaPeriyasamy thanks team for the unlimited support.

2020-06-13 16:06 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-beta-pre-release