fix: add deduct functionality added for selling cycle
frappe/erpnext pull request #21636
Opened 2020-05-07 09:56 UTC by vishdha

We have use case where we need to deduct tax in selling cycle

![WheelHouse_Cannabis_Dispensary_ACC_SINV_2020_00897](https://user-images.githubusercontent.com/6947417/81280924-d1493d00-9076-11ea-90e7-af68489ab66b.png)

we added add and deduct functionality for selling cycle
![Uploading WheelHouse_Cannabis_Dispensary_ACC_SINV_2020_00897 (1).png…]()

2020-05-07 11:06 UTC, nabinhait reviewed
@vishdha Please explain the use case

2020-05-08 07:37 UTC, neilLasrado commented
@nabinhait In the state of California for the cannabis industry,  

the cultivator (seller) is supposed to pay the cultivation tax on the sale of produce. However, this tax needs to be collected by the distributor (buyer) while making a purchase and remitted to the govt. Hence the cultivators need to raise Sales Invoices with the total amount - cultivation tax

Also if a distributor is reselling the produce to another distributor, the cultivation tax is 'passed along'. The final distributor who puts the produce in the retail market is responsible for paying the tax. So the distributors also need to raise Sales Invoices with the total amount - cultivation tax while selling to another distributer. 

You can read more about the same here -> https://www.cdtfa.ca.gov/industry/cannabis.htm#Cultivators

2020-05-21 11:12 UTC, neilLasrado commented
@nabinhait can you please look into this

2020-07-13 05:37 UTC, vishdha commented
@nabinhait  Please review this

2020-09-08 05:56 UTC, nabinhait requested changes
Seems like you have not fixed tax amount many places like 'item-wise sales register' and 'sales register' report. And gl entries for taxes on sales invoice.

Basically, search globally for all the instance of 'add_deduct_tax' which is implemented in purchase cycle and give it a thought whether it needs to replicated for sales or not.

2020-09-08 05:56 UTC, nabinhait commented on erpnext/accounts/doctype/sales_taxes_and_charges/sales_taxes_and_charges.json
> +   "options": "Valuation and Total\nValuation\nTotal",
What is the usecase for Valuation in sales cycle?

2020-09-08 05:57 UTC, nabinhait commented
Add tests

2020-09-27 15:52 UTC, sagarvora commented
@vishdha Any updates?

2021-01-13 11:12 UTC, closed without merging