feat: save shipping address to woocommerece customer
frappe/erpnext pull request #21654
Opened 2020-05-08 09:44 UTC by scmmishra

Solves: https://github.com/frappe/erpnext/issues/21481

To test, you can run the `test_sales_order_for_woocommerce` method

2020-05-08 09:44 UTC, scmmishra commented
@Mergifyio backport version-12-hotfix

2020-05-12 14:43 UTC, Mangesh-Khairnar requested changes

2020-05-12 14:43 UTC, Mangesh-Khairnar commented on erpnext/erpnext_integrations/connectors/woocommerce_connection.py
>  	address = address.save()
Not returning anything, check line 79, 80

2020-05-18 10:05 UTC, Mangesh-Khairnar commented on erpnext/erpnext_integrations/connectors/woocommerce_connection.py
> +	return contact
no point in returning the contact?

2020-05-18 10:06 UTC, Mangesh-Khairnar requested changes

2020-05-18 10:06 UTC, Mangesh-Khairnar commented on erpnext/erpnext_integrations/connectors/woocommerce_connection.py
> +		contact = create_contact(raw_billing_data, customer)
variable is not used anywhere

2020-05-19 08:00 UTC, Mangesh-Khairnar approved these changes

2020-05-19 08:01 UTC, merged