fix: Adding status Overdue in Sales Order
frappe/erpnext pull request #21683
Opened 2020-05-11 10:09 UTC by anupamvs

**Issue-** In the Sales Order list, we can not apply overdue status filter. Unless click on "Overdue" status from the list then it will apply some filters and will show the result.
![image](https://user-images.githubusercontent.com/20715976/81550125-6d3bb700-939d-11ea-9864-3daaea2eeba3.png)

**Fix-**
![image](https://user-images.githubusercontent.com/20715976/81550151-788ee280-939d-11ea-8266-4e0994bbc2d4.png)

2020-05-11 14:38 UTC, nabinhait requested changes

2020-05-11 14:38 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +	frappe.db.sql(""" update `tabSales Order` set status = 'Overdue'
Don't set overdue status from background job, it will overwrite "To Deliver" and "To Bill" status, which is more important.

2020-05-11 14:38 UTC, nabinhait commented on erpnext/selling/doctype/sales_order/sales_order.json
> +   "options": "\nDraft\nOn Hold\nTo Deliver and Bill\nTo Bill\nTo Deliver\nCompleted\nCancelled\nClosed\nOverdue",
Do the same changes in purchase order also

2020-05-11 14:38 UTC, nabinhait commented on erpnext/selling/doctype/sales_order/sales_order_list.js
> +		} else if (doc.status === "Overdue") {
no changes required as we are not setting from background jobs

2020-05-14 04:49 UTC, rmehta commented
I don't think this design is right. Overdue should be a separate status column than this that should be set by background job.

2020-05-14 07:36 UTC, nabinhait commented
> I don't think this design is right. Overdue should be a separate status column than this that should be set by background job.

Good suggestion 👍 
There are already 3 status fields in Sales Order, maybe we can add the "Overdue" status in the existing "Delivery Status" field. It has existing options like "Not Delivered", "Partially Delivered" and "Fully Delivered". And we can set overdue status from background job.

2020-05-18 05:51 UTC, nabinhait commented
closing this for now.

2020-05-18 05:51 UTC, closed without merging