chore: Added Italian Import Supplier Invoice to Menu
frappe/erpnext pull request #21920
Opened 2020-05-25 16:20 UTC by marination

- Added Italian Import Supplier Invoice to Buying Module View if any Company is Italian
![Screenshot 2020-05-25 at 9 34 48 PM](https://user-images.githubusercontent.com/25857446/82829730-99912080-9ed1-11ea-9e82-2e48b015dee1.png)

- Added Permissions similar to Purchase Invoice for Import Supplier Invoice

2020-05-26 04:53 UTC, deepeshgarg007 requested changes

2020-05-26 04:53 UTC, deepeshgarg007 commented on erpnext/regional/doctype/import_supplier_invoice/import_supplier_invoice.json
> +   "email": 1,
Permission for regional specific doctypes should be added in the regional setup and add a patch to add permissions for existing users. Current fix will make the doctype visible for all countries.

Refer this link for reference
https://github.com/frappe/erpnext/blob/develop/erpnext/regional/india/setup.py#L21

2020-05-27 16:35 UTC, marination commented
@deepeshgarg007  done

2020-05-28 07:03 UTC, deepeshgarg007 approved these changes

2020-05-28 07:03 UTC, merged