[Feature] Homepage refactor
frappe/erpnext pull request #22119
Opened 2020-06-05 03:31 UTC by casesolved-co-uk

Closes #20744
Affects #21515

Refactored Homepage:
- Sections, Cards, Products & Blog Posts are now configured in Web Page Sections to allow reordering, mix 'n match and selection of specific objects (#20744)
- Section titles can now be rendered with an H1 tag for SEO (#21515)
- Sections can be rendered as Bootstrap Grid, Card Group, Card Deck or Card Columns
- Cards can be rendered vertical or horizontal (the template macro should be reused for all cards, e.g. products, to give consistency)
- Card links can now be configured with anchor text and nofollow attributes for SEO
- Other Web Pages could also be parents to the new `Web Page Sections` (not just the Homepage)
- Other ERPNext docs that make sense as website published cards could easily be added to `Web Page Section Item`

New DocType hierarchy:
- Homepage (Single)
  - Web Page Sections (Child)
    - Web Page Section (Parent)
      - Web Page Section Item (Child; contains Dynamic Link to:)
        - Web Page Card (Parent)
        - Item (Parent)
        - Blog Post (Parent)

The functionality has been refactored with a view to being integrated with the frappe Web Page page builder, but this was too much work.
If acceptable after review, I will also submit to the version-12-hotfix branch.
I will now update the Homepage documentation to match.

2020-06-19 09:48 UTC, Anurag810 requested changes

2020-06-19 09:48 UTC, Anurag810 commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +		cards = frappe.db.get_all('Homepage Section Card', fields='*', order_by='parent,idx')
why get all fields? list only those which are required.
 ``` fields = ['name', 'title']```

2020-06-19 09:48 UTC, Anurag810 commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +		sections = frappe.db.get_all('Homepage Section', fields='*', order_by='section_order')
why get all fields? list only those which are required.
```fields = ['name', 'title']```

2020-06-19 09:48 UTC, Anurag810 commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +			fields=['name'],
It already returns the name, if fields argument is not there.

2020-06-19 09:49 UTC, Anurag810 commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +			fields=['name'],
no need to specify fields = ["name"]

2020-06-19 12:04 UTC, casesolved-co-uk commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +		sections = frappe.db.get_all('Homepage Section', fields='*', order_by='section_order')
It's a patch, so gets run once only, so it makes little difference.

2020-06-19 12:05 UTC, casesolved-co-uk commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +			fields=['name'],
It's more verbose so people know exactly what is happening rather than needing to know the default behaviour.

2020-08-16 12:44 UTC, barredterra requested changes
Nice work. Btw, I don't think it should go into `version-12-hotfix`, as you mentioned, because it's not a fix.

2020-08-16 12:44 UTC, barredterra commented on erpnext/portal/doctype/homepage/test_homepage.py
> +	def setup_test_data(self):
Name this method "setUp" and it will get executed automatically before every test case. (Check the unittest docs for details.)

2020-09-04 00:42 UTC, casesolved-co-uk commented on erpnext/patches.txt
> +erpnext.patches.v12_0.refactor_homepage_20744
Move patch to v13_0

2020-09-04 00:42 UTC, casesolved-co-uk commented on erpnext/patches/v12_0/refactor_homepage_20744.py
> +# Copyright (c) 2020, Frappe and Contributors
Move patch to v13_0

2020-09-08 04:40 UTC, rmehta commented
@casesolved-co-uk thanks for this PR, but we can deprecate this feature with the new Web Page Builder https://docs.erpnext.com/docs/user/manual/en/website/web-page-builder

Shall we remove the "Home Page" altogether?

@netchampfaris

2020-09-28 06:04 UTC, netchampfaris commented
@rmehta Yes, we can run a patch to create these pages using Page Builder.

2020-09-29 00:03 UTC, casesolved-co-uk commented
@rmehta & @netchampfaris so you can reference existing Item and Blog db content to create cards on other pages using the Web Page Builder?
If not it doesn't close #20744

2020-11-08 15:30 UTC, casesolved-co-uk commented
Active

2021-01-11 11:58 UTC, closed without merging