fix: Don't prompt for Quality Inspection on Return Documents.
frappe/erpnext pull request #22199
Opened 2020-06-11 11:10 UTC by marination

- Once QI is done on Receipt, don't prompt again on Return.

2020-06-11 18:24 UTC, deepeshgarg007 requested changes

2020-06-11 18:24 UTC, deepeshgarg007 commented on erpnext/controllers/stock_controller.py
> +		if not self.is_return:
![image](https://user-images.githubusercontent.com/42651287/84425087-a38b8100-ac3e-11ea-9cf3-25847256cad8.png)

Many doctypes are inherited from Stock Controller and some of them don't have the is return field. 
```suggestion
		if not self.get('is_return'):
```

2020-06-12 07:02 UTC, marination commented
@deepeshgarg007 done

2020-06-14 11:39 UTC, deepeshgarg007 approved these changes

2020-06-14 11:39 UTC, merged