added: /support
frappe/erpnext pull request #22194
Opened 2020-06-11 07:49 UTC by AfshanKhan

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2020-06-12 07:25 UTC, scmmishra approved these changes

2020-06-12 07:25 UTC, scmmishra commented on erpnext/www/support/index.py
> +	return frappe.db.sql(
Use `frappe.get_list` (ORM) here instead of SQL query

2020-06-12 07:25 UTC, scmmishra commented on erpnext/www/support/index.py
> +	if not favorite_articles or len(favorite_articles) < 3:
```suggestion
	if not favorite_articles:
```

If you get a list, show it anyway, or add latest articles next to it. So if you get 2 favorite articles, add 4 recent ones

2020-06-12 07:26 UTC, scmmishra requested changes
Minor changes mentioned above

2020-06-12 11:56 UTC, AfshanKhan commented
> Minor changes mentioned above

Changes have been pushed

2020-06-15 06:41 UTC, scmmishra requested changes

2020-06-15 06:41 UTC, scmmishra commented on erpnext/www/support/index.py
> +		order_by="creation desc", limit=(6-len(favorite_articles)))
```suggestion
		latest_articles = frappe.get_all("Help Article", 
			fields=["title", "content", "route", "category"], 
			filters={"title": ['not in', tuple(title_list)], "published": 1}, 
			order_by="creation desc", limit=(6-len(favorite_articles)))
```

2020-06-15 06:41 UTC, scmmishra commented on erpnext/www/support/index.py
> +		filters={"title": ['not in', tuple(title_list)], "published": 1},
Use name instead of title

2020-06-15 06:54 UTC, scmmishra submitted a review, later dismissed

2020-06-16 14:22 UTC, surajshetty3416 commented
@AfshanKhan Please add screenshots & description. Also, always try to write a good fitting PR title.

https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

2020-06-17 10:46 UTC, Anurag810 approved these changes

2020-06-17 10:47 UTC, merged