Stock Ageing TypeError: ‘<’ not supported between instances of ‘int’ …
frappe/erpnext pull request #22206
Opened 2020-06-11 16:37 UTC by clarkejj

…and ‘str’

Re this user report https://discuss.erpnext.com/t/stock-ageing-report-typeerror-not-supported-between-instances-of-int-and-str/62605

Notes: 

ASSUMPTION:  This error arises in current version-12 production?

WARNING: This proposed change has not been tested

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2020-06-11 18:04 UTC, deepeshgarg007 requested changes

2020-06-11 18:04 UTC, deepeshgarg007 commented on erpnext/stock/report/stock_ageing/stock_ageing.py
> +					if 0 < cint(batch[0]) <= qty_to_pop:
`flt` should be used instead of `cint` as qty can be fraction value as well

2020-06-12 12:00 UTC, clarkejj reviewed
As Deepesh advised on review of my original proposed commit - change cint to flt since batch[0] can be int or float - see line 49

Thanks Deepesh!

2020-06-12 12:57 UTC, marination commented on erpnext/stock/report/stock_ageing/stock_ageing.py
> +						flt(batch[0]) -= qty_to_pop
```suggestion
						batch[0] = flt(batch[0]) - qty_to_pop
```
Can't assign values to a function call so `flt(batch[0])` is problematic

2020-06-12 13:25 UTC, clarkejj reviewed
Many thanks for your patient pointer Marica - that assignment violation is clear to me in retrospect, but a good relearning and change commit exercise in any case!

2020-06-12 14:08 UTC, clarkejj commented
Hi Deepesh and Marica - so once this fix is ok with all checks passing, will you then push this to develop, version-12-hotfix and other backport expected branches where required?

2020-06-12 15:20 UTC, deepeshgarg007 commented
Mergifyio backport version-12-hotfix

2020-06-12 15:41 UTC, deepeshgarg007 approved these changes

2020-06-12 15:44 UTC, merged

2020-06-12 16:09 UTC, clarkejj commented
Excellent thanks for the process learning coaching Deepesh and Marica

John

2020-06-25 07:13 UTC, marination commented
@clarkejj Can you please send these changes on version-12-hotfix as well ?