fix: Limit revenue sum within date range of report in Customer Acq. Report
frappe/erpnext pull request #22210
Opened 2020-06-12 06:17 UTC by abhishekbalam

Improvement on this:
#22075

The revenue was being calculated from 
the 1st invoice ever created, and hence
is too high. Only adding revenue
within date range.

Also limited count of new/repeated customers
to within daterange for Territory-wise as Monthly
already does that.

2020-06-12 06:51 UTC, abhishekbalam commented
Changes only done in the last function, had to 
convert spaces to tabs as I didn't have the last 
PR branch. From Line 162...

2020-06-14 11:39 UTC, deepeshgarg007 commented
@abhishekbalam  can you resolve merge conflicts

2020-06-15 05:29 UTC, abhishekbalam commented
@deepeshgarg007 
Done, please check.
If possible pls run locally and see if the report looks fine 👍

2020-06-16 17:06 UTC, deepeshgarg007 requested changes

2020-06-16 17:06 UTC, deepeshgarg007 commented on erpnext/selling/report/customer_acquisition_and_loyalty/customer_acquisition_and_loyalty.py
> +		if filters.from_date <= si.posting_date.strftime('%Y-%m-%d'):
```suggestion
		if getdate(filters.from_date) <= getdate(si.posting_date):
```

2020-06-16 17:06 UTC, deepeshgarg007 commented on erpnext/selling/report/customer_acquisition_and_loyalty/customer_acquisition_and_loyalty.py
> +		if filters.from_date <= si.posting_date.strftime('%Y-%m-%d'):
Also don't forget to import getdate

2020-06-17 11:35 UTC, abhishekbalam commented on erpnext/selling/report/customer_acquisition_and_loyalty/customer_acquisition_and_loyalty.py
> +		if filters.from_date <= si.posting_date.strftime('%Y-%m-%d'):
Ok, doing

2020-06-18 06:24 UTC, deepeshgarg007 approved these changes

2020-06-18 06:25 UTC, merged