fix: Student Admission
frappe/erpnext pull request #22255
Opened 2020-06-15 14:55 UTC by anupamvs

2020-06-16 11:23 UTC, anupamvs commented
@Mergifyio backport version-12-hotfix

2020-06-16 12:28 UTC, Anurag810 approved these changes

2020-06-16 12:32 UTC, Anurag810 requested changes

2020-06-16 12:32 UTC, Anurag810 commented on erpnext/education/doctype/student_applicant/student_applicant.py
> +		if student_admission and student_admission.min_age and \
You can use ```frappe.utils.date_diff()``` for getting diffrence. it return the value in days

2020-06-16 12:32 UTC, Anurag810 commented on erpnext/education/doctype/student_applicant/student_applicant.py
> +		if student_admission and student_admission.max_age and \
You can use ```frappe.utils.date_diff()``` for getting diffrence. it return the value in days.

2020-06-17 07:06 UTC, Anurag810 approved these changes

2020-06-17 07:08 UTC, merged