fix: Adding filter in academic term
frappe/erpnext pull request #22265
Opened 2020-06-16 10:50 UTC by anupamvs

2020-06-16 11:22 UTC, anupamvs commented
@mergifyio backport version-12-hotfix

2020-06-16 16:58 UTC, deepeshgarg007 requested changes

2020-06-16 16:58 UTC, deepeshgarg007 commented on erpnext/education/doctype/fee_structure/fee_structure.js
> +		frm.set_query("academic_term", function(){
```suggestion
		frm.set_query("academic_term", function() {
```

2020-06-16 16:58 UTC, deepeshgarg007 commented on erpnext/education/doctype/fee_structure/fee_structure.js
> +			return{
```suggestion
			return {
```

2020-06-16 16:58 UTC, deepeshgarg007 commented on erpnext/education/doctype/fee_structure/fee_structure.js
> +				"filters":{
```suggestion
				"filters": {
```

2020-06-16 16:58 UTC, deepeshgarg007 commented on erpnext/education/doctype/fee_structure/fee_structure.js
> +					"academic_year": (frm.doc.academic_year)
```suggestion
					"academic_year":  frm.doc.academic_year
```

2020-06-17 10:04 UTC, deepeshgarg007 approved these changes

2020-06-17 10:04 UTC, merged