feat: Enhancement in subscription [WIP]
frappe/erpnext pull request #22263
Opened 2020-06-16 06:25 UTC by deepeshgarg007

2020-06-23 05:00 UTC, nabinhait requested changes
update docs

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/subscription.json
> +   "label": "Follow Calendar Months",
Write a description of the field

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/subscription.json
> +   "fieldname": "end",
end_date

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/subscription.json
> +   "label": "Generate New Invoices Past Due Date"
Generate New Invoices On Due Date

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription_plan/subscription_plan.json
> +   "options": "\nFixed rate\nBased on price list\nMonthly rate",
The options should be in Title case, patch to fix existing

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription_plan/subscription_plan.json
> + "modified": "2020-06-14 22:39:48.732956",
Fix roles for subscription plan

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription_plan/subscription_plan.json
>     "label": "Price Determination",
Subscription Price Based On

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription_settings/subscription_settings.json
> +   "role": "Administrator",
Remove administrator
Add accounts manager and accounts user role

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription_invoice/subscription_invoice.json
> + "permissions": [],
Fix permissions

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/test_subscription.py
> +		subscription.process()
Add new test cases for "follow_calendar_months" and  "generate_new_invoices_past_due_date"

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/subscription.py
> +	return frappe.db.get_all('Subscription', {'status': 'Cancelled'})
status not cancelled

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/subscription.py
> +			return False
```suggestion
		if invoice and getdate(self.current_invoice_start) <= getdate(invoice.posting_date) <= getdate(self.current_invoice_end):
			return True
		return False
```

2020-06-23 05:00 UTC, nabinhait commented on erpnext/accounts/doctype/subscription/subscription.py
> +		if not current_invoice or self.is_not_outstanding(current_invoice):
`is_not_outstanding` can be renamed to `is_paid`

2020-06-23 13:07 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/subscription/subscription.json
> +   "label": "Generate New Invoices Past Due Date"
New invoices will be generate past 'Due Date' and not on 'Due Date' Itself so I feel past due date makes more sense here, rest changes I have made

2020-06-23 14:09 UTC, nabinhait requested changes
- fix travis
- change label of Price Determination

2020-06-23 14:09 UTC, nabinhait commented on erpnext/accounts/doctype/subscription_plan/subscription_plan.json
>     "label": "Price Determination",
?

2020-06-23 14:17 UTC, deepeshgarg007 commented
> * change label of Price Determination

![image](https://user-images.githubusercontent.com/42651287/85414963-656d5600-b58a-11ea-9750-1428cb2e68c9.png)

2020-07-23 05:41 UTC, nabinhait approved these changes

2020-07-23 05:41 UTC, merged