fix(Immutable Ledger): Item wise backdated stock entry posting
frappe/erpnext pull request #22366
Opened 2020-06-21 14:32 UTC by deepeshgarg007

Currently System won't allow backdated entry for any Item before the last stock transaction.

After this fix Item Wise Backdated will be checked

For Eg: If Stock Transaction is posted for Item A is made at 21 June 2020
Then Stock Transaction for Item B can still be made at 20 June 2020

2020-06-21 16:10 UTC, szufisher commented on erpnext/utilities/transaction_base.py
> +			fiscal_year = get_fiscal_year(self.get('posting_date'), as_dict=True).name
this line can be before the `for item in self.get('items')`

2020-06-22 12:02 UTC, nabinhait requested changes

2020-06-22 12:02 UTC, nabinhait commented on erpnext/utilities/transaction_base.py
> +				frappe.throw(_("""Last Stock Transaction for item {0} was on {1}.
The multiline message creates problem in translations. Please use `<br>` tag to create a multiline message.

2020-06-22 13:10 UTC, nabinhait approved these changes

2020-06-22 13:35 UTC, merged

2020-08-18 07:59 UTC, sammish commented
@nabinhait @deepeshgarg007 when can we expect the release in version-13

Please update very urgent