fix: Login page doesn't load for new sites
frappe/erpnext pull request #22388
Opened 2020-06-22 16:34 UTC by akurungadam

Login page broken as active domains are not set for new sites

2020-06-23 05:09 UTC, nabinhait approved these changes

2020-06-23 05:09 UTC, nabinhait commented on erpnext/templates/includes/footer/footer_powered.html
> -{% set label = domains[0].domain %}
`let label = null;`

Otherwise, it will give error on line 20

2020-06-23 05:09 UTC, nabinhait requested changes

2020-06-23 05:09 UTC, nabinhait commented on erpnext/templates/includes/footer/footer_powered.html
> -{% set label = domains[0].domain %}
let label = null;

Otherwise, it will give error on line 20

2020-06-23 05:20 UTC, Anurag810 commented
@nabinhait please this also #22394. both PR are for same issue.

2020-06-23 05:41 UTC, nabinhait approved these changes

2020-06-23 05:41 UTC, merged

2020-06-26 09:02 UTC, revant commented
https://travis-ci.com/github/frappe/frappe_docker/jobs/353812594#L827

Added a test to check index page of new site created using develop branch