Healthcare - Laboratory module enhancements
frappe/erpnext pull request #22416
Opened 2020-06-24 10:55 UTC by akurungadam

refactor: 
- Rename fields, child doctypes, style corrections
- Rearranged form fields, minor fixes

feat:
- Support for lab test results based on Secondary UOMs
- Allow optional result events
- Configure Result Legend
- Configure worksheet instructions
- Result formatting options in Lab Test
- Lab Test Print
  - Option to print Result Legend
  - Print Lab Test worksheet if not submitted
  - Print as per result format

2020-06-29 12:45 UTC, ruchamahabal commented
@akurungadam Can you add screenshots for the worksheet, result legend, and the modifications you have made in the result child tables?

2020-06-30 04:56 UTC, akurungadam commented
hey Rucha, I've updated the PR with relevant screen grabs. thanks

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/descriptive_test_result/descriptive_test_result.json
> +   "report_hide": 1
I guess **Allow Blank** field can be removed since **Require Result Value** takes care of that. Also, **Require Result Value** should be changed to **Result Value Required**. What's the difference between these fields?

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/normal_test_result/normal_test_result.js
> +// License: ESS license.txt
delete the js files for child tables

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/special_test_items/special_test_items.json
>  {
Delete the **Special Test Items** doctype files as you have renamed it to **Descriptive Test Result**

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/special_test_template/special_test_template.json
>  {
Delete the **Special Test Template** doctype files as you have renamed it to **Descriptive Test Template**

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/print_format/lab_test_print/lab_test_print.json
> + "html": "<div >\n  {% if letter_head and not no_letterhead -%}\n    <div class=\"letter-head\">{{ letter_head }}</div>\n    <hr>\n  {%- endif %}\n\n  {% if (doc.docstatus != 1) %}\n  <div align=\"ce
Can we remove the colons (":") from the patient information as the bold format for labels is already helping us differentiate between the label and value.

![lab-test](https://user-images.githubusercontent.com/24353136/86566950-25de3b00-bf88-11ea-8d61-9bd6bd30e6be.png)

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.js
> +				frappe.model.set_value(frm.doctype, frm.docname, 'report_preference', data.message.report_preference);
use an array of values to be updated as a parameter and call set_value only once

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +		frappe.db.set_value(self.doctype,self.name,'submitted_date', getdate())
Use `db_set` method in class methods

```suggestion
		self.db_set('submitted_date', getdate())
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +		frappe.db.set_value('Lab Test', self.name, 'status', 'Completed')
```suggestion
		self.db_set('status', 'Completed')
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
>  		insert_lab_test_to_medical_record(self)
medical record insertion should happen at last after the status has been set. So, if in case there are any exceptions the medical record won't be inserted.

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +		frappe.db.set_value('Lab Test', self.name, 'status', 'Cancelled')
```suggestion
		self.db_set('status', 'Cancelled')
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
>  		if(self.sensitivity_test_items):
```suggestion
		if self.sensitivity_test_items:
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +			if frappe.db.get_value('Lab Prescription', self.prescription, 'invoiced') == 1:
```suggestion
			if frappe.db.get_value('Lab Prescription', self.prescription, 'invoiced'):
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +				except Exception:
Can the Exception be more specific as TypeError or something? This is too generic.

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +	frappe.db.sql('''update `tabLab Test` set status=%s, approved_date=%s where name = %s''', (status, getdate(), name))
Use ORM with filters

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +	lab_test.descriptive_toggle = '1'
why 1 as a string? It should be an integer representing a boolean value, shouldn't it?

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +		lab_test.sensitivity_toggle = '1'
Same here. Why string?

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +	if(frappe.db.get_value('Healthcare Settings', None, 'create_sample_collection_for_lab_test') == '1'):
You can use `get_cached_value` for such checks:

```suggestion
	if frappe.db.get_cached_value('Healthcare Settings', None, 'create_sample_collection_for_lab_test'):
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
>  		if(sample_collection):
```suggestion
		if sample_collection:
```
Remove brackets from all such conditions

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
>  	medical_record.save(ignore_permissions=True)
add `ignore_mandatory` flag too

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +		where pe.patient = %s and lp.parent = pe.name and lp.lab_test_created = 0''', (patient))
Write a multiline SQL query

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test/lab_test_list.js
> +		if(doc.status=='Approved'){
```suggestion
		if (doc.status=='Approved') {
```
Add spaces for all such conditions

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/healthcare/doctype/lab_test_template/lab_test_template.py
> +			frappe.db.set_value(self.doctype, self.name, 'change_in_item', 0)
```suggestion
			self.db_set('change_in_item', 0)
```

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/patches/v13_0/healthcare_lab_module_rename_doctypes.py
> +		'Organism Test Item': 'Organism Test Result',
The **Organism Test Item** doctype is a new addition and it does not already exist in ERPNext. So you can remove this line.

2020-07-06 09:09 UTC, ruchamahabal commented on erpnext/patches/v13_0/healthcare_lab_module_rename_doctypes.py
> +			frappe.delete_doc("DocType", old_dt)
```suggestion
	for old_dt, new_dt in doctypes.items():
		if not frappe.db.table_exists(new_dt) and frappe.db.table_exists(old_dt):
			frappe.rename_doc('DocType', old_dt, new_dt)
```

Also, remove all doctype folders which are renamed

2020-07-06 09:17 UTC, ruchamahabal requested changes
Thank you for the PR! Some suggestions and changes required.

2020-07-08 16:23 UTC, akurungadam commented on erpnext/healthcare/doctype/descriptive_test_result/descriptive_test_result.json
> +   "report_hide": 1
Looks like the result_value_required should be a hidden field. This is an _internal_ field used to mark the result items for grouped tests - grouped tests bring in test names (result_value_required false) and test events (result_value_required true) based on which the result field is validated.

2020-07-09 09:58 UTC, akurungadam commented on erpnext/healthcare/doctype/lab_test/lab_test.py
>  	medical_record.save(ignore_permissions=True)
it's not an insert, we'll come up fixing the medical records creation in a separate PR

2020-07-09 14:07 UTC, akurungadam commented on erpnext/healthcare/doctype/lab_test/lab_test.py
> +				except Exception:
Didn't want to miss catching anything here, as we don't want to halt the save. So merely added a warning now.

2020-07-23 07:37 UTC, ruchamahabal submitted a review, later dismissed

2020-07-23 09:00 UTC, ruchamahabal approved these changes

2020-07-23 09:30 UTC, merged