refactor(WIP): Fleet Management
frappe/erpnext pull request #22664
Opened 2020-07-13 08:42 UTC by Anurag810

2020-09-08 06:13 UTC, nabinhait requested changes
- Add Description of the PR

**Vehicle**
- Make Vehicle document non-submittable
- Remove initial odometer field from Vehicle. Instead, add a button "Create Vehicle Log" there. Initial odometer value also should be added manually via Vehicle Log.

**Vehicle Log**
- On cancellation of Vehicle Log, update the maximum odometer value based on Vehicle Log.
- Validatation: Vehicle Log must be entered after the last Vehicle log date.

2020-10-12 09:24 UTC, rmehta requested changes
No screenshot? 

Disappointing work.

2020-10-12 09:24 UTC, rmehta commented on erpnext/hr/doctype/vehicle_log/vehicle_log.js
> +		if (!frm.doc.license_plate){
why not mandatory via field settings?

2020-10-12 09:24 UTC, rmehta commented on erpnext/hr/doctype/vehicle_log/vehicle_log.py
> +		if self.distance_covered < 0:
can be negative?????

2020-10-12 09:24 UTC, rmehta commented on erpnext/hr/doctype/vehicle_log/vehicle_log.js
> +			cur_frm.set_value("distance_covered", frm.doc.odometer - frm.doc.last_odometer);
server side logic?

2020-10-13 06:33 UTC, Anurag810 commented
will open separate pr for this was

2020-10-13 06:33 UTC, closed without merging