fix: making owner fieldtype to link
frappe/erpnext pull request #22661
Opened 2020-07-12 14:41 UTC by anupamvs

Issue- Columns cannot be added.
![leadowner_b](https://user-images.githubusercontent.com/20715976/87249277-dca45480-c47b-11ea-8dfa-87a945fbbd54.gif)

Fix- Making owner column fieldtype-> Link
![leadowner](https://user-images.githubusercontent.com/20715976/87249260-b1ba0080-c47b-11ea-835a-2d6f75514020.gif)

2020-07-12 14:42 UTC, anupamvs commented
@mergifyio backport version-12-hotfix

2020-07-14 07:44 UTC, Anurag810 requested changes
Travis Failing

2020-07-15 16:24 UTC, deepeshgarg007 approved these changes

2020-07-17 12:06 UTC, deepeshgarg007 approved these changes

2020-07-17 12:07 UTC, merged