chore: Export Buying Dashboard
frappe/erpnext pull request #22767
Opened 2020-07-22 07:22 UTC by marination

- Deleted dashboard_fixtures for buying module
- Exported Buying Dashboard, 4 number cards, 4 charts

2020-07-22 11:06 UTC, nabinhait requested changes

2020-07-22 11:06 UTC, nabinhait commented on erpnext/buying/dashboard_chart/material_request_analysis/material_request_analysis.json
> + "filters_json": "[[\"Material Request\",\"status\",\"not in\",[\"Draft\",\"Cancelled\",\"Stopped\",null],false],[\"Material Request\",\"material_request_type\",\"=\",\"Purchase\",false],[\"Material
Change transaction_date filter operator from `Between` to `Timestamp`

2020-07-22 11:06 UTC, nabinhait commented on erpnext/buying/number_card/annual_purchase/annual_purchase.json
> + "filters_json": "[[\"Purchase Order\",\"transaction_date\",\"Between\",[\"2020-03-24\",\"2021-03-23\"],false],[\"Purchase Order\",\"status\",\"not in\",[\"Draft\",\"Cancelled\",\"Closed\",null],fals
Change transaction_date filter operator from `Between` to `Timestamp`

2020-07-22 15:50 UTC, marination commented
@nabinhait done

2020-07-23 05:38 UTC, nabinhait approved these changes

2020-07-23 05:38 UTC, merged