fix: cannot change customer fields if credit exhausted
frappe/erpnext pull request #22838
Opened 2020-07-29 06:37 UTC by nextchamp-saqib

To replicate:
- Set a credit limit for a customer
- Set Administrator or any other user as Credit Controller in Accounts Setting
- Make sales invoice greater than the credit limit for the customer
- Now system won't allow changing Tax ID or any other field for that customer.

2020-07-29 09:57 UTC, nextchamp-saqib commented
@mergifyio backport version-12-hotfix

2020-08-12 15:23 UTC, nabinhait requested changes

2020-08-12 15:23 UTC, nabinhait commented on erpnext/selling/doctype/customer/customer.py
> +			for d in frappe.db.get_all("Customer Credit Limit", filters={'parent': self.name}, fields=["credit_limit"], order_by="idx")]
Why is it based on idx? It should be checked based on company

2020-08-13 03:48 UTC, nabinhait approved these changes

2020-08-13 03:49 UTC, merged