fix: minor payroll_dashboard fixes
frappe/erpnext pull request #22832
Opened 2020-07-28 10:57 UTC by Anurag810

get_query in monthly attendance sheet and Changed filters in job applicants cards

2020-07-28 12:05 UTC, ruchamahabal requested changes

2020-07-28 12:05 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.js
> +
```suggestion
			"reqd": 1
```
Remove the extra line and comma

2020-08-03 03:27 UTC, nabinhait approved these changes

2020-08-03 03:27 UTC, merged

2020-08-03 03:29 UTC, nabinhait commented
@Mergifyio backport version-13-beta-pre-release