refactor: Crm reports
frappe/erpnext pull request #22844
Opened 2020-07-29 10:13 UTC by anupamvs

2020-07-30 07:37 UTC, marination requested changes

2020-07-30 07:37 UTC, marination commented on erpnext/crm/report/lead_details/lead_details.py
> +		},
Not sure if adding Notes is useful. A report should have compact and to-the-point data. If its long form data, report is not the best way to show that

2020-07-30 07:37 UTC, marination commented on erpnext/crm/report/lead_details/lead_details.py
> +	return " and {}".format(" and ".join(conditions)) if conditions else ""
```suggestion
		conditions.append("and territory=%(territory)s")

	if filters.get("status"):
		conditions.append("and status=%(status)s")

	return conditions if conditions else ""
```

2020-07-30 07:37 UTC, marination commented on erpnext/crm/report/lost_opportunity/lost_opportunity.py
> +			`tabOpportunity`.contact_by
You can also fetch:
-  Lost Reason to analyse trends in why opportunities are lost
- Territory, to know where the most loss is happening
- Sales Stage to know where in the sales cycle improvement can happen
Just a suggestion

2020-07-30 07:37 UTC, marination commented on erpnext/crm/report/lost_opportunity/lost_opportunity.py
> +	return " and {}".format(" and ".join(conditions)) if conditions else ""
here also, you prefix 'and' before each condition as parent query has conditions already. And `return conditions if conditions else "" `. Simpler the better

2020-08-23 14:56 UTC, anupamvs commented on erpnext/crm/report/lost_opportunity/lost_opportunity.py
> +			`tabOpportunity`.contact_by
@marination Done!

2020-08-24 05:41 UTC, marination approved these changes, later dismissed

2020-08-24 12:32 UTC, anupamvs commented
@marination docs https://github.com/frappe/erpnext_documentation/pull/133

2020-08-24 14:12 UTC, marination approved these changes

2020-08-24 14:45 UTC, merged