feat: Return tracking in PR/DN [WIP]
frappe/erpnext pull request #22859
Opened 2020-07-31 10:30 UTC by marination

- Returned Qty fields in Items Table
 ![Screenshot 2020-07-31 at 4 01 17 PM](https://user-images.githubusercontent.com/25857446/89026621-a7867600-d346-11ea-86df-2a6d83881e7c.png)

- % Returned in parent doc
 ![Screenshot 2020-07-31 at 4 02 02 PM](https://user-images.githubusercontent.com/25857446/89026630-ace3c080-d346-11ea-8896-73dee8f42f81.png)

- Status 'Return Issued' added on original PR/DN if 100% returned. If partially returned , priority given to 'To Bill'
![Screenshot 2020-07-31 at 4 03 48 PM](https://user-images.githubusercontent.com/25857446/89026705-cbe25280-d346-11ea-8542-90feab42c6a8.png)

- List View
 ![Screenshot 2020-07-31 at 4 04 35 PM](https://user-images.githubusercontent.com/25857446/89026777-e7e5f400-d346-11ea-9c44-3deab0fbab2b.png)

2020-10-28 05:50 UTC, rohitwaghchaure commented
During test found below issues

1. Make purchase receipt for 3 quantity, make purchase return for 1 quantity and submit it. After that do one more purchase return entry, system shows default quantity as 3. It should show default quantity as 2 because 1 quantity already has returned.

1. Make delivery note for 3 quantity, and do sales return for 1 quantity. Then make sales invoice for 2 quantity and check delivery note status. It shows the status as "To Bill", should show the status as "Completed"

2020-11-03 17:48 UTC, marination commented
Reports bit is already ported to v12 https://github.com/frappe/erpnext/pull/23804

2020-11-18 12:31 UTC, gavindsouza requested changes

2020-11-18 12:31 UTC, gavindsouza commented on erpnext/accounts/report/received_items_to_be_billed/received_items_to_be_billed.py
> +		_("Purchase Receipt") + ":Link/Purchase Receipt:160",
Use JSON style API response

2020-11-18 12:31 UTC, gavindsouza commented on erpnext/controllers/sales_and_purchase_return.py
> +		""".format(child_doctype, doctype, reference_field),
~`.format`~. Try using ORM instead.

2020-11-18 12:31 UTC, gavindsouza commented on erpnext/controllers/sales_and_purchase_return.py
> +	return data[0]
`IndexError`?

2020-11-19 02:57 UTC, nabinhait commented
@marination resolve conflict

2020-12-06 17:13 UTC, rohitwaghchaure approved these changes

2020-12-06 17:13 UTC, merged