fix: Opportunity Status fix
frappe/erpnext pull request #22944
Opened 2020-08-06 18:42 UTC by anupamvs

**Issue -** On various doc event (validate, on_submit, on_cancel) of Quotation, It always sets the opportunity status to **null**.

**Fix -** Opportunity status changes when quotation event/status changes.

| Quoatation Status/Event  | Opportunity Status |
| ------------- | ------------- |
| on_submit  | Quotation  |
| Lost  | Lost  | 
| on_cancel  | Open  |

2020-09-07 14:51 UTC, anupamvs commented
@rohitwaghchaure can you review this?

2020-09-08 04:29 UTC, rmehta requested changes

2020-09-08 04:29 UTC, rmehta commented on erpnext/selling/doctype/quotation/quotation.py
> +		self.update_opportunity('Quotation')
what if Quotation is "Lost"? should this not be fixed via `status_updater.py`?

2020-10-13 17:29 UTC, rohitwaghchaure commented on erpnext/selling/doctype/quotation/quotation.py
>  		opp.set_status(update=True)
why set_status called two times?

2021-01-11 12:03 UTC, rohitwaghchaure approved these changes

2021-01-11 12:04 UTC, merged