fix(membership): currency should be a link
frappe/erpnext pull request #22966
Opened 2020-08-09 12:09 UTC by barredterra

Currency should be a Link field. If there's a valid reason memberships can only be in USD or INR, restricting the query might be a better approach.

2020-08-28 05:21 UTC, ruchamahabal approved these changes

2020-08-31 14:53 UTC, ruchamahabal requested changes

2020-08-31 14:53 UTC, ruchamahabal commented on erpnext/non_profit/doctype/membership/membership.json
>    },
@barredterra You will also need to change the modified timestamp in this case.

2020-09-19 13:01 UTC, deepeshgarg007 approved these changes

2020-09-19 13:03 UTC, merged