fix: user created manual job card not linking job card operations wit…
frappe/erpnext pull request #23126
Opened 2020-08-24 12:21 UTC by rohitwaghchaure

2020-08-25 09:58 UTC, rmehta requested changes

2020-08-25 09:58 UTC, rmehta commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +class OperatiobMismatchError(frappe.ValidationError): pass
typo `OperationMismatchError`

2020-08-28 07:00 UTC, rohitwaghchaure commented on erpnext/manufacturing/doctype/job_card/job_card.py
> +class OperatiobMismatchError(frappe.ValidationError): pass
Fixed

2020-08-28 07:01 UTC, rohitwaghchaure commented
@Mergifyio backport develop

2020-08-31 06:22 UTC, merged