feat: Create Issue from Opportunity
frappe/erpnext pull request #23152
Opened 2020-08-25 12:31 UTC by michellealva

This PR lets you create an Issue from the Opportunity via the create button.

![issue](https://user-images.githubusercontent.com/50285544/91174257-aace1100-e6fc-11ea-8ecd-d3af9c6a95e7.gif)

- The "Raised By" is auto-populated based on the contact set in the Opportunity
- The "Subject" field is the Customer Name

2020-08-26 07:24 UTC, rohitwaghchaure commented on erpnext/crm/doctype/opportunity/opportunity.js
> +			frm.add_custom_button(__('Issue'),
Check whether use has permission to create the Issue or not 
use below code
```
if (in_list(frappe.boot.user.can_create, "Issue")) {
   frm.add_custom_button(__('Issue'),
     function() {
                    frappe.new_doc('Issue', {
                              'raised_by': frm.doc.contact_email,
                              'subject': frm.doc.title
                    });
      }, __('Create'));
}
```

2020-08-26 09:53 UTC, michellealva commented
@rohitwaghchaure done, also, should the subject be copied from the customer's name or should it be left blank?

2020-08-26 11:00 UTC, rmehta requested changes
👍 

- add opportunity field in Issue
- add "DocType Link" instead of button

2020-08-27 12:02 UTC, anupamvs commented
@rmehta should we add Dynamic Link in issue so that it can be linked to any doc?

2020-08-28 03:58 UTC, rmehta commented
@anupamvs not a bad thought. Issue is general purpose, the origin document can be anything.

2021-01-11 12:05 UTC, closed without merging