feat : Leave type with partial payment
frappe/erpnext pull request #23173
Opened 2020-08-26 11:52 UTC by Anurag810

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2020-08-27 07:22 UTC, Anurag810 commented
docs: https://github.com/frappe/erpnext_documentation/pull/135

2020-10-12 09:29 UTC, rmehta requested changes
test missing

2020-10-12 09:29 UTC, rmehta commented on erpnext/payroll/doctype/salary_slip/salary_slip.py
> +		leave_types = frappe.db.sql(""" Select name, is_lwp, is_ppl, fraction_of_daily_salary_per_leave, include_holiday
You also have `or_conditions` in get_all

2020-10-16 07:46 UTC, Anurag810 commented
There already a test for LWP and a fraction of PPL is added in LWP.

2020-10-23 13:13 UTC, sagarvora commented
@Anurag810 Please fix breaking checks.

2020-11-17 07:07 UTC, nabinhait requested changes
Please write a specific test case for partial paid leave

2020-11-17 07:07 UTC, nabinhait commented on erpnext/payroll/doctype/salary_slip/salary_slip.js
> +					frm.fields_dict.absent_days.set_description("Unmarked Days is treated as "+ r.message[0] +". You can can change this in " + frappe.utils.get_form_link("Payroll Settings", "Payroll Settings", tru
Make it multilingual

2020-11-17 07:07 UTC, nabinhait commented on erpnext/hr/doctype/leave_type/leave_type.py
> +		if self.is_ppl and 0 < self.fraction_of_daily_salary_per_leave < 1 :
```suggestion
		if self.is_ppl and (self.fraction_of_daily_salary_per_leave < 0 or  self.fraction_of_daily_salary_per_leave > 1):
```

2020-11-25 10:30 UTC, nabinhait approved these changes

2020-11-25 10:30 UTC, merged