feat: Add Naming Series for Project DocType
frappe/erpnext pull request #23210
Opened 2020-08-30 14:08 UTC by michellealva

- Added Naming Series (PROJ.####) for Project DocType.

**Before:**

![image](https://user-images.githubusercontent.com/50285544/91661218-3c23f580-eaf8-11ea-9ba7-008c3033716b.png)

**After:**

![image](https://user-images.githubusercontent.com/50285544/91661235-5362e300-eaf8-11ea-813d-b47d0a2ceedd.png)

2020-08-30 14:09 UTC, michellealva commented
@Mergifyio backport version-12-hotfix

2020-09-02 18:50 UTC, hrwX requested changes

2020-09-02 18:50 UTC, hrwX commented on erpnext/projects/doctype/project/project.json
> +   "options": "PROJ.####",
```suggestion
   "options": "PROJ-.####",
```

2020-10-06 07:27 UTC, hrwX approved these changes, later dismissed

2021-01-14 11:05 UTC, marination approved these changes

2021-01-14 11:49 UTC, merged