fix: sql error on saving sales invoice without a sales order
frappe/erpnext pull request #23278
Opened 2020-09-07 00:36 UTC by barry86m

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

erpnext/controllers/selling_controller.py", line 85, in set_missing_lead_customer_details doesn't pass a value for posting_date
erpnext/accounts/party.py, line 60, in _get_party_details requires posting_date or it defaults to None

Fix is if self.posting_date is set pass details to party._get_party_details, if not pass None - which is the default behaviour of party._get_party_details

closes #23276

> Screenshots/GIFs

2020-09-16 08:09 UTC, sagarvora commented
Travis check a false negative, not really failing: https://travis-ci.com/github/frappe/erpnext/builds/183004011

2020-09-16 08:10 UTC, sagarvora requested changes

2020-09-16 08:10 UTC, sagarvora commented on erpnext/controllers/selling_controller.py
> +				posting_date=self.posting_date if hasattr(self, 'posting_date') else None,
```suggestion
				posting_date=self.get('posting_date'),
```

2020-09-20 15:10 UTC, deepeshgarg007 approved these changes

2020-09-20 15:10 UTC, merged