fix: consumed qty logic for subcontracted raw materials
frappe/erpnext pull request #23314
Opened 2020-09-12 09:55 UTC by rohitwaghchaure

**Issue**

Consumed quantity for the raw materials in subcontracted purchase receipt showing in negative

<img width="566" alt="Screenshot 2020-09-12 at 12 28 48 AM" src="https://user-images.githubusercontent.com/8780500/92992973-1c36fd80-f50c-11ea-876d-9f722aaf1666.png">

**After Fix**
<img width="839" alt="Screenshot 2020-09-12 at 12 29 48 AM" src="https://user-images.githubusercontent.com/8780500/92992959-0cb7b480-f50c-11ea-882e-0f624040b371.png">

2020-09-14 12:42 UTC, rohitwaghchaure commented
![image](https://user-images.githubusercontent.com/8780500/93087211-e0d83280-f6b5-11ea-832b-1310719ead80.png)

2020-09-14 15:51 UTC, nabinhait requested changes

2020-09-14 15:51 UTC, nabinhait commented on erpnext/controllers/buying_controller.py
> +		distinct_purchase_receipts[key].append(pr.name)
These 3 lines can be written like 
`distinct_purchase_receipts.setdefault(key, []).append(pr.name)`

2020-09-14 15:51 UTC, nabinhait commented on erpnext/controllers/buying_controller.py
> +	for args, references in distinct_purchase_receipts.items():
Use `iteritems()` for python 3

2020-09-15 14:10 UTC, nabinhait approved these changes

2020-09-15 14:10 UTC, merged