feat: Consider Holiday List in Student Leave Application and Attendance
frappe/erpnext pull request #23388
Opened 2020-09-21 19:04 UTC by ruchamahabal

- Validations for Holiday List in Student Attendance

   ![attendance_validation](https://user-images.githubusercontent.com/24353136/93808289-6be29b00-fc69-11ea-986c-99c5ebc8641c.png)

- **Total Leave Days** field added in Student Leave Application which is = days between `from_date` and `to_date` - number of holidays

   ![total_leave_days](https://user-images.githubusercontent.com/24353136/93808336-769d3000-fc69-11ea-9e23-d11096e20fe2.png)

- Student Attendance record creation on Leave Application submission skipped for holidays
- Holidays are shown as "H" in the Student Monthly Attendance Sheet

   ![monthly](https://user-images.githubusercontent.com/24353136/93809162-94b76000-fc6a-11ea-878b-73f211465b60.png)

- Fixed other attendance related reports
   - Student Batch wise Attendance
   - Absent Student Report
      
![attendance_validation](https://user-images.githubusercontent.com/24353136/93809638-21621e00-fc6b-11ea-8ef7-1f8a2ee0b587.png)

- Added Test

2020-09-22 06:39 UTC, Anurag810 reviewed
@ruchamahabal I think we can use generalized this with our attendance, monthly attendance sheet, leave application in HR. both looks same. it was just a thought. As it sales order for healthcare.

2020-10-14 14:28 UTC, nabinhait requested changes

2020-10-14 14:28 UTC, nabinhait commented on erpnext/education/doctype/student_attendance/student_attendance.py
> +			frappe.throw(_('Attendance cannot be marked for {0} as it is a holiday.').format(frappe.bold(self.date)))
Date should be displayed in user format

2020-10-14 14:28 UTC, nabinhait commented on erpnext/education/report/absent_student_report/absent_student_report.py
> +		msgprint(_("No attendance has been marked for {0} as it is a Holiday").format(frappe.bold(filters.get("date"))))
Date in user format

2020-10-14 14:28 UTC, nabinhait commented on erpnext/education/report/student_batch_wise_attendance/student_batch_wise_attendance.py
> +		msgprint(_("No attendance has been marked for {0} as it is a Holiday").format(frappe.bold(filters.get("date"))))
Date in user format

2020-11-09 13:10 UTC, nabinhait approved these changes

2020-11-09 13:11 UTC, merged