fix(HR): Remove Calculate Total Score button from Appraisal form
frappe/erpnext pull request #23500
Opened 2020-10-03 17:05 UTC by abhishekbalam

The "Calculate Total Score" button does not look good and 
it feels obtrusive. An alternate solution without using the button.
The calculation is triggered by the child table field change events.

Before:
![image](https://user-images.githubusercontent.com/15175501/94997422-910bcd80-05c8-11eb-879a-507d75b45c04.png)

After:

Pls click on the img to see the gif.
<a href="https://gifyu.com/image/6u62"><img src="https://s1.gifyu.com/images/image24f319c5040d77f9.png" alt="image24f319c5040d77f9.png" border="0" /></a>

Also made some edge case fixes were the Total Score was being set to NaN and improved a validation error message.

2020-10-05 09:05 UTC, Anurag810 requested changes

2020-10-05 09:05 UTC, Anurag810 commented on erpnext/hr/doctype/appraisal/appraisal.js
> +<<<<<<< Updated upstream
Please resolve conflicts

2020-10-05 12:23 UTC, abhishekbalam commented on erpnext/hr/doctype/appraisal/appraisal.js
> +<<<<<<< Updated upstream
done

2020-10-07 09:22 UTC, Anurag810 requested changes

2020-10-07 09:22 UTC, Anurag810 commented on erpnext/hr/doctype/appraisal/appraisal.js
> +			frm.refresh_field('calculate_total');
```frm.set_value``` already refresh field

2020-10-07 09:46 UTC, Anurag810 requested changes

2020-10-07 09:46 UTC, Anurag810 commented on erpnext/hr/doctype/appraisal/appraisal.json
> +  "company",
Move the company field at the top.

2020-10-07 09:46 UTC, Anurag810 commented on erpnext/hr/doctype/appraisal/appraisal.json
> +  "amended_from"
Move this field to top tooo.

2020-10-07 09:46 UTC, Anurag810 commented on erpnext/hr/doctype/appraisal/appraisal.json
> +  "company",
The value of the company should be fetched from employee master. Keep the field read-only doesn't allow to change.
![image](https://user-images.githubusercontent.com/32095923/95314468-f6084180-08ae-11eb-93f5-2609304c7900.png)

2020-10-07 10:22 UTC, abhishekbalam commented
@Anurag810 
Changes made and gif updated.

2020-10-07 14:29 UTC, merged

2020-11-20 08:23 UTC, dawoodjee commented
Why cant this be automated on change of the score field?