chore: validate reference document
frappe/erpnext pull request #23526
Opened 2020-10-07 09:30 UTC by nextchamp-saqib

2020-10-07 14:12 UTC, barredterra approved these changes

2020-10-07 14:13 UTC, barredterra requested changes
`from frappe import _`

2020-10-07 14:19 UTC, marination commented
Add a description with a screenshot of the message too please

2020-10-08 08:20 UTC, nextchamp-saqib commented
So it turns out this won't be needed hence closing this.

2020-10-08 08:20 UTC, closed without merging