fix(Employee): Field level change in Exit section
frappe/erpnext pull request #23524
Opened 2020-10-06 10:33 UTC by michellealva

invalid

2020-10-07 08:30 UTC, Anurag810 requested changes
Have you removed the relieving date because it is not visible in the second screenshot?

2020-10-07 10:12 UTC, michellealva commented
@Anurag810 no, it's dependent on the stats of the employee and is only shown when the status is left. In the second screenshot, the status was still Active, hence not visible.

2020-10-12 10:53 UTC, rohitwaghchaure approved these changes

2020-10-12 10:53 UTC, merged

2020-10-12 10:55 UTC, rohitwaghchaure commented
@michellealva we need to write patch to shift data from Reason for Resignation to Reason for Leaving