chore: validate is_group of child parent account
frappe/erpnext pull request #23550
Opened 2020-10-08 09:32 UTC by nextchamp-saqib

**Problem:**
Converting a account to a group, then adding an account to it throws:

<img width="505" alt="Screenshot 2020-10-08 at 3 00 53 PM" src="https://user-images.githubusercontent.com/25369014/95440874-13084780-0977-11eb-9639-98660d6735c1.png">

**Now:**
Throw proper message if child company account is not a group while adding an account in parent company

<img width="511" alt="Screenshot 2020-10-08 at 3 01 33 PM" src="https://user-images.githubusercontent.com/25369014/95440943-29ae9e80-0977-11eb-87e3-cbd1f54eeee8.png">

2020-10-13 15:56 UTC, deepeshgarg007 commented
@nextchamp-saqib Please resolve merge conflicts

2020-10-14 11:04 UTC, nabinhait requested changes

2020-10-14 11:04 UTC, nabinhait commented on erpnext/accounts/doctype/account/account.py
> +				frappe.throw(_("While creating account for Child Company {0}, parent account {1} is found \
Don't use "\" and "<br>" in message for translations.

2020-10-26 13:18 UTC, deepeshgarg007 requested changes

2020-10-26 13:18 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/account/account.py
> +				msg = _("Please convert the parent account in corresponding child company to a group account.")
```suggestion
				msg += _("Please convert the parent account in corresponding child company to a group account.")
```

2020-10-27 08:24 UTC, deepeshgarg007 approved these changes

2020-10-27 08:24 UTC, merged