fix: Typo/Grammatical fixes in Settings
frappe/erpnext pull request #23612
Opened 2020-10-13 05:12 UTC by michellealva

Multiple grammatical fixes/title case formatting and typo fixes in:
- Stock Settings

2020-10-13 06:53 UTC, Anurag810 submitted a review, later dismissed

2020-10-16 05:02 UTC, sagarvora requested changes

2020-10-16 05:02 UTC, sagarvora commented on erpnext/accounts/doctype/accounts_settings/accounts_settings.json
> +   "label": "Accounts Frozen Up To"
```suggestion
   "label": "Accounts Frozen Till Date"
```

2020-10-16 05:02 UTC, sagarvora commented on erpnext/accounts/doctype/accounts_settings/accounts_settings.json
> +   "description": "The role that is allowed to submit transactions that exceed credit limits set",
```suggestion
   "description": "This role is allowed to submit transactions that exceed credit limits",
```

2020-10-16 05:02 UTC, sagarvora commented on erpnext/accounts/doctype/accounts_settings/accounts_settings.json
> +   "label": "Show Payment Schedule In Print"
I don't think we capitalise short prepositions.
Refer https://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html

2020-10-16 05:02 UTC, sagarvora commented on erpnext/accounts/doctype/accounts_settings/accounts_settings.json
> +   "description": "The percentage you are allowed to bill more against the amount ordered. For example, If the order value is $100 for an item and tolerance is set as 10%, then you are allowed to bil
```suggestion
   "description": "The percentage you are allowed to bill more against the amount ordered. For example, if the order value is $100 for an item and tolerance is set as 10%, then you are allowed to bill up to $110 ",
```

2020-10-16 05:02 UTC, sagarvora commented on erpnext/accounts/doctype/accounts_settings/accounts_settings.json
> +   "description": "If \"Months\" is selected, then a fixed amount will be booked as deferred revenue or expense for each month irrespective of the number of days in a month. It will be prorated if de
```suggestion
   "description": "If \"Months\" is selected, a fixed amount will be booked as deferred revenue or expense for each month irrespective of the number of days in a month. It will be prorated if deferred revenue or expense is not booked for an entire month",
```

2020-10-16 05:02 UTC, sagarvora commented on erpnext/buying/doctype/buying_settings/buying_settings.json
> +   "label": "Allow Item to Be Added Multiple Times in a Transaction"
```suggestion
   "label": "Allow Item To Be Added Multiple Times in a Transaction"
```
Refer **Capitalize Verbs and Helping Verbs** here:
https://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html

2020-10-16 05:02 UTC, sagarvora commented on erpnext/hr/doctype/hr_settings/hr_settings.json
> +   "description": "Employee records are created using the selected field ",
```suggestion
   "description": "Employee records are created using the selected field",
```

2020-10-16 05:02 UTC, sagarvora commented on erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
> +   "label": "Time Between Operations (Mins)"
Not sure here, but I don't think units are capitalised.

2020-10-16 05:02 UTC, sagarvora commented on erpnext/manufacturing/doctype/manufacturing_settings/manufacturing_settings.json
> +   "description": "Allow multiple material consumption against a Work Order",
```suggestion
   "description": "Allow multiple material consumptions against a Work Order",
```

2020-10-23 12:52 UTC, nabinhait approved these changes

2020-10-23 12:52 UTC, merged