feat: Attendance enhancements and Monthly Attendance Sheet Refactor
frappe/erpnext pull request #23665
Opened 2020-10-16 06:48 UTC by Anurag810

Tracking Remaining Half-day status on half-day leave or attendance:
Use Case: Suppose Employee is on half-day Leave so we also need to track attendance for remaining half-day

Added field **Remaining Half Day Status** in Attendance if the status is Half-Day:
![image](https://user-images.githubusercontent.com/32095923/96221501-5894c800-0fa8-11eb-8210-d0bd6c7a1703.png)

Added field **Remaining Half Day Status** in Leave Application if Application contains Half-day:
![image](https://user-images.githubusercontent.com/32095923/96221836-d78a0080-0fa8-11eb-83dc-19356f8163b7.png)

Added Abbreviation for Leave types:
![image](https://user-images.githubusercontent.com/32095923/96220813-174fe880-0fa7-11eb-8363-5f9fa8e11c80.png)

Added Attendance Status Master with Status Abbr.:
![image](https://user-images.githubusercontent.com/32095923/96221054-7b72ac80-0fa7-11eb-8967-bb664bb4c30a.png)

Complete Code Refactor for Monthly Attendance Sheet:
Broken code into Smaller Function.
Added generic Date filter. removed Hardcoded Filters. (Record of more than one month Can be seen )
Removed Horcoded Abbreviation.
Different Abbr for Different Leave type.
teak attendance of both remaining Half day is Half-Day.

![image](https://user-images.githubusercontent.com/32095923/96222286-9c3c0180-0fa9-11eb-9fd0-89ceef3a36a6.png)

2020-10-21 11:36 UTC, Anurag810 commented
Doc: https://github.com/frappe/erpnext_documentation/pull/179

2020-10-26 11:25 UTC, Anurag810 commented
Doc: frappe/erpnext_documentation#179

2020-12-03 10:08 UTC, harshal2530 commented
@Anurag810  Any Update!

2021-01-18 08:07 UTC, ruchamahabal requested changes
Requesting changes. Also, try using uniform quote styles throughout one file.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_request/attendance_request.json
> +  "status",
If we are replacing `reason` with `status` then we need to rename the field in the patch too so that old data is not lost.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.js
> +	},
Reset these values on the server-side too.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.js
> +			cur_frm.set_value(field, 0);
```suggestion
			frm.set_value(field, 0);
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.py
> +			frappe.throw(_("Attendance status can be either Present, leave or Half day"))
There can be different possibilities too, like "present" and "leave" can be checked together but not "half day" and so on. Can you take that into consideration too?

```suggestion
			frappe.throw(_("Attendance status can either be Present, Leave or Half day."))
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.py
> +			msg += _("Duplicate Default Status for {0}.{1}Reference : {2}").format(references[i], "<br>", bold(link)) + "<hr>"
```suggestion
			msg += _("A Default Status for {0} already exists. {1} Reference : {2}").format(references[i], "<br>", bold(link)) + "<hr>"
```
Also why hr tag at the end? Looks as if something is missing in the message.

![image](https://user-images.githubusercontent.com/24353136/104886263-6edb6700-598f-11eb-987b-9c03c838768f.png)

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/employee_checkin/employee_checkin.py
> +			hd_status, p_status, a_status = get_applicable_status()
```suggestion
			half_day_status, present_status, absent_status = get_applicable_status()
```
Can you change the variable names for better context? Lookout for these variables in the whole file.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/leave_application/leave_application.py
> +		on_leave_status = [status.name for status in statuses if status.is_leave == 1]
```suggestion
		half_day_status = [status.name for status in statuses if status.is_half_day]
		on_leave_status = [status.name for status in statuses if status.is_leave]
```
The if statement will return 1 only so no need to check explicitly.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/shift_type/shift_type.py
> +		print(statuses)
```suggestion
```
Remove print statements.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/shift_type/shift_type.py
> +		if not(check_a_status and check_hd_status and check_p_status):
```suggestion
		if not (check_a_status and check_hd_status and check_p_status):
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +]
Write in a single line?

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		record, emp_att_map = add_data(emp_map, att_map, holiday_map, filters, default_holiday_list, leave_list=leave_list)
```suggestion
		record, attendance = add_data(emp_map, att_map, holiday_map, filters, default_holiday_list, leave_list=leave_list)
```
Better variable names for more context?

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +				if len(abbr) == 1 and  abbr[0] not in ["<b>WO</b>", "<b>H</b>"]:
```suggestion
				if len(abbr) and  abbr[0] not in ["<b>WO</b>", "<b>H</b>"]:
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +			status = get_status(attendance_detail, holiday_map, emp_holiday_list, day)
```suggestion
			status = get_status(attendance_detail, holiday_map, emp_holiday_list, day)
```
You are anyway setting the status immediately so you can remove the default assignment.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		early_exit = 1 %s) as early_exit_count""" % (conditions, conditions), filters)
Write multiline SQL.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		where leave_type is not NULL %s group by leave_type, status""" % conditions, filters, as_dict=1)
Write multiline SQL.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		print(d)
```suggestion
```
Remove print statement.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +						status = "Holiday"
Should this loop still continue running once you get that day in the holiday map? If not, you can return the status from here itself:

```suggestion
					if holiday_map[emp_holiday_list][idx][1]:
						return "Weekly Off"
					else:
						return "Holiday"
```

If you choose to do this, on line 271 also, return the status directly.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +			days.append(cstr(day+1)+ " " +day_name + " "+ month_name +"::100")
```suggestion
		if get_att_map_key:
			days.append(str(day+1) + "/" + str(month))
		else:
			date = str(year) + "-" + str(month)+ "-" + str(day+1)
			day_name = day_abbr[getdate(date).weekday()]
			day_name += "," if add_month else ''
			days.append(cstr(day+1) + " " + day_name + " " + month_name + "::100")
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		,filters, as_dict=1)
Multiline SQL.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +				where parent=%s and holiday_date BETWEEN %s and %s ''', (d, getdate(from_date), getdate(to_date)))
Multiline SQL

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		elif status_map[status]['is_half_day']:
```suggestion
		if status_map[status]["is_present"]:
			present += 1
		elif status_map[status]["is_leave'"]:
			leave += 1
		elif status_map[status]["is_half_day"]:
```

Try using uniform quote styles throughout one file.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/patches/v13_0/create_attendance_status_leave_type_abbr_and_set_remaining_half_day_status.py
> +    frappe.reload_doc("HR", "doctype", 'Attendance')
```suggestion
    frappe.reload_doc("HR", "doctype", "Attendance Status")
    frappe.reload_doc("HR", "doctype", "Leave Application")
    frappe.reload_doc("HR", "doctype", "Attendance")
    frappe.reload_doc("HR", "doctype", "Leave Type")
```

Patch failing. You will have to reload Leave Type too:

![image](https://user-images.githubusercontent.com/24353136/104883868-6da83b00-598b-11eb-9615-987e96166fa0.png)

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance/attendance.json
> +   "label": "Is leave"
We will have to set values for these hidden checkboxes in old Attendance records too right?
Should be handled in the patch.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance/attendance.js
> +		frm.set_query("remaining_half_day_status", function() {
I am allowed to select "Absent" in "remaining half day status". Is this fine?

![image](https://user-images.githubusercontent.com/24353136/104885222-b2cd6c80-598d-11eb-9e11-ac00454bc059.png)

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_request/attendance_request.json
> +   "label": "Half Day Date",
Why do we need to capture half day date separately? If will be within from and to dates right?

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_request/attendance_request.json
> +   "label": "Remaining Half Day status",
```suggestion
   "label": "Remaining Half Day Status",
```
Title casing for labels

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_request/attendance_request.py
>  				if self.half_day and date_diff(getdate(self.half_day_date), getdate(attendance_date)) == 0:
```suggestion
				if self.half_day and getdate(self.half_day_date) == getdate(attendance_date):
```
Instead of computing `date_diff` you can simply check if those two dates are equal I think.

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.json
> +   "description": "Will be used as default Status while <b>Attendance</b> creation through Document Type. ",
```suggestion
   "description": "Will be used as the default Status during <b>Attendance</b> creation. ",
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.json
> +   "description": "If Status is not Present, Half Day, or Leave. It Will be considered as Absent.",
```suggestion
   "description": "If Status is not Present, Half Day, or Leave, it will be considered as Absent.",
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/attendance_status/attendance_status.py
> +				references.append("Leave application")
```suggestion
				references.append("Leave Application")
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/doctype/leave_application/leave_application.py
> +		att = frappe.get_all("Attendance", filters = {"leave_application": self.name, "is_half_day": 1})[0].name
```suggestion
		attendance = frappe.get_all("Attendance", filters = {"leave_application": self.name, "is_half_day": 1})[0].name
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.js
> +			"label": __("From date"),
```suggestion
			"label": __("From Date"),
```
Labels in title case

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.js
> +			"label": __("To date"),
```suggestion
			"label": __("To Date"),
```
Labels in title case

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		frappe.throw(_("To date can not less than From date"))
```suggestion
		frappe.throw(_("To Date cannot be less than From Date"))
```

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.js
> +			"fieldtype": "Date",
Also, add a default value for the ongoing month?

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.js
>  			"reqd": 1
Also, add a default value for the ongoing month?

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		frappe.throw(_("Please select interval period less than 2 months"))
```suggestion
		frappe.throw(_("Please select the interval period between From Date and To Date to be less than 2 months"))
```

Any reason to limit the period?

2021-01-18 08:07 UTC, ruchamahabal commented on erpnext/hr/report/monthly_attendance_sheet/monthly_attendance_sheet.py
> +		frappe.throw(_("Please select date having same Year"))
```suggestion
		frappe.throw(_("Please select the From Date and the To Date from the same Year."))
```

2021-03-01 13:51 UTC, Anurag810 commented
will update pr

2021-03-01 13:51 UTC, closed without merging