fix: copying po no when mapping doc
frappe/erpnext pull request #23729
Opened 2020-10-26 11:33 UTC by AfshanKhan

When creating a delivery note from a sales invoice or sales invoice from a delivery note. The customer's Purchase Order number was not being copied. Fixed that.

![Screenshot 2020-10-26 at 5 02 29 PM](https://user-images.githubusercontent.com/33727827/97167600-1855f680-17ad-11eb-8f1d-1f629d354f41.png)

![Screenshot 2020-10-26 at 5 02 47 PM](https://user-images.githubusercontent.com/33727827/97167617-1ee46e00-17ad-11eb-8baf-3ee3bced8d16.png)

2020-10-26 11:39 UTC, AfshanKhan commented
Backport at https://github.com/frappe/erpnext/pull/23730

2020-10-26 14:04 UTC, nabinhait requested changes

2020-10-26 14:04 UTC, nabinhait commented on erpnext/controllers/selling_controller.py
> +				self.po_no += ', '.join(list(set([d.po_no for d in dn_po_nos if d.po_no])))
The current code can lead to repititive po_no if same po_no is present in Sales Order and Delivery Note.

```suggestion
		po_nos = []
		sales_orders = list(set([d.get(ref_fieldname1) for d in self.items if d.get(ref_fieldname1)]))
		if sales_orders:
			so_po_nos = frappe.get_all('Sales Order', 'po_no', filters = {'name': ('in', sales_orders)})
			if so_po_nos and so_po_nos[0].get('po_no'):
				po_nos = [d.po_no for d in so_po_nos if d.po_no]

		delivery_notes = list(set([d.get(ref_fieldname2) for d in self.items if d.get(ref_fieldname2)]))
		if delivery_notes:
			dn_po_nos = frappe.get_all('Delivery Note', 'po_no', filters = {'name': ('in', delivery_notes)})
			if dn_po_nos and dn_po_nos[0].get('po_no'):
				po_nos += [d.po_no for d in dn_po_nos if d.po_no]

		self.po_no = ', '.join(list(set(po_nos)))
```

2020-10-26 14:04 UTC, nabinhait commented on erpnext/controllers/selling_controller.py
> +				self.po_no += ', '.join(list(set([d.po_no for d in dn_po_nos if d.po_no])))
Also you can write a small function `get_po_nos(ref_doctype, ref_fieldname)` which will return po_nos from the ref doc.

2020-11-09 08:14 UTC, marination commented on erpnext/controllers/selling_controller.py
> +			if po_no_list and po_no_list[0].get('po_no'):
we could have a dict such as `[{'po_no': None}, {'po_no': 'PO-1234'}]`, in that case it just skips the whole `po_no_list `

2020-11-09 09:10 UTC, marination commented
Case: 
Create two Sales Orders. One with Po no 'PO-1234' and one with 'PO-5678'.
Fetch these in one Sales Invoice (get Items from) and submit. Now Sales Invoice Po no is `PO-1234, PO-5678`.
From this Sales Invoice create a Delivery Note . The Po no in the Delivery Note is:
![Screenshot 2020-11-09 at 2 41 07 PM](https://user-images.githubusercontent.com/25857446/98521327-45b89f00-2299-11eb-96be-d7d107b4722a.png)

When the list looks like this => ['**PO-5678**', '**PO-1234**', '**PO-1234, PO-5678**'], `set` wont work since the last element is a comma joined string.

2020-11-11 06:48 UTC, marination approved these changes

2020-11-11 12:14 UTC, merged