feat: Sync old shopify orders [WIP]
frappe/erpnext pull request #23841
Opened 2020-11-05 12:54 UTC by deepeshgarg007

2020-11-05 14:04 UTC, Alchez commented
@deepeshgarg007, I'm currently working on a [different Shopify feature](https://github.com/ParsimonyGit/erpnext/pull/6) that uses their [python library](https://pypi.org/project/ShopifyAPI/) to manage sessions and resources. I'm planning to contribute that here once it's ready, maybe you want to pick up the library for this too?

2020-11-10 06:43 UTC, saurabh6790 requested changes

2020-11-10 06:43 UTC, saurabh6790 commented on erpnext/erpnext_integrations/doctype/shopify_settings/shopify_settings.py
> +		pass
do not comment this code

2020-11-10 06:43 UTC, saurabh6790 commented on erpnext/loan_management/doctype/loan_repayment/loan_repayment.py
> +			penalty_amount += (entry.interest_amount * (loan_type_details.penalty_interest_rate / 100) * no_of_late_days)
intentional?

2020-11-10 08:59 UTC, saurabh6790 approved these changes

2020-11-13 11:23 UTC, merged

2020-11-19 11:28 UTC, rmehta commented
@Alchez we are planning to move integations out of ERPNext - do you have a custom app?

2020-11-19 11:54 UTC, Alchez commented
@rmehta Currently I'm building it on top of the existing Shopify code base, so it's on a forked repo of ERPNext. I could contribute it soon, and then it could be moved out?

2021-01-08 09:50 UTC, Alchez commented
@rmehta @deepeshgarg007 

Any word on moving Shopify out into a custom app? We would be happy to work together and contribute our additions