feat: Configurable accounting dimension filters and validations
frappe/erpnext pull request #23912
Opened 2020-11-16 04:27 UTC by deepeshgarg007

2020-11-19 11:24 UTC, rmehta requested changes

2020-11-19 11:24 UTC, rmehta commented on erpnext/accounts/doctype/accounting_dimension/accounting_dimension.py
> +def get_dimension_filters(with_costcenter_and_project=False):
`cost_center`

2020-11-19 11:24 UTC, rmehta commented on erpnext/controllers/queries.py
> +		result = frappe.db.sql("""SELECT name from `tab{doctype}` where
use ORM

2020-11-19 11:24 UTC, rmehta commented on erpnext/public/js/utils/dimension_tree_filter.js
>  let default_dimensions = {};
file needs to be namespaced

2020-11-19 11:24 UTC, rmehta commented on erpnext/public/js/utils/dimension_tree_filter.js
>  let default_dimensions = {};
```
erpnext.accounts.dimensions = {
  setup(doctype) {
     // if (doctype) is applicable, then set the filters
     this.fetch_custom_dimensions(doctype).then(() => this.setup_filters());
  }

  fetch_custom_dimensions(doctype) {

  }
}
```

in `sales_invoice.js`

```
onload(frm) {
   erpnext.accounts.dimensions.setup(frm.doctype);
   ...
}
```

2020-11-25 12:10 UTC, netchampfaris commented on erpnext/accounts/doctype/accounting_dimension_filter/test_accounting_dimension_filter.py
> +from erpnext.exceptions import InvalidAccountDimension, MandatoryDimension
Consistent error class naming
```suggestion
from erpnext.exceptions import InvalidAccountDimensionError, MandatoryAccountDimensionError
```

2021-01-16 08:27 UTC, merged