feat: Introducing telephony module
frappe/erpnext pull request #24032
Opened 2020-11-30 08:04 UTC by leela

Introducing a module named Telephony, that holds all the common doctype's needed to integrate any telephony communication app.

**Added**
* New module named Telephony added.
* `Incoming Call Settings` and `Incoming Call Handling Schedule` doctype's added
* Moved call_log doctype from communication into Telephony module
* Added validations for new doctype's
* Phone icon that is part of frappe is moved into ERP

**Screenshot**
![incoming_call_settings](https://user-images.githubusercontent.com/36557/100583256-73c95600-3310-11eb-9481-255839ca4764.png)

2020-12-01 06:02 UTC, surajshetty3416 requested changes

2020-12-01 06:02 UTC, surajshetty3416 commented on erpnext/telephony/doctype/incoming_call_settings/incoming_call_settings.js
> +			frappe.throw(`Please fix overlapping time slots for ${day}.`);
```suggestion
			frappe.throw(__("Please fix overlapping time slots for {0}.", [day]);
```
User facing strings should be translatable.
https://github.com/frappe/erpnext/wiki/Coding-Standards#user-facing-messages-must-be-translated

More information on translations: https://frappeframework.com/docs/user/en/translations

2020-12-01 06:02 UTC, surajshetty3416 commented on erpnext/telephony/doctype/incoming_call_settings/incoming_call_settings.js
> +			errors.push(`Call Schedule Row ${row}: To time slot should always be ahead of From time slot.`);
```suggestion
			errors.push(__("Call Schedule Row {0}: To time slot should always be ahead of From time slot."), [row]);
```

2020-12-01 06:02 UTC, surajshetty3416 commented on erpnext/telephony/doctype/incoming_call_settings/incoming_call_settings.py
> +				)
```suggestion
				errors.append(_("Call Schedule Row {0}: To time slot should always be ahead of From time slot.").format(record.idx))
```
https://github.com/frappe/erpnext/wiki/Coding-Standards#user-facing-messages-must-be-translated

2020-12-01 06:02 UTC, surajshetty3416 commented on erpnext/telephony/doctype/incoming_call_settings/incoming_call_settings.py
> +					frappe.throw(f"Please fix overlapping time slots for {day}.")
```suggestion
					frappe.throw(_("Please fix overlapping time slots for {0}.").format(day))
```

2020-12-01 07:20 UTC, surajshetty3416 approved these changes

2020-12-01 07:34 UTC, merged

2021-01-04 06:20 UTC, ameerbaathar commented
how to use the API for this feature ?

2023-04-02 04:13 UTC, nashwan762 commented
O