fix: charts not displaying when tree_type changed
frappe/erpnext pull request #24148
Opened 2020-12-16 09:53 UTC by hasnain2808

Charts were not displaying on clicking the checkboxes in Sales and Purchase Analytics Reports
**Solved**
![analytics report](https://user-images.githubusercontent.com/28212972/102332734-826f6880-3fb2-11eb-9820-a404ecb1ea7f.gif)

2020-12-17 10:38 UTC, Anurag810 requested changes

2020-12-17 10:38 UTC, Anurag810 commented on erpnext/buying/report/purchase_analytics/purchase_analytics.js
> +					let found = false;
What is `found` please use a better variable name and also check other variable names.

2020-12-17 10:38 UTC, Anurag810 commented on erpnext/buying/report/purchase_analytics/purchase_analytics.js
> +					for (let i = 0; i < new_datasets.length; i++) {
use `for-each loop` for better readability.

2020-12-17 10:39 UTC, Anurag810 requested changes
Also, port to version-12

2020-12-17 10:49 UTC, Anurag810 requested changes
> Charts were not displaying on clicking the checkboxes in Sales and Purchase Analytics Reports
> **Solved**
>![image](https://user-images.githubusercontent.com/32095923/102478689-e746c380-4083-11eb-93ce-f442148d85bf.png)


Why It is showing two lines if only one row is checked. on switching tree type to **Item Group**

2020-12-17 10:57 UTC, hasnain2808 commented
> > Charts were not displaying on clicking the checkboxes in Sales and Purchase Analytics Reports
> > **Solved**
> >![analytics report](https://user-images.githubusercontent.com/28212972/102332734-826f6880-3fb2-11eb-9820-a404ecb1ea7f.gif)
> 
> Why It is showing two lines if only one row is checked. on switching tree type to **Item Group**

@Anurag810 
It is looking that way because the gif Is looping
Will upload the full video soon

2020-12-22 07:14 UTC, hasnain2808 commented
@Anurag810 
[Full Video](https://drive.google.com/file/d/1zKXlt0QJPGVxe--H3FuQqCnS3zlPOau7/view?usp=sharing)

2021-01-05 08:33 UTC, merged

2021-01-05 08:33 UTC, Anurag810 approved these changes