fix: allow addition and removal of employee in payroll Entry
frappe/erpnext pull request #24169
Opened 2020-12-17 09:58 UTC by Anurag810

Allow Addition and removal of the employee during payroll. Delete and button is visible now.
![Screenshot 2020-12-17 at 3 15 05 PM](https://user-images.githubusercontent.com/32095923/102472620-79e36480-407c-11eb-9b01-253b7caac0ed.png)

2020-12-17 10:20 UTC, abhishekbalam submitted a review, later dismissed

2020-12-18 05:49 UTC, deepeshgarg007 requested changes
@Anurag810 Its not this simple. Just removing read-only fields won't do. You'll have to filter the employees based on the parameters selected in Payroll Entry. Check for employees whose salary has been already precessed for the current month. Also some employee accruals are also needed to be considered

2020-12-18 06:28 UTC, dufani1 commented
This is very good

2020-12-18 06:31 UTC, dufani1 commented
@Anurag810  Please add filter of selecting employees based on salary currency

2020-12-23 11:51 UTC, Anurag810 commented
> @Anurag810 Its not this simple. Just removing read-only fields won't do. You'll have to filter the employees based on the parameters selected in Payroll Entry. Check for employees whose salary has been already precessed for the current month. Also some employee accruals are also needed to be considered

done

2020-12-30 11:19 UTC, rohitwaghchaure approved these changes

2020-12-30 11:20 UTC, merged