Update item_tax_template_dashboard.py
frappe/erpnext pull request #24311
Opened 2021-01-05 17:50 UTC by wojosc

added missing backlink and label. 

In Item Groups I can set Item Tax Temple in Table taxes.

![image](https://user-images.githubusercontent.com/22279621/103680433-76117680-4f86-11eb-96ef-018343ee7901.png)

For example in Item I can also set Item Tax Temple inside a Table called taxes:
![image](https://user-images.githubusercontent.com/22279621/103680688-d2749600-4f86-11eb-926d-bc62205787f5.png)

2021-01-06 04:03 UTC, deepeshgarg007 requested changes
@wojosc can you please add screenshots of the dashboards. I fell these changes might not work properly because there is no field with name `item_tax_template` in any of these two doctypes

2021-01-06 17:32 UTC, wojosc commented
This would be the dashboard of Item Tax Template with the Item highlighted in green:
![image](https://user-images.githubusercontent.com/22279621/103800905-46797180-504d-11eb-9ba0-6f68dae78e6b.png)

2021-01-11 15:30 UTC, wojosc commented
@deepeshgarg007 yes, you are right. the fields are not found in the doctypes item or item group directly but in the subtable with the according information.

2021-01-12 07:39 UTC, deepeshgarg007 approved these changes

2021-01-12 07:39 UTC, merged