feat: capture Rate of stock UOM in purchase
frappe/erpnext pull request #24315
Opened 2021-01-06 14:45 UTC by anupamvs

**Usecase-** Consider stock UOM of Pen is NOS and Conversion UOM is Box, Currently, the system shows rate as per Conversion UOM.

**Solution-** Added a field on item level to show Rate Field also as per stock UOM.
**Calculation-** rate/conversion_factor

![image](https://user-images.githubusercontent.com/20715976/103780887-9b23e900-505b-11eb-9288-1bee31dd096a.png)

2021-01-11 11:38 UTC, marination commented on erpnext/accounts/doctype/purchase_invoice_item/purchase_invoice_item.json
> +   "label": "Rate of Stock UOM",
```suggestion
   "label": "Rate (Stock UOM)",
```

2021-01-11 12:01 UTC, marination commented on erpnext/accounts/doctype/purchase_invoice_item/purchase_invoice_item.json
>    "is_free_item",
move the checkbox to the bottom of the column. Alignment is messy as it is at the top

2021-01-12 05:55 UTC, deepeshgarg007 requested changes
Server Side code seems to be missing. Add that as well

2021-01-18 18:07 UTC, anupamvs commented
@deepeshgarg007 @marination Done the changes.

2021-01-19 15:17 UTC, marination commented on erpnext/public/js/controllers/buying.js
> +		item.stock_uom_rate = item.rate/item.conversion_factor;
```suggestion
		item.stock_uom_rate = flt(item.rate) / (flt(item.conversion_factor) || 1);
```
Better to be cautious

2021-01-19 15:24 UTC, marination commented on erpnext/controllers/buying_controller.py
> +				d.stock_uom_rate = d.rate / d.conversion_factor
So the field `stock_uom_rate` is takes company currency (INR). `rate` field takes the currency in the transaction , lets say USD.
You are then dividing price in USD by conversion factor and displaying it in INR
![Screenshot 2021-01-19 at 8 49 36 PM](https://user-images.githubusercontent.com/25857446/105054434-00360080-5a98-11eb-8a95-110d3168e467.png)
`Rate (Stock UOM)` should have been **1 USD or 73.46 INR**
1 USD would be better, lets show rate in stock uom in transaction currency

2021-01-19 15:24 UTC, marination commented on erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
> +   "read_only": 1
should this be visible if uom = stock uom. Then it will just show the same value. Hide if both uom fields are the same maybe ? (display depends on)

2021-01-19 15:41 UTC, marination requested changes
Also via **Update Items** in Purchase Order, it does not get updated on changing rate (check for uom change and conversion factor change too). Please check that as well.

2021-01-19 15:41 UTC, marination commented on erpnext/accounts/doctype/purchase_invoice_item/purchase_invoice_item.json
> +   "read_only": 1
Hide if both uom fields are the same (display depends on)

2021-01-19 15:41 UTC, marination commented on erpnext/stock/doctype/purchase_receipt_item/purchase_receipt_item.json
> +   "read_only": 1
Hide if both uom fields are the same (display depends on)

2021-01-19 15:41 UTC, marination commented on erpnext/public/js/controllers/buying.js
> +		refresh_field("stock_uom_rate", item.name, item.parentfield);
Should change on changing UOM too. Does not happen currently as seen in Purchase Order:
1200/15 = 80, not 5.33. It seems to show 80/15, which is not the right rate.
![Screenshot 2021-01-19 at 9 11 12 PM](https://user-images.githubusercontent.com/25857446/105056400-25c40980-5a9a-11eb-9c33-a236c1435b1d.png)

2021-01-19 15:42 UTC, marination commented
@anupamvs Now that we have discussed to uniformly add it on sales side as well, you can try to move the js controller logic in transaction controller itself, instead of buying controller.

2021-02-11 14:49 UTC, nabinhait approved these changes

2021-02-11 14:49 UTC, merged