fix: dynamic links for reports
frappe/erpnext pull request #24462
Opened 2021-01-25 11:56 UTC by pateljannat

**Issue:**

1. The issue was present in three reports.

- Bank Clearance Summary
- Prospect Engaged But Not Converted.
- Payment Period Based on Invoice Date

2. The Dynamic transaction Links were not opening the correct document. 
3. Instead an error used to appear.

![Screenshot 2021-01-25 at 5 05 58 PM](https://user-images.githubusercontent.com/31363128/105700975-a1f19d80-5f2f-11eb-8e3c-96f04ffae2ec.png)

2021-01-27 17:44 UTC, hasnain2808 requested changes

2021-01-27 17:44 UTC, hasnain2808 commented on erpnext/crm/report/prospects_engaged_but_not_converted/prospects_engaged_but_not_converted.py
> +			"width": 100
```	
"fieldtype": "Link",
"options": "Doctype",
```

2021-01-27 17:44 UTC, hasnain2808 commented on erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py
> +			"width": 130
```	
"fieldtype": "Link",
"options": "Doctype",
```

2021-01-27 17:44 UTC, hasnain2808 commented on erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py
> +			"fieldname": "payment_document",
"label": _("Payment Document Type"),
"fieldname": "payment_document_type",

2021-01-27 17:44 UTC, hasnain2808 commented on erpnext/accounts/report/bank_clearance_summary/bank_clearance_summary.py
> +			"options": "payment_document",
"options": "payment_document_type",

2021-01-27 17:44 UTC, hasnain2808 commented on erpnext/crm/report/prospects_engaged_but_not_converted/prospects_engaged_but_not_converted.py
> +			"fieldname": "reference_document",
"label": _("Reference Document Type"),
"fieldname": "reference_document_type",

2021-01-27 17:44 UTC, hasnain2808 commented on erpnext/crm/report/prospects_engaged_but_not_converted/prospects_engaged_but_not_converted.py
> +			"options": "reference_document",
"options": "reference_document_type",

2021-02-10 06:42 UTC, hasnain2808 commented
👍

2021-02-11 14:40 UTC, nabinhait approved these changes

2021-02-11 14:41 UTC, merged