fix: payroll issues
frappe/erpnext pull request #24540
Opened 2021-02-03 09:08 UTC by AfshanKhan

backport of https://github.com/frappe/erpnext/pull/24528 and https://github.com/frappe/erpnext/pull/24529

2021-02-15 08:00 UTC, Anurag810 requested changes

2021-02-15 08:00 UTC, Anurag810 commented on erpnext/payroll/doctype/payroll_entry/payroll_entry.js
> +	fill_details: function (frm) {
you can name it `set_payable_account_and _currency`, `fill_details` is little ammbigous.

2021-02-15 08:00 UTC, Anurag810 commented on erpnext/payroll/doctype/payroll_entry/payroll_entry.js
> +			}
you can move this to function and name it `get_employee_filters` or `get_employee_query_condiitons`

2021-02-15 08:00 UTC, Anurag810 commented on erpnext/payroll/doctype/payroll_entry/payroll_entry.py
>  	return frappe.db.sql_list("""
please update this query and get salary slips based on payroll entry reference in the salary slips document.

2021-03-25 08:28 UTC, Anurag810 reviewed
@AfshanKhan Fix Sider. Waiting for green check...

2021-03-25 09:59 UTC, AfshanKhan commented
> @AfshanKhan Fix Sider. Waiting for green check...

@Anurag810 Slider is fixed.

2021-04-07 09:43 UTC, merged