fix: social media post fixes
frappe/erpnext pull request #24664
Opened 2021-02-18 10:01 UTC by anupamvs

2021-07-30 08:02 UTC, anupamvs commented
@ruchamahabal can you review this?

2021-08-16 12:23 UTC, ruchamahabal requested changes

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.js
> +			frappe.throw(__("Select atleast one Social Media from Share on."));
```suggestion
			frappe.throw(__("Select atleast one Social Media Platform to Share on."));
```

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.py
> +			frappe.throw(_("Select atleast one Social Media from Share on."))
```suggestion
			frappe.throw(_("Select atleast one Social Media Platform to Share on."))
```

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.py
> +			frappe.throw(_("Tweet length Must be less than 280."))
```suggestion
		if self.text and len(self.text) > 280:
			frappe.throw(_("Tweet length must be less than 280."))
```

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.py
>  			self.post_status = "Scheduled"
Use `db_set` when you are setting any value on submit or cancel

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.py
> +		frappe.db.set_value('Social Media Post', self.name, 'post_status', 'Deleted')
```suggestion
		self.db_set('post_status', 'Deleted')
```

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.py
> +			frappe.log_error(message=frappe.get_traceback() , title=title)
```suggestion
			frappe.log_error(message=frappe.get_traceback(), title=title)
```

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/linkedin_settings/linkedin_settings.py
> +			frappe.throw(content["message"], title="LinkedIn Error - Unauthorized")
```suggestion
			frappe.throw(content["message"], title=_("LinkedIn Error - Unauthorized"))
```

2021-08-16 12:23 UTC, ruchamahabal commented on erpnext/crm/doctype/linkedin_settings/linkedin_settings.py
> +			frappe.throw(content["message"], title="LinkedIn Error - Access Denied")
```suggestion
			frappe.msgprint(_("You didn't have permission to access this API"))
			frappe.throw(content["message"], title=_("LinkedIn Error - Access Denied"))
```

2021-08-24 12:22 UTC, ruchamahabal commented on erpnext/crm/doctype/social_media_post/social_media_post.js
> +        if (frm.doc.test) {
```suggestion
        if (frm.doc.text) {
```

2021-08-24 13:09 UTC, ruchamahabal approved these changes

2021-08-24 13:45 UTC, merged