refactor: Setup Taxes and Charges
frappe/erpnext pull request #24805
Opened 2021-03-04 20:24 UTC by barredterra

We try to create appropriate Taxes and Charges Templates (and corresponding VAT accounts) for every country.

This process uses very basic input data like this:

```json
"Finland Tax": {
	"account_name": "VAT",
	"tax_rate": 24.00
}
```

When creating a Company based in Finland, ERPNext will go ahead and

(1) create a liability account named "VAT", 
(2) create a Sales Taxes and Charges Template named "Finland Tax" with the account from (1)
(3) create a Purchase Taxes and Charges Template named "Finland Tax" with the account from (1)
(4) create an Item Tax Template named "Finland Tax" with the account from (1)

The problem with this approach is that it's far too coarse. For example,

- we can also have tax assets, not just liabilities
- we might use different accounts for sales and purchase taxes.
- ...

This PR introduces a more complex data structure that can be used optionally. This way the above cases can be solved. The code is refactored to use the new structure and reuse existing accounts.

2021-03-08 19:16 UTC, barredterra commented
Please merge #24819 first, as it solves some "Duplicate Entry" errors.

2021-04-17 17:26 UTC, barredterra commented
Regarding the failing test: `tax_rule.get_tax_template` returns the correct value, but I guess it gets overwritten by indian localization?

```
FAIL: test_taxes_fetch_via_tax_rule (erpnext.accounts.doctype.tax_rule.test_tax_rule.TestTaxRule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/frappe-bench/apps/erpnext/erpnext/accounts/doctype/tax_rule/test_tax_rule.py", line 165, in test_taxes_fetch_via_tax_rule
    self.assertEqual(quotation.taxes_and_charges, "_Test Sales Taxes and Charges Template - _TC")
AssertionError: 'In State GST - _TC' != '_Test Sales Taxes and Charges Template - _TC'
- In State GST - _TC
+ _Test Sales Taxes and Charges Template - _TC
```

2021-04-17 17:37 UTC, deepeshgarg007 commented
@barredterra I am unable to update the branch from my end, please update your branch once and push

2021-04-17 17:39 UTC, barredterra commented
Done, @deepeshgarg007

2021-04-17 17:41 UTC, deepeshgarg007 commented
> Regarding the failing test: `tax_rule.get_tax_template` returns the correct value, but I guess it gets overwritten by indian localization?
> 
> ```
> FAIL: test_taxes_fetch_via_tax_rule (erpnext.accounts.doctype.tax_rule.test_tax_rule.TestTaxRule)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/runner/frappe-bench/apps/erpnext/erpnext/accounts/doctype/tax_rule/test_tax_rule.py", line 165, in test_taxes_fetch_via_tax_rule
>     self.assertEqual(quotation.taxes_and_charges, "_Test Sales Taxes and Charges Template - _TC")
> AssertionError: 'In State GST - _TC' != '_Test Sales Taxes and Charges Template - _TC'
> - In State GST - _TC
> + _Test Sales Taxes and Charges Template - _TC
> ```

I'll look into this

2021-04-18 11:31 UTC, deepeshgarg007 requested changes

2021-04-18 11:31 UTC, deepeshgarg007 commented on erpnext/setup/setup_wizard/data/country_wise_tax.json
> +						"is_default": 1,
@barredterra I guess "allow edits from maintainers" is not enabled for this PR hence I am not able to make any changes. Remove the `is_default` check from here to fix the test case.

2021-04-18 11:31 UTC, deepeshgarg007 commented on erpnext/setup/setup_wizard/data/country_wise_tax.json
> +						"is_default": 1,
Item Tax Templates don't have any is_default property so this can be removed as well

2021-04-19 03:42 UTC, deepeshgarg007 approved these changes

2021-04-19 03:42 UTC, merged