fix: multiple price rules margin.
frappe/erpnext pull request #24844
Opened 2021-03-10 23:48 UTC by dj12djdjs

Multiple pricing rules are only applied to discount amount or percentage and disregards margin amount and percentage noted in the this issue #20791 
I have some further information at this [discussion.](https://discuss.erpnext.com/t/pricing-rule-w-apply-multiple-pricing-rules-margin/72118)

This PR applies the same logic to margin as already existed for discount rate.

2021-03-16 16:15 UTC, barredterra requested changes

2021-03-16 16:15 UTC, barredterra commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> +		item_details[field] += (pricing_rule.get(field, 0)
How can I understand the `+=`? Margins from multiple price rules get added together? This changes the previous behaviour, right?

2021-03-19 06:49 UTC, dj12djdjs commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> +		item_details[field] += (pricing_rule.get(field, 0)
Yes, this does alter the previous behavior of pricing rules.

So, the new behavior is just copying what is being applied to discount from multiple price rules.
https://github.com/frappe/erpnext/blob/c6a1e3b450e3ce585da374fe41d041bae68cfcc5/erpnext/accounts/doctype/pricing_rule/pricing_rule.py#L356-L368

Previously, when multiple pricing rules are applied only the last pricing rules margin would be applied.
https://github.com/frappe/erpnext/blob/c6a1e3b450e3ce585da374fe41d041bae68cfcc5/erpnext/accounts/doctype/pricing_rule/pricing_rule.py#L333-L339

[Here](https://discuss.erpnext.com/t/pricing-rule-w-apply-multiple-pricing-rules-margin/72118) you can see the behavior previous to this patch in action vs what I was expecting.

2021-03-19 15:31 UTC, barredterra commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> +		item_details[field] += (pricing_rule.get(field, 0)
Okay, makes sense. Thanks for clarifying.

2021-03-23 20:31 UTC, dj12djdjs commented
Are we switching coding style to use spaces instead of tabs? I keep getting Sider problems that indentation is using tabs.

2021-08-24 07:07 UTC, barredterra reviewed
Sorry to request changes again, but maybe consider adding a test to ensure your desired behavior works and will continue to work in the future. As an example, see this test case: https://github.com/frappe/erpnext/blob/87dddbe868e0aa57bee141ae94986b6bbdd7abaf/erpnext/accounts/doctype/pricing_rule/test_pricing_rule.py#L103-L148

2021-08-24 15:45 UTC, nabinhait approved these changes

2021-08-24 15:45 UTC, merged

2021-08-24 15:46 UTC, nabinhait commented
@dj12djdjs Can you please send another PR to the develop branch?

2021-08-24 16:12 UTC, dj12djdjs commented
@nabinhait @barredterra 

Yes I will redo on develop with some tests.