fix: Allow zero valuation in stock reconciliation
frappe/erpnext pull request #24888
Opened 2021-03-15 14:08 UTC by ankush

Stock reconciliation can not be done for customer provided item as they have zero valuation. This change adds a checkbox in item table to allow such items.

Related issue: ISS-20-21-10248

2021-03-16 06:15 UTC, sagarvora commented on erpnext/stock/doctype/stock_reconciliation_item/stock_reconciliation_item.json
> +   "no_copy": 1,
This may not be needed, since the item itself gets copied.
```suggestion
```

2021-03-23 04:38 UTC, marination commented on erpnext/stock/doctype/stock_reconciliation_item/stock_reconciliation_item.json
> +   "print_hide": 1
Let's keep this read only and have its display depend on its own value. It is auto set for customer provided items anyway. And as of now for regular items we don't need this.

2021-03-23 04:41 UTC, marination commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
Can you also additionally add a function to set a customer provided Item's valuation rate to zero?

In other transactions even if the user accidentally adds a rate, the system automatically sets it to zero again.
Lets do that here to make sure it never accidentally has a valuation.

2021-03-23 07:23 UTC, marination requested changes

2021-03-23 07:23 UTC, marination commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +		self.set_zero_value_for_customer_items()
```suggestion
		self.set_zero_value_for_customer_provided_items()
```

2021-03-23 07:23 UTC, marination commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +	def set_zero_value_for_customer_items(self):
```suggestion
	def set_zero_value_for_customer_provided_items(self):
```

2021-03-23 07:23 UTC, marination commented on erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py
> +			msgprint(_("Valuation rate for customer provided items has been set to zero."))
```suggestion
			msgprint(_("Valuation rate for customer provided items has been set to zero."), title=_("Note"), indicator="blue")
```

2021-03-23 07:38 UTC, marination approved these changes

2021-03-23 08:28 UTC, merged