Remove uses of six.PY2 in codebase
frappe/erpnext pull request #25062
Opened 2021-03-30 07:46 UTC by krishnagirishp

This pull request removes the use of six.PY2 from the codebase. This is being done because python2 is no longer supported.
If the project is ok with it, I am interested in opening more pull requests which completely remove python2 support from the project.

2021-03-30 09:03 UTC, Alchez requested changes

2021-03-30 09:03 UTC, Alchez commented on erpnext/erpnext_integrations/doctype/amazon_mws_settings/amazon_mws_api.py
> +		quote = urllib.parse.quote
This could be an import instead

2021-03-30 09:03 UTC, Alchez commented on erpnext/regional/india/e_invoice/utils.py
> +	JSONDecodeError = json.JSONDecodeError
You could just replace this on line 387

2021-03-31 09:13 UTC, krishnagirishp commented
@Alchez can you take another look at this pull request

2021-03-31 09:23 UTC, Alchez approved these changes

2021-03-31 09:24 UTC, Alchez commented
> @Alchez can you take another look at this pull request

Seems fine to me now :+1:

2021-05-23 14:56 UTC, ankush approved these changes
LGTM

2021-05-23 15:43 UTC, merged

2021-05-23 15:47 UTC, ankush commented
> I am interested in opening more pull requests which completely remove python2 support from the project.

Sure. Try to keep changes limited to individual modules in PR. You can tag me for stock/buying/manufacturing changes. 

Send PR to `version-13-hotfix` branch for now. We are merging those changes back to `develop` branch after it's released (for now).