feat!: add pick batch button
frappe/erpnext pull request #25413
Opened 2021-04-20 16:34 UTC by 18alantom

### Old Functionality
**Add Serial No** was used for both Serial and Batch number entries.
`// Add .gif`

### New Functionality
- Depending on whether item has serial number or batch number, **Add Serial No** or **Pick Batch No** is shown.
- If both are present **Add Serial No** is shown.
`// Add .gif`

2021-04-21 08:23 UTC, Alchez commented
@18alantom, shouldn't both the buttons show up if both serial numbers and batches are enabled?

Would it be better to split the Selector dialog, one each for serial and batch? And then let all the controls handle it accordingly?

2021-04-21 09:34 UTC, 18alantom commented
@Alchez yeah ideally both should show, but the code responsible for the dialog box gives **Serial No**  higher precedence so both would lead to the serial number dialog showing. 

So this is just a tentative cosmetic PR to avoid confusion as to which dialog box is gonna pop up; incorporating both into a single dialog requires UX changes and much more refactoring.

2021-04-23 10:23 UTC, rohitwaghchaure commented on erpnext/public/js/utils.js
> +				} else {
Why else?

2021-04-23 10:25 UTC, rohitwaghchaure commented on erpnext/public/js/utils.js
> +					callback, on_close, true);
just put single quotes instead of callback and on_close and remove the row 64 and 65

2021-05-07 08:02 UTC, nabinhait requested changes

2021-05-07 08:02 UTC, nabinhait commented on erpnext/public/js/utils.js
> +function attachSelectorButton(innerText, appendLoction, context, grid_row) {
don't use came casing

2021-05-07 14:59 UTC, nabinhait approved these changes

2021-05-07 15:00 UTC, merged