feat: stock entry by source warehouse
frappe/erpnext pull request #25462
Opened 2021-04-23 16:59 UTC by dj12djdjs

port of: #25430

2021-05-24 11:52 UTC, ankush requested changes

2021-05-24 11:52 UTC, ankush commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +			"item_code": d[0],
Use `as_dict` in `frappe.db.sql` so you can use column name instead of index.

2021-05-24 11:52 UTC, ankush commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		and exists(select name from `tabWarehouse` where lft >= %s and rgt <= %s and name=bin.warehouse)
This is a correlated subquery. Not sure why it's required. Why not just join the tables?

2021-05-24 11:52 UTC, ankush commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		where i.name=bin.item_code and i.disabled=0 and i.is_stock_item = 1
```suggestion
		on i.name=bin.item_code where i.disabled=0 and i.is_stock_item = 1
```

Prefer explicit joins over implicit joins.

2021-05-24 11:52 UTC, ankush commented on erpnext/stock/doctype/stock_entry/stock_entry.js
> +				if(!frm.doc.from_warehouse) frappe.throw(__("Please select source warehouse!"));
For consistency, it would be better to open a modal dialogue that asks for selecting a warehouse? 🤔 

Take a look at how it's done in Stock Reconciliation.

2021-05-28 02:49 UTC, dj12djdjs commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		and exists(select name from `tabWarehouse` where lft >= %s and rgt <= %s and name=bin.warehouse)
I was lazy. Just copied from here: https://github.com/frappe/erpnext/blob/59769c7a8685fb22ba18cccd9283e2e912784b59/erpnext/stock/doctype/stock_reconciliation/stock_reconciliation.py#L477

I'll re-write the query joining the tables.

2021-07-23 14:22 UTC, closed without merging

2023-03-25 09:36 UTC, muchai commented
Let me see about including inventory dimensions. Our use case is stock is stored in numbered crates. Which are moved too. We manage this has inventory dimensions, and as well as serialized inventory.