fix: fixed stock levels dashboard not displaying after any action
frappe/erpnext pull request #25506
Opened 2021-04-28 14:11 UTC by noahjacob

**Issue :**

- Opening Item the first time.
![image](https://user-images.githubusercontent.com/43572428/116417706-28808880-a859-11eb-8276-d3fb0ffdc360.png)
-Opening it the second time without refreshing.
![image](https://user-images.githubusercontent.com/43572428/116418308-a5abfd80-a859-11eb-99b4-84c423e28fdf.png)

2021-04-28 14:36 UTC, ankush commented
@noahjacob semgrep failures are unrelated to your change but can you add a separate commit fixing those too?

2021-04-28 14:46 UTC, ankush commented
A longer explanation of this bug:

item-dashboard is loaded using async call in `item.js`:
https://github.com/frappe/erpnext/blob/7f932cfb30f32224cbf500efa86ea7d87462b543/erpnext/stock/doctype/item/item.js#L382

This makes a network request the first time it is called, and then it's stored in localStorage.

The next request uses a cached version. 

Also in `item.js` following line is called after updating item attribute details, this causes race condition:

https://github.com/frappe/erpnext/blob/7f932cfb30f32224cbf500efa86ea7d87462b543/erpnext/stock/doctype/item/item.js#L771

When this line is executed in...

1. First request - item_dashboard.js is still loading so nothing is done there.
2. Subsequent requests - item_dashboard.js is already loaded and it's making a network request to get item data.  During this time the section is empty hence `refresh_sections()` removes it.

Solution: By reordering execution, this race condition can be avoided.

2021-04-29 04:57 UTC, surajshetty3416 requested changes

2021-04-29 04:57 UTC, surajshetty3416 commented on erpnext/stock/doctype/item/item.js
> +								}
```suggestion
								if (no_of_combinations === 1) {
									msg = __("Make {0} Variant", [no_of_combinations]);
								} else {
									msg = __("Make {0} Variants", [no_of_combinations]);
								}
```

2021-04-29 05:32 UTC, ankush approved these changes

2021-04-29 05:33 UTC, merged

2021-06-30 09:07 UTC, sagarvora commented
@ankush @noahjacob, has this been backported to `v13`?

2021-06-30 09:20 UTC, ankush commented
@sagarvora it was backported but it broke after https://github.com/frappe/frappe/pull/13355

check comments.