ci: Enable Parallel tests
frappe/erpnext pull request #25635
Opened 2021-05-08 08:30 UTC by surajshetty3416

[WIP]

### Run unit tests parallelly
across multiple instances in batches to reduce wait time for green tick. 
(After this the wait time will be down to around **~22 mins** from **~40 mins**)

- [ ] Fix failing tests
- [x] Enable coverage for parallel test

---
- Cleaner test reports
		**Before:**
		<img width="1011" alt="Screenshot 2021-05-08 at 1 46 38 PM" src="https://user-images.githubusercontent.com/13928957/117532480-5d34d280-b005-11eb-88ff-1ba545f29d62.png">
		**Now:**
		<img width="721" alt="Screenshot 2021-05-08 at 1 47 35 PM" src="https://user-images.githubusercontent.com/13928957/117532484-658d0d80-b005-11eb-9131-e08c2fd1da64.png">

Dependent on https://github.com/frappe/frappe/pull/13165

2021-05-09 03:54 UTC, surajshetty3416 commented
Test time is not balanced across build instances.

<img width="839" alt="Screenshot 2021-05-08 at 8 47 38 PM" src="https://user-images.githubusercontent.com/13928957/117560085-4c896880-b0a8-11eb-9df6-2e96fa8c9d48.png">

2021-05-09 08:04 UTC, Alchez commented
@surajshetty3416, can we not salvage anything from this? The cleaner reports are a good change.

2021-05-09 17:22 UTC, surajshetty3416 commented
@Alchez will re-open this with a better solution... Stay Tuned!

2021-05-10 15:29 UTC, Alchez requested changes

2021-05-10 15:29 UTC, Alchez commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> +		if self.condition and ("=" in self.condition) and re.match(r'[\w\.:_]+\s*={1}\s*[\w\.@\'"]+', self.condition):
I think you should keep the multi-string, since the regexp has both the quotes

2021-05-10 15:32 UTC, surajshetty3416 commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> +		if self.condition and ("=" in self.condition) and re.match(r'[\w\.:_]+\s*={1}\s*[\w\.@\'"]+', self.condition):
@Alchez single quote inside regex has been escaped so it should not be an issue.

2021-05-10 15:38 UTC, Alchez commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> +		if self.condition and ("=" in self.condition) and re.match(r'[\w\.:_]+\s*={1}\s*[\w\.@\'"]+', self.condition):
Ah, no worries then

2021-05-13 10:11 UTC, merged