fix: Update leave allocation after submit
frappe/erpnext pull request #25975
Opened 2021-06-07 15:32 UTC by pateljannat

1. New Leave can now be updated in Leave Allocation after submit.

2021-06-08 07:43 UTC, gavindsouza requested changes

2021-06-08 07:43 UTC, gavindsouza commented on erpnext/hr/doctype/leave_allocation/leave_allocation.py
> +								fields=["leaves"])
1. You can use 'pluck' instead. 
2. Running `validate_against_leave_applications` before this could mean one less db call

2021-06-08 07:43 UTC, gavindsouza commented on erpnext/hr/doctype/leave_allocation/test_leave_allocation.py
> +		frappe.db.sql("delete from `tabLeave Ledger Entry`")
There's `frappe.db.delete`

2021-06-08 07:43 UTC, gavindsouza commented on erpnext/hr/doctype/leave_allocation/leave_allocation.py
> +			)
Inconsistent pattern of using literals and constructors. Maybe just stick to literals since they save you the effort of looking up if `dict` exists in locals() etc

2021-06-08 07:43 UTC, gavindsouza commented on erpnext/hr/doctype/leave_allocation/leave_allocation.py
> +			ledger_entries = frappe.get_all("Leave Ledger Entry",
This whole block should be a separate method on its own. Something like `update_leave_ledger` perhaps?

2021-06-23 12:28 UTC, nabinhait approved these changes

2021-06-24 07:43 UTC, merged