Validate Product Bundle for existing transactions before deletion
frappe/erpnext pull request #25977
Opened 2021-06-08 07:02 UTC by AfshanKhan

### Problem
The user can delete **Product Bundles** even if a transaction exists against them.

### Steps to replicate
1. Create a **Product Bundle**.
2. Create a **Sales Invoice** with the **Item** as the **Product Bundle**.
3. Now delete the **Product Bundle**.

### Enhancement
Now there is a validation to check if any transaction exists for the product bundle and the following message is displayed to the user when they try deleting any **Product Bundle**.
![image](https://user-images.githubusercontent.com/33727827/121138153-0bc27200-c855-11eb-8bf9-f3005a81121e.png)

2021-06-08 11:47 UTC, nextchamp-saqib requested changes

2021-06-08 11:47 UTC, nextchamp-saqib commented on erpnext/selling/doctype/product_bundle/product_bundle.py
> +		invoices = frappe.db.get_all("Sales Invoice Item", {"item_code": self.new_item_code, "docstatus": ["!=", 2]}, ["parent"])
The product bundle can be linked with any transactions, stock entry, purchase invoice. 

Check the `check_if_linked_document_exists` method from `item.py`

2021-06-08 11:47 UTC, nextchamp-saqib commented on erpnext/selling/doctype/product_bundle/product_bundle.py
> +			frappe.throw("This Product Bundle is linked with Sales Invoice: {0}. You will have to cancel these invoices in order to cancel this Product Bundle".format(", ".join(invoice_links)))
```suggestion
			frappe.throw("This Product Bundle is linked with Sales Invoice: {0}. You will have to cancel these invoices in order to delete this Product Bundle".format(", ".join(invoice_links)), title=_("Not Allowed"))
```

2021-06-16 05:21 UTC, deepeshgarg007 reviewed
We should also provide a disable checkbox similar to item master to disable any specific product bundle

2021-06-16 09:03 UTC, nextchamp-saqib requested changes

2021-06-16 09:03 UTC, nextchamp-saqib commented on erpnext/selling/doctype/product_bundle/product_bundle.py
> +			invoices = frappe.db.get_all(item_doctype, {"item_code": self.new_item_code, "docstatus": ["!=", 2]}, ["parent"])
```suggestion
			invoices = frappe.db.get_all(item_doctype, {"item_code": self.new_item_code, "docstatus": 1}, ["parent"])
```

2021-07-01 14:04 UTC, merged