fix: timesheet amount issue
frappe/erpnext pull request #25993
Opened 2021-06-09 06:48 UTC by anupamvs

**Issues**-
- Timesheet amount is not changed when a user changes currency in the Sales Invoice.
- Project reference(Project Name) is missing from the Sales Invoice Timesheet child table.
- The exchange rate is set to 0 by default in Timesheet.

2021-06-23 08:46 UTC, ruchamahabal requested changes, later dismissed

2021-06-23 08:46 UTC, ruchamahabal commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +			'project_name': row.project_name.name
```suggestion
			'project_name': row.project_name
```

2021-06-23 08:46 UTC, ruchamahabal commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> +		calculate_total_billing_amount(cur_frm)
On changing currency, the amount item table and timesheets are different. Am I missing something?


https://user-images.githubusercontent.com/24353136/123066130-6818ba80-d42d-11eb-8584-4f92d65f241a.mp4

2021-08-10 14:35 UTC, pateljannat approved these changes

2021-08-10 15:02 UTC, merged