fix(Issue): Remove response_by and resolution_by if sla is removed
frappe/erpnext pull request #25997
Opened 2021-06-09 22:02 UTC by GangaManoj

**_Issue:_**
The _Response By_ and _Resolution By_ fields continue to be visible even after SLA is removed.

_**Fix:**_
Make the display for the two fields depend on the _Service Level Agreement_ field.

<details>
<summary> Images </summary>

Before Removing SLA:

![Screenshot 2021-06-10 at 3 29 55 AM](https://user-images.githubusercontent.com/25903035/121435226-24896f80-c99c-11eb-9631-8188b3f31fda.png)

After Removing SLA:

![Screenshot 2021-06-10 at 3 31 12 AM](https://user-images.githubusercontent.com/25903035/121435331-51d61d80-c99c-11eb-8d92-3e956bd5cb25.png)

</details>

2021-06-15 09:13 UTC, harshit-30 commented
@GangaManoj is it hiding or emptying the values set?

2021-06-15 23:03 UTC, GangaManoj commented
@harshit-30 I've reset the values as well now, thanks for pointing it out.

2021-06-16 06:34 UTC, nextchamp-saqib requested changes

2021-06-16 06:34 UTC, nextchamp-saqib commented on erpnext/support/doctype/issue/issue.py
> +			self.reset_associated_fields()
```suggestion
			self.reset_sla_fields()
```

2021-06-16 06:34 UTC, nextchamp-saqib commented on erpnext/support/doctype/issue/issue.py
> +	def reset_associated_fields(self):
```suggestion
	def reset_sla_fields(self):
```

2021-06-18 06:12 UTC, nextchamp-saqib commented
@GangaManoj  Don't forget to raise one for `develop` too

2021-06-18 06:12 UTC, merged

2021-07-01 15:48 UTC, ankush commented
@GangaManoj @nextchamp-saqib ref: https://github.com/frappe/erpnext/pull/26291