feat: Organizational Chart
frappe/erpnext pull request #26261
Opened 2021-06-29 21:42 UTC by ruchamahabal

## Organizational Charts

An organizational chart shows the organizational structure by depicting connections between different employees with their designation, image, and name. In large organizations where it's difficult to remember names, people can interact with the org chart and know the hierarchy through faces and other info.

## Desktop View
https://user-images.githubusercontent.com/24353136/123866697-0be0f980-d94b-11eb-9c0d-4e95b7773d8c.mp4

## Mobile View

![image](https://user-images.githubusercontent.com/24353136/123869511-b870aa80-d94e-11eb-8615-8509d2bbe455.png)

![Untitled 2](https://user-images.githubusercontent.com/24353136/123870322-cbd04580-d94f-11eb-9e01-8f9015871d6a.png)

After clicking on sibling group:

![node-group](https://user-images.githubusercontent.com/24353136/123870674-4dc06e80-d950-11eb-8dc0-e9ad23bbee14.png)

ToDo

- [ ] Optimise rendering
- [ ] Handle multiple root nodes / orphan nodes
- [ ] Documentation

2021-07-04 10:26 UTC, olamide2 commented
This is Great

Will we be able to change relationship by using  drag and drop from the chart ?

2021-07-04 13:58 UTC, ruchamahabal commented
> This is Great
> 
> Will we be able to change relationship by using drag and drop from the chart ?

Thanks. No this is just for visualising the hierarchy based on the "reports to" field and not building the employee tree.

2021-07-24 21:17 UTC, aschl commented
Closes https://github.com/frappe/erpnext/issues/4087

2021-08-10 06:08 UTC, nabinhait requested changes

2021-08-10 06:08 UTC, nabinhait commented on .github/helper/install.sh
> +bench start &> bench_run_logs.txt &
Should it be `bench start > bench_run_logs.txt &`

2021-08-10 06:36 UTC, ankush commented on .github/helper/install.sh
> +bench start &> bench_run_logs.txt &
I added this to log the bench console which can be shown in case of some failure. 

`&>` is for capturing both stdout and stderr.

2021-08-10 11:42 UTC, nabinhait approved these changes

2021-08-10 11:42 UTC, merged