fix: moving campaign from selling to CRM
frappe/erpnext pull request #26272
Opened 2021-06-30 12:50 UTC by anupamvs

Changing Campaign module Selling -> CRM

2021-07-08 07:35 UTC, ruchamahabal commented
For the reviewer:

1. Check related imports
2. Check migration and installation on a new site
3. Check if a patch is required
4. Check if Desk Page updated

2021-07-12 09:16 UTC, pateljannat requested changes

2021-07-12 09:16 UTC, pateljannat commented on erpnext/crm/doctype/campaign/campaign.py
> -from frappe.model.naming import set_name_by_naming_series
Import for set_name_by_naming_series has been removed but its still being called from autoname function

2021-07-12 09:16 UTC, pateljannat commented on erpnext/crm/doctype/campaign/campaign.js
> +			frm.toggle_display("naming_series", frappe.boot.sysdefaults.campaign_naming_by=="Naming Series");
The field campaign_naming_by is still in the Selling settings. Should we create a CRM setting and move it there?

2021-07-26 17:14 UTC, anupamvs commented on erpnext/crm/doctype/campaign/campaign.js
> +			frm.toggle_display("naming_series", frappe.boot.sysdefaults.campaign_naming_by=="Naming Series");
Yeah! CRM setting is not introduced yet. In my roadmap maybe in next month.

2021-07-27 12:03 UTC, pateljannat approved these changes

2021-07-27 12:04 UTC, merged