feat: Production Plan: make the item_code filter into a 'like' search rather than a link field
frappe/erpnext pull request #26569
Opened 2021-07-21 00:42 UTC by casesolved-co-uk

Allows you to add multiple items with similar item_codes to the same production plan rather than the strict single item according to a link field

2021-07-21 01:00 UTC, casesolved-co-uk commented
Won't-fix old format SQL

2021-07-21 14:22 UTC, ankush commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +		pending_mr = frappe.db.sql("""   # nosemgrep
```suggestion
		pending_mr = frappe.db.sql(""" 
```

This is becoming part of the query string. Remove it, I will be fixing that sql rule.

2021-07-22 11:03 UTC, ankush commented
This looks neat 👍  Especially because planning is usually not done on item level it makes sense to use "LIKE" filtering... will do some manual testing before merging.

2021-07-22 13:54 UTC, casesolved-co-uk commented
@ankush Thanks. It's not the best solution. I would have liked to change the buttons to be additive instead of clear and fill from scratch, but the would need to implement checks to see if the lines were already added. This quick fix is the next best thing.

2021-07-30 10:00 UTC, ankush requested changes

2021-07-30 10:00 UTC, ankush commented on erpnext/manufacturing/doctype/production_plan/production_plan.json
> +   "description": "Searches for item codes like this string",
Replace "string" with text, string is programmer-talk. Or remove the full description. We usually don't like writing descriptions, it should be obvious wherever possible.

2021-07-30 10:00 UTC, ankush commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				"item": '%' + self.item_code + '%',
when `self.item_code` is not entered by the user, this will give a string concatenation error. (Same with SO query down below)

2021-07-30 10:01 UTC, ankush commented
btw we were thinking of removing all these fitler fields and adding modal dialog (already present in many other documents) Might take some time for this though. 

![Screenshot 2021-07-30 at 3 30 20 PM](https://user-images.githubusercontent.com/9079960/127637067-c73d8c55-eb3b-46a1-8800-1ccd3a0fecbb.png)

2021-07-30 23:08 UTC, casesolved-co-uk commented on erpnext/manufacturing/doctype/production_plan/production_plan.json
> +   "description": "Searches for item codes like this string",
I'll change the word but I think this is the wrong policy on descriptions.

This is an extremely powerful and easy self-documentation opportunity. ERP systems are very much **not** straightforward to pick up, each field is rarely obvious and often has knock-on implications in many related documents and fields. This one field for example doesn't just get used to filter Sales Orders, but also the Items that are added to the PP. This is not obvious.

My opinion (who has spent several years with ERP system users) is that **every** field or section should have a description, unless it truly is obvious like `Date of Birth` kind of stuff. A user shouldn't need to refer to the documentation to make sense of the form, which incidentally rarely fully describes the features anyway.

Another very much not obvious field is `Include Exploded Items`. I had to read the code before I understood what that did. Who wants a production plan that doesn't `Include Exploded Items` ? As it turns out, it's just a broken, badly named feature that I had to fix.

2021-07-30 23:26 UTC, casesolved-co-uk commented
> btw we were thinking of removing all these filter fields and adding modal dialog (already present in many other documents) Might take some time for this though.

Makes sense if it adds functionality, like a full set of custom field filters. But in general I don't agree many dialogs are the answer, they break the user experience, like the Warehouse dialog on `Get Raw Materials For Production`. This should be on-page.

Dialogs are also a bad idea if they force the user to enter the same thing twice, like filtering for Sales Orders containing an Item, then filtering again for Items.

Another example of pointless feature creep is the `awesomplete` js that moves the page around every time you complete a field. This is extremely annoying. Users like things to be where they left them, not constantly searching for them because they moved or the section was auto-collapsed. Imagine someone moving all your stuff around your room every day without asking and with no way to stop it. You would quickly move.

In general, your time would be better spent making existing functionality 100% bug-free and usable than continuous feature-creep and refactoring. ERPNext is losing customers daily.

2021-08-21 11:20 UTC, casesolved-co-uk commented
[https://erpnext.org/contribute](https://erpnext.org/contribute) 😆

2021-08-26 16:28 UTC, ankush commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				"item": '%' + self.item_code + '%',
I don't think the change you did in last commit will solve this. 

F-strings will convert `None` to string literal `'None'` and then search for item code like `%None%`

2021-08-26 16:34 UTC, nameduser0 commented on erpnext/manufacturing/doctype/production_plan/production_plan.py
> +				"item": '%' + self.item_code + '%',
In all instances the additional filter conditions are only added if item_code is truthy

2021-08-27 12:57 UTC, ankush commented
LGTM. Just resolve conflicts or allow maintainer edits.

2021-08-27 14:42 UTC, nameduser0 commented
> LGTM. Just resolve conflicts or allow maintainer edits.

@ankush See comments on #25845. conflicts are unresolvable due to that breaking change.

2021-08-30 13:43 UTC, closed without merging

2021-08-30 14:50 UTC, casesolved-co-uk commented
@ankush Your last comment on the other thread is also incorrect. A BOM captures both the raw materials (subitems) and process (operations). So as I stated, if items have the same BOM, they are by definition the same item. And if this is how the system is being used, it is simply abuse.

2021-08-30 14:53 UTC, ankush commented
Not everyone captures all the processes in BOM. We are software developers, we don't enforce good systems to end-users.  🤷 

If you want this strict check the add a setting in manufacturing settings to disallow selling/fetching BOM template... even make it a default behaviour.