fix: added progress bar in repost item valuation
frappe/erpnext pull request #26680
Opened 2021-07-27 16:54 UTC by rohitwaghchaure

backport https://github.com/frappe/erpnext/pull/26630

2021-07-30 14:12 UTC, ankush requested changes

2021-07-30 14:12 UTC, ankush commented on erpnext/stock/stock_ledger.py
> +def repost_future_sle(args=None, doc=None, voucher_type=None, voucher_no=None, allow_negative_stock=None, via_landed_cost_voucher=False):
```suggestion
def repost_future_sle(args=None, voucher_type=None, voucher_no=None, allow_negative_stock=None, via_landed_cost_voucher=False, doc=None):
```

New kwarg should be last. Possibility of breaking someone's function call that's using positional args.

2021-07-30 14:12 UTC, ankush commented on erpnext/stock/stock_ledger.py
> +			"posting_time": args[i].get('posting_time'),
Any particular need for this change? 
IF any of these are None, `.get` will propagate `None` which would eventually fail, instead of failing early.

2021-07-30 14:12 UTC, ankush commented on erpnext/stock/stock_ledger.py
> -def get_args_for_voucher(voucher_type, voucher_no):
There might be someone using this as its public functionality. 

how about adding it back like this for backward compatibility :

```python
def get_args_for_voucher(voucher_type, voucher_no):
	return get_items_to_be_repost(voucher_type, voucher_no)
```

2021-07-30 18:35 UTC, rohitwaghchaure commented on erpnext/stock/stock_ledger.py
> +def repost_future_sle(args=None, doc=None, voucher_type=None, voucher_no=None, allow_negative_stock=None, via_landed_cost_voucher=False):
Fixed

2021-07-30 18:35 UTC, rohitwaghchaure commented on erpnext/stock/stock_ledger.py
> +			"posting_time": args[i].get('posting_time'),
Added validation and used [key]

2021-07-30 18:36 UTC, rohitwaghchaure commented on erpnext/stock/stock_ledger.py
> -def get_args_for_voucher(voucher_type, voucher_no):
get_args_for_voucher is not used anywhere in the code

2021-08-02 05:31 UTC, ankush approved these changes

2021-08-02 05:31 UTC, merged