patch: Delete all orphaned tables
frappe/erpnext pull request #26743
Opened 2021-07-30 17:22 UTC by GangaManoj

Patch for https://github.com/frappe/erpnext/pull/26239.

2021-08-02 08:01 UTC, ankush requested changes
Looks correct. Some minor changes are required.

2021-08-02 08:01 UTC, ankush commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    return False
```suggestion
    return getdate(parent_creation_time) > getdate(child_creation_time)
```

2021-08-02 08:01 UTC, ankush commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    return True
```suggestion
    return not bool(frappe.get_value('DocType', doctype, 'istable'))
```

2021-08-02 08:01 UTC, ankush commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +            if (doctype.doctype_name not in affected_doctypes) and is_not_child_table(doctype.doctype_name):
Instead of doing this just remove duplicates at the end or use `set`.  `not in <list>` gets expensive as list grows larger.

2021-08-02 08:01 UTC, ankush commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    child_creation_time = frappe.db.get_value(doctype, doc, 'creation')
These could probably be queried along with other data from the loop where this function gets called. There could be 1000s of orphaned docs, so these additional queries in loop could be expensive.

2021-08-02 08:01 UTC, ankush commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    if has_deleted_company_transactions():
You need to do `reload_doc` on TDR, so v12->v13 updates don't fail. Check patch test results.

2021-08-02 08:45 UTC, GangaManoj commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    return False
fix: Make code more concise

2021-08-02 16:30 UTC, GangaManoj commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +            if (doctype.doctype_name not in affected_doctypes) and is_not_child_table(doctype.doctype_name):
Done.

2021-08-02 16:40 UTC, GangaManoj commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    if has_deleted_company_transactions():
Done.

2021-08-02 17:08 UTC, GangaManoj commented on erpnext/patches/v13_0/delete_orphaned_tables.py
> +    child_creation_time = frappe.db.get_value(doctype, doc, 'creation')
I did the second, but I don't think `parent_creation_time` can be fetched anywhere else.

2021-08-09 11:45 UTC, nextchamp-saqib approved these changes

2021-08-09 11:46 UTC, merged