Onboarding cleanup
frappe/erpnext pull request #27112
Opened 2021-08-24 13:20 UTC by kamaljohnson

feat(onboarding-cleanup): Add onboarding steps for **Accounting**, **Assets** and **Selling** modules

 ### Accounting
 - **Review Company** _( show 'Company List' )_
 
![image](https://user-images.githubusercontent.com/22856401/130619325-040c40e4-9349-4075-abe3-07694fd78dc5.png)

 - **Review Chart of Accounts** _( show 'Chart of Accounts' )_

![image](https://user-images.githubusercontent.com/22856401/130619464-ed7e0bdc-973a-4fa4-9f26-e60480f09cc6.png)

 - **Setting up Taxes** _( form tour for 'Sales Taxes and Charges Template' )_

![image](https://user-images.githubusercontent.com/22856401/130619599-0ae961d7-3787-4a12-8d27-a1fe80999a2e.png) 

 - **Account Settings** _( form tour for 'Account Settings' )_

![image](https://user-images.githubusercontent.com/22856401/130619626-0af2a46d-bf02-4beb-bf43-3d02797204b5.png)

 - **Cost Centers for Budgeting and Analysis** _( show 'Cost Center Tree' )_

![image](https://user-images.githubusercontent.com/22856401/130619653-86401eea-dc4d-4374-aec3-11e889334443.png)

 - **Create your first Purchase Invoice** _( form tour for 'Purchase Invoice' )_

![image](https://user-images.githubusercontent.com/22856401/130619676-1fb31757-d82b-4cc0-a603-ec68591de9e1.png)

 - **Updating Opening Balances** _(  video tutorial )_ 

![image](https://user-images.githubusercontent.com/22856401/130619702-6dbb9121-f18f-495e-b1d5-02b6855d264d.png)

 - **Financial Statements** _( show general report )_

![image](https://user-images.githubusercontent.com/22856401/130619734-b450b31e-b6d3-4e1c-850e-c68574b445c3.png)
   
 ### Assets
 - **Review Fixed Asset Accounts** _( show 'Chart of Accounts' )_

![image](https://user-images.githubusercontent.com/22856401/130619877-b441d695-4fc2-456d-885f-2fbc049a2eff.png) 

 - **Define Asset Category** _( form tour for 'Asset Category' )_
 
![image](https://user-images.githubusercontent.com/22856401/130619927-1c2cec2f-750c-4fac-b2ac-0e25c9636709.png)

 - **Create Asset Item** _(  form tour for 'Item' )_

![image](https://user-images.githubusercontent.com/22856401/130619978-88a80800-c250-4a34-913d-858d30590937.png)

 - **Purchase an Asset** _( form tour for 'Purchase Receipt' )_

![image](https://user-images.githubusercontent.com/22856401/130620005-59baa44e-101d-4638-ac19-0d95cd2b4d98.png)

 - **Add an Existing Asset** _( form tour for 'Asset' )_

![image](https://user-images.githubusercontent.com/22856401/130620024-6179c2e8-0cd9-45bf-a207-4ccd65743e83.png)

### Selling
 - **Selling Settings** _( form tour for 'Selling Settings' )_
 
![image](https://user-images.githubusercontent.com/22856401/130620091-565eafe2-891b-483e-813d-73144eb49ea1.png)

- **Sales Order** _( form tour for 'Sales Order' )_

![image](https://user-images.githubusercontent.com/22856401/130620125-0f9a32b2-0c79-4b47-b1f7-044feba7d44e.png)

2021-08-25 16:20 UTC, nabinhait requested changes

2021-08-25 16:20 UTC, nabinhait commented on erpnext/accounts/form_tour/purchase_invoice/purchase_invoice.json
> +   "title": "List Of Items"
```suggestion
   "title": "List of Items"
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/accounts/form_tour/purchase_invoice/purchase_invoice.json
> +   "description": "Add Items in the table",
```suggestion
   "description": "Add items in the table",
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/accounts/form_tour/sales_taxes_and_charges_template/sales_taxes_and_charges_template.json
> +   "title": "Is this Default?"
```suggestion
   "title": "Is this Default Tax Template?"
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/accounts/onboarding_step/financial_statements/financial_statements.json
> + "description": "# Financial Statements\n\nIn ERPNext, you can get crucial financial reports like [Balance Sheet] and {Profit and Loss] statements with a click of a button. You can run in the report
```suggestion
 "description": "# Financial Statements\n\nIn ERPNext, you can get crucial financial reports like [Balance Sheet] and [Profit and Loss] statements with a click of a button. You can run in the report for a different period and plot analytics charts premised on statement data. For more reports, check sections like Financial Statements, General Ledger, and Profitability reports.\n\n<b>[Check Accounting reports](https://docs.erpnext.com/docs/v13/user/manual/en/accounts/accounting-reports)</b>",
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/assets/form_tour/asset_category/asset_category.json
> +   "description": "Name Asset category. You can create categories based on Asset Types. like Furniture, Property, Electronics etc.",
```suggestion
   "description": "Name Asset category. You can create categories based on Asset Types like Furniture, Property, Electronics etc.",
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/assets/onboarding_step/existing_asset/existing_asset.json
> + "action_label": "Add an existing asset item",
```suggestion
 "action_label": "Add an existing Asset",
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/assets/onboarding_step/existing_asset/existing_asset.json
> + "description": "# Add an Existing Asset\n\nIf you are just starting with ERPNext, you will need to enter Assets you already possess. You can add them as opening fixed assets in ERPNext. Please note
```suggestion
 "description": "# Add an Existing Asset\n\nIf you are just starting with ERPNext, you will need to enter Assets you already possess. You can add them as existing fixed assets in ERPNext. Please note that you will have to make a Journal Entry separately updating the opening balance in the fixed asset account.",
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/selling/doctype/sales_order/sales_order.js
> +frappe.tour['Sales Order'] = [
Remove this

2021-08-25 16:20 UTC, nabinhait commented on erpnext/stock/form_tour/item/item.json
> +   "description": "Check Auto Create Asset on Purchase",
```suggestion
   "description": "On checking it, the system will create an Asset automatically on purchase",
```

2021-08-25 16:20 UTC, nabinhait commented on erpnext/stock/form_tour/item/item.json
> +   "description": "Select a naming series",
```suggestion
   "description": "Select a naming series which will be used to create an Asset automatically",
```

2021-08-26 14:30 UTC, nabinhait commented
@kamaljohnson Errors while installing fixtures

2021-08-26 14:48 UTC, kamaljohnson commented
> @kamaljohnson Errors while installing fixtures

@nabinhait the local site is running fine for me, Can you please show the error.

2021-08-27 10:17 UTC, merged

2021-11-22 08:59 UTC, nextchamp-saqib commented
@mergifyio backport version-13-hotfix

2021-11-22 09:08 UTC, nextchamp-saqib commented
@mergifyio backport version-13-pre-release