feat: Taxjar Integration update
frappe/erpnext pull request #27143
Opened 2021-08-25 13:30 UTC by nemesis189

TaxJar is a platform that provides automated sales tax compliance, the api integration helps in auto-calculating sales tax in sales invoices. Primarily this integration is being developed to accommodate and ease taxation for the United States region.
ERPNext had the basic api integration setup, this update is to polish it further and make it fit for certification.
The tax rates are based on the states and products(product tax category).

**Updates:**
1. Tax calculation for line items(every row of the items table)
2. Address validation and retrieving state codes (api requires 2 letter state codes ex New York - NY)
3. **Product Tax Category Doctype** for different tax categories 
4. **Product tax category** field in Item master and Sales Item table, **Tax Collectable, Taxable Amount** fields in Sales Item Table that stores the said values from api response
5. Correct posting of Return invoices
6. API calls having the `x-api-version` and `plugin` parameters
7. Corrected shipping address assignment order

- TaxJar Settings page in ERPNext
  <img src='https://user-images.githubusercontent.com/36098155/130796726-60bacc7d-a4ca-47c1-9909-43662428f6d2.png' width='500'>

- Product Tax Category field in Item Master
  <img width="500" alt="Screenshot 2021-08-25 at 6 35 23 PM" src="https://user-images.githubusercontent.com/36098155/130796942-812596f2-9ddf-4980-b36d-b3ade2a499b3.png">

- Sales Taxes and charges table auto populating with the rates
   <img width="500" alt="Screenshot 2021-08-25 at 6 36 13 PM" src="https://user-images.githubusercontent.com/36098155/130797314-2aa9bee8-cf23-4254-8ba2-c6699e54f604.png">

- Taxable Amount and Tax Collectible retrieved form the response and stored 
   <img width='500' src='https://user-images.githubusercontent.com/36098155/130797508-0c154855-f758-460a-9295-bba38ac2602c.png'>

- Transactions and breakdown on the TaxJar account transactions dashboard
   <img width="500" alt="Screenshot 2021-08-25 at 6 40 40 PM" src="https://user-images.githubusercontent.com/36098155/130798050-274f61cc-3c06-4cad-ab3e-eb629fecfee3.png">

2021-08-30 16:32 UTC, deepeshgarg007 requested changes

2021-08-30 16:32 UTC, deepeshgarg007 commented on erpnext/erpnext_integrations/taxjar_integration.py
> +		if tax_dict['amount']<0:
```suggestion
		if doc.is_return:
```

There could be cases where a regular Sales Invoice might have a negative amount tax row, better to check if Invoice is a credit note

2021-08-30 16:32 UTC, deepeshgarg007 commented on erpnext/regional/united_states/setup.py
> +	add_permission(doctype, 'All', 0)
Remove permission for 'All' Role

2021-08-31 13:03 UTC, merged

2021-11-23 09:55 UTC, ashish-greycube commented
on migration from 12 to 13..it gives following  message

```
Executing execute:frappe.reload_doc("erpnext_integrations", "doctype", "Product Tax Category") in site1.local
/home/frappe/frappe-bench/apps/erpnext/erpnext/erpnext_integrations/doctype/product_tax_category/product_tax_category.json missing
```