fix: patches were breaking while migrating
frappe/erpnext pull request #27195
Opened 2021-08-27 07:17 UTC by shadrak98

Fixes for the following errors occurred while migrating:

- frappe.exceptions.ValidationError: Fieldtype cannot be changed from Data to Currency
- frappe.exceptions.LinkValidationError: Could not find Report: E-Invoice Summary
- pymysql.err.OperationalError: (1054, "Unknown column 'first_response_time' in 'field list'")
- TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
- frappe.exceptions.LinkExistsError: Cannot delete or cancel because Report "A" is linked with Desktop Icon "B" 
- frappe.database.database.InvalidColumnName: Invalid field name

2021-08-27 07:29 UTC, saurabh6790 requested changes

2021-08-27 07:29 UTC, saurabh6790 commented on erpnext/patches/v13_0/rename_issue_doctype_fields.py
> +		frappe.reload_doc('crm', 'doctype', 'opportunity', force=True)
Don't use `force=True`, as it will reset custom role and permissions

2021-08-27 07:29 UTC, saurabh6790 commented on erpnext/patches/v13_0/delete_old_sales_reports.py
> +def check_linked_reports(report):
make it a utility function, as we are also using it in delete_old_purchase_reports.py

2021-08-27 07:33 UTC, nabinhait commented on erpnext/patches/v13_0/rename_issue_doctype_fields.py
> +		frappe.reload_doc('crm', 'doctype', 'opportunity', force=True)
I don't think `force=True` will reset permissions, that is maintained in Custom Perm in db.

2021-08-27 07:49 UTC, ankush commented on erpnext/patches/v13_0/rename_issue_doctype_fields.py
> +		frappe.reload_doc('crm', 'doctype', 'opportunity', force=True)
`force` just ignores `modified` key. 

https://github.com/frappe/frappe/blob/1ac27efa7a252701e4c7c61c8aacc90fe401cb99/frappe/modules/import_file.py#L60-L64

You can also just bump the modified key if you want it to migrate again.

2021-08-27 11:12 UTC, merged

2021-09-06 08:33 UTC, elan-k commented
Looks like, we are getting the same issue while migrating the site to V13.

I have taken new backup files today and try to upload the same, But no luck it still fails at "Migrate Site" under "New Site from Backup" job. 

@ankush : Could you please help us to resolve the same? 

Or 

Is there anything I'm missing here while doing a migration to V13 ?

PFA : Screens for your reference here, 
![image](https://user-images.githubusercontent.com/78781781/132185187-8db4550c-cb1e-44bc-8c8b-a60133462837.png)

![image](https://user-images.githubusercontent.com/78781781/132183936-9eda038d-33fe-4d46-9409-41d28e780f32.png)

![image](https://user-images.githubusercontent.com/78781781/132185612-cebf51ea-7ce3-4ec5-a96a-41f99c6d9ec4.png)

![image](https://user-images.githubusercontent.com/78781781/132185925-3252606a-83d0-4b50-be37-dee2ba7c8976.png)

Thanks in Advance

2021-09-06 09:13 UTC, shadrak98 commented
@elan-k AFAIK this PR was not included in the latest release 13.10.0.

2021-09-28 18:37 UTC, elan-k commented
Looks like, we are getting a new issue while migrating the site to V13.

I have taken new backup files today and try to upload the same, But no luck it still fails at "Migrate Site" under "New Site from Backup" job.

Migrate fails at "Executing erpnext.patches.v12_0.update_vehicle_no_reqd_condition"

@shadrak98 : Could you please help us to resolve the same? Or any workaround for the same !

PFA: Screens for your reference here,
![image](https://user-images.githubusercontent.com/78781781/135145718-0cf48a84-3a0b-4ca8-9a0b-d4d95a361fa9.png)

![image](https://user-images.githubusercontent.com/78781781/135145885-e0a7e333-5230-4767-acb8-4a1da4821765.png)

Thanks in Advance!

2021-09-29 12:59 UTC, shadrak98 commented
@elan-k Solution to this is to reload the doc again in the console with force=True as an additional parameter.
`frappe.reload_doc('custom', 'doctype', 'custom_field', force=True)` then run migration again

2021-09-30 08:49 UTC, elan-k commented
@shadrak98 : Thank you for your quick response on this issue. 

We have hosted our site with frappecloud.com, where we don't have access to the console or database. 

I'm just taking backups from the existing site (V12) then uploading the same to the new site (V13), which will migrate the site to V13 as per the guide provided (https://frappecloud.com/docs/sites/version-upgrade). But we are failed at, 

 "Executing erpnext.patches.v12_0.update_vehicle_no_reqd_condition"

Is there any suggestion on our scenario here?

Thanks in Advance!

2021-09-30 09:25 UTC, ankush commented
Hi @elan-k please open a new issue with error you're seeing on https://github.com/frappe/frappe and we will get it fixed. 

Comments on old PRs will can go unnoticed.