fix: General Ledger translation issues
frappe/erpnext pull request #27298
Opened 2021-09-01 14:14 UTC by rtdany10

Options of group_by filter are translated. Assertion in the code was made against English sentences and hence would always return false in case where English isn't the system language.

Based on #27277

2021-09-03 14:07 UTC, rtdany10 commented
@ankush unrelated test failing. Can we merge this?

2021-09-07 10:25 UTC, rtdany10 commented
@ankush

2021-09-07 11:54 UTC, ankush requested changes
A better solution would be to remove translations from business logic altogether.

The options are anyways translated, so it's not required in the code. 

Example: `value` attribute contains actual value while display label can be whatever translate function returns. 

![Screenshot 2021-09-07 at 5 22 32 PM](https://user-images.githubusercontent.com/9079960/132340250-7b160d27-3c39-49ff-81fe-90b6fd9237bc.png)

2021-09-07 14:39 UTC, ankush commented
Oh well, removing all translation calls also removes it from `_messages` 🤦

2021-09-08 10:57 UTC, ankush approved these changes

2021-09-08 10:58 UTC, merged