refactor: finance books
frappe/erpnext pull request #27491
Opened 2021-09-14 14:14 UTC by GangaManoj

## Company

- Add a new checkbox 'Enable Finance Books'.
- Make 'Default Finance Book' mandatory if 'Enable Finance Books' is checked.
- Move 'Default Finance Book' to the 'Fixed Asset Defaults' section.

![Screenshot 2021-09-14 at 7 10 37 PM](https://user-images.githubusercontent.com/25903035/133268627-b15742da-82f8-4cab-9c82-fb6a43958e73.png)

## Asset

- If 'Enable Finance Books' is checked:
   - The 'Finance Book' column in the Finance Books table will be visible.
    
     ![Screenshot 2021-09-14 at 7 19 24 PM](https://user-images.githubusercontent.com/25903035/133272138-c7f3549d-9d48-49d9-a97b-a5a525d503e0.png)

   - Add Row and Delete Row will be enabled for the Finance Books table.

     ![Screenshot 2021-09-14 at 7 29 41 PM](https://user-images.githubusercontent.com/25903035/133272246-6f0f2c1d-3c06-4dd4-a3af-1975775ca47c.png)

     ![Screenshot 2021-09-14 at 7 30 30 PM](https://user-images.githubusercontent.com/25903035/133272263-fbb17b2d-9054-4c57-9d08-05ef3abfd73b.png)

   - The 'Finance Book' column in the Depreciation Schedule table will be visible.

     ![Screenshot 2021-09-14 at 7 31 40 PM](https://user-images.githubusercontent.com/25903035/133272024-93be58aa-a914-4a33-a927-e99cf4e5cb02.png)

- If 'Enable Finance Books' is unchecked:
   - The 'Finance Book' column in the Finance Books table will not be visible.
   - Add Row and Delete Row will not be enabled for the Finance Books table.
   - The 'Finance Book' column in the Depreciation Schedule table will not be visible.
   
   ![Screenshot 2021-09-14 at 7 38 12 PM](https://user-images.githubusercontent.com/25903035/133273058-5cc5de0a-428c-45f9-8ccf-536dccfce42f.png)

## Journal Entry

- The 'Finance Book' field will only be visible if 'Enable Finance Books' is checked.

_When checked:_

![Screenshot 2021-09-14 at 7 43 04 PM](https://user-images.githubusercontent.com/25903035/133274016-84c52ac9-9feb-42e2-9dc8-24a6d0358d77.png)

_When unchecked:_

![Screenshot 2021-09-14 at 7 44 21 PM](https://user-images.githubusercontent.com/25903035/133274177-adc5f56a-ecf4-4aee-90ea-d4f5e33c4acb.png)

2021-10-12 08:20 UTC, nextchamp-saqib requested changes

2021-10-12 08:20 UTC, nextchamp-saqib commented on erpnext/setup/doctype/company/company.json
> +   "mandatory_depends_on": "enable_finance_books",
`default_finance_book` should be hidden if `enable_finance_books` is unchecked

2021-10-12 08:20 UTC, nextchamp-saqib commented on erpnext/setup/doctype/company/company.py
> +		make_property_setter("Asset Finance Book", "finance_book", "hidden", not(enable_finance_books), "Check", validate_fields_for_doctype=False)
This also needs to be executed with a patch for existing users who are not using finance books

We can maybe check if the default finance book is set OR if a user has more than one finance book, then enable finance books.
If not, make these property setters to hide the finance book field.

2021-10-12 08:21 UTC, nextchamp-saqib commented on erpnext/assets/doctype/asset/asset.js
> +		frappe.db.get_value("Company", frm.doc.company, "enable_finance_books", (r) => {
In Asset Category too.

2021-10-27 00:04 UTC, GangaManoj commented on erpnext/setup/doctype/company/company.json
> +   "mandatory_depends_on": "enable_finance_books",
Done.

2021-10-27 00:08 UTC, GangaManoj commented on erpnext/assets/doctype/asset/asset.js
> +		frappe.db.get_value("Company", frm.doc.company, "enable_finance_books", (r) => {
But there's a problem there- Asset Categories aren't linked with a single Company. What if one of the companies listed has Finance Books enabled, but the rest don't?

2021-10-27 00:43 UTC, GangaManoj commented on erpnext/setup/doctype/company/company.py
> +		make_property_setter("Asset Finance Book", "finance_book", "hidden", not(enable_finance_books), "Check", validate_fields_for_doctype=False)
I just wrote the patch, but then I realised that this is all wrong- I shouldn't be using property setters here, because that would affect the visibility of that field for docs linked with ALL companies. 

I should make js changes instead- make those fields hidden by default, but after entering a Company, check its Enable Finance Books value and decide its visibility accordingly.

2021-10-27 09:45 UTC, nextchamp-saqib commented on erpnext/assets/doctype/asset/asset.js
> +		frappe.db.get_value("Company", frm.doc.company, "enable_finance_books", (r) => {
Make it visible if any one of the companies has it enabled. 

But also add a validation that, if for a company, FB is enabled, then it is mandatory to select a FB just for that company's row

2021-10-27 12:59 UTC, GangaManoj commented on erpnext/assets/doctype/asset/asset.js
> +		frappe.db.get_value("Company", frm.doc.company, "enable_finance_books", (r) => {
But the list of companies and finance books are in two separate tables, so if any of the Companies listed has Finance Books enabled, the Finance Books entered will be linked with all of them.

2021-11-02 11:08 UTC, closed without merging