feat: Sales Commission Payout
frappe/erpnext pull request #27597
Opened 2021-09-20 10:21 UTC by AfshanKhan

2021-10-28 07:47 UTC, deepeshgarg007 requested changes

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
> +				doc.reload()
Why doc.reload is needed here?

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
> +			outstanding_amount = 0
What if partial commission is only paid out, are we tracking partial payments anywhere?

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
> +				frappe.throw(_("Please set {0} in {1}").format(frappe.bold("Salary Component for Sales Commission"), get_link_to_form("Payroll Settings", "Payroll Settings")))
Break this into two lines for better readability

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
> +		sales_persons_details = frappe.get_all("Sales Team", filters={"parent": ['in', records]}, fields=["sales_person", "commission_rate", "incentives", "allocated_percentage", "allocated_amount", "paren
Break into two lines

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
> +		if len(sales_persons_details):
No need to check `len`, just `sales_persons_details` should be fine

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
> +					employee_details = frappe.db.get_value("Employee", filters={"name":emp}, fieldname=["company", "department", "designation", "branch"], as_dict=True)
Two queries in for loop. These can easily be moved out of the loop.
Also remember to add a space after `:`

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/process_sales_commission/process_sales_commission.py
> +	def map_sales_persons_details(self, sales_persons, sales_persons_details):
This function will become redundant if the queries are moved out of the for loop

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/sales_commission/sales_commission.js
> +				'reqd': 1
This should not be mandatory, user should be able to make a payment entry even without the mode of mayment

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/sales_commission/sales_commission.py
> +		if self.total_commission_amount <= 0:
We have a docfield check for this in framework itself, you can use that

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/sales_commission/sales_commission.py
> +def add(record, sales_person):
Add a better function name and some comments to explain what this function does
Why contributions with docstatus 0 are being considered?

2021-10-28 07:47 UTC, deepeshgarg007 commented on erpnext/payroll/doctype/sales_commission/sales_commission.py
> +		self.db_set("status", "Paid")
What if there is only a partial payout, we should track this in an outstanding amount field just like in sales invoices and then updated the status accordingly.

2021-10-28 08:27 UTC, AfshanKhan commented on erpnext/payroll/doctype/sales_commission/sales_commission.py
> +		if self.total_commission_amount <= 0:
That only checks for less than 0 not for equal to 0

2021-10-28 08:29 UTC, AfshanKhan commented on erpnext/payroll/doctype/sales_commission/sales_commission.js
> +				'reqd': 1
This is required to get the paid from account for payment entry. Hence mandatory

2022-03-21 06:54 UTC, pushkarjsh88 commented
@deepeshgarg007 What is the current status on this?  Can this be reopened since it will be required in the Healthcare in some or there other way.

2022-05-18 13:18 UTC, federicocalvo commented
Hi @AfshanKhan ! this pr is very useful and a big missing feature in ERPNext. They should add people from Frappe in the control so that it does not die.

2022-07-02 09:15 UTC, closed without merging