fix: Unlink PO on cancelling SO
frappe/erpnext pull request #27609
Opened 2021-09-20 13:35 UTC by GangaManoj

_Problem:_

- On cancelling a Sales Order, Purchase Orders linked with it also get cancelled.

_Fix:_

- Unlink associated Purchase Orders on cancelling Sales Orders.

2021-10-28 13:35 UTC, deepeshgarg007 requested changes

2021-10-28 13:35 UTC, deepeshgarg007 commented on erpnext/controllers/accounts_controller.py
> +			if self.doctype == "Sales Order":
We can also create Purchase Order from Sales Order as well. Shouldn't this be other way round as well?

2021-10-28 13:35 UTC, deepeshgarg007 commented on erpnext/controllers/accounts_controller.py
> +		linked_po = frappe.get_all(
As far as I know, `set_value` only updates one record at a time, can you try with multiple items as well?

2021-10-28 13:48 UTC, GangaManoj commented on erpnext/controllers/accounts_controller.py
> +		linked_po = frappe.get_all(
yeah, it worked perfectly when I tried it on the console, which is why this is so baffling.

2021-10-28 13:50 UTC, GangaManoj commented on erpnext/controllers/accounts_controller.py
> +			if self.doctype == "Sales Order":
There doesn't seem to be an option to do that.

![Screenshot 2021-10-28 at 7 20 19 PM](https://user-images.githubusercontent.com/25903035/139269444-f6a5d6df-c301-4f6e-ae08-1c58e5a10caf.png)

2021-10-29 06:27 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-hotfix

2021-10-29 06:27 UTC, merged