feat(HR): Added new fields to the Appraisal and Appraisal Template Doctype
frappe/erpnext pull request #27610
Opened 2021-09-20 14:53 UTC by mohammedyusufshaikh

Before this pull request the Appraisal Doctype had few parameters on which the candidate would be evaluated but after this pull request is merged a lot more parameters would available to evaluate the candidate for appraisal. 

Some of the fields which were added are as follows:
1] Behavioural Assessment (Table)
2] Self Improvement Areas (Table)
3] Revised Designation and Compensation
4] Additional fields for employee detail
<img width="1430" alt="Screenshot 2021-09-20 at 8 16 20 PM" src="https://user-images.githubusercontent.com/49878143/134023079-8166ee61-9bea-4327-8182-88239eb31667.png">
<img width="1427" alt="Screenshot 2021-09-20 at 8 17 08 PM" src="https://user-images.githubusercontent.com/49878143/134023092-9ab6ea24-3fb5-45e0-a834-934a30475f00.png">
<img width="1408" alt="Screenshot 2021-09-20 at 8 21 10 PM" src="https://user-images.githubusercontent.com/49878143/134023615-2712fa15-9caa-4eed-9618-ad33a3215c03.png">

2021-10-01 06:26 UTC, anupamvs requested changes

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.js
> +		for (let i = 0; i<kra_assessment.length; i++) {
use forEach

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.js
> +		var d = locals[cdt][cdn];
let d = frappe.get_doc(cdt, cdn)

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.js
> +			d.target_score = 0;
use frappe.model.set_value(cdt, cdn, 'target_score', 0)

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.js
> +		var d = locals[cdt][cdn];
frappe.get_doc

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.py
> +		chk = frappe.db.sql('''select name from `tabAppraisal` where employee=%s
Query formatting. 

- select -> SELECT
- from -> FROM
- where-> WHERE
- and -> AND
- or -> OR

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.py
> +		total_mentor_score, total_w, total_self_score = 0, 0, 0
total_mentor_score = total_w = total_self_score = 0 this will also works.

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.py
> +			if d.target_score > 5 or d.target_score < 1:
if d. target_score not in range(1, 6):

2021-10-01 06:26 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.py
> +			if d.achieved_score > 5 or d.achieved_score < 1:
if d. achieved_score not in range(1, 6):

2021-10-01 06:28 UTC, anupamvs commented on erpnext/hr/doctype/appraisal/appraisal.js
> +
why?

2021-10-20 05:25 UTC, ruchamahabal commented
Will be adding more enhancements and opening a separate PR. Closing for now.

2021-10-20 05:25 UTC, closed without merging

2022-01-15 08:58 UTC, ushashmi commented
Any update on this