fix: Add indexes in stock queries
frappe/erpnext pull request #27758
Opened 2021-10-03 09:21 UTC by deepeshgarg007

2021-10-04 06:10 UTC, nextchamp-saqib commented on erpnext/stock/doctype/bin/bin.py
>  			+ flt(self.indented_qty) + flt(self.planned_qty) - flt(self.reserved_qty)
```suggestion
```

2021-10-11 05:33 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-hotfix

2021-10-11 07:11 UTC, ankush requested changes

2021-10-11 07:11 UTC, ankush commented on erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py
> +	frappe.db.add_index("Stock Ledger Entry", ["voucher_detail_no"])
```suggestion
```

This is created via doctype now https://github.com/frappe/erpnext/pull/27866

2021-10-11 07:11 UTC, ankush commented on erpnext/stock/utils.py
> +def get_or_make_bin(item_code, warehouse):
```suggestion
def get_or_make_bin(item_code, warehouse) -> str:
```

Add some indication that this returns bin name instead of bin object like the function above.

2021-10-11 10:26 UTC, ankush submitted a review, later dismissed

2021-10-11 10:26 UTC, ankush commented on erpnext/stock/doctype/stock_ledger_entry/stock_ledger_entry.py
> +	frappe.db.add_index("Stock Ledger Entry", ["item_code", "warehouse"], "item_warehouse")
```suggestion
	frappe.db.add_index("Stock Ledger Entry", ["warehouse", "item_code"], "item_warehouse")
```

Might be beneficial. Needs some more testing (or better yet a generic perf test suite. 😅  )

2021-10-12 14:43 UTC, ankush approved these changes

2021-10-12 14:45 UTC, merged