feat: CRM Settings
frappe/erpnext pull request #27788
Opened 2021-10-05 05:26 UTC by anupamvs

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-10-05 05:54 UTC, umairsy commented
1. Introduce Column break in Lead and Opportunity section, to maintain left - right balance.
2.  Move first section in the last and put section heading. May be third section can be called "Quotation Settings", and out campaign setting under Leads.

2021-10-20 05:41 UTC, ruchamahabal requested changes

2021-10-20 05:41 UTC, ruchamahabal commented on erpnext/selling/doctype/crm_settings/crm_settings.json
> + "name": "CRM Settings",
We need a patch to update CRM Settings for Selling Settings.

2021-10-20 05:41 UTC, ruchamahabal commented on erpnext/selling/doctype/crm_settings/crm_settings.json
> +   "label": "Allow Creation of Multiple Leads form a Email"
```suggestion
   "label": "Allow Creation of Multiple Leads from an Email"
```

**Allow Lead Duplication based on Emails** 

Is this better?

2021-10-20 05:41 UTC, ruchamahabal commented on erpnext/selling/doctype/crm_settings/crm_settings.json
> +   "description": "Auto close Opportunity after the no. of days mentioned above",
```suggestion
   "description": "Auto close Replied Opportunity after the no. of days mentioned above",
```

2021-10-20 05:41 UTC, ruchamahabal commented on erpnext/selling/doctype/crm_settings/crm_settings.json
> +   "label": "Close Opportunity After Days"
```suggestion
   "label": "Close Replied Opportunity After Days"
```

2021-10-20 05:41 UTC, ruchamahabal commented on erpnext/crm/doctype/opportunity/opportunity.py
> +			customer = frappe.db.sql("""SELECT
Can be rewritten using `frappe.qb`?

2021-11-03 03:14 UTC, anupamvs commented on erpnext/crm/doctype/opportunity/opportunity.py
> +			customer = frappe.db.sql("""SELECT
I don't think so join is possible.

2021-11-23 05:07 UTC, ruchamahabal commented on erpnext/crm/doctype/opportunity/opportunity.py
> +			customer = frappe.db.sql("""SELECT
@anupamvs join is possible

![image](https://user-images.githubusercontent.com/24353136/142973973-8b01f9ba-1527-463a-9683-4cba3656f8b2.png)

You can convert all the queries and fix linter issues

2021-12-06 08:21 UTC, ruchamahabal approved these changes

2021-12-06 08:22 UTC, merged