fix: updated packed_items getting fetched on sales return
frappe/erpnext pull request #28607
Opened 2021-11-29 08:27 UTC by noahjacob

### Issue
- When creating a Sales Return from a **Delivery Note**, if the **Delivery Note** contains a **Product Bundle** item, on saving the return document, the updated packed_items are fetched instead of the packed_items from the **Delivery Note**.

<details>
<summary>Product Bundles</summary>

### Product Bundle Before Creating Delivery Note
![image](https://user-images.githubusercontent.com/43572428/143830598-b02b8883-8293-481e-b9f9-098e2167e87b.png)

### Updated Product Bundle

![image](https://user-images.githubusercontent.com/43572428/143831509-f3b5a259-478f-479d-9a4a-2c5f02585886.png)

</details>

![return_map](https://user-images.githubusercontent.com/43572428/143831779-453728e5-4d89-45d7-995e-92a3ace62965.gif)

### Fix
- If document is a Return, mapped packed_items are kept as it is instead of fetching packed_items from **Product Bundle**.
- Packed_items qtys are recalculated if the item qty is changed.

![return_map_fix](https://user-images.githubusercontent.com/43572428/143832390-5bbe8404-96bc-4364-a2ad-03f3e96bc4d0.gif)

### Steps 
- Create a **Product Bundle**.
- Create a **Delivery Note** with the **Product Bundle**.
- Update the **Product Bundle**.
- Create a "Sales Return" via the **Delivery Note**.
- Save the "Sales Return" document.

2021-11-29 13:07 UTC, ankush commented
Product bundle should be a submittable doctype with versioning like BOM! 😐

2021-11-30 06:09 UTC, ankush commented
This would apply to Sales Invoice with `update_stock` too right? Can you check and fix both cases in one PR then?

Perheps this is best handled in that util function instead of a single doctype 😅

2021-11-30 08:20 UTC, noahjacob commented
> This would apply to Sales Invoice with `update_stock` too right? Can you check and fix both cases in one PR then?
> 
> Perhaps this is best handled in that util function instead of a single doctype 😅

Moved it to stock.utils and did the same for Credit Note.

2022-01-21 05:21 UTC, ankush commented on erpnext/stock/utils.py
> +def calculate_mapped_packed_items_return(self):
function with `self` as argument? 😄

2022-01-21 05:37 UTC, ankush commented on erpnext/stock/utils.py
> +			for p_item, d_p_item in zip(return_doc.packed_items, against_doc.packed_items):
If you have two bundle this for loop adds last bundle to all references. It's not being checked which item they actually belong to here.

2022-01-21 05:39 UTC, ankush requested changes

2022-01-21 05:39 UTC, ankush commented on erpnext/stock/utils.py
> +			for p_item, d_p_item in zip(return_doc.packed_items, against_doc.packed_items):
original

<img width="1422" alt="Screenshot 2022-01-21 at 11 08 23 AM" src="https://user-images.githubusercontent.com/9079960/150472249-35c6d8c5-a447-4673-87fd-cbf6d834a5a6.png">



returned:
<img width="1422" alt="Screenshot 2022-01-21 at 11 08 44 AM" src="https://user-images.githubusercontent.com/9079960/150472257-ff0596b0-3457-4321-83b5-faa50e29bd41.png">

2022-01-21 06:20 UTC, ankush approved these changes

2022-01-21 06:20 UTC, merged