Bug fix/purchase receipt/warehouse
frappe/erpnext pull request #28673
Opened 2021-12-01 17:24 UTC by s-aga-r

#### Source/Reference: ISS-21-22-09054

### Issue(s): Purchase Receipt

_Problem:_
- When populating the "Accepted Warehouse" field it adds that warehouse as the default warehouse on all the item rows. This is helpful because often the same warehouse for all the items received. But if the user changes the warehouse for an item. In that case, this field becomes confusing as it is holding another warehouse.

_Proposed Solution:_
- If the warehouse of all items is the same, then set that warehouse to "Accepted Warehouse" otherwise None.

<details>
<summary>Images/GIF</summary>

_Before:_

https://user-images.githubusercontent.com/63660334/144282361-d6e8ef46-ae48-42ed-a86c-8136cf993b45.gif

_After:_

https://user-images.githubusercontent.com/25903035/130674996-a6d891e4-4220-4574-87fc-5b32bca6992a.png
</details>

2021-12-01 17:49 UTC, ankush requested changes

2021-12-01 17:49 UTC, ankush commented on erpnext/stock/utils.py
> +def reset_default_field(doc, default_field, child_table_name, child_table_field):
This should have a docstring to describe what it does. 

Also a util that's only used once isn't a util 😜 we should extend this to all similar fields in other "set default X" type fields.

2021-12-01 17:51 UTC, ankush commented on erpnext/stock/utils.py
> +def reset_default_field(doc, default_field, child_table_name, child_table_field):
Also add a 2 small test cases for util function. Mixed values and same value. 


A minor optimization: if default_field is empty in document then this function doesn't even need to run.

2021-12-02 13:53 UTC, s-aga-r commented
@ankush Where to put this "test_utils.py" file

2021-12-08 12:33 UTC, ankush commented
@s-aga-r linter failing. Setup pre-commit locally to avoid these issues: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#linting

2021-12-08 15:18 UTC, closed without merging