feat: Items/BOQ in Task
frappe/erpnext pull request #28757
Opened 2021-12-06 11:20 UTC by noahjacob

## WIP

2021-12-07 06:33 UTC, mujeerhashmi commented
We can also have BOM Operation for Tasks. So that we will have the provision to track equipment costs.

2021-12-10 08:03 UTC, muchai commented
Is this not tied to projects/project tasks?
It's a very exciting feature, and I thought it's applicable in construction industry, steel structures firms...

2022-02-08 05:02 UTC, rmehta requested changes

2022-02-08 05:02 UTC, rmehta commented on erpnext/projects/doctype/task/task.js
> +	calculate_total_estimated_costs(frm) {
all business logic should be serverside

2022-03-09 08:11 UTC, deepeshgarg007 commented
Closing this due to no action

2022-03-09 08:11 UTC, closed without merging