feat: Reconciliation in POS using Credit Note
frappe/erpnext pull request #28775
Opened 2021-12-07 11:26 UTC by nemesis189

**WIP**
----

<h3>Updates:</h3>

- Adding Sales Invoice credit note with outstanding as an advance payment
- Added 'Credit Note' as a Mode of Payment
- Added a checkbox in POS Invoice called `Ignore Payments for Return` to skip payment validation while creating return credit notes via Point Of Sale
---

<details open>
<summary><b>Pre requisite Feats added:</b></summary>
<ol>
<li>Adding Sales Invoice credit note with outstanding as an advance payment </li>
<ul>
<li>Earlier only Payment entires and Journal Entries could be added as an advance for payment in the Advances table.</li>
<li>Now, any sales invoice credit note with outstanding < 0 can be used for advance payment</li>
</ul>

<li>Added 'Credit Note' as a Mode of Payment:</li>
<ul>
<li>A new Mode Of Payment 'Credit Note' has been added which works only for POS currently, it fetches POS Invoice credit notes with negative outstanding</li>
<ul>
</details>

---

<h3>Feature Description:</h3>

- In Point of Sale now we can make use of a POS invoice credit note with negative outstanding for payments. 
- We can select the 'Credit Note' as the mode of payment where all the POS invoice credit notes(returns) with negative outstanding would be listed down and the total of the selected invoice would be added to the `paid_amount` and the outstanding amount of the selected credit note becomes 0.
- While closing a POS, if CN is used as a mode of payment for any invoice, a third consolidated invoice - **Consolidated Advances Invoice** is created along with the usual two other (consolidated sales invoice and consolidated credit return) consolidated invoices.
---
**Consider the following scenario (also the steps):**
1. Make a new opening entry for POS
2. Create a few pos invoices(3-4) and close the POS
3. Now the next day one of the invoices needs to be returned so for that - make a new opening entry again(for a new day) and make return for 1-2 invoices through the UI created in the above steps, **while doing so make sure the checkbox `Ignore Payments For Return` is checked(Add it to pos screen via POS Settings). ** This step will make POS return credit notes with negative outstanding which would be used for reconciliation or as payments
4. Make a new pos sale and in payments select 'Credit Note' as mode of payment and select one of the credit notes created in the above steps.
5. Complete the transaction, make another transaction with mode of payment as Credit Note.
6. Close this POS session by creating a closing entry.
7. Check the 3 consolidated invoices created, the consolidated sales invoice should have the **Consolidated Advances Invoice** added to the **Advances** table of the invoice as an advance payment

2021-12-18 06:34 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/mode_of_payment/mode_of_payment.json
> + "migration_hash": "54043fbbb01893f2866c8367069f2ed0",
```suggestion
```

2021-12-18 06:34 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.json
> + "migration_hash": "68e462071d0c4b17941f5e6c57acfd88",
```suggestion
```

2021-12-18 06:35 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_settings/pos_settings.json
> + "modified": "2021-11-25 19:59:53.015244",
```suggestion
 "modified": "2021-04-19 14:56:24.465218",
```

2021-12-18 06:35 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/sales_invoice_payment/sales_invoice_payment.json
> + "migration_hash": "c3a1e585986db6aa4b3cc4f0f24c4400",
```suggestion
```

2022-01-12 07:27 UTC, nextchamp-saqib requested changes

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.py
> +		cn_inv.outstanding_amount = 0
```suggestion
		cn_inv.outstanding_amount -= flt(cn_mop.amount)
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.py
> +		cn_inv.outstanding_amount = flt(cn_mop.amount)
```suggestion
		cn_inv.outstanding_amount += flt(cn_mop.amount)
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.py
> +		cn_inv = frappe.get_doc('POS Invoice',cn_mop.credit_note)
There can be multiple Credit Note payments too

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.json
> +  "consolidate_advances_credit_note",
Rename this to `consolidated_credit_note_payment`

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.json
> +  "ignore_payments_for_return",
Should be renamed to something like `Use as Payment`
Check with @harshit-30 for a better label

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +				break
There can be multiple Credit Note payments too. So don't `break` just after finding the first one

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +		cn.outstanding_amount = flt(cn_amount_mapping[cn.name]) if not set_zero else 0.0
This should reduce the `outstanding` by the `amount` and incase of cancellation, increase by that value

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +	if len(invoices) >= 100 and closing_entry:
```suggestion
	if len(invoices) >= 10 and closing_entry:
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +	if len(merge_logs) >= 100:
```suggestion
	if len(merge_logs) >= 10:
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.js
> -		var parent_fields = ['project', 'due_date', 'is_opening', 'source', 'total_advance', 'get_advances',
Use `depends_on` to hide the advance related fields if `set_advances` is not checked or `advances` doesn't have rows

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +		self.save() # save consolidated_sales_invoice & consolidated_credit_note ref in merge log)
```suggestion
		self.save() # save consolidated_sales_invoice & consolidated_credit_note ref in merge log
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +		# frappe.throw('here')
```suggestion
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +			advance_credit_note_doc = frappe.get_doc("Sales Invoice", advance_credit_note)
This `get_doc` can be eliminated, if you return `advance_credit_note` doc from `process_merging_into_credit_note`

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +				# "ref_exchange_rate": flt(si.get("exchange_rate")) # exchange_rate of advance entry
```suggestion
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +	def get_advance_pos_credit_notes(self, invoice, payment, advance=None):
`set_credit_note_payment_as_advance`

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice_merge_log/pos_invoice_merge_log.py
> +				set_pos_cn_outstanding_value(advances, cn_amount_mapping, set_zero=False)
This should not be done in `update_pos_invoices`

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		print('HELLOOOOOO', len(self.payments) == 0 , len(self.advances)==0)
```suggestion
```

2022-01-12 07:27 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		if self.is_return and not self.is_pos:
This validation was specifically for `is_pos` invoices. This shouldn't be bypassed.

2022-01-13 06:01 UTC, nextchamp-saqib commented on erpnext/controllers/accounts_controller.py
> +				customer = %s and outstanding_amount != 0
```suggestion
				customer = %s and outstanding_amount > 0
```

2022-01-31 08:34 UTC, closed without merging

2022-06-20 11:05 UTC, OneiricIT commented
Any update on this?
Would be finally good to see an easy way to allocate credit on customer account to new / other Sales invoices in system...

https://discuss.erpnext.com/t/allocate-credit-note-debit-note-to-another-sales-invoice-purchase-invoice/29329/6