feat: Deferred Revenue and Expense report with actual and upcoming postings
frappe/erpnext pull request #28822
Opened 2021-12-10 15:11 UTC by ruthra-kumar

### Deferred Revenue and Expense Report
This report aim to provide a simplified view of all deferred income/expense in a certain period. It can help in identifying the actual and expected posting.

### Deferred Revenue
<img width="1552" alt="def_revenue" src="https://user-images.githubusercontent.com/3272205/145595902-5c57a12e-1559-4e61-a471-7aad7276cbd6.png">

### Deferred Expense
<img width="1552" alt="def_expense" src="https://user-images.githubusercontent.com/3272205/145595967-98d6e46e-d00f-46b7-a369-4fef1b02f0ca.png">

2021-12-14 09:49 UTC, deepeshgarg007 requested changes

2021-12-14 09:49 UTC, deepeshgarg007 commented on erpnext/accounts/report/deferred_revenue_and_expense/deferred_revenue_and_expense.py
> +	def get_postings(self):
Seems like a dead function, not called from anywhere

2021-12-14 09:49 UTC, deepeshgarg007 commented on erpnext/accounts/report/deferred_revenue_and_expense/deferred_revenue_and_expense.js
> +			"label": __("Show with upcoming revenue/expense"),
This also shows unbooked values for the previous months, may better to call this label as "Show expected revenue/expense" and this should be unchecked by default

2021-12-14 09:49 UTC, deepeshgarg007 commented
Fix the linting issues

2021-12-14 10:29 UTC, ruthra-kumar commented on erpnext/accounts/report/deferred_revenue_and_expense/deferred_revenue_and_expense.js
> +			"label": __("Show with upcoming revenue/expense"),
Agreed. 
Along with this, I think it's better if it only shows the actual posting(bar graph) when unchecked. Thoughts?

2021-12-14 10:44 UTC, deepeshgarg007 commented on erpnext/accounts/report/deferred_revenue_and_expense/deferred_revenue_and_expense.js
> +			"label": __("Show with upcoming revenue/expense"),
If someone wants to compare the expected and actual posting, how do they do that then?

2021-12-14 15:33 UTC, ruthra-kumar commented on erpnext/accounts/report/deferred_revenue_and_expense/deferred_revenue_and_expense.py
> +	def get_postings(self):
removed

2021-12-14 15:35 UTC, ruthra-kumar commented on erpnext/accounts/report/deferred_revenue_and_expense/deferred_revenue_and_expense.js
> +			"label": __("Show with upcoming revenue/expense"),
renamed and 'unchecked' by default.

2021-12-15 09:32 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-hotfix

2021-12-15 09:33 UTC, merged