Update de.csv
frappe/erpnext pull request #29037
Opened 2021-12-26 11:46 UTC by wojosc

Especially to allign Sales Orders (Aufträge) Sales Invoices (Ausgangsrechnungen) to Purchase Orders (Bestellungen) Purchase Invoice (Eingangsrechnungen). Both are a definate opposite and are kept short.

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2021-12-29 17:02 UTC, barredterra requested changes

2021-12-29 17:02 UTC, barredterra commented on erpnext/translations/de.csv
> +Total Billed Hours,Summe Angekündigt Stunden,
```suggestion
Total Billed Hours,Summe abgerechneter Stunden,
```

2021-12-29 17:02 UTC, barredterra commented on erpnext/translations/de.csv
> +Total Billable Amount,Summe abrechenbare Betrag,
```suggestion
Total Billable Amount,Summe abrechenbarer Betrag,
```

2021-12-29 17:02 UTC, barredterra commented on erpnext/translations/de.csv
> +Minute,Protokoll,
Needs context. "Minute" (as a unit of time) would also be correct.

2021-12-29 17:02 UTC, barredterra commented on erpnext/translations/de.csv
> +New Purchase Invoice,Neue Ausgangsrechnung,
```suggestion
New Purchase Invoice,Neue Eingangsrechnung,
```

2021-12-29 17:02 UTC, barredterra commented on erpnext/translations/de.csv
> +Customer's Purchase Order No,Bestell Nr. des Kunden,
```suggestion
Customer's Purchase Order No,Bestellnummer des Kunden,
```

2021-12-30 09:50 UTC, wojosc commented on erpnext/translations/de.csv
> +Minute,Protokoll,
> Needs context. "Minute" (as a unit of time) would also be correct.

Both occour. Minute das the time factor and minute as a type of meeting. No idea which one will be which :/

2021-12-30 09:52 UTC, wojosc commented on erpnext/translations/de.csv
> +Total Billed Hours,Summe Angekündigt Stunden,
> 

Maybe sogar "Summe angekündigter Stunden" ?

2021-12-31 13:08 UTC, barredterra commented on erpnext/translations/de.csv
> +Total Billed Hours,Summe Angekündigt Stunden,
Wieso angekündigt?

2021-12-31 13:10 UTC, barredterra commented on erpnext/translations/de.csv
> +Minute,Protokoll,
We'd need to [add context](https://frappeframework.com/docs/v13/user/en/translations#6-adding-context-for-a-string) to the translatable strings in the source code.

2021-12-31 16:42 UTC, barredterra commented on erpnext/translations/de.csv
> +Minute,Protokoll,
```suggestion
Minute,Minute,
```

2021-12-31 16:43 UTC, barredterra approved these changes

2022-01-02 10:59 UTC, merged