feat: exclude existing serial numbers while auto creating new
frappe/erpnext pull request #29292
Opened 2022-01-14 13:05 UTC by rtdany10

In cases where Serial No is auto generated, consider the serial number template is XYZ.### and that the counter is at 0.

Assume I create a purchase receipt with 1 qty and manually input the serial number as XYZ005.
And if I create another purchase receipt with 10 qty and no serial number given, the system will try to use serial numbers XYZ001 to XYZ010. In that case, I will get a validation error regarding XYZ005.

Further: https://discuss.erpnext.com/t/serial-number-generation-problem/84831

This PR aims to solve the issue by checking if the serial number already exists or not.
#no-docs

2022-01-14 13:17 UTC, ankush requested changes

2022-01-14 13:17 UTC, ankush commented on erpnext/stock/doctype/serial_no/serial_no.py
> +	return sno
overall fix is okay; some suggestions on naming:

function should be probably be called "get_new_serial_number", along with argument "series" it makes it pretty clear as to what it does. 

Also `sno` is bad variable name; `sr_no` maybe?

---

up to you: Add a test case for this behaviour. (just encode the steps you described in a unit test 😄)

2022-01-14 13:31 UTC, rtdany10 commented on erpnext/stock/doctype/serial_no/serial_no.py
> +	return sno
Have renamed. Will also add a test case. :)

2022-01-14 16:20 UTC, rtdany10 commented
@mergifyio backport version-13-hotfix

2022-01-15 14:37 UTC, ankush approved these changes

2022-01-15 14:38 UTC, merged