feat: POS multicurrency support
frappe/erpnext pull request #29478
Opened 2022-01-27 08:15 UTC by this-gavagai

This PR provides multicurrency functionality to the POS.

At present, the POS does not provide any mechanisms for managing multiple currencies, and furthermore it tolerates incoherent data if a user attempts to use conflicting modes of payment within a POS profile. This PR adds logic, validation, and user interface elements to allow multicurrency functionality while making as few changes as possible to the underlying architecture.

Significant code changes are as follows:
- Currency fields added to both POS Opening Entry and POS Closing Entry
- In POS Closing Entry, summary fields for total sales made consistent to always display in company default currency
- Some verification checks added to ensure that account currencies match POS Invoice currency
- Extended POS Invoice Merge Log document to separate consolidated invoices by currency
- Added UI methods to change currency via menu item
- Filter available payment modes to only those matching POS Invoice currency

2022-02-03 04:53 UTC, this-gavagai commented
Hello, is there anything I can do to facilitate code review?

2022-02-15 07:51 UTC, this-gavagai commented
Am I misunderstanding the process for feature submissions? It's almost three weeks now without even acknowledgment of this PR. Any suggestions would be greatly appreciated. @nextchamp-saqib

2022-02-15 08:16 UTC, nextchamp-saqib commented
Hey, @this-gavagai

I have gone through the changes, but haven't found time to review/pull & test locally.
I have kept this as well as other POS features on my to-do list. I'll review this soon. 

In the meantime, you could add test cases for simple multi currency scenarios.

Thanks for contributing!

2022-02-23 05:31 UTC, nextchamp-saqib requested changes

2022-02-23 05:31 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.py
> +				if customer_currency and customer_currency != profile.get('currency') and not self.currency:
```suggestion
				if customer_currency and customer_currency != profile.get('currency'):
```

Customer Currency should overwrite existing currency in the Invoice, right?
Is this intentional? If yes, Can you help me understand with an example?

2022-02-23 05:31 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.py
> +			frappe.throw(_("Change Account does not match invoice currency"))
```suggestion
		change_account_currency = frappe.db.get_value("Account", self.account_for_change_amount, "account_currency")
		if self.change_amount and self.currency != change_account_currency:
			frappe.throw(_("Change Account Currency {} does not match with Invoice Currency {}").format(change_account_currency, self.currency))
```

2022-02-23 05:31 UTC, nextchamp-saqib commented on erpnext/accounts/doctype/pos_invoice/pos_invoice.py
> +		if frappe.db.get_value("Account", acct, "account_currency") == doc.currency:
```suggestion
		mop_account = mode_of_payments_info.get(row.mode_of_payment, {}).get('default_account')
		if mop_account and \
			frappe.db.get_value("Account", mop_account, "account_currency", cache=True) == doc.currency:
```

2022-02-24 09:05 UTC, this-gavagai commented
Thank you so much for reviewing this @nextchamp-saqib! I am travelling for a week or so right now and without easy access to a development environment, but I'll review the code changes and create the tests as soon as I can.

2022-03-14 10:58 UTC, closed without merging