fix: if an item code is too long, truncate before setting BOM name
frappe/erpnext pull request #29815
Opened 2022-02-15 11:06 UTC by Alchez

<details>
<summary>Traceback</summary>

```python
DataError: (1406, "Data too long for column 'parent' at row 1")
  File "frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "__init__.py", line 1097, in call
    return fn(*args, **newargs)
  File "frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "frappe/model/document.py", line 296, in _save
    self.insert()
  File "frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "frappe/model/document.py", line 901, in run_before_save_methods
    self.run_method("validate")
  File "frappe/model/document.py", line 802, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "frappe/model/document.py", line 1081, in composer
    return composed(self, method, *args, **kwargs)
  File "frappe/model/document.py", line 1064, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "frappe/model/document.py", line 796, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "erpnext/manufacturing/doctype/bom/bom.py", line 68, in validate
    self.update_cost(update_parent=False, from_child_bom=True, save=False)
  File "erpnext/manufacturing/doctype/bom/bom.py", line 267, in update_cost
    self.update_exploded_items()
  File "erpnext/manufacturing/doctype/bom/bom.py", line 544, in update_exploded_items
    self.add_exploded_items()
  File "erpnext/manufacturing/doctype/bom/bom.py", line 622, in add_exploded_items
    ch.db_insert()
  File "frappe/model/base_document.py", line 330, in db_insert
    ), list(d.values()))
  File "frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
```

</details>

2022-02-16 07:04 UTC, ankush commented
This will allow inserting but mess up with versioning right? because for versioning item code is used to find existing BOMs. 

https://github.com/frappe/erpnext/blob/fa57a38cc1bd7462bfe3e2a6e0bc92fcf8c17a84/erpnext/manufacturing/doctype/bom/bom.py#L112-L113

<img width="1069" alt="Screenshot 2022-02-16 at 12 32 48 PM" src="https://user-images.githubusercontent.com/9079960/154213195-04c58a85-c770-4fca-9f35-ae48ae4521a3.png">



(and even if it works it looks like this 🙈 )

<img width="1069" alt="Screenshot 2022-02-16 at 12 31 48 PM" src="https://user-images.githubusercontent.com/9079960/154213066-b1ea4d58-e72c-4a94-bece-fd6224fa65c7.png">


Not sure who _really_ needs >100 character item codes TBH. A better solution could be to increase length in such cases.

2022-02-16 09:40 UTC, Alchez commented
@ankush 

> A better solution could be to increase length in DB table in such odd cases.

I agree with this, but I'm not sure if there's an easy way to increase the maxlength of the `name` field for BOM. And would it persist after an update?

2022-02-16 10:40 UTC, Alchez commented
@ankush I've made some changes so that versioning no longer relies on the item, and simply the current version, which is what the old code was looking for too.

2022-02-26 06:38 UTC, ankush requested changes

2022-02-26 06:38 UTC, ankush commented on erpnext/manufacturing/doctype/bom/bom.py
> -			if names:
@Alchez new logic for versioning doesn't consider cancelled items (check last test case I added which fails)

2022-03-02 10:04 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.py
> -			if names:
@ankush, oh thanks for the test case! I've added a fix for checking cancelled BOMs. It's fairly implicit, but I'm not sure about a better way to do it.

2022-03-02 10:47 UTC, Alchez commented on erpnext/manufacturing/doctype/bom/bom.py
> +			indexes = [cint(part[2] for part in valid_bom_parts)]
@ankush

Do you think there's a better way to do this? Should we even bother with this anymore and simply let the system fail with an error message?

If we do, and an item has a `-` or '/' character in its name, then this logic will fail.

I was thinking I could remove all amended documents entirely by adding it as a filter in the `get_all` above:

```python
existing_boms = frappe.get_all(
	  "BOM",
	  filters={"item": self.item, "amended_from": ["is", "not set"]},
	  pluck="name"
)
```

That should let me change this back to:

```suggestion
			indexes = [cint(part[-1] for part in valid_bom_parts)]
```

which, although still implicit, is better than the current state, I think.

2022-03-11 11:19 UTC, ankush approved these changes
LGTM.

2022-03-11 11:41 UTC, merged