Separate discount account
frappe/erpnext pull request #30642
Opened 2022-04-08 02:44 UTC by rahib-hassan

Discount Accounting removed from Account Settings for separation in Sales and Purchase Invoice and added to Selling and Buying Settings.

Removed hide/un-hide discount account in Item since default_discount_account has been moved to Item Defaults.

2022-04-08 05:54 UTC, ankush commented
@rahib-hassan follow semantic commit convention

https://www.conventionalcommits.org/en/v1.0.0/

2022-04-08 05:56 UTC, ankush requested changes
A patch should be added for users who have already enabled it globally to enable it in both sales/purchase side?

2022-04-08 05:56 UTC, ankush commented on erpnext/accounts/doctype/accounts_settings/accounts_settings.py
> -		enable_discount_accounting = cint(self.enable_discount_accounting)
These fields should be removed from accounts settings.

2022-04-12 13:09 UTC, ankush commented on erpnext/patches/v14_0/discount_accounting_separation.py
> +    discount_account = doc.enable_discount_accounting
for patches this is fine but avoid getting whole doc just for single value. `get_single_value` or `get_value` should be used. 

reason `get_doc` is bad for performance.

2022-04-12 13:12 UTC, ankush commented
All dependent code needs to be updated. This is the reason behind failing tests. 


<img width="1052" alt="Screenshot 2022-04-12 at 6 41 25 PM" src="https://user-images.githubusercontent.com/9079960/162970123-37e639da-7040-4732-96d0-e5815a8d8b4f.png">

2022-04-12 13:13 UTC, ankush commented on erpnext/patches/v14_0/discount_accounting_separation.py
> +        for doctype in ["Buying Settings", "Selling Settings"]:
```suggestion
        for doctype in ["Buying Settings", "Selling Settings"]:
```

We use tabs for formatting code. 

Setup pre-commit and add editorconfig plugin to automate this: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#linting

2022-04-14 07:42 UTC, deepeshgarg007 requested changes

2022-04-14 07:42 UTC, deepeshgarg007 commented on erpnext/buying/doctype/buying_settings/buying_settings.json
> +   "label": "Enable Discount Accounting"
```suggestion
   "label": "Enable Discount Accounting for Buying"
```

2022-04-14 07:42 UTC, deepeshgarg007 commented on erpnext/selling/doctype/selling_settings/selling_settings.json
> +   "label": "Enable Discount Accounting"
```suggestion
   "label": "Enable Discount Accounting for Sales"
```

2022-04-14 12:02 UTC, ankush commented
@rahib-hassan update docs: https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/discount_accounting

2022-04-20 08:12 UTC, ankush commented on erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
> +def enable_discount_accounting(enable=1):
There's already a simpler/reliable way to do this.
https://github.com/frappe/erpnext/blob/c42dcaa6cff5c87a10d58854cd10089f5ba53efb/erpnext/stock/doctype/stock_entry/test_stock_entry.py#L769

2022-04-20 11:19 UTC, ankush commented on erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py
> +		enable_discount_accounting(enable=0)
@rahib-hassan this isn't required, `change_settings` decorator rolls it back to previous value after test runs.

2022-04-21 07:15 UTC, rahib-hassan commented
> A patch should be added for users who have already enabled it globally to enable it in both sales/purchase side?
@ankush This has been done already.

2022-04-21 07:39 UTC, ankush commented
@deepeshgarg007 review? I am not much familiar with this but based on diff it appears to be okay to me.

2022-04-25 08:37 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-hotfix

2022-04-25 08:37 UTC, merged

2022-04-26 12:19 UTC, ankush commented
@rahib-hassan backport this manually on v13 if required. 

because of merge commit it's better to backport this as "squashed"


```bash
wget https://github.com/frappe/erpnext/pull/30642.patch
git apply 30642.patch
# commit ... pr.. 
```