feat: subcontracting module
frappe/erpnext pull request #30955
Opened 2022-05-10 09:50 UTC by s-aga-r

### Problem
Currently, the whole subcontracting flow is not intuitive and is sort of a work-around. It even takes a while to figure out the flow.

### Possible Solution
Have an explicit flow for subcontracting:
![image](https://user-images.githubusercontent.com/88872881/152283613-48bd7645-7e12-4282-9c76-ed72ecf78567.png)

### Possible Changes

**DocType(s)**

**New**

- [ ] Subcontracting Order
- [ ] Subcontracting Order Service Item (child)
- [ ] Subcontracting Order Finished Good Item (child)
- [ ] Subcontracting Order Supplied Item (child)
- [ ] Subcontracting Receipt 
- [ ] Subcontracting Receipt Service Item (child)
- [ ] Subcontracting Receipt Finished Good Item (child)
- [ ] Subcontracting Receipt Supplied Item (child)

**To Be Removed**

- [ ] Purchase Order Item Supplied (child)

**Master level**

- [ ] ~~Mark Service item for subcontracting and then map Service Item with FG (BOM)~~
- [ ] Add default subcontractor for the service item
- [ ] ~~Purchase Order (PO)~~
- [ ] Mark PO for subcontracting
- [ ] ~~On selecting the service item (show the RMs and the cost of the RMs if the item mapping is done) or manually select a BOM for every service item~~
- [ ] Option to create Subcontracting Order (SCO) from a submitted PO

**Subcontracting Order (SCO)**

- [ ] Create from PO
- [ ] Create independently (PO*)
- [ ] Select supplier
- [ ] ~~Select FG items (if started from PO then populate basis service item mapping)~~
- [ ] Add warehouse info for material transfer
- [ ] Status: Draft/Open/Partially Received/Completed/Material transferred/Partial Material Transferred
- [ ] Option to create a Stock entry (material transfer) on a submitted SCO
- [ ] Option to create Subcontracting Receipt

**Material Transfer**

- [ ] Create from submitted SCO
- [ ] Independently create Stock Entry and provide a reference for SCO
- [ ] Fetch all the RMs and the quantity
- [ ] Provide From and To warehouse information
- [ ] Transfer partially or full quantity
- [ ] Transfer additional material
- [ ] Update status of SCO basis of the material transferred.
- [ ] Eway bill for transfer?

**Subcontracting Receipt (SCR)**

- [ ] Create from SCO
- [ ] Create independently and provide a reference for SCO (fetch all information)
- [ ] Perform quality inspection (settings could be configured)
- [ ] Partially receive -update SCO status
- [ ] Complete receipt - update SCO status
- [ ] Create return basis the quality inspection - update SCO status
- [ ] Stock update

**Create Purchase Receipt**

- [ ] From PO or SCO or independently by providing the reference for the PO
- [ ] Update PO status.

2022-06-14 07:13 UTC, nabinhait requested changes

2022-06-14 07:13 UTC, nabinhait commented on erpnext/buying/doctype/purchase_order/purchase_order.py
> +						)
```suggestion
						_("Row #{0}: Finished Good Item is not specified for service item {1}").format(
							 item.idx, item.item_code
						)
```

2022-06-14 07:13 UTC, nabinhait commented on erpnext/buying/doctype/purchase_order/purchase_order.py
> +						)
Use this pattern to mention row in all messages

2022-06-14 14:07 UTC, s-aga-r commented
Failing checks are not related #[4061143](https://github.com/frappe/erpnext/pull/30955/commits/406114374bbee4831df5fdaa3a49d8980e703d86)

2022-06-30 07:02 UTC, s-aga-r commented
Will fix **TEST 2** #[e4b1d6f](https://github.com/frappe/erpnext/pull/30955/commits/e4b1d6f0cb0f274b1d493bf69586d6029e5ea498)

2022-07-01 10:43 UTC, rohitwaghchaure commented
@s-aga-r 
Done with the testing, everything is working fine. Just found few minor issues which are as follows

1) If purchase receipt created against purchase order with new flow then system throws an error "Supplier Warehouse" is mandatory. This field should be mandatory only if the purchase receipt made against the old flow purchase order

2) Created Purchase Order (new flow) for 4 quantity and then created subcontracting order from purchase order. System has pulled items details from purchase order with quantity as 1. Ideally quantity should be 4, even system was not allowing to edit the quantity from 1 to 4.

3) I can able to create n number of Subcontracting Purchase Orders against the main purchase order. The button "Create Subcontracting Order" should be hidden after creating of Subcontracting Purchase Orders

2022-07-01 11:03 UTC, s-aga-r commented
> For the 2nd issue

There are two cases:

1. When Service Item Qty and FG Item Qty are different.

https://user-images.githubusercontent.com/63660334/176882414-ab34af36-f3d8-418f-9e43-e1d4b31042b0.mov

2. When Service Item Qty and FG Item Qty are equal. 

https://user-images.githubusercontent.com/63660334/176882431-1421cca9-8daf-404f-97fd-cd3db66d138c.mov

2022-07-01 11:06 UTC, rohitwaghchaure commented
@s-aga-r 

While checking valuation I found one issue that the rate is different in Subcontracting PO, PR

Subcontracting PO :- Rate was set as 1000
<img width="1317" alt="Screenshot 2022-07-01 at 4 31 23 PM" src="https://user-images.githubusercontent.com/8780500/176882568-8121f6d6-3261-4221-8ba0-34dbf9f1b5d1.png">

Stock Transfer :- Rate was 1000
<img width="1305" alt="Screenshot 2022-07-01 at 4 32 25 PM" src="https://user-images.githubusercontent.com/8780500/176882627-2c83821a-8343-43a7-93ec-b74baf4ca5df.png">

Subcontracting PR :-  Rate set to 640, 
<img width="1335" alt="Screenshot 2022-07-01 at 4 32 03 PM" src="https://user-images.githubusercontent.com/8780500/176882682-fa97cd9a-0c5e-4c1b-b534-46b0e0c94827.png">

If rate we are calculating as per FIFO then rate should be 400 (2*100 + 1000 = 1200 / 3) and not 640
Before subcontracting PR the Stock Queue was "[[2.0, 100.0], [3.0, 1000.0]]"
<img width="1040" alt="Screenshot 2022-07-01 at 4 35 42 PM" src="https://user-images.githubusercontent.com/8780500/176882956-89d6f9dc-4b24-41f7-a1bd-1bc38ad5a231.png">

2022-07-01 11:13 UTC, rohitwaghchaure commented
> > For the 2nd issue
> 
> There are two cases:
> 
> 1. When Service Item Qty and FG Item Qty are different.
> 
>  Screen.Recording.2022-07-01.at.4.29.11.PM.mov 
> 2. When Service Item Qty and FG Item Qty are equal.
> 
>  Screen.Recording.2022-07-01.at.4.30.03.PM.mov

@s-aga-r Ok Understood
can we not set default qty as 1 and let user manually set the "Finished Good Item Qty"? or on change of Qty field can we set same qty to "Finished Good Item Qty" field? if user wants to change then they will change it manually.

2022-07-01 13:54 UTC, s-aga-r commented
> > > For the 2nd issue
> > 
> > 
> > There are two cases:
> > 
> > 1. When Service Item Qty and FG Item Qty are different.
> > 
> > Screen.Recording.2022-07-01.at.4.29.11.PM.mov
> > 2. When Service Item Qty and FG Item Qty are equal.
> > Screen.Recording.2022-07-01.at.4.30.03.PM.mov
> 
> @s-aga-r Ok Understood can we not set default qty as 1 and let user manually set the "Finished Good Item Qty"? or on change of Qty field can we set same qty to "Finished Good Item Qty" field? if user wants to change then they will change it manually.

Both Qty and FG Item Qty are by default 1.

https://user-images.githubusercontent.com/63660334/176908324-29d06336-2710-47ff-9a9f-aa1970419667.mov

2022-07-08 09:51 UTC, merged