fix: filters - added date filter on get_price()
frappe/erpnext pull request #31040
Opened 2022-05-16 16:56 UTC by SherinKR

> Please provide enough information so that others can review your pull request:
    
    Added date filter on get_price() with current date

> Explain the **details** for making this change. What existing problem does the pull request solve?

   Currently in erpnext.utilities.product.get_price() , It doesn't check with any kind of date validation or filters. Added Current Date filter and applied with Item Price Validity.

> Screenshots/GIFs

 Reference Issue : #29806

2022-05-17 05:41 UTC, ankush requested changes

2022-05-17 05:41 UTC, ankush commented on erpnext/utilities/product.py
> +				["valid_upto", ">=", frappe.utils.nowdate()],
This is probably incorrect. 

valid_from and valid_upto both can be empty in which case it means "no limit"

2022-05-17 06:29 UTC, ankush commented on erpnext/utilities/product.py
> +				["valid_upto", ">=", frappe.utils.nowdate()],
@SherinKR why was this comment marked resolved?

2022-05-25 14:00 UTC, deepeshgarg007 commented
Closing this PR because of no response, please reopen again when issues are resolved

2022-05-25 14:00 UTC, closed without merging