fix: change project's actual_start_date fieldtype from Data to Date
frappe/erpnext pull request #31085
Opened 2022-05-21 16:14 UTC by sersaber

I have noticed that project's “actual_start_date” is not shown with the same format that other start/end dates in some reports. See image below.

![project_report](https://user-images.githubusercontent.com/93864988/169659387-bcbf5777-a173-4a19-9ff2-3f4b6d3da7a4.png)

This is because the field actual_start_date is defined as "Data" instead of "Date" in the doctype. I have looked through the code and the fields actual_start_date and actual_end_date are managed in the same way, but actual_end_date is defined as "Date" while actual_start_date is defined as "Data". I think this could be a typo.

2022-05-23 05:25 UTC, ruchamahabal requested changes
@sersaber You also need to update the `modified` timestamp to sync the changes on migrate.

2022-05-25 20:50 UTC, sersaber commented
I think I have made the change suggested by @[ruchamahabal](https://github.com/ruchamahabal), but I'm not sure if it's correct.

2022-05-26 04:34 UTC, ruchamahabal approved these changes

2022-05-26 04:34 UTC, merged

2022-05-26 04:39 UTC, ruchamahabal commented
@sersaber A note for future contributions: Commit messages must follow the conventional commit specifications:
https://www.conventionalcommits.org/en/v1.0.0-beta.2/

2022-05-26 05:09 UTC, ankush commented
This will likely require a patch in case some bad data is present in this column that can't be converted.

2022-05-26 05:17 UTC, ruchamahabal commented
> This will likely require a patch in case some bad data is present in this column that can't be converted.

This field is read-only and is set from timesheets, so only dates would be present in it. No open-ended data