fix: consider from date in SLE query
frappe/erpnext pull request #31925
Opened 2022-08-22 12:33 UTC by rtdany10

In cases where from date isn't provided, the system throws error, but it doesn't apply the from date in the query if provided.

2022-08-23 04:08 UTC, rtdany10 commented
@s-aga-r please check

2022-08-23 04:46 UTC, s-aga-r approved these changes

2022-08-23 04:51 UTC, s-aga-r commented
> @s-aga-r please check

@rtdany10 Add a test case for the same.

2022-08-23 04:52 UTC, s-aga-r requested changes
Add a test case for the same.

2022-08-23 13:00 UTC, rtdany10 commented
@s-aga-r I'm not sure why the existing test case is failing. Any pointers?

2022-08-24 07:46 UTC, s-aga-r commented
> @s-aga-r I'm not sure why the existing test case is failing. Any pointers?

@rtdany10 not sure, but it can be because tests have from_filter and now it's applying in the query?

2022-08-26 05:20 UTC, rtdany10 commented
> > @s-aga-r I'm not sure why the existing test case is failing. Any pointers?
> 
> @rtdany10 not sure, but it can be because tests have from_filter and now it's applying in the query?

@s-aga-r  I'm not sure, cause there are no hard-coded values, comparison occurs between SLE values and report values. I'll try digging deeper.

2022-09-01 05:36 UTC, s-aga-r commented
> > > @s-aga-r I'm not sure why the existing test case is failing. Any pointers?
> > 
> > 
> > @rtdany10 not sure, but it can be because tests have from_filter and now it's applying in the query?
> 
> @s-aga-r I'm not sure, cause there are no hard-coded values, comparison occurs between SLE values and report values. I'll try digging deeper.

Hi, @rtdany10 any update on this? Got a Support Ticket related to this.

2022-09-01 12:26 UTC, ankush requested changes

2022-09-01 12:26 UTC, ankush commented on erpnext/stock/report/stock_balance/test_stock_balance.py
> +					where posting_date >= %s and posting_date <= %s and is_cancelled=0
Never modify test code to them like this! It is encoding a known supported business use case. 😅

2022-09-01 12:26 UTC, ankush commented on erpnext/stock/report/stock_balance/stock_balance.py
> +		query = query.where(sle.posting_date >= from_date)
This is incorrect. Stock balance report has to fetch all SLEs, the from date is only used for computing opening qty. 

This is somewhat inefficient but that's how it's correctly implemented.

2022-09-01 12:27 UTC, ankush commented on erpnext/stock/report/stock_balance/stock_balance.py
> +		query = query.where(sle.posting_date >= from_date)
@s-aga-r

2022-09-01 12:27 UTC, ankush commented on erpnext/stock/report/stock_balance/stock_balance.py
> +		query = query.where(sle.posting_date >= from_date)
also refer https://github.com/frappe/erpnext/issues/29183

2022-09-01 12:27 UTC, closed without merging