fix: gl entries for asset repair
frappe/erpnext pull request #31943
Opened 2022-08-24 07:03 UTC by nabinhait

**Multiple fixes related to GL Entries for Asset Repair**

- GL Entry in case of periodical inventory system
- GL entry if the repair cost is zero
- Removed the unused "Repair and Maintenance Account" field from Company
- Removed stock entry reference on cancellation
- Added tests for the gl entries

2022-08-24 07:04 UTC, nabinhait commented
@Mergifyio backport version-14-hotfix

2022-08-24 13:29 UTC, shwetankdeshmukh commented
What about the conditions match for [ERP Software](https://www.osplabs.com/healthcare-cloud-solutions/)?

2022-08-25 06:40 UTC, deepeshgarg007 requested changes

2022-08-25 06:40 UTC, deepeshgarg007 commented on erpnext/assets/doctype/asset_repair/asset_repair.py
> +							"against": item.expense_account,
```suggestion
							"against": item.expense_account or default_expense_account,
```

2022-08-25 06:41 UTC, deepeshgarg007 commented
@Mergifyio backport version-14-hotfix

2022-08-25 07:54 UTC, deepeshgarg007 commented
@ergifyio backport version-14-hotfix version-13-hotfix

2022-08-25 07:54 UTC, merged