fix: upgrade process to version-14 when currency opportunity wass not set
frappe/erpnext pull request #31982
Opened 2022-08-25 18:48 UTC by FHenry

I encounter Opportunity without currency on customer erpnext instance, It make the upgrade crash

2022-08-25 20:40 UTC, FHenry commented
patch test will failed until https://github.com/frappe/frappe/pull/17959 will be merge

2022-08-30 05:01 UTC, deepeshgarg007 commented
@FHenry Can you update the error(Traceback) in the description as well?

2022-08-30 06:24 UTC, FHenry commented
> @FHenry Can you update the error(Traceback) in the description as well?

@deepeshgarg007 Hello, done.

2022-09-02 20:01 UTC, FHenry commented
@deepeshgarg007 I agree that it should not happen, because if you set an amount on opportunity, the currency come with since last version-12, but this record come from early version-12 upgraded to version-13 a year ago. 
If I got this problem, I will not be the only one, seems to be harmless to make it more secure for all case, even the one that should not happen

2022-09-04 13:32 UTC, deepeshgarg007 requested changes

2022-09-04 13:32 UTC, deepeshgarg007 commented on erpnext/patches/v14_0/update_opportunity_currency_fields.py
> +				f' Opportunity `{opportunity.name}` has no currency set. We force it to company currency : `{opportunity.currency}`"\n',
```suggestion
				f' Opportunity `{opportunity.name}` has no currency set. Setting it to company currency as default: `{opportunity.currency}`"\n',
```

2022-09-04 13:33 UTC, deepeshgarg007 commented
@Mergifyio backport version-14-hotfix

2022-09-04 13:33 UTC, merged