fix: Incoming rate precision fixes for intra company transfer
frappe/erpnext pull request #32272
Opened 2022-09-19 10:54 UTC by deepeshgarg007

2022-09-20 09:15 UTC, nabinhait approved these changes, later dismissed

2022-10-11 09:40 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-hotfix version-14-hotfix

2022-10-11 11:15 UTC, nabinhait requested changes

2022-10-11 11:15 UTC, nabinhait commented on erpnext/controllers/stock_controller.py
> +			if abs(sle_rounding_diff) > 0.1 and (
Instead of a hardcoded value (0.1), you can use a value based on the precision of the debit/credit field of GLE.
Ref: https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/general_ledger.py#L402

2022-10-11 11:15 UTC, nabinhait commented on erpnext/accounts/doctype/sales_invoice_item/sales_invoice_item.json
> +   "precision": "6",
The same should be done for DN and also in PR/PI for the valuation_rate field.

2022-10-11 11:15 UTC, nabinhait commented on erpnext/controllers/stock_controller.py
> +				gl_list.append(
We need a discussion on GLE

2022-10-12 10:53 UTC, merged