fix: pricing rule item_code UOM apply & conversions
frappe/erpnext pull request #32566
Opened 2022-10-11 10:38 UTC by maharshivpatel

there were multiple issues with pricing rule's apply_on_field ==  "item_code" ( UOM : blank, other_than_stock_uom etc ). I have added required checks and proper conversions.

### Before:
https://user-images.githubusercontent.com/39730881/195068408-1a3a2d4a-7aca-4b3e-8c54-397dd471ba68.mov

### After:
https://user-images.githubusercontent.com/39730881/195068483-ec7e121d-6ddc-4dd4-a9dd-6a3c71de0a83.mov

2022-10-12 09:16 UTC, deepeshgarg007 requested changes
Also need a test case for this, please add that too

2022-10-12 09:16 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/pricing_rule/pricing_rule.py
> -					"price_list_rate": pricing_rule_rate * args.get("conversion_factor", 1),
So the conversion factor coming from the args should be the `rule_conversion_factor` itself. Why this is not coming investigating and fixing that would be a proper fix

2022-10-12 09:16 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/pricing_rule/utils.py
> +				)
What this exactly does I am not able to understand, please explain this as well

2022-10-18 16:55 UTC, deepeshgarg007 commented
@Mergifyio backport version-13-hotfix version-14-hotfix

2022-10-18 16:56 UTC, merged

2022-10-26 08:55 UTC, sjain17 commented
Thank you for fixing this bug; however, it is still not considering the max qty limitations.