fix: Curreny in SOA print for multi-currency party
frappe/erpnext pull request #32699
Opened 2022-10-24 12:05 UTC by deepeshgarg007

Fixes: https://github.com/frappe/erpnext/issues/32400

2022-10-24 12:05 UTC, deepeshgarg007 commented
@Mergifyio backport version-14-hotfix

2022-10-24 13:20 UTC, maharshivpatel requested changes
We also need to consider when user selects currency from the filter.

2022-10-24 13:20 UTC, maharshivpatel commented on erpnext/accounts/report/general_ledger/general_ledger.html
> +						{%= format_currency(data[i].debit, data[i].account_currency) %}</td>
```suggestion
						{%= format_currency(data[i].debit, filters.presentation_currency || data[i].account_currency) %}</td>
```

2022-10-24 13:20 UTC, maharshivpatel commented on erpnext/accounts/report/general_ledger/general_ledger.html
> +						{%= format_currency(data[i].credit, data[i].account_currency) %}</td>
```suggestion
						{%= format_currency(data[i].credit, filters.presentation_currency || data[i].account_currency) %}</td>
```

2022-10-24 13:20 UTC, maharshivpatel commented on erpnext/accounts/report/general_ledger/general_ledger.html
> +					{%= data[i].account && format_currency(data[i].debit, data[i].account_currency) %}
```suggestion
					{%= data[i].account && format_currency(data[i].debit, filters.presentation_currency || data[i].account_currency) %}
```

2022-10-24 13:20 UTC, maharshivpatel commented on erpnext/accounts/report/general_ledger/general_ledger.html
> +					{%= data[i].account && format_currency(data[i].credit, data[i].account_currency) %}
```suggestion
					{%= data[i].account && format_currency(data[i].credit, filters.presentation_currency || data[i].account_currency) %}
```

2022-10-24 13:20 UTC, maharshivpatel commented on erpnext/accounts/report/general_ledger/general_ledger.html
> +					{%= format_currency(data[i].balance, data[i].account_currency) %}
```suggestion
					{%= format_currency(data[i].balance, filters.presentation_currency || data[i].account_currency) %}
```

2022-10-28 15:11 UTC, deepeshgarg007 commented
@Mergifyio backport version-14-hotfix

2022-10-28 15:11 UTC, merged