fix: Scan Barcode UX
frappe/erpnext pull request #32799
Opened 2022-11-01 13:02 UTC by rohitwaghchaure

2022-11-02 15:45 UTC, dj12djdjs requested changes

2022-11-02 15:45 UTC, dj12djdjs commented on erpnext/public/js/utils/barcode_scanner.js
> +					debugger
remove break point
```suggestion
```

2022-11-02 15:45 UTC, dj12djdjs commented on erpnext/public/js/utils/barcode_scanner.js
> +		const {item_code, barcode, batch_no, serial_no, uom} = r.message;
`uom` isn't being used in this scope?

2022-11-02 15:50 UTC, dj12djdjs commented
I like your approach for this. There is one thing I think needs to be validated. If the user is scanning into the purchase receipt, if there are any items missing from the scan. The user should be notified instead of just posting to stock. Example:


![pr-scan-missing-qty](https://user-images.githubusercontent.com/29856401/199537298-349f3364-be6a-4e57-9bfd-bd652510f7aa.gif)


```patch
diff --git a/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py b/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
index f85c478..1da4c2f 100644
--- a/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
+++ b/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
@@ -5,6 +5,7 @@
 import frappe
 from frappe import _, throw
 from frappe.desk.notifications import clear_doctype_notifications
+from frappe.model.docstatus import DocStatus
 from frappe.model.mapper import get_mapped_doc
 from frappe.utils import cint, flt, getdate, nowdate
 
@@ -117,6 +118,7 @@ class PurchaseReceipt(BuyingController):
 		self.validate_uom_is_integer("stock_uom", "stock_qty")
 		self.validate_cwip_accounts()
 		self.validate_provisional_expense_account()
+		self.validate_scanned_qty()
 
 		self.check_on_hold_or_closed_status()
 
@@ -128,6 +130,21 @@ class PurchaseReceipt(BuyingController):
 		self.reset_default_field_value("rejected_warehouse", "items", "rejected_warehouse")
 		self.reset_default_field_value("set_from_warehouse", "items", "from_warehouse")
 
+	def validate_scanned_qty(self):
+		if self.docstatus == DocStatus.submitted():
+			raise_error = False
+			if any([d.has_item_scanned for d in self.items]):
+				for item in self.items:
+					if not item.has_item_scanned:
+						raise_error = True
+						frappe.msgprint(
+							_("Row {0}: {1} hasn't been scanned.").format(item.idx, item.item_code),
+							_("Item(s) not Scanned"),
+							indicator="red",
+						)
+			if raise_error:
+				raise frappe.ValidationError
+
 	def validate_cwip_accounts(self):
 		for item in self.get("items"):
 			if item.is_fixed_asset and is_cwip_accounting_enabled(item.asset_category):
```

2022-11-03 09:30 UTC, rohitwaghchaure commented on erpnext/public/js/utils/barcode_scanner.js
> +					debugger
Fixed

2022-11-03 09:31 UTC, rohitwaghchaure commented on erpnext/public/js/utils/barcode_scanner.js
> +		const {item_code, barcode, batch_no, serial_no, uom} = r.message;
Fixed

2022-11-03 09:32 UTC, rohitwaghchaure commented
> I like your approach for this. There is one thing I think needs to be validated. If the user is scanning into the purchase receipt, if there are any items missing from the scan. The user should be notified instead of just posting to stock. Example:
> 
> ![pr-scan-missing-qty](https://user-images.githubusercontent.com/29856401/199537298-349f3364-be6a-4e57-9bfd-bd652510f7aa.gif) [ ![pr-scan-missing-qty](https://user-images.githubusercontent.com/29856401/199537298-349f3364-be6a-4e57-9bfd-bd652510f7aa.gif) ](https://user-images.githubusercontent.com/29856401/199537298-349f3364-be6a-4e57-9bfd-bd652510f7aa.gif) [ ](https://user-images.githubusercontent.com/29856401/199537298-349f3364-be6a-4e57-9bfd-bd652510f7aa.gif)
> 
> ```diff
> diff --git a/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py b/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> index f85c478..1da4c2f 100644
> --- a/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> +++ b/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py
> @@ -5,6 +5,7 @@
>  import frappe
>  from frappe import _, throw
>  from frappe.desk.notifications import clear_doctype_notifications
> +from frappe.model.docstatus import DocStatus
>  from frappe.model.mapper import get_mapped_doc
>  from frappe.utils import cint, flt, getdate, nowdate
>  
> @@ -117,6 +118,7 @@ class PurchaseReceipt(BuyingController):
>  		self.validate_uom_is_integer("stock_uom", "stock_qty")
>  		self.validate_cwip_accounts()
>  		self.validate_provisional_expense_account()
> +		self.validate_scanned_qty()
>  
>  		self.check_on_hold_or_closed_status()
>  
> @@ -128,6 +130,21 @@ class PurchaseReceipt(BuyingController):
>  		self.reset_default_field_value("rejected_warehouse", "items", "rejected_warehouse")
>  		self.reset_default_field_value("set_from_warehouse", "items", "from_warehouse")
>  
> +	def validate_scanned_qty(self):
> +		if self.docstatus == DocStatus.submitted():
> +			raise_error = False
> +			if any([d.has_item_scanned for d in self.items]):
> +				for item in self.items:
> +					if not item.has_item_scanned:
> +						raise_error = True
> +						frappe.msgprint(
> +							_("Row {0}: {1} hasn't been scanned.").format(item.idx, item.item_code),
> +							_("Item(s) not Scanned"),
> +							indicator="red",
> +						)
> +			if raise_error:
> +				raise frappe.ValidationError
> +
>  	def validate_cwip_accounts(self):
>  		for item in self.get("items"):
>  			if item.is_fixed_asset and is_cwip_accounting_enabled(item.asset_category):
> ```


This no need to put in the core.. can be achieve using Server Script / Client Script

2022-11-03 13:45 UTC, dj12djdjs commented
> This no need to put in the core.. can be achieve using Server Script / Client Script

@rohitwaghchaure Sounds good. I tested this PR. This is a very nice improvement to barcode scanning flow!

2022-11-04 05:33 UTC, rohitwaghchaure commented
> > This no need to put in the core.. can be achieve using Server Script / Client Script
> 
> @rohitwaghchaure Sounds good. I tested this PR. This is a very nice improvement to barcode scanning flow!

Thanks a lot for giving your valuable feedback.

2022-11-04 05:34 UTC, merged

2022-11-10 14:29 UTC, TurkerTunali commented
I think that, this feature should have an "Enabled" check in the Stock Settings.