fix: Internal Transfer Material Request cycle and tracking fixed till purchase receipt
frappe/erpnext pull request #32905
Opened 2022-11-09 07:28 UTC by vishdha

Problem statement:
1. User create Material Request -> Purchase Order. Material Request status get updated (Ordered)
2. Purchase Order (Internal)-> Sales Order(Internal) -> Delivery Note(Internal) -> Purchase Receipt
3. Purchase Receipt get submitted still Material Request status remain same (Ordered) Instead it should be Received
4. This fixed added link of material request and status get updated of MR(Received) once PR submitted 

https://user-images.githubusercontent.com/6947417/200765870-63e7340d-942c-4bcd-876b-195d7f53ec29.mp4

2022-11-09 08:59 UTC, vishdha commented
@deepeshgarg007 @rohitwaghchaure  Please review and backport to V14 and v13

2022-11-11 08:09 UTC, vishdha commented
@sagarvora @rohitwaghchaure @deepeshgarg007 Can you review this.

2022-11-14 07:51 UTC, s-aga-r requested changes
@vishdha Could you add a test case for the same?

2022-11-15 12:14 UTC, vishdha commented
@s-aga-r Test case added for same

2022-11-15 16:46 UTC, s-aga-r commented
> @s-aga-r Test case added for same

@vishdha Test is failing, please fix it.

2022-11-16 10:16 UTC, vishdha commented
> 

@s-aga-r Please review and merge this its import to merge in version-14

2022-11-18 06:26 UTC, s-aga-r approved these changes

2022-11-18 06:26 UTC, s-aga-r commented on erpnext/selling/doctype/sales_order_item/sales_order_item.json
> +  },
@vishdha Don't edit the DocType JSON file manually.

2022-11-18 07:45 UTC, merged