refactor(region): Splitting of KSA(Saudi Arabia) Region from ERPNext.
frappe/erpnext pull request #33770
Opened 2023-01-21 11:45 UTC by sankarsubramaniankvs

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

2023-01-22 13:54 UTC, rtdany10 commented
@sankarsubramaniankvs are you guys working on phase 2 of KSA e-Invoicing?

2023-01-22 14:05 UTC, sankarsubramaniankvs commented
Yes. We are working on cleartax integration for KSA region.

2023-01-25 09:05 UTC, deepeshgarg007 requested changes
No git history is being transferred right now on the repo https://github.com/8848digital/KSA
Please follow https://github.com/frappe/erpnext/wiki/Guide-to-splitting-modules-from-ERPNext

2023-01-25 09:05 UTC, deepeshgarg007 commented on erpnext/patches/v13_0/disable_ksa_print_format_for_others.py
> +from ksa.install import add_print_formats
All the patches should also be moved to the custom app, there should be no dependency on any other app

2023-01-25 09:05 UTC, deepeshgarg007 commented on erpnext/setup/setup_wizard/operations/taxes_setup.py
> +			if frappe.scrub(country) == 'saudi_arabia':
This validation is not needed

2023-01-27 06:58 UTC, closed without merging