fix: get value_after_depreciation functions and manual depr entry not updating asset value
frappe/erpnext pull request #33788
Opened 2023-01-23 07:45 UTC by AnandBaburajan

1. There were a lot of functions which (sometimes incorrectly) fetched the asset's current value after depreciation, so refactored all of them to use one function.
2. When manual depreciation entries (created using the `Create Depreciation Entry` option in the `Manage` dropdown of assets with `calculate_depreciation` not checked) are submitted, the value of the asset isn't updated, so fixed that.

2023-01-30 12:27 UTC, deepeshgarg007 requested changes

2023-01-30 12:27 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/journal_entry/journal_entry.py
> +				asset = frappe.get_doc("Asset", d.reference_name)
Use `get_value` instead of `get_doc`

2023-01-30 23:54 UTC, barredterra commented
Is there a corresponding PR that implements these changes on the develop branch?

2023-01-31 03:20 UTC, AnandBaburajan commented
@barredterra not yet, I've to think more about some things. I'll open a PR in a day or two.

2023-01-31 05:29 UTC, merged

2023-01-31 11:43 UTC, barredterra commented
@AnandBaburajan isn't the correct procedure to send PRs to develop, then (partially) backport them? This way we can avoid features going missing with an upgrade. For example, if somebody upgrades to develop right now, your features will not be there.

2023-01-31 12:16 UTC, AnandBaburajan commented
> @AnandBaburajan isn't the correct procedure to send PRs to develop, then (partially) backport them?

Yep, but like I said, I've to think more about some of those features/fixes (there might be some design changes) which would go into develop and fixing bugs in v13 and v14 was the first priority so opened this PR.

2023-01-31 12:55 UTC, barredterra commented
Understood. IMHO it doesn't make sense to solve a bug in a lower version and "maybe sometime" (to exaggerate) in the `develop` branch. This has lead to problems in the past and will continue to do so, unless we follow the proper process.