refactor(region): Splitting of KSA(Saudi Arabia) Region from ERPNext
frappe/erpnext pull request #33895
Opened 2023-01-31 06:25 UTC by sankarsubramaniankvs

This Pull Request Will remove the code related to Saudi Arabia Region from ERPNext. It will come in a separate app that will be published in the frappe marketplace and will be used only by companies that need KSA Compliance. The idea behind it is to remove code unnecessary for a user. ERPNext should only have a generic code that can be used by everyone.

2023-02-12 16:21 UTC, deepeshgarg007 requested changes
Add a depreciation warning on version-14 like https://github.com/frappe/erpnext/pull/30861/files

Add a patch to delete doctypes from old modules https://github.com/frappe/erpnext/pull/30830/files#diff-bdbb775d3a1469cacdfc456d9abbc26cc35c72fdeeeb96d6db481d3856a11abaR1

2023-02-12 16:21 UTC, deepeshgarg007 commented on erpnext/hooks.py
> -			"erpnext.regional.saudi_arabia.utils.create_qr_code",
Din't find this in the new app

2023-02-12 16:21 UTC, deepeshgarg007 commented on erpnext/hooks.py
> -			"erpnext.regional.italy.utils.sales_invoice_on_cancel",
Din't find this in the new app

2023-02-12 16:21 UTC, deepeshgarg007 commented on erpnext/hooks.py
> -			"erpnext.regional.saudi_arabia.utils.delete_qr_code_file",
Din't find this in the new app

2023-02-12 16:21 UTC, deepeshgarg007 commented on erpnext/hooks.py
> -	"POS Invoice": {"on_submit": ["erpnext.regional.saudi_arabia.utils.create_qr_code"]},
Din't find this in the new app

2023-02-17 01:46 UTC, sankarsubramaniankvs commented
> erpnext

I have added the patches

2023-02-17 01:47 UTC, sankarsubramaniankvs commented on erpnext/hooks.py
> -			"erpnext.regional.saudi_arabia.utils.create_qr_code",
Have added all required hooks to the new app

2023-02-17 01:47 UTC, sankarsubramaniankvs commented on erpnext/hooks.py
> -			"erpnext.regional.italy.utils.sales_invoice_on_cancel",
Have added all required hooks to the new app

2023-02-17 01:47 UTC, sankarsubramaniankvs commented on erpnext/hooks.py
> -			"erpnext.regional.saudi_arabia.utils.delete_qr_code_file",
Have added all required hooks to the new app

2023-02-17 01:48 UTC, sankarsubramaniankvs commented on erpnext/hooks.py
> -	"POS Invoice": {"on_submit": ["erpnext.regional.saudi_arabia.utils.create_qr_code"]},
Have added all required hooks to the new app

2023-02-19 08:05 UTC, deepeshgarg007 requested changes

2023-02-19 08:05 UTC, deepeshgarg007 commented on erpnext/patches/v15_0/saudi_depreciation_warning.py
> +		"When upgrading to ERPNext version-15, please install the app to continue using the Education domain: https://github.com/8848digital/KSA",
```suggestion
		"When upgrading to ERPNext version-15, please install the app to continue using the KSA VAT features: https://github.com/8848digital/KSA",
```

2023-02-19 08:05 UTC, deepeshgarg007 commented on erpnext/patches/v15_0/saudi_depreciation_warning.py
> +		"Saudi Arabia Region is moved to a separate app and will be removed from ERPNext in version-15.\n"
```suggestion
		"Regional features for KSA are moved to a separate app and will be removed from ERPNext in version-15.\n"
```

2023-02-19 08:07 UTC, deepeshgarg007 commented
2 checks also failing, please fix them

2023-02-21 17:22 UTC, merged

2023-03-03 02:03 UTC, barredterra commented
@sankarsubramaniankvs you forgot to clean up the accounting workspace:

https://github.com/frappe/erpnext/blob/c3d455653e717b539a6fc567fcd8ddbdbf5c717f/erpnext/accounts/workspace/accounting/accounting.json#L519-L530

https://github.com/frappe/erpnext/blob/c3d455653e717b539a6fc567fcd8ddbdbf5c717f/erpnext/accounts/workspace/accounting/accounting.json#L1032-L1042

2023-03-06 05:32 UTC, sankarsubramaniankvs commented
> 

Hi @barredterra. Thanks for bringing this to my notice. will check this out