fix: should never get cutomer price on purchase document
frappe/erpnext pull request #34002
Opened 2023-02-10 14:40 UTC by FHenry

In some case in Purchase Order the field Customer is set with the customer coming from Material Request or erpnext/erpnext/stock/doctype/material_request/material_request.make_purchase_order_based_on_supplier, and in this case the get_item_detail and in fine get_item_price 
	if args.get("customer"):
			conditions += " and customer=%(customer)s"
        elif args.get("supplier"):
	        conditions += " and supplier=%(supplier)s"

Then customer win... on Purchase document this is a non sense

2023-02-10 15:10 UTC, s-aga-r requested changes

2023-02-10 15:10 UTC, s-aga-r commented on erpnext/stock/get_item_details.py
> +	):
Use `in` keyword to check the doctype:

`if (args.get("doctype") in ["Purchase Order", "Purchase Receipt", "Purchase Invoice"]):`

2023-02-11 06:56 UTC, deepeshgarg007 commented
@FHenry Can you please add a test case for this scenario as well so that such an issue is not repeated again

2023-02-12 08:19 UTC, FHenry commented
> @FHenry Can you please add a test case for this scenario as well so that such an issue is not repeated again

@deepeshgarg007 Ok, I'm on it

2023-02-12 13:23 UTC, FHenry commented
> @FHenry Can you please add a test case for this scenario as well so that such an issue is not repeated again

@deepeshgarg007 ok test is done

2023-02-13 15:26 UTC, merged

2023-02-13 20:20 UTC, FHenry commented
@Mergifyio backport version-13-hotfix

2023-02-13 20:20 UTC, FHenry commented
@Mergifyio backport version-14-hotfix

2023-02-13 20:22 UTC, FHenry commented
@deepeshgarg007, @s-aga-r 
 Is it possible to add backport label it to  version-13-hotfix and version-14-hotfix or the process is make other PRs ?