feat: Closing balance for period closing and reporting
frappe/erpnext pull request #34257
Opened 2023-03-01 09:19 UTC by deepeshgarg007

2023-03-22 12:32 UTC, nabinhait requested changes

2023-03-22 12:32 UTC, nabinhait commented on erpnext/accounts/general_ledger.py
> +		message += _("You cannot create any new accounting entries till this date.")
```suggestion
		message += _("You cannot create/amend any accounting entries till this date.")
```

2023-03-24 06:28 UTC, nabinhait approved these changes

2023-03-24 06:29 UTC, merged

2023-12-01 11:43 UTC, JitendraSAW commented
@deepeshgarg007 , Can you help us as we can check this Use Case, Can you provide any List of Transactions or Flow we can check the same.