feat: Making Quotation Templates possible
frappe/erpnext pull request #34371
Opened 2023-03-09 06:25 UTC by intellimomentum

In the Quotation form, the button "Get Items From", let you only import items from opportunities.
This feature makes it possible to import pre-defined items from so called "Quotation Templates":

![image](https://user-images.githubusercontent.com/120707986/223937345-16b03384-2fdd-419f-968d-60feeff683aa.png)

![image](https://user-images.githubusercontent.com/120707986/223938144-cb589e8c-329d-453f-bb2c-5ef76a1c3f95.png)

![image](https://user-images.githubusercontent.com/120707986/223938362-0d74465f-04f2-466e-8551-bc14ca70c1cb.png)

2023-03-10 08:01 UTC, intellimomentum commented
Any questions about the feature?
It works very well in our company and increases the quotation creation speed massively!

2023-03-11 05:35 UTC, dj12djdjs commented
I think this is pretty useful.

Just wondering, could the same thing be dome with the existing Product Bundle functionality?

2023-03-13 11:59 UTC, intellimomentum commented
Hello,

In many aspects, the functionality is similar.
However, there are a few significant differences:
- Product Bundles behave like a fixed configured product, it is not
possible to change the number of a product in the product bundle.
- You don't always want to group the individual products. Offers for PV
installations are a good example of this. Basically all customers need the
same products for which a few simple quote templates can be created: Solar
panels, cables, inverters, electrical installation ... However, there are
always differences in the number of panels (to give just one example).
- Product Bundles are a single product from the viewpoint of a customer.
(One price, just included items but not individually listed with a price
and position in a quotation)

Hope this helps

Yours sincerely
Bernhard Hein


Am Sa., 11. März 2023 um 06:35 Uhr schrieb Devin Slauenwhite <
***@***.***>:

> I think this is pretty useful.
>
> Just wondering, could the same thing be dome with the existing Product
> Bundle functionality?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/frappe/erpnext/pull/34371#issuecomment-1464832698>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4Y5XEUHBCIKHKJUVL5Q6STW3QFKJANCNFSM6AAAAAAVUVKB7A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-19 14:58 UTC, barredterra requested changes
Please format your code with prettier (use tabs) and remove useless comments like "Again, the Doctype we want to pick up". This will likely increase the chances of someone reviewing this. For details, please check the [contribution guidelines](https://github.com/frappe/erpnext/wiki/Contribution-Guidelines).

And maybe we can get a comment from @deepeshgarg007, if he's open for a feature like this.

2023-04-19 14:58 UTC, barredterra commented on erpnext/selling/doctype/quotation/quotation.js
> +					  }
```suggestion
					for (field of ['item_code', 'qty']) {
						let row = frm.get_field("items").grid.grid_rows[items_idx + 1];
						row.doc[field] = item[field];
						row.refresh_field(field);
					}
```

2023-05-15 16:13 UTC, closed without merging