fix: bank reconciliation rounding preventing clearance
frappe/erpnext pull request #35447
Opened 2023-05-28 19:46 UTC by casesolved-co-uk

Fixes #35440 

version-14-hotfix

2023-06-05 14:23 UTC, barredterra requested changes
Not sure about the general implementation approach. How is this handled in other doctypes?

2023-06-05 14:23 UTC, barredterra commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +			self._cy_precision = math.log(fraction_units, 10)
`log(1000, 10) != 3`
```suggestion
			self._cy_precision = round(math.log(fraction_units, 10))
```

`math.log` returns a float, while `flt` expects an integer as precision.

2023-06-05 14:23 UTC, barredterra commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +			import math
This import should be at the top of the file

2023-06-05 14:23 UTC, barredterra commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +		"frappe needs a money datatype"
```suggestion
```

2023-06-05 14:23 UTC, barredterra commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +	_cy_precision = None
```suggestion
	_currency_precision = None
```

I don't like guessing

2023-06-05 16:05 UTC, casesolved-co-uk commented
> Not sure about the general implementation approach. How is this handled in other doctypes?

You're the reviewer, you tell me

2023-06-05 16:36 UTC, barredterra commented
> You're the reviewer, you tell me

Nope. You are proposing this change, so if you want to get it merged you'll have to do the work and convince the reviewers that it is correct.

2023-06-05 17:11 UTC, casesolved-co-uk commented
> > You're the reviewer, you tell me
> 
> Nope. You are proposing this change, so if you want to get it merged you'll have to do the work and convince the reviewers that it is correct.

It's a bug fix, and it's been tested to fix the bug. Any architectural policies are your preprogative

2023-06-05 17:21 UTC, barredterra commented
Anyone would think you're just here to display your arrogance instead of collaborating productively.

2023-06-05 18:17 UTC, casesolved-co-uk commented
> Anyone would think you're just here to display your arrogance instead of collaborating productively.

On the contrary, I think it's arrogant to expect everyone fixing bugs in your software to know every single detail of the software architecture.

No wonder there are thousands of ignored issues and pull requests.

Explain to me how fixing bugs in your software and amending your review comments is arrogant?

2023-06-05 20:32 UTC, barredterra commented
It's not my software. I'm reviewing you PR on my own time and money. If you're not willing to be friendly and put in the required effort, I will simply stop reviewing your PRs.

2023-06-05 21:12 UTC, casesolved-co-uk commented
> It's not my software. I'm reviewing you PR on my own time and money. If you're not willing to be friendly and put in the required effort, I will simply stop reviewing your PRs.

I have been friendly, it's you calling me names.
I have put in the required effort by finding and fixing the bug and testing it.
Your review is almost entirely cosmetic and personal preference and yet I STILL made the changes.

If it's not your software, why are you a maintainer and reviewer authorized by frappe?
How is calling me arrogant friendly?
How is fixing bugs in your software and amending your review comments not "collaborating productively"?
How is not recognising the value and contributions of mine not arrogant?

We are all contributing on our own time and money given this is open source software. Where is your appreciation?

I refer you to your own code of conduct:

> Examples of behavior that contributes to creating a positive environment include:
> 
> Using welcoming and inclusive language
> Being respectful of differing viewpoints and experiences
> Gracefully accepting constructive criticism
> Focusing on what is best for the community
> Showing empathy towards other community members
>
> Examples of unacceptable behavior by participants include:
> 
> The use of sexualized language or imagery and unwelcome sexual attention or advances
> Trolling, insulting/derogatory comments, and personal or political attacks
> Public or private harassment
> Publishing others' private information, such as a physical or electronic address, without explicit permission
> Other conduct which could reasonably be considered inappropriate in a professional setting

2023-07-09 11:13 UTC, casesolved-co-uk commented
I see this is blocked.
Congratulations 👏

2023-07-24 06:33 UTC, closed without merging