feat: Record Advance Payments as Liability
frappe/erpnext pull request #35537
Opened 2023-06-02 12:30 UTC by GursheenK

Ability to let user record advance payments as liability instead of a negative asset.

The current flow allows the user to record **Advance Payments** by storing it as a **Negative Asset** in the General Ledger. It uses the Default Receivable account from the Company master to achieve this. 

Added the option to allow users to **Book Advance Payments as Liability**. When selected, the user needs to provide the Default Advances Received Account and the Default Advances Paid Account in the Company master.

Any Advance Payment Entries will therefore use the liability account. Any new Sales/Purchase Invoices that in turn fetch the Advance Payment Entries show the account used for the entry. 

Similar behaviour for any Payment Reconciliations.

The Default Advances Received / Default Advances Paid accounts can be set from the following Doctypes for multiple companies - 

- Customer / Customer Group
- Supplier / Supplier Group

If they are not set in any of the above, the default liability account from the Company master is used.

Issue #34282

2023-06-03 18:51 UTC, mujeerhashmi commented
Can this be back ported to version-14 ?

2023-06-05 10:01 UTC, deepeshgarg007 requested changes

2023-06-05 10:01 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/party_account/party_account.json
> +  "advances_received_account",
The way `account` column is used for both parties like customer and supplier, maybe the same column `advance_account` can be used for both customer and supplier, with no need for separate columns (fields). Just a filter for respective account type in the masters would be enough

2023-06-05 10:01 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/payment_entry/payment_entry.js
> +
Looks like a change from other PR, remove this

2023-06-05 10:01 UTC, deepeshgarg007 commented on erpnext/controllers/accounts_controller.py
> +	if party_type == "Customer":
Else condition missing

2023-06-05 12:09 UTC, deepeshgarg007 commented on erpnext/controllers/accounts_controller.py
> +			party_account = frappe.db.get_values("Company", {"company_name": self.company}, ["default_receivable_account", "default_advances_received_account"])
This can also be a different one setup in the customer/supplier master. Right now we are just considering from the company

2023-06-09 06:57 UTC, closed without merging