feat: Record Advance Payment as a liability
frappe/erpnext pull request #35609
Opened 2023-06-08 08:08 UTC by GursheenK

Uses a single field for both Advance Liability Accounts in order to record the Advance Payments as a Liability instead of an Asset.

Changed the Payment Entry Doctype to set off Liability Account amount when References like Orders/Invoices exist.

Issue #34282

2023-06-09 03:39 UTC, s-aga-r commented
@deepeshgarg007 @GursheenK Why two [PRs](https://github.com/frappe/erpnext/pull/35537)?

2023-06-09 06:55 UTC, deepeshgarg007 requested changes

2023-06-09 06:55 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
> +		if book_advance_payments_as_liability:
Simply call `get_liability_account` from here and check if `book_advance_payments_as_liability` is enabled or not inside the function itself

2023-06-09 06:55 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
> +		book_advance_payments_as_liability = frappe.get_value(
This should be on `validate`, not on submit

2023-06-09 06:55 UTC, deepeshgarg007 commented on erpnext/accounts/doctype/payment_entry/payment_entry.js
> +					console.log(r.message);
Remove this

2023-07-01 12:19 UTC, merged

2023-08-08 08:57 UTC, rtdany10 commented
@deepeshgarg007 will this be backported?