feat: added method for getting ordered quantity in the supplier score…
frappe/erpnext pull request #35791
Opened 2023-06-19 16:33 UTC by Vishnu7025

feat: added method for getting ordered quantity in the supplier scorecard variable.
@ankush

2023-06-21 03:57 UTC, s-aga-r requested changes

2023-06-21 03:57 UTC, s-aga-r commented on erpnext/buying/doctype/supplier_scorecard_variable/supplier_scorecard_variable.py
> +
```suggestion
def get_ordered_qty(scorecard):
    """Returns the total number of ordered quantity (based on Purchase Orders)"""

    po = frappe.qb.DocType("Purchase Order")

    return (
        frappe.qb.from_(po)
        .select(Sum(po.total_qty))
        .where(
            (po.supplier == scorecard.supplier)
            & (po.docstatus == 1)
            & (po.transaction_date >= scorecard.get("start_date"))
            & (po.transaction_date <= scorecard.get("end_date"))
        )
    ).run(as_list=True)[0][0] or 0


```

2023-06-21 07:44 UTC, Vishnu7025 commented
@s-aga-r

2023-06-21 08:03 UTC, s-aga-r commented
> @s-aga-r 

@Vishnu7025 also fix checks

2023-06-24 07:09 UTC, deepeshgarg007 commented
@Vishnu7025 Please setup https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#linting locally and resolve linting issues. Reopen once done

2023-06-24 07:09 UTC, closed without merging