feat: added proforma invoice doctype
frappe/erpnext pull request #35975
Opened 2023-07-03 10:28 UTC by RitvikSardana

2023-07-10 07:26 UTC, s-aga-r commented
@RitvikSardana setup https://pre-commit.com/, use https://www.conventionalcommits.org/en/v1.0.0/

2023-07-11 05:35 UTC, deepeshgarg007 requested changes

2023-07-11 05:35 UTC, deepeshgarg007 commented on erpnext/selling/doctype/proforma_invoice/proforma_invoice.py
> +	return doclist
This function can be commodified using the one in `sales_order.py`. No need to make a new one

2023-07-11 05:35 UTC, deepeshgarg007 commented on erpnext/selling/doctype/sales_order/sales_order.py
> +
Duplicate code

2023-07-22 12:58 UTC, closed without merging