fix: bank reconciliation rounding preventing clearance
frappe/erpnext pull request #36268
Opened 2023-07-24 10:07 UTC by casesolved-co-uk

Fixes https://github.com/frappe/erpnext/issues/35440

version-14-hotfix

2023-07-24 12:56 UTC, ankush requested changes

2023-07-24 12:56 UTC, ankush commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +	_currency_precision = None
This will be a class variable (?) and kinda behave weirdly in multi-tenant deploys.

2023-07-24 14:29 UTC, casesolved-co-uk commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +	_currency_precision = None
It will behave as a default and be overridden when initialised in an instance of the class

2023-07-24 15:01 UTC, ankush commented on erpnext/accounts/doctype/bank_transaction/bank_transaction.py
> +	_currency_precision = None
@casesolved-co-uk the override will continue to stay there when a request from another site is fired. 

It's basically a bug like this: https://github.com/frappe/frappe/pull/20052



```
worker starts: class attr is None
first request is fired: class attr is set to 2
second request is fired from some other site: class attr still stays 2 and site's preferences aren't respected.
```

2023-08-11 20:42 UTC, closed without merging

2023-08-14 12:34 UTC, casesolved-co-uk commented
.