feat: Create multiple Task From Issue Doctype
frappe/erpnext pull request #36816
Opened 2023-08-25 09:44 UTC by viralkansodiya

Create multiple Task From Issue Doctype(Custom Button)

For check in more details please view this video

[](https://youtu.be/R6eL8dkOWUg?si=W0vLVHoKzuqaiIIR)

2023-08-28 09:40 UTC, viralkansodiya commented
[](https://youtu.be/R6eL8dkOWUg?si=nzs5uWAerQT7oWxL)

2023-09-07 06:21 UTC, ankush requested changes

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.py
> +def create_new_task_from_issue(self, assign_to):
```suggestion
def create_new_task_from_issue(issue, assign_to):
```

`self` is a convention for objects to refer to self. It shouldn't be used like this.

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.py
> +	self = frappe.json.loads(self)
What is this? `frappe.json` isn't a thing. You're indirectly using json module.

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.py
> +	doc.project = self.get("project")
too much repetition. Use `get_mapped_doc` instead which is used everywhere for mapping one document to another.

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.py
> +	frappe.msgprint("Task Created Successfully , {0}".format(get_link_to_form("Task", doc.name)))
https://frappeframework.com/docs/user/en/translations 
```suggestion
	frappe.msgprint(_("Task Created Successfully: {0}").format(get_link_to_form("Task", doc.name)))
```

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.py
> +		return
```suggestion
def get_if_task_exist(issue):
	return bool(frappe.db.exists("Task", {"issue": issue}))
```

Why do you need this much code? This method can be removed entirely. There's `frappe.db.exist` on client side too.

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.js
> +                        d.hide();
Why is this required?

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.js
> +                    }
Format this correctly please, it's not readable at all.

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.js
> +        if(!frm.doc.__islocal) {
```suggestion
        if(!frm.is_new()) {
```

2023-09-07 06:21 UTC, ankush commented on erpnext/support/doctype/issue/issue.py
> +from frappe.desk.form.assign_to import add
```suggestion
from frappe.desk.form.assign_to import add as add_assignment
```

Better readability

2023-09-07 06:27 UTC, deepeshgarg007 commented
@viralkansodiya Doesn't look like a very high-in-demand feature, maybe keep this as a Client Script/Server Script on the site where this is needed?

2023-09-07 06:29 UTC, ankush commented
Also, implicitly creating tasks isn't of much use IMO. It should at least let me say what task I'm supposed to do.

2023-09-07 06:29 UTC, closed without merging

2023-09-07 07:13 UTC, viralkansodiya commented
@deepeshgarg007 
In Services companies, clients create an 'Issue'.  Customer Support team will review and provide information and close the issue when possible. When the issue raised by client requires some additional work, a Task is created and this task maybe used even in timesheets. 

So this feature is very useful for services companies. 

Request you to kindly reconsider merging this PR once I implement changes suggested by Ankush.