feat:New Report Timesheet Billing Summary , combination of three report
frappe/erpnext pull request #37020
Opened 2023-09-11 04:39 UTC by viralpatel15

This Report is Combination of three report

Project Billing Summary
Employee Billing Summary
Daily Timesheet Summary

2023-09-19 14:39 UTC, deepeshgarg007 requested changes
As you pointed out this is a combination of three existing reports, try and reuse as much code as possible instead of copy-pasting.

Add a screenshot of the report in the description which will help reviewers visualize how the final report looks

2023-09-19 14:39 UTC, deepeshgarg007 commented on erpnext/projects/report/timesheet_billing_summary/timesheet_billing_summary.py
> +def get_billable_and_total_duration(activity, start_time, end_time):
An identical function exists in the `billing_summary.py`, that can be used. Why copy paste?

2023-09-25 15:45 UTC, viralpatel15 commented
> As you pointed out this is a combination of three existing reports, try and reuse as much code as possible instead of copy-pasting.
> 
> Add a screenshot of the report in the description which will help reviewers visualize how the final report looks

![image](https://github.com/frappe/erpnext/assets/98073516/c879a600-a424-40a9-8d9b-36fb0f18070d)

![Screenshot 2023-09-25 211326](https://github.com/frappe/erpnext/assets/98073516/b3b9b14a-1c5a-4103-91ba-3a4b06d6d28b)

2023-10-02 05:17 UTC, deepeshgarg007 commented
@viralpatel15 You can reopen this PR once the requested changes have been made

2023-10-02 05:17 UTC, closed without merging