fix: make changes that enable gantt view for job cards
frappe/erpnext pull request #37661
Opened 2023-10-24 13:34 UTC by Didiman1998

**Title: Make changes that enable gantt view for job cards**

**Description:**
This pull request fixes an issue in the Gantt View for Job Cards in ERPNext. In the current state you cant use the Gantt View at all. 

You can look at our before-after pictures, where we explain what exactly we have changed to make it work.

Thanks for considering this pull request and please backport it to version-14-hotfix and version-13-hotfix if possible. Cause we found this bug in version 14 too.

**BEFORE**
![image](https://github.com/frappe/erpnext/assets/118364772/e4a4fa50-d292-47e6-943a-94add3bb2753)

**AFTER**
![image](https://github.com/frappe/erpnext/assets/118364772/4e663fae-0f6f-48aa-a78e-ccd04fd95719)

2023-10-26 06:52 UTC, s-aga-r requested changes
Add fields `expected_start_date` and `expected_end_date` in [job_card_list.js](https://github.com/frappe/erpnext/blob/74b6bfb9eb50c58b59bd6c1cc31b66b77023a394/erpnext/manufacturing/doctype/job_card/job_card_list.js#L3) instead of adding them to the List View. 

Example: [bom_list.js](https://github.com/frappe/erpnext/blob/74b6bfb9eb50c58b59bd6c1cc31b66b77023a394/erpnext/manufacturing/doctype/bom/bom_list.js#L2)

2023-10-30 09:31 UTC, Didiman1998 commented
@s-aga-r 

Done like you have commented it 👍
If you need anything else, you can let me know

2023-10-30 09:32 UTC, Didiman1998 commented
> Add fields `expected_start_date` and `expected_end_date` in [job_card_list.js](https://github.com/frappe/erpnext/blob/74b6bfb9eb50c58b59bd6c1cc31b66b77023a394/erpnext/manufacturing/doctype/job_card/job_card_list.js#L3) instead of adding them to the List View.
> 
> Example: [bom_list.js](https://github.com/frappe/erpnext/blob/74b6bfb9eb50c58b59bd6c1cc31b66b77023a394/erpnext/manufacturing/doctype/bom/bom_list.js#L2)

Done like you have commented it 👍
If you need anything else, you can let me know

2023-10-30 09:48 UTC, s-aga-r approved these changes

2023-10-30 09:48 UTC, merged

2023-11-09 06:57 UTC, TurkerTunali commented
Gant view is a hidden gem in the ERP industry. Thank you fixing it. @Didiman1998