fix: consistency in display reserved_stock checkbox on Sales Order Item according global settings and item.is_stock_item
frappe/erpnext pull request #38322
Opened 2023-11-24 09:30 UTC by FHenry

> Please provide enough information so that others can review your pull request:

1 : Global setting consistency in Sales Order Item grid table
If Reserved Stock In Stock Settings is OFF, the reserve stock column should not be available in column choice on Sales Order Item grid table and reserve_stock must be set to 0 on Sales Order Item data
It give to user headache to understand what is the meaning of reserve stock column

2 : Maintain Stock consistency in Sales Order Item grid table
If Reserved Stock In Stock Settings is ON
If an Item is **not** Maintain Stock there is no need to display Reserve Stock checkbox field in Sales Order Item detail form.
It give to user headache to understand what is the meaning of reserve stock checkbox for a non Maintain Stock item
The value must be defaulted to 0 in this case.

> Explain the **details** for making this change. What existing problem does the pull request solve?

Item "Item 1" is Maintain Stock
Item "no stock" is not Maintain Stock

Actually :
Add Item "Item 1" to a Sales Order The Reserve stock checkbox is in detail Sales Order Item Form => OK
Add Item "no stock" to a Sales Order The Reserve stock checkbox is in detail Sales Order Item Form and defaulted to 1 => KO

With this PR :
Add Item "Item 1" to a Sales Order The Reserve stock checkbox is in detail Sales Order Item Form => OK
Add Item "no stock" to a Sales Order The Reserve stock checkbox is **not** in detail Sales Order Item Form and defaulted to 0 => OK

> Screenshots/GIFs

Before :

https://github.com/frappe/erpnext/assets/1050053/4f2b44fd-05c7-489f-92a2-e64713c2c046

After :
Stock Setting Reserved Stock OFF

https://github.com/frappe/erpnext/assets/1050053/bcdf7d20-c7c2-4002-9a82-60ba74bb0f66

Stock Setting Reserved Stock ON with non Maintain Stock item

https://github.com/frappe/erpnext/assets/1050053/ba9e1266-ccfa-4c91-aad4-4928275dfda9

> no-doc

2023-11-25 00:37 UTC, dj12djdjs commented on erpnext/selling/doctype/sales_order_item/sales_order_item.json
> +  "is_stock_item",
Is this required? It looks like you're checking the cached value from item during validation?

2023-12-05 07:30 UTC, FHenry commented
Note to reviewer : the failed test MariaDB (Test 3) is not related to this PR.

But If you want to suggest me different implementation  to get is_stock_item from item, that could be more Frappe Ways , than adding a field in Sales Order Item : Is Stock Item (hidden and defaulted with item.is_stock_item)
like use async/await in erpnext/buying/doctype/purchase_order/purchase_order.js 
`frappe.ui.form.on("Purchase Order Item", { item_code: ...`

I will be happy to work on it

2023-12-07 21:03 UTC, dj12djdjs commented
@FHenry I mean I don't see the `is_stock_item` field you created used anywhere. 

I think it can be deleted, or am I totally missing something here?

2023-12-08 12:22 UTC, FHenry commented
> @FHenry I mean I don't see the `is_stock_item` field you created used anywhere.
> 
> I think it can be deleted, or am I totally missing something here?

I use it in the json
  "depends_on": "eval:doc.is_stock_item",
of the field rerserve_stock

Like that when an Item is fetch 
Sales Order Item.is_stock_item 
 is populated with 
item.is_stock_item 
and then reserve_stock is displayed or not

2023-12-12 21:35 UTC, FHenry commented
@dj12djdjs did you have time to check this PR ?

2024-01-15 05:23 UTC, s-aga-r requested changes

2024-01-15 05:23 UTC, s-aga-r commented on .editorconfig
> +insert_final_newline = false
Undo these changes.

2024-01-15 05:23 UTC, s-aga-r commented on erpnext/selling/doctype/sales_order/sales_order.js
> +						);
Fix spacing.

2024-01-15 05:23 UTC, s-aga-r commented on erpnext/selling/doctype/sales_order/sales_order.py
> +				item.reserve_stock = 0
get `enable_stock_reservation` from DB once and use it in the iteration.

Why we are fetching `is_stock_item` from Item master as you have added a field is_stock_item in the Sales Order Item itself?

2024-01-16 16:38 UTC, s-aga-r requested changes

2024-01-16 16:38 UTC, s-aga-r commented on erpnext/selling/doctype/sales_order/sales_order.py
> +
get `enable_stock_reservation` from DB once and use it in the iteration.

2024-01-17 05:13 UTC, s-aga-r approved these changes

2024-01-17 05:13 UTC, s-aga-r commented
Unrelated failing tests.

2024-01-17 05:13 UTC, merged