fix(pe): set contact fields
frappe/erpnext pull request #39748
Opened 2024-02-06 01:07 UTC by blaggacao

# Context

Notifications generall depend on the `contact_*` set of fields.

Payment Entries have a stup implementation that lets you select a contact.

However, unlike every other transactional document, they don't aquire the default contact, if set.

This makes communication automations which depend on the default contact property difficult to implement, because the `contact_*` set of fields are not available.

# Proposed Solution

- [x] like other tx documents, let PEs aquire default contact data, too

2024-02-14 10:03 UTC, blaggacao commented
![image](https://github.com/frappe/erpnext/assets/7548295/d6e2d5c9-a864-47b4-8789-235734043b62)

2024-02-17 00:34 UTC, barredterra requested changes

2024-02-17 00:34 UTC, barredterra commented on erpnext/accounts/doctype/payment_entry/payment_entry.py
> +			set_contact_details(self, party=frappe._dict({"name": self.party}), party_type=self.party_type)
```suggestion
			if not self.contact_person:
				set_contact_details(self, party=frappe._dict({"name": self.party}), party_type=self.party_type)
```

Otherwise this will always overwrite a manually selected contact with the primary contact.

2024-03-10 20:26 UTC, blaggacao commented
This is still desireable.

2024-03-12 23:40 UTC, barredterra approved these changes

2024-03-12 23:40 UTC, merged