Email campaign's status will update in the status #39179
frappe/erpnext pull request #39776
Opened 2024-02-07 07:09 UTC by harshkhatri7287

The status of the email campaign is scheduled to update daily, but it was not updating it in the database,
Now the updated status is directly set in the database also.

2024-02-08 10:27 UTC, khushrrp commented on erpnext/crm/doctype/email_campaign/email_campaign.py
> +			frappe.db.set_value("Email Campaign", self.name, "status", "Scheduled")
use self.status in place of all status values here.

2024-02-09 07:03 UTC, harshkhatri7287 commented
@leela @venetanji Please proceed this PR for pending tests.

2024-02-13 11:18 UTC, khushali-beehyv commented
@deepeshgarg007 @rohitwaghchaure  Can you please help this PR to proceed for the tests and the review process ?

2024-02-13 17:44 UTC, barredterra requested changes
Thanks for the fix! I'm afraid this is not the right place for writing to the database.

Better add `email_campaign.save()` here, after line 146:

https://github.com/frappe/erpnext/blob/22291d32e6dfee445b15a2519e111a781b73abd5/erpnext/crm/doctype/email_campaign/email_campaign.py#L142-L146

2024-03-04 17:45 UTC, barredterra approved these changes

2024-03-05 09:13 UTC, harshkhatri7287 commented
Hi @barredterra, One required test case is failing, Can you please explain this, why is it happening?

2024-03-05 09:44 UTC, merged