Update job_card.py
frappe/erpnext pull request #40245
Opened 2024-03-02 11:47 UTC by Nandhinidevi123

https://github.com/frappe/erpnext/issues/40235
The overproduction percentage is entered in the manufacturing settings. However, the overproduction percentage is not considered on job cards, preventing the entry of overproduction quantity in the job card.

2024-03-12 16:33 UTC, s-aga-r requested changes
@Nandhinidevi123 Also add a test case.

2024-03-13 08:21 UTC, Nandhinidevi123 commented
> @Nandhinidevi123 Also add a test case.

@s-aga-r Testing video Added

2024-03-13 08:51 UTC, s-aga-r commented
> > @Nandhinidevi123 Also add a test case.
> 
> @s-aga-r Testing video Added

@Nandhinidevi123 From test case I meant unit test case. See [this](https://github.com/frappe/erpnext/blob/8d405684ce69f4cff9ce9536d06500eaed1a4835/erpnext/manufacturing/doctype/work_order/test_work_order.py#L94-L107) example for your reference.

2024-03-26 08:34 UTC, Nandhinidevi123 commented
> > > @Nandhinidevi123 Also add a test case.
> > 
> > 
> > @s-aga-r Testing video Added
> 
> @Nandhinidevi123 From test case I meant unit test case. See [this](https://github.com/frappe/erpnext/blob/8d405684ce69f4cff9ce9536d06500eaed1a4835/erpnext/manufacturing/doctype/work_order/test_work_order.py#L94-L107) example for your reference.

@s-aga-r add test case added

2024-03-26 15:34 UTC, s-aga-r commented
@Nandhinidevi123 please fix the failing checks.

2024-04-24 02:05 UTC, closed without merging