feat: feat: accept apply write off amount on Point of sale and use this to send to sales invoice
frappe/erpnext pull request #40417
Opened 2024-03-12 14:50 UTC by devdiogenes

The objective is allow the POS user to inform how much change was passed to the customer, and add the difference to the write-off amount.

**pos_payment.js:**
-> A new column hes been added to totals for the write-off amount. 
-> In the total change column, if there is change value, it div becames editable, allowing the user to input the actual change value.
-> The write-off amount will be calculed based in the change column that the user edited, using the focus and focusout events.

![Media 1](https://github.com/frappe/erpnext/assets/103958767/3a2f3139-08f0-49f6-87b8-1512cf46c8d9)

**pos_invoice_merge_log.py:**
-> When mergin a POS Invoice to Sales Invoice, the write_off_amount and base_write_off_amount values are added for consolidation

![Media 2](https://github.com/frappe/erpnext/assets/103958767/fda5dc90-f11f-443f-b065-dd861b9fc1df)

2024-03-22 12:45 UTC, HarryPaulo commented
waint for reviewers

2024-04-10 23:13 UTC, devdiogenes commented
Waiting for review

2024-04-29 18:59 UTC, HarryPaulo commented
someone can review this? @rohitwaghchaure?

2024-05-15 11:06 UTC, HarryPaulo commented
@ankush can you review this?

2024-05-31 01:31 UTC, devdiogenes commented
Hello, can someone review this?

2024-06-17 12:21 UTC, devdiogenes commented
Waiting reviewers

2024-07-04 00:11 UTC, devdiogenes commented
Waiting review

2024-07-20 10:16 UTC, devdiogenes commented
Waiting review

2024-08-08 16:42 UTC, devdiogenes commented
Hello @rohitwaghchaure, @s-aga-r 
Could you guys help me checking why didn't my workflow checks run?

2024-09-09 10:53 UTC, devdiogenes commented
Active it

2024-09-10 14:02 UTC, devdiogenes commented
waiting review

2024-10-05 18:26 UTC, devdiogenes commented
Waiting review

2024-11-18 11:21 UTC, devdiogenes commented
Waiting for review

2024-12-12 11:08 UTC, devdiogenes commented
i'm waiting review

2024-12-30 18:42 UTC, devdiogenes commented
Waiting review

2025-01-16 00:50 UTC, diptanilsaha requested changes
![image](https://github.com/user-attachments/assets/2a2078c2-439b-4dae-acc5-1fb11bb3d5a2)

After completing an order with a write-off amount, the POS invoice created is marked as 'Unpaid'. Please investigate and fix the issue.

2025-01-16 11:21 UTC, HarryPaulo commented
@diptanilsaha actually the problem is on native code of write off amount this is not working properly, sooner i will create a PR.

2025-01-21 20:58 UTC, HarryPaulo commented
@diptanilsaha to this PR works, you need to take a look into this other PR
https://github.com/frappe/erpnext/pull/43303


Why all the javascript and python codes that calculate the "write_off_amount" and "change_amount" have undergone a recent change that makes this PR no longer work.

2025-01-22 16:59 UTC, HarryPaulo commented
@nabinhait 
@diptanilsaha 

Can you help us to understand this PR https://github.com/frappe/erpnext/pull/30395?  

Because this PR impact on POS Sales where **change amount** and **write off amount** need work together.

We have two PR oppend to try to change back this funcionality
https://github.com/frappe/erpnext/pull/40417
https://github.com/frappe/erpnext/pull/43303

How we expect this to work:

**Example 1: ** 
I create a POS Invoice with Grand Total: $195,00, customer need to pay me $195.
Customer Pay me with CASH, $200.
Automatically the change amount will be: $5,00

IF the customer SAY, KEEP the change, this amount will stay on my cashier, so i will set ZERO to change, and the write off will be setted as $-5,00.

If that was the only sale of the day, at the end of the day I would have R$200 in my cash register.


**Example 2: Writeoff amount and Change amount on the same POS Invoice**

I create a POS Invoice with Grand Total: $194,99, customer need to pay me $194,99.
Customer Pay me with CASH, $200.
Automatically the change amount will be: **$5,01**

IF with dont have **$0,01** to give the change, we just  give to customer $5,00, so juste set $5,00 on change amount and the write off amount will be setted as **$- 0,01**.


Currently it is not possible to apply "Write off amount" and "Change amount" at the same time, and this is BROKE for Sales Invoice with is_pos checked, or POS Invoice...


I want to know where ERPNext is going, because this change doesn't make sense, but I need to understand where you want to go so I can make some kind of improvement that makes sense for us...

2025-01-23 05:30 UTC, diptanilsaha commented
Both of the examples you provided are reasonable and I understand the importance of this feature. However, I need some time to work on it. Thanks for your patience.

2025-01-28 16:47 UTC, diptanilsaha commented
@HarryPaulo, while your examples are valid, we cannot label them as "Write Off" based on the definition of the term. Instead, it would be more appropriate to refer to them as "Extra Income" or "Tips." 

For this reason, I am closing this pull request. Create a new GitHub issue to request this as a feature.

Thank you for your contribution!

2025-01-28 16:47 UTC, closed without merging

2025-01-29 12:23 UTC, HarryPaulo commented
@diptanilsaha 
First, thanks for your time and your analysis!

But Could you give me examples of applicability of the current "Write off" field and and for what purpose was it designed, and why did you choose to create another field, because i need this feature and probably i will create a new PR for this and not create github inssue ...?


I don't see the point in having 2 fields for an operation where just 1 field would be enough, This act of accounting for the difference in receipts from a sale is centralized in just one account.

In my view, "Write off" would be enough:
Example:

1. If the customer pays more, the accounting movement would be a negative expense.
Example, using a payment Entry: 
https://github.com/user-attachments/assets/556da951-2133-419b-b4fc-9b6d2c2e04b0

2. If the customer pays less, the accounting movement would be a POSITIVE expense.
Example, using a payment Entry: 
https://github.com/user-attachments/assets/7a2b3dd6-ad6a-421a-b2f5-150a1a1cf189

In the Profit and Loss Statement report, we want to see a sum of all movements on "Write off" account.


If your idea is to apply 2 fields to have an operation in a "revenue" account, it will be necessary to change a lot of things in the system, to accommodate something that already worked.

2025-01-29 15:55 UTC, diptanilsaha commented
@HarryPaulo 

The "Write-off" field allows for small amounts to be adjusted. For instance, if an invoice totals $5.05 and the customer pays $5 in cash, then $0.05 can be written off.

This issue appears to be specific to the "Cash" payment method, requiring us to reconsider our implementation.

Negative write-off has a separate use case and I feel, in this scenario, it is not applicable.

I asked you to raise a GitHub issue because it allows for a more organized discussion. This way, other community members can participate instead of having debates in the comments section of a pull request (PR). The comments section of a PR serves a different purpose. While you can always submit a PR, GitHub issues are the best place for discussions.

2025-01-29 19:26 UTC, HarryPaulo commented
done...

https://github.com/frappe/erpnext/issues/45607