feat: validating asset scrap date
frappe/erpnext pull request #43093
Opened 2024-09-06 11:43 UTC by rahulgupta8848

## Background/Context

1. When we select Asset Scrapping, the system by default takes the current date and scraps the asset as on the date
2. In case the company wants to scrap their asset with backdated effect, then that cannot be achieved in the present system as there is no option to select the scrap date anywhere.
3. Also, there is no restriction on scrapping the asset even if depreciation entries are posted

## Solution Summary

1. If a user wants to scrap an asset, then the system will ask for a scrapping date (as shown in the below screenshot).
2. According to the date entered by the user, the asset will be scrapped on that date with back dated effect.
4. The scrapping date cannot be before the purchase date or it cannot be after the current date. Also, If the depreciation entries are passed, asset can only be scrap after the last depreciation date and not before it. In such cases depreciation entry needs to be manually cancelled first and then scrapping can be possible.

![image](https://github.com/user-attachments/assets/dbcbf069-1eba-4082-86f8-b40ed0a5bcfd)

2024-09-10 06:52 UTC, nabinhait requested changes

2024-09-10 06:52 UTC, nabinhait commented on erpnext/assets/doctype/asset/asset.py
> +				):
You can get last depreciation date simply by using `get_value`:

```
last_booked_depreciation_date = frappe.db.get_value(
		"Depreciation Schedule",
		{
			"parent": asset,
			"docstatus": 1,
			"journal_entry": ["!=", ""],
		},
		"schedule_date",
		order_by="schedule_date desc",
	)
```

2024-09-10 06:52 UTC, nabinhait commented on erpnext/assets/doctype/asset/depreciation.py
> +	date = scrap_date if scrap_date else today()
```suggestion
	date = scrap_date or today()
```

2024-09-10 06:52 UTC, nabinhait commented on erpnext/assets/doctype/asset/asset.js
> +		title: "Enter date to scrap asset",
```suggestion
		title: __("Enter date to scrap asset"),
```

2024-09-10 06:52 UTC, nabinhait commented on erpnext/assets/doctype/asset/asset.js
> +				method: "erpnext.assets.doctype.asset.asset.validate_asset_scrap_date",
We should call the `scrap_asset` method from here as it is the primary task and `validate_asset_scrap_date` should be called from inside the `scrap_asset function`

2024-09-10 06:52 UTC, nabinhait commented on erpnext/assets/doctype/asset/test_asset.py
> +				self.assertTrue(
This does not make any sense, you should check for `assertRaise` by defining an error class to it.

2024-09-10 06:52 UTC, nabinhait commented on erpnext/assets/doctype/asset/test_asset.py
> +				last_depreciated_row = entry
Like before here also you can get last depreciation date using `get_value`.

2024-09-11 07:52 UTC, rahulgupta8848 commented
@nabinhait i have implemented all the suggested changes please look into it

2024-09-12 06:07 UTC, nabinhait approved these changes

2024-09-12 06:07 UTC, merged

2025-05-29 09:06 UTC, khushi8112 commented
Closes https://github.com/frappe/erpnext/issues/42514