feat(Sales Invoice): allow linking to project without adding timesheets
frappe/erpnext pull request #44295
Opened 2024-11-22 12:52 UTC by barredterra

2025-01-24 11:32 UTC, nabinhait requested changes

2025-01-24 11:32 UTC, nabinhait commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			self.save()
Why `save`?

2025-01-24 12:16 UTC, barredterra commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			self.save()
This is supposed to be called via API. I assume changes would be lost if we don't save?

2025-01-27 07:49 UTC, nabinhait approved these changes

2025-01-27 07:50 UTC, nabinhait commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +			self.save()
I thought the same function was called fromthe client side

2025-01-27 07:50 UTC, merged

2025-01-27 09:53 UTC, barredterra commented
Maybe a better approach, since it would prevent the additional API call: checkbox _Add Timesheets On Save_ in **Sales Invoice**.