[Fix] Mode of payment issue
frappe/erpnext pull request #6399
Opened 2016-09-19 08:30 UTC by rohitwaghchaure

2016-09-19 14:04 UTC, nabinhait commented on erpnext/patches/v7_0/update_mode_of_payment_type.py
> +				[si_doc.remove(d) for d in remove_payment]
If you are not using the result, avoid using list comprehension. Instead use normal for loop, for better readability.

2016-09-19 14:05 UTC, nabinhait requested changes

2016-09-19 18:19 UTC, rohitwaghchaure commented on erpnext/patches/v7_0/update_mode_of_payment_type.py
> +				[si_doc.remove(d) for d in remove_payment]
Completed

2016-09-20 05:26 UTC, nabinhait approved these changes

2016-09-20 05:26 UTC, merged