[feature] preferred email for payroll
frappe/erpnext pull request #6419
Opened 2016-09-21 03:31 UTC by RobertSchouten

adds a dropdown menu to employee that allows you to specify a preferred email_address to send to for payroll and newsletter
also adds description in hr settings

2016-09-21 07:31 UTC, nabinhait commented on erpnext/hr/doctype/employee/employee.js
> +			if (frm.fields[i].df.label===frm.doc.prefered_contact_email){
Label can be customized, instead implement it using fieldname.

`frm.fields[i].df.fieldname===frappe.model.scrub(frm.doc.prefered_contact_email)`

2016-09-21 07:32 UTC, nabinhait requested changes

2016-09-21 07:56 UTC, RobertSchouten commented on erpnext/hr/doctype/employee/employee.js
> +			if (frm.fields[i].df.label===frm.doc.prefered_contact_email){
i thought about that but it doesn't allow for customisation but if u think it should b will change

2016-09-22 07:19 UTC, nabinhait commented on erpnext/patches.txt
> +execute:frappe.db.sql("update `tabEmployee` set prefered_contact_email = IFNULL(prefered_contact_email,'') ")
why this?
may be we should set "Company Email" as prefered_contact_email and company_email field value as preferred_email.

2016-09-22 08:47 UTC, RobertSchouten commented on erpnext/patches.txt
> +execute:frappe.db.sql("update `tabEmployee` set prefered_contact_email = IFNULL(prefered_contact_email,'') ")
the reason for it is due to when a select field is add and has a frappe.ui.form.on hook it changes the value from null to empty causing the event trigger to trigger before the page has loaded properly resulting in the child field updating with the same value as the previous open'd employee (only occurs when you change from one employee to the other with refreshing)

if we set to company email n patch so has correct data then you cant select a blank option for opt out (for the people without email)

2016-10-17 12:13 UTC, merged