Group similar items in PO
frappe/erpnext pull request #6513
Opened 2016-09-30 11:54 UTC by KanchanChauhan

Fixed https://github.com/frappe/erpnext/issues/6041

2016-10-19 16:25 UTC, rmehta requested changes

2016-10-19 16:25 UTC, rmehta commented on erpnext/buying/doctype/purchase_order/purchase_order.json
> +   "label": "Group same item",
should be "Group Same Items" -> labels in title case

2016-10-19 16:25 UTC, rmehta commented on erpnext/buying/doctype/purchase_order/purchase_order.py
> +
add a simple test case?

2016-10-20 09:03 UTC, KanchanChauhan commented on erpnext/buying/doctype/purchase_order/purchase_order.py
> +
Done

2016-10-20 10:41 UTC, merged