[Fix] sales order status showing completed, while it's status was to bill
frappe/erpnext pull request #6554
Opened 2016-10-05 17:32 UTC by rohitwaghchaure

2016-10-06 12:01 UTC, rohitwaghchaure commented
Done

2016-10-07 07:30 UTC, nabinhait requested changes

2016-10-07 07:30 UTC, nabinhait commented on erpnext/controllers/status_updater.py
> +			ref_doc.db_set("status", ref_doc.status)
Instead of `ref_doc.db_set("status", ref_doc.status)`, you can use `ref_doc.set_status(update=True)`

2016-10-07 07:30 UTC, nabinhait commented on erpnext/patches/v7_0/update_status_of_zero_amount_sales_order.py
> +		sales_order.set_status(update_modified = False)
sales_order.set_status(update=True, update_modified = False)

Remove the next line

2016-10-07 08:26 UTC, rohitwaghchaure commented on erpnext/patches/v7_0/update_status_of_zero_amount_sales_order.py
> +		sales_order.set_status(update_modified = False)
Done

2016-10-07 08:26 UTC, rohitwaghchaure commented on erpnext/controllers/status_updater.py
> +			ref_doc.db_set("status", ref_doc.status)
Done

2016-10-07 08:50 UTC, merged