[fix #6566]
frappe/erpnext pull request #6577
Opened 2016-10-07 13:32 UTC by PawanMeh

Documentation for Fiscal Year

2016-10-08 05:46 UTC, rmehta requested changes

2016-10-08 05:46 UTC, rmehta commented on erpnext/docs/user/manual/en/accounts/setup/fiscal-year.md
> +In case you have more than One Company sharing the same Fiscal Year, you can
why "One Company" is in title case?

2016-10-08 05:46 UTC, rmehta commented on erpnext/docs/user/manual/en/accounts/setup/fiscal-year.md
> +
What is "Company Grid" is not clear!

2016-10-10 09:06 UTC, PawanMeh commented
Hi Faris,

I am not sure if you were viewing the latest commit, please see below screen shot for your reference

![screen shot 2016-10-10 at 2 28 54 pm](https://cloud.githubusercontent.com/assets/20460498/19231241/94c17530-8ef6-11e6-8e77-2be58ced1394.png)

2016-10-16 08:58 UTC, merged