Add multiple emoloyee in salary structure
frappe/erpnext pull request #6621
Opened 2016-10-16 06:42 UTC by mainul94

2016-10-19 16:29 UTC, rmehta commented
@mainul94 thanks for the contribution

Can you add some screenshots for this?

Some other thoughts: Maybe we can skip building. Directly filter and check employees from the list view and then set salary structure?

2016-10-20 05:17 UTC, mainul94 commented
@rmehta 
I added a button ("Sync employee") in salary structure and redirect to a single DocType ("Salary Structure Employee Assign") with salary structure Id and Company.
In "Salary Structure Employee Assign" DocType user can see also Employee who Belong this Salary Structure and who not.
As Link Attendance, User can add or remove Employee by Check or Uncheck.
![salary_structure](https://cloud.githubusercontent.com/assets/9250275/19547071/b3338798-96b6-11e6-88f7-d9b66a11e417.png)
![employee_assign](https://cloud.githubusercontent.com/assets/9250275/19547072/b33e7270-96b6-11e6-9fc4-fdafe9c777e1.png)

2016-10-21 03:38 UTC, rmehta commented
@mainul94 I still think this will be an overkill to maintain a separate UI for this. How about we add a simple dialog inside the Salary Structure and ask users to work with just a couple of filters, maybe company, department, branch?

2016-10-22 04:25 UTC, mainul94 commented
@rmehta 
Ok I will fix and add dialog for add Employee.

2016-10-24 04:39 UTC, mainul94 commented
@rmehta Now Multi Employee add in a Dialog.
![1](https://cloud.githubusercontent.com/assets/9250275/19633693/2a38419a-99d6-11e6-81b2-81907279099c.png)
![2](https://cloud.githubusercontent.com/assets/9250275/19633692/2a378750-99d6-11e6-931f-3ebc0adc51e7.png)

2016-10-24 04:59 UTC, rmehta commented
👍 great! I would usually not go with so much code. 

Maybe just add it via the filters and let users delete from the table itself?

2016-10-24 05:02 UTC, mainul94 commented
@rmehta Yes user can delete from table itself. It's validated if any employee in exists in table then not add again.

2016-10-24 05:06 UTC, rmehta requested changes

2016-10-24 05:06 UTC, rmehta commented on erpnext/hr/doctype/salary_structure/salary_structure.py
> +	return frappe.get_all('Employee',filters=args['filters'], fields=['name', 'employee_name'])
use `frappe.get_list` here. Permissions matter!

2016-10-24 05:06 UTC, rmehta commented on erpnext/hr/doctype/salary_structure/salary_structure.js
> +		var employees = $.map(frm.doc.employees, function(d) { return d.employee });
Remove the checkbox code, just add the employees in the table and then let the user decide

2016-10-24 05:06 UTC, rmehta commented on erpnext/hr/doctype/salary_structure/salary_structure.js
> +	getEmployees:function (frm) {
We usually use `snake_case`, so for consistency sake, `get_employees` will be better :)

2016-10-24 05:07 UTC, rmehta commented
Let the user delete the employees from the table itself, even lesser code :)

2016-10-24 05:35 UTC, mainul94 commented
@rmehta Please check it now.

2016-10-24 05:44 UTC, mainul94 commented on erpnext/hr/doctype/salary_structure/salary_structure.js
> +		frm.$emp_dialog.get_input('set_employee').removeClass('btn-xs').addClass('btn-primary pull-right').on('click', function () {
Fixed Please Check.

2016-10-24 05:51 UTC, rmehta commented
:+1: awesome :)

2016-10-24 05:52 UTC, merged