[fix] #6363
frappe/erpnext pull request #6662
Opened 2016-10-20 11:30 UTC by PawanMeh

1. Added ability to add 'Weights' against Tasks related to a project

1. Added calculation methods for % Tasks Completed based on weights, percentage & completion

1. Added documentation changes

2016-10-21 03:49 UTC, rmehta commented on erpnext/projects/doctype/project/project.json
> +   "fieldname": "pct_comp_method",
Always use full names `percent_complete_method`

Also maybe this should be in the "Tasks" section rather than the header section

2016-10-21 08:34 UTC, PawanMeh commented on erpnext/projects/doctype/project/project.json
> +   "fieldname": "pct_comp_method",
1. I have made the changes regarding the renaming of the field to percent_complete_method.

1. For the % Complete Method and %Tasks Completed, I feel they need to remain on the top where the user can see them without scrolling. The reasons being that %Complete Method usually is set up when the project is set up initially (you may or may not know all tasks at this point) and once the project starts a key parameter is %Tasks Completed which should be available upfront without scrolling.

Also both the fields with a vertical scroll in between may mess up the Grid alignment.

You can let me know if you still want #2 to be changed and I will re-push the changes accordingly.

2016-10-24 05:53 UTC, rmehta requested changes

2016-10-24 05:53 UTC, rmehta commented on erpnext/projects/doctype/project/project.json
> +<<<<<<< 6ef2c9faa43ba40bef00abc29cd9a5de980b2037
You need to remove this merge conflict

2016-10-24 06:26 UTC, merged