Fetch serial no by default
frappe/erpnext pull request #6705
Opened 2016-10-25 17:47 UTC by KanchanChauhan

2016-10-25 18:14 UTC, bcornwellmott commented
I'm concerned about having this happen automatically without any user interaction. Users could forget this is a serial numbered part and transfer incorrect serial numbers without any warning or prompt. Could we have this trigger on a button press or a checbox in the Stock Settings?

2016-10-25 18:17 UTC, KanchanChauhan commented
@bcornwellmott It will happen only if "Automatically Set Serial Nos based on FIFO" is checked in Stock Settings.

2016-10-26 07:33 UTC, nabinhait requested changes

2016-10-26 07:33 UTC, nabinhait commented on erpnext/stock/doctype/stock_entry/stock_entry.js
> +cur_frm.cscript.qty = function(doc, cdt, cdn) {
Always use `frappe.ui.form.on`

2016-10-26 07:33 UTC, nabinhait commented on erpnext/stock/doctype/stock_entry/stock_entry.js
> +		var d = locals[cdt][cdn];
return if no `s_warehouse && item_code && qty`

2016-10-26 07:33 UTC, nabinhait commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +		if args.get('fetch_serial_no'):
Actually it does not make any sense, as qty is always zero.

2016-10-26 07:33 UTC, nabinhait commented on erpnext/stock/get_item_details.py
> +def get_serial_nos_by_fifo(args, item_doc = None):
`item_doc` is not used

2016-10-26 09:29 UTC, KanchanChauhan commented on erpnext/stock/get_item_details.py
> +def get_serial_nos_by_fifo(args, item_doc = None):
All changes done

2016-10-26 11:01 UTC, nabinhait approved these changes

2016-10-26 11:01 UTC, merged