Minor fixes
frappe/erpnext pull request #6799
Opened 2016-11-02 02:06 UTC by rmehta

2016-11-02 04:41 UTC, nabinhait requested changes

2016-11-02 04:41 UTC, nabinhait commented on erpnext/schools/doctype/academic_term/academic_term.py
> +        if self.term_end_date and get_datetime_(year.year_end_date) and (self.term_end_date > get_datetime(year.year_end_date)):
get_datetime_ ?

2016-11-02 05:24 UTC, rmehta commented on erpnext/schools/doctype/academic_term/academic_term.py
> +        if self.term_end_date and get_datetime_(year.year_end_date) and (self.term_end_date > get_datetime(year.year_end_date)):
thanks! fixed :)

2016-11-03 05:10 UTC, nabinhait approved these changes

2016-11-03 05:10 UTC, merged