Credit Note, Debit Note, Excise Entry info added
frappe/erpnext pull request #6833
Opened 2016-11-05 09:09 UTC by KanchanChauhan

Fixed https://github.com/frappe/erpnext/issues/6512

2016-11-07 11:37 UTC, rmehta requested changes

2016-11-07 11:37 UTC, rmehta commented on erpnext/docs/user/manual/en/accounts/journal-entry.md
> +#### Excise Entry
This is only for India, maybe this should be a separate article (maybe we should have separate sections for country-wise pages)

2016-11-07 11:37 UTC, rmehta commented on erpnext/docs/user/manual/en/accounts/journal-entry.md
> +Credit note is a note which is given to the customer when we get his returned
Try and use gender neutral language, also documentation is best written in 3rd person.

`"Credit Note" is made for a Customer against a Sales Invoice when the company needs to refund or adjust a payment. When a Credit Note is made, the seller can either make a payment to the customer or adjust the amount in another invoice.`

2016-11-07 11:37 UTC, rmehta commented on erpnext/docs/user/manual/en/accounts/journal-entry.md
> +
Screenshot would be better!

2016-11-07 12:38 UTC, KanchanChauhan commented on erpnext/docs/user/manual/en/accounts/journal-entry.md
> +Credit note is a note which is given to the customer when we get his returned
Sales Invoice or Sales Return?

2016-11-07 17:43 UTC, KanchanChauhan commented on erpnext/docs/user/manual/en/accounts/journal-entry.md
> +#### Excise Entry
Added a note, since option is available for other countries as well.

2016-11-09 06:11 UTC, nabinhait approved these changes

2016-11-09 06:12 UTC, merged