[Fix] Fetch Serial No by default for  Delivery Note Item
frappe/erpnext pull request #6920
Opened 2016-11-13 15:50 UTC by KanchanChauhan

Fixed https://github.com/frappe/erpnext/issues/6706

2016-11-16 08:57 UTC, nabinhait requested changes

2016-11-16 08:57 UTC, nabinhait commented on erpnext/stock/doctype/delivery_note/delivery_note.js
> +		d.qty||(d.qty=1)
???

2016-11-16 08:57 UTC, nabinhait commented on erpnext/stock/doctype/delivery_note/delivery_note.js
> +		if(!d.item_code && !d.warehouse && !d.qty) return;
all the 3 fields are mandatory right? In that case, condition should be based on "OR"

2016-11-16 08:57 UTC, nabinhait commented on erpnext/stock/doctype/delivery_note/delivery_note.js
> +	set_serial_no: function(doc, cdt, cdn) {
use `frm` instead of `doc` in args

2016-11-17 07:05 UTC, KanchanChauhan commented
Changes done

2016-11-22 12:08 UTC, KanchanChauhan commented
Call set_serial_no from server side

2016-12-05 11:21 UTC, nabinhait approved these changes

2016-12-05 11:21 UTC, merged