User can able to add multiple item group, customer group in the POS profile.
frappe/erpnext pull request #6969
Opened 2016-11-16 18:45 UTC by rohitwaghchaure

2016-11-17 04:19 UTC, rmehta requested changes
Add test cases

2016-11-17 04:19 UTC, rmehta commented on erpnext/accounts/doctype/sales_invoice/pos.py
> +	cond = "1=1"
Add docstrings

2016-11-17 08:08 UTC, rohitwaghchaure commented
Done

2016-11-21 09:56 UTC, nabinhait approved these changes

2016-11-21 09:57 UTC, merged