Bug due Translation support in Support Analytics
frappe/erpnext pull request #7068
Opened 2016-11-25 02:36 UTC by MaxMorais

I think no one that don't speak english use this!
But today talking about this report, I discovered that it dont work!

For my surprise, it don't work have 2 years, if you aren't a english speaker!

2016-11-25 05:50 UTC, nabinhait requested changes
@MaxMorais Can you please send this PR to hotfix branch?

2016-11-25 10:44 UTC, rmehta approved these changes

2016-11-28 07:11 UTC, nabinhait approved these changes

2016-11-28 07:11 UTC, merged

2016-11-28 07:11 UTC, nabinhait commented
merged, will cherry-pick into hotfix branch