[Enhancement] Budget Against Project #7036
frappe/erpnext pull request #7094
Opened 2016-11-28 17:37 UTC by manassolanki

Budget Allocation for project and validate before every Journal Entry with linked project
#6560

2016-12-07 09:32 UTC, rmehta requested changes

2016-12-07 09:32 UTC, rmehta commented on erpnext/accounts/doctype/budget/budget.py
use `-` as a separator for naming series instead of `/`

2016-12-07 09:32 UTC, rmehta commented on erpnext/accounts/doctype/budget/budget.py
>  		self.validate_duplicate()
Why not make the field mandatory?

2016-12-07 11:46 UTC, manassolanki commented on erpnext/accounts/doctype/budget/budget.py
>  		self.validate_duplicate()
This is because we have to make budget either against project or cost center mandatory, not for both of them.

2016-12-07 13:07 UTC, manassolanki commented on erpnext/accounts/doctype/budget/budget.py
Actually there is  -  already in cost center and fiscal year naming so using that again make it very hard to understand the name.
Ex.  Mumbai - MPC/2016-2017/001

2016-12-08 08:22 UTC, nabinhait approved these changes

2016-12-08 08:22 UTC, merged