[WIP] Employee Loan Management
frappe/erpnext pull request #7126
Opened 2016-12-02 09:17 UTC by KanchanChauhan

2017-01-05 04:23 UTC, rmehta requested changes

2017-01-05 04:23 UTC, rmehta commented on erpnext/docs/user/manual/en/human-resources/employee-loan-management.md
> +
Don't use the term EMI - call it "Repayment". In general always avoid acronyms!

@KanchanChauhan @nabinhait

2017-01-09 07:19 UTC, KanchanChauhan commented
@rmehta @nabinhait Done.

2017-01-16 06:27 UTC, nabinhait requested changes
Accounting Entry missing on submission of Employee Loan and Salary Slip.

2017-01-16 06:27 UTC, nabinhait commented on erpnext/hr/doctype/employee_loan/test_employee_loan.py
> +					"rate_of_interest": 8.4,
Don't pass all these values, instead in `validate` of employee_loan, set those values if missing.

2017-01-16 06:27 UTC, nabinhait commented on erpnext/hr/doctype/employee_loan/test_employee_loan.py
> +		self.assertEquals(employee_loan.repayment_schedule[14].balance_loan_amount, 73699)
Make it a for loop, for better readability.

2017-01-16 06:27 UTC, nabinhait commented on erpnext/hr/doctype/employee_loan/test_employee_loan.py
> +					"repayment_method": "Repay Over Number of Periods",
Write a test case for "Repay Fixed Amount Every Month"

2017-01-16 06:27 UTC, nabinhait commented on erpnext/hr/doctype/salary_slip/salary_slip.py
> +		employee_loans = frappe.db.sql("""select * from `tabRepayment Schedule`
Never select *, use specific column names.

2017-01-16 06:27 UTC, nabinhait commented on erpnext/hr/doctype/employee_loan/employee_loan.json
> +   "label": "Include in Salary Slip",
Repay from Salary?

2017-01-16 06:27 UTC, nabinhait commented on erpnext/hr/doctype/salary_slip/salary_slip.py
> +				self.loan_repayment =+  employee_loan.total_payment
Why processing in python? Use `sum(repayment_amount)` in query.

2017-01-16 06:29 UTC, nabinhait commented
Test Case for loan amount in salary slip

2017-01-30 09:39 UTC, rmehta approved these changes

2017-01-30 09:45 UTC, rmehta approved these changes

2017-01-30 09:45 UTC, merged