[Enhancement] Auto book of an employee's expense claim
frappe/erpnext pull request #7267
Opened 2016-12-19 18:31 UTC by rohitwaghchaure

2017-01-04 09:43 UTC, nabinhait commented
@rohitwaghchaure Is it ready to merge?

2017-01-04 09:43 UTC, nabinhait commented
test case is failing

2017-01-04 17:33 UTC, rohitwaghchaure commented
@nabinhait Travis is fixed

2017-01-16 07:26 UTC, nabinhait requested changes

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/doctype/journal_entry/journal_entry.py
> +		exchange_rate = get_exchange_rate(ref_doc.posting_date, args.get("party_account"), args.get("party_account_currency"),
ref_doc.get("posting_date") or ref_doc.get("transaction_date")

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/doctype/journal_entry/journal_entry.py
> +		bank_row.exchange_rate = get_exchange_rate(ref_doc.posting_date, bank_account["account"],
ref_doc.get("posting_date") or ref_doc.get("transaction_date")

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/doctype/payment_entry/payment_entry.js
> +		frm.set_query("party_type", function() {
set_query not needed

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.js
> +		this.frm.set_query("party_type", function() {
set_query not needed

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/party.py
> +		if not account and party_type != 'Employee':
Use explicit condition `if not account and party_type in ('Customer', 'Supplier')`

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/party.py
> +		if not account and party_type != 'Employee':
same as above

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/report/general_ledger/general_ledger.js
>  			"fieldtype": "Select",
make it link field, linked to Party Type

2017-01-16 07:26 UTC, nabinhait commented on erpnext/accounts/report/unpaid_expense_claim/unpaid_expense_claim.py
> +			and gle.party is not null and ec.docstatus = 1 and {cond} group by ec.name
and ec.is_paid = 0 ???

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/employee/employee.json
> +   "fieldname": "is_frozen",
why needed?

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/employee/employee.json
> +   "fieldtype": "Data",
Data?

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.js
> +					"report_type": "Balance Sheet",
Use root_type="Liability" and account_type="Payable"

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		if self.total_sanctioned_amount == self.total_amount_reimbursed and self.docstatus == 1:
less than equal to

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		if self.total_sanctioned_amount == self.total_amount_reimbursed and self.docstatus == 1:
or is_paid

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +			self.payable_account = frappe.db.get_value("Company", self.company, "default_expense_payable")
use default_payable_account field

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		if self.is_paid:
If is_paid, make both debit and credit entry for party_account, like POS

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +					"against_voucher_type": self.doctype,
against_voucher_type and against_voucher is only used against party, mainly to calculate outstanding, in this case can be used for reimbursement_amount

2017-01-16 07:26 UTC, nabinhait commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		and party is null """, doc.name ,as_dict=1)[0].amt
party is not null??

calculate based on party and excluding this voucher

2017-01-16 07:26 UTC, nabinhait commented on erpnext/patches/v7_2/update_party_type.py
> +def execute():
Only make party type for existing accounts.

2017-01-16 07:26 UTC, nabinhait commented on erpnext/setup/doctype/company/company.js
> +		frm.fields_dict['default_expense_payable'].get_query = function() {
not needed

2017-01-16 07:26 UTC, nabinhait commented on erpnext/setup/doctype/company/company.json
> +   "fieldname": "default_expense_payable",
not needed

2017-01-16 07:26 UTC, nabinhait commented on erpnext/setup/doctype/company/company.py
> +		if not self.default_expense_payable:
not needed

2017-01-16 07:26 UTC, nabinhait commented on erpnext/setup/doctype/party_type/party_type.json
> +   "role": "Administrator",
Administrator?

Give access to Accounts User and Accounts Manager roles

2017-01-16 07:26 UTC, nabinhait commented on erpnext/setup/doctype/party_type/party_type.py
> +def get_party_type(doctype, txt, searchfield, start, page_len, filters):
not needed

2017-01-19 11:01 UTC, rohitwaghchaure commented on erpnext/hr/doctype/expense_claim/expense_claim.py
> +		if self.total_sanctioned_amount == self.total_amount_reimbursed and self.docstatus == 1:
If is_paid is off and user has paid using journal entry

2017-02-01 06:32 UTC, merged