Create User button in Employee if no User ID selected
frappe/erpnext pull request #7279
Opened 2016-12-20 08:57 UTC by KanchanChauhan

Fixed https://github.com/frappe/erpnext/issues/7173

2016-12-21 06:10 UTC, nabinhait requested changes

2016-12-21 06:10 UTC, nabinhait commented on erpnext/hr/doctype/employee/employee.json
> + "icon": "icon-user",
why icon has been overwritten? Seems like, your local sites has not migrated.

2016-12-21 06:10 UTC, nabinhait commented on erpnext/hr/doctype/employee/employee.py
> +	user.save()
user should be enabled?

Also, why use mapper for this? May be `new_doc` will be sufficient and cleaner in this case.

2016-12-21 10:48 UTC, KanchanChauhan commented on erpnext/hr/doctype/employee/employee.json
> + "icon": "icon-user",
This is some issue, every time you change something in doctype, it changes back to icon-user.

2016-12-21 10:48 UTC, KanchanChauhan commented on erpnext/hr/doctype/employee/employee.py
> +	user.save()
Done

2016-12-23 10:01 UTC, nabinhait approved these changes

2016-12-23 10:01 UTC, merged