Report : Batch Item Expiry Status
frappe/erpnext pull request #7284
Opened 2016-12-21 07:24 UTC by revant

- Select From Date and To Date
- Lists Item Batches about to expire or already expired
- Expiry Status column shows number of days in which item/batch will expire

2016-12-21 08:01 UTC, rmehta requested changes

2016-12-21 08:01 UTC, rmehta commented on erpnext/stock/report/batch_item_expiry_status/batch_item_expiry_status.py
> +			qty_dict.expiry_status = "Expires in {} day(s)".format(expires_in_days)
translatable ? `_(""Expires in {} day(s)")`

2016-12-21 08:38 UTC, revant commented on erpnext/stock/report/batch_item_expiry_status/batch_item_expiry_status.py
> +			qty_dict.expiry_status = "Expires in {} day(s)".format(expires_in_days)
![columnrename](https://cloud.githubusercontent.com/assets/1040161/21382431/a0005e02-c786-11e6-82c4-787e5d4e4883.png)

How about renaming the column to (already translatable) "Expiry (In Days)" and data as plain int?

2016-12-21 08:46 UTC, rmehta commented on erpnext/stock/report/batch_item_expiry_status/batch_item_expiry_status.py
> +			qty_dict.expiry_status = "Expires in {} day(s)".format(expires_in_days)
Cool that works better!

Btw there is a better way using `get_columns` using JSON 

https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/report/profitability_analysis/profitability_analysis.py#L121

2016-12-26 10:40 UTC, nabinhait approved these changes

2016-12-26 10:40 UTC, merged

2016-12-27 15:37 UTC, mdwala commented
Isn't available quantity per batch is most required field for all?