[minor] Show Item quantity (Actual) in warehouse set query
frappe/erpnext pull request #7467
Opened 2017-01-12 12:31 UTC by suyashphadtare

Currently Applicable For Sales Order/Delivery Note Item child table warehouse link.

![image](https://cloud.githubusercontent.com/assets/10596607/21889696/4792b640-d8f0-11e6-89e2-a669f6c2fafb.png)

Note - If there is no entry for specified item in BIN doctype then warehouse link will not show any warehouses.

2017-01-17 06:04 UTC, nabinhait commented
We should show all warehouses in the Sales Order irrespective of it has qty available or not. Because, after getting SO, we can make or purchase those items and deliver later.

2017-01-17 06:05 UTC, nabinhait requested changes
We should show all warehouses in the Sales Order irrespective of it has qty available or not. Because, after getting SO, we can make or purchase those items and deliver later.

2017-01-18 11:16 UTC, suyashphadtare commented
I have made changes so all warehouses will be shown in Sales Order.
For Delivery Note, iI have kept same sql query so all warehouses will show in drop-down.

2017-01-30 07:03 UTC, rmehta commented on erpnext/controllers/queries.py
> +								CONCAT_WS(" : ", "Actual Qty", ifnull( ({sub_query}), 0) ) as actual_qty
so much whitespace on the left causes un-necessary scrolling

2017-02-01 05:22 UTC, suyashphadtare commented
I have removed unnecessary whitespace.

2017-02-09 06:19 UTC, nabinhait commented
@suyashphadtare Can you please rebase your commits? There are lot of unwanted commits included into this PR.

2017-02-10 14:21 UTC, suyashphadtare commented
@nabinhait I have rebased my commits.

2017-02-20 13:37 UTC, nabinhait approved these changes

2017-02-20 13:40 UTC, merged