chart of account ordered using shown_number + auto generate shown_num…
frappe/erpnext pull request #7505
Opened 2017-01-16 10:39 UTC by ahmadRagheb

…ber based on tree level

2017-01-30 06:52 UTC, rmehta commented
please share a screenshot / animated GIF of this feature

2017-01-30 06:56 UTC, rmehta requested changes

2017-01-30 06:56 UTC, rmehta commented on erpnext/accounts/report/financial_statements.py
> +		# if a.report_type != b.report_type and a.report_type == "Balance Sheet":
please don't keep commented code.

Also this feature should work with / without account numbers

2017-01-30 06:56 UTC, rmehta commented on erpnext/accounts/utils.py
> +#added by ahmad ragheb
we don't add names in code, your authorship will be in the commit log

2017-01-30 06:56 UTC, rmehta commented on erpnext/accounts/utils.py
> +		bb3 = frappe.db.sql(query, as_dict=1)
use descriptive variable names

2017-01-30 06:56 UTC, rmehta commented on erpnext/accounts/utils.py
> +			have_brothers = False
`sibings` and `parent`! (lets be gender neutral)

2017-04-14 04:57 UTC, nabinhait commented
Closing this as per https://github.com/frappe/erpnext/wiki/Pull-Request-Guidelines. Please reopen after making suggested changes.

2017-04-14 04:57 UTC, closed without merging