Patch to update Salary Detail where Salary Component Abbr is null
frappe/erpnext pull request #7561
Opened 2017-01-22 05:34 UTC by KanchanChauhan

Edits to Salary slips generated before abbr was added Salary Component  was not possible.
<img width="420" alt="screen shot 2017-01-22 at 11 03 09 am" src="https://cloud.githubusercontent.com/assets/16913064/22180310/7c0f0cda-e092-11e6-8813-fb86304c6aea.png">

2017-01-23 07:25 UTC, nabinhait commented on erpnext/patches/v7_2/update_abbr_in_salary_slips.py
> +		frappe.db.sql("""update `tabSalary Detail` set abbr = %s""",(salary_component_abbr))
`Where` condition is missing.

2017-01-23 07:25 UTC, nabinhait requested changes
Where condition is missing.

2017-01-23 09:03 UTC, KanchanChauhan commented
Done

2017-01-24 04:54 UTC, rohitwaghchaure approved these changes

2017-01-25 11:53 UTC, nabinhait approved these changes

2017-01-25 11:53 UTC, merged