[Fix] Account filter in Process Payroll and Salary Component
frappe/erpnext pull request #7614
Opened 2017-01-30 11:13 UTC by KanchanChauhan

2017-01-30 11:32 UTC, rmehta requested changes

2017-01-30 11:32 UTC, rmehta commented on erpnext/hr/doctype/salary_component/salary_component.js
> +cur_frm.set_query("default_account", "accounts", function(doc, cdt, cdn) {
never use `cur_frm` !

add this in `setup` event

2017-01-30 11:39 UTC, KanchanChauhan commented on erpnext/hr/doctype/salary_component/salary_component.js
> +cur_frm.set_query("default_account", "accounts", function(doc, cdt, cdn) {
Done

2017-01-30 11:39 UTC, rmehta approved these changes

2017-02-02 08:18 UTC, nabinhait requested changes

2017-02-02 08:18 UTC, nabinhait commented on erpnext/hr/doctype/salary_component/salary_component.js
> +			var account_types = ["Bank", "Cash"];
Account type linked to salary company is not bank / cash, it should be Expense account (root_type="Expense")

2017-02-02 09:12 UTC, KanchanChauhan commented on erpnext/hr/doctype/salary_component/salary_component.js
> +			var account_types = ["Bank", "Cash"];
Added both account_type and root_type

2017-02-06 06:06 UTC, nabinhait approved these changes

2017-02-06 06:06 UTC, merged