[Fix] Set default tax on quotation when it's making from the lead
frappe/erpnext pull request #7654
Opened 2017-02-02 11:48 UTC by rohitwaghchaure

2017-02-06 06:27 UTC, nabinhait requested changes

2017-02-06 06:27 UTC, nabinhait commented on erpnext/controllers/selling_controller.py
> +		self.set_other_charges()
@rohitwaghchaure Why so? This code applies to all sales transactions which is not intended.

2017-02-06 06:44 UTC, rohitwaghchaure commented on erpnext/controllers/selling_controller.py
> +		self.set_other_charges()
Fixed

2017-02-09 06:09 UTC, nabinhait approved these changes

2017-02-09 06:13 UTC, merged