[Fix] Cleanup supplied items if supply raw material is set as No
frappe/erpnext pull request #7764
Opened 2017-02-16 11:54 UTC by rohitwaghchaure

2017-02-16 12:54 UTC, nabinhait requested changes

2017-02-16 12:54 UTC, nabinhait commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
> +		frm.set_value("supplied_items", [])
Don't make `supplied_items` blank here.

Instead, set blank on the server side https://github.com/frappe/erpnext/blob/master/erpnext/controllers/buying_controller.py#L163

2017-02-17 07:03 UTC, rohitwaghchaure commented on erpnext/accounts/doctype/purchase_invoice/purchase_invoice.js
> +		frm.set_value("supplied_items", [])
Done

2017-02-17 07:05 UTC, nabinhait approved these changes

2017-02-17 07:06 UTC, merged