Add Sales Orders to Project costing and billing section
frappe/erpnext pull request #7842
Opened 2017-02-24 01:49 UTC by superlack

To provide the same level of "dashboard" financial tracking for projects to work alongside external clients that use PO's

2017-02-24 07:31 UTC, nabinhait commented on erpnext/selling/doctype/sales_order/sales_order.py
> +		for d in self.items:
"Project" field does not exists in Sales Order Item table, it is in the parent table.

2017-02-24 07:31 UTC, nabinhait requested changes
Travis failing

2017-02-24 14:46 UTC, superlack commented
Will fix, originally tested with "total" fields in SO.  Thanks

2017-02-24 21:49 UTC, superlack commented
I fixed the errors (to the best of my knowledge), but Travis is showing errors on the following
`test_overlap_with_half_day (erpnext.hr.doctype.leave_application.test_leave_application.TestLeaveApplication) ... ERROR
test_overlap_with_half_day_not_applicable (erpnext.hr.doctype.leave_application.test_leave_application.TestLeaveApplication) ... ERROR`

2017-02-27 07:00 UTC, nabinhait commented on erpnext/projects/doctype/project/project.py
> +		total_sales_cost = frappe.db.sql("""select sum(total)
Should not it be `grand_total`?

2017-02-27 14:48 UTC, superlack commented on erpnext/projects/doctype/project/project.py
> +		total_sales_cost = frappe.db.sql("""select sum(total)
You're right, I was thinking about how the billing hours don't show taxes, but those are further malleable unlike SO/SINV

2017-03-01 11:21 UTC, superlack commented
I hope that's everything

2017-03-01 11:50 UTC, nabinhait approved these changes

2017-03-01 11:50 UTC, merged