Multiple Salary Fixes
frappe/erpnext pull request #7952
Opened 2017-03-08 06:39 UTC by KanchanChauhan

- [ ] Formula and condition takes changes in Salary Slip into consideration
- [ ] Same employee cannot be in multiple active Salary Structure for same time period
- [ ] Calculations done based on joining date and relieving date

Fixed https://github.com/frappe/erpnext/issues/7924

2017-03-08 08:57 UTC, nabinhait requested changes
Check inline comments

2017-03-08 08:57 UTC, nabinhait commented on erpnext/hr/doctype/salary_slip/salary_slip.py
> +			self.add_earning_for_hourly_wages(self._salary_structure_doc, self._salary_structure_doc.salary_component, wages_amount)
This is not required now, because we have updated salary slip earnings and deductions into "data".

2017-03-08 08:57 UTC, nabinhait commented on erpnext/hr/doctype/salary_structure/salary_structure.py
> +			or (%s between from_date and ifnull(to_date, '2199-12-31')))
There should be another condition ` or from_date between %(from_date)s and %(to_date)`

2017-03-08 09:57 UTC, KanchanChauhan commented on erpnext/hr/doctype/salary_slip/salary_slip.py
> +			self.add_earning_for_hourly_wages(self._salary_structure_doc, self._salary_structure_doc.salary_component, wages_amount)
Done

2017-03-09 06:12 UTC, nabinhait requested changes

2017-03-09 06:12 UTC, nabinhait commented on erpnext/hr/doctype/salary_structure/salary_structure.py
> +			and parent in (select name from `tabSalary Structure`
"in" query becomes very slow if there are too many values in sub query.

Instead you can write like this:
`and exists(select name from `tabSalary Structure` where name=`tabSalary Structure Employee`.parent and is_active = 'Yes') and parent != %(salary_struct)s`

2017-03-12 11:18 UTC, merged