Add link field Device Package Code (fixes #8094)
frappe/erpnext pull request #8126
Opened 2017-03-23 18:54 UTC by kickapoo

2017-03-24 07:46 UTC, kickapoo commented
@nabinhait  From the fail on the Travis integration (and as far as I can understand) the test fail to something else. 
Can you please check

2017-03-24 07:52 UTC, nabinhait commented
@kickapoo Yes, I have already pushed a fix for it.

2017-03-24 07:59 UTC, kickapoo commented
@nabinhait So I have to rebase for the pull ?

2017-03-24 08:00 UTC, nabinhait commented
Yes I think.

2017-03-24 08:03 UTC, nabinhait commented
By the way, can we call it "Package Code" only? It should be more generic in nature, can be used for non-device items.

2017-03-24 08:05 UTC, kickapoo commented
@dottenbr  Please check the namespace issue @nabinhait  states on the above message

2017-03-24 12:21 UTC, dottenbr commented
I am fine with Package Code or Device Package Code ... both are fine with me

2017-03-27 17:54 UTC, dottenbr commented
this should be easy to merge, is a requirement for our data import

2017-03-28 08:24 UTC, nabinhait requested changes

2017-03-28 08:24 UTC, nabinhait commented on erpnext/stock/doctype/package_code/package_code.json
> +   "role": "System Manager",
Instead of System Manager, the permission should be applied for "Stock User" and "Stock Manager"

2017-03-28 13:36 UTC, kickapoo commented
@nabinhait recheck please

2017-03-28 15:18 UTC, nabinhait approved these changes

2017-03-28 15:18 UTC, merged

2017-03-31 09:05 UTC, rmehta commented
@kickapoo @dottenbr @nabinhait  I think this was an example of a bad merge. We need correct use case, documentation, test cases and the feature needs to be linked to the overall workflow.

Let us not do half-baked features. This is where the problem starts.

I am reverting this PR