Add Short Code field (fixes #8099)
frappe/erpnext pull request #8179
Opened 2017-03-28 08:38 UTC by kickapoo

Please @nabinhait  review :)

2017-03-31 12:45 UTC, nabinhait commented
- [ ] How is short code used? This is just creating the short code, not linked to any workflow yet
- [ ] Test cases?

A broader discussion, can we do without short codes completely? Is this global search in v8 is pretty good!

2017-03-31 12:45 UTC, nabinhait requested changes

2017-03-31 12:45 UTC, nabinhait commented on erpnext/selling/doctype/customer/customer.py
> +	new_sc = ''
put this in short_code.py (files this long should be separated)

2017-04-04 09:47 UTC, kickapoo commented
Short Code is self explained. Customer has a short code like: Frappe Inc --> FRI. 
Please @nabinhait provide documentation file path so @dottenbr can take over and add the proper explanation. 
I will add Test Cases. 
@nabinhait Blacklist can't be bootstraped, mayde someone want KKK as short code. Its up to the "someone".

2017-04-05 03:27 UTC, rmehta commented
@kickapoo  we still need workflow linked (where is this used???) No point having just made a feature that is unconnected.

2017-04-05 12:40 UTC, kickapoo commented
@dottenbr  please take over on @rmehta comment.

2017-04-06 10:19 UTC, dottenbr commented
Customer Short Code is used for searching in quotations, sales orders. It will also be used at ESO to generate assembly numbers (item numbers). If you don't see this as useful to others we can make it a customization. We should decide these things before we implement it though.

2017-04-06 10:21 UTC, rmehta commented
This point is not whether its useful, whether its complete.

2017-04-06 10:30 UTC, kickapoo commented
@rmehta if you aren't donna use it there is not reason to complete it and spend time on it. I can write the Unit Tested that are requested for this.

So please clearify the final call with won't merge flag or not so we can schedule our eso-internal features.

2017-04-06 10:33 UTC, rmehta commented
Its not about me using it. At this point, you are not using it either 😅

2017-04-06 11:19 UTC, dottenbr commented
It is not complete but we have a path to how to use it. We are using it 100% and we need it but we don't have it because we designed it as a contribution rather than a customization.

Do you want this in or out @rmehta?

Why was this closed @kickapoo?

2017-04-14 05:56 UTC, nabinhait commented
Closing this as per https://github.com/frappe/erpnext/wiki/Pull-Request-Guidelines. Please reopen after implementing workflow.

2017-04-14 05:56 UTC, closed without merging