[WIP] [Enhancement] Employee Address moved to Address
frappe/erpnext pull request #8205
Opened 2017-03-29 11:53 UTC by KanchanChauhan

2017-04-13 14:06 UTC, nabinhait requested changes

2017-04-13 14:06 UTC, nabinhait commented on erpnext/patches/v8_0/employee_address_update.py
> +						where
don't use so many tabs, use only one extra tab

2017-04-13 14:06 UTC, nabinhait commented on erpnext/patches/v8_0/employee_address_update.py
> +	address = address.split("\n")
lets call it address_lines

2017-04-13 14:06 UTC, nabinhait commented on erpnext/patches/v8_0/employee_address_update.py
> +	new_address.insert()
Set flags for `ignore_validate` and `ignore_mandatory`

2017-04-14 06:26 UTC, KanchanChauhan commented
@nabinhait All done

2017-05-11 08:15 UTC, nabinhait commented
there is a huge chance to map the data in wrong field and also a chance to loosing data. Closing the PR

2017-05-11 08:15 UTC, closed without merging