Rename DocType LetterHead (fixes #8110)
frappe/erpnext pull request #8266
Opened 2017-03-31 10:01 UTC by kickapoo

2017-04-05 12:42 UTC, dottenbr commented
LetterHead should be Letterhead

2017-04-06 10:02 UTC, nabinhait requested changes
- You need to search and replace in the code.
- While renaming a doctype using `rename_doc` function, it will replace all the field's "Options" value wherever Letterhead is linked to. But it will not change teh underline json files. You need to save those doctype manually or using script to update the json.

2017-04-06 10:06 UTC, kickapoo commented
@nabinhait 
If I understand correct. Rename_doc as patch still remains but I have to manually search and replace the name to ? frappe and erpnext folders? only erpnext ?

2017-04-06 10:14 UTC, kickapoo commented
@nabinhait Recheck

2017-04-06 10:38 UTC, nabinhait requested changes
- You need to manually correct the files for Letterhead doctype. You can save the letterehead doctype, it will create the directory. Then you can copy the codes from existing old directory, if code exists. And then delete the old directory.
- I also think, we should call it "Letterhead", instead of "LetterHead". @dottenbr @rmehta Can you suggest?

2017-04-06 10:38 UTC, nabinhait commented on erpnext/patches/v8_0/rename_letterhead_doctype.py
> +    old_name = 'LetterHead'
old_name is "Letter Head"

2017-04-06 10:38 UTC, nabinhait commented on erpnext/patches/v4_0/reset_permissions_for_masters.py
> +		"HR Settings", "Industry Type", "Leave Type", "LetterHead",
When this patch will run, it is still "Letter Head"

2017-04-06 10:38 UTC, nabinhait commented on erpnext/accounts/doctype/journal_entry/journal_entry.json
> +   "label": "LetterHead",
You need to change "modified" date-stamp as well in all json, otherwise it will not be reloaded with `bench update`.

2017-04-06 10:48 UTC, kickapoo commented
I closing this one. I am not in to replacing file names and copy pasting directories. Its seems to me that is a process that can take the core team 5 minutes to resolve.

2017-04-06 10:48 UTC, closed without merging