[fix] Auto serial no fecthed on the invoice even if stock update is disabled issue
frappe/erpnext pull request #8292
Opened 2017-04-03 08:47 UTC by rohitwaghchaure

2017-04-04 04:15 UTC, nabinhait requested changes

2017-04-04 04:15 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +								stock_qty = item.get('stock_qty') * -1 if item.get('stock_qty') < 0 else item.get('stock_qty')
`stock_qty` field does not exists in Purchase Invoice

2017-04-04 04:15 UTC, nabinhait commented on erpnext/public/js/controllers/transaction.js
> +			"update_stock": (me.frm.doc.doctype == 'Sales Invoice') ? cint(me.frm.doc.update_stock) : 0
also applicable to purchase invoice?

2017-04-04 04:15 UTC, nabinhait commented on erpnext/stock/get_item_details.py
> +		"update_stock": args.get("update_stock") if args.get('doctype') == 'Sales Invoice' else 0,
PI?

2017-04-04 04:15 UTC, nabinhait commented on erpnext/stock/get_item_details.py
> +	if args.get('doctype') == 'Sales Invoice' and not args.get('update_stock'):
PI?

2017-04-04 04:15 UTC, nabinhait commented on erpnext/stock/get_item_details.py
> +	if out.uom != args.uom:
always set conversion_factor and stock_qty, even if sales uom and stock uom is same.

2017-04-13 13:25 UTC, nabinhait requested changes

2017-04-13 13:25 UTC, nabinhait commented on erpnext/controllers/accounts_controller.py
> +								qty_field = "qty" if ret.doctype == 'Purchase Invoice' else "stock_qty"
Can you fix this, as now we have stock_qty field in Purchase Invoice Item?

2017-04-14 12:15 UTC, rohitwaghchaure commented on erpnext/controllers/accounts_controller.py
> +								qty_field = "qty" if ret.doctype == 'Purchase Invoice' else "stock_qty"
Fixed

2017-04-17 08:25 UTC, nabinhait approved these changes

2017-04-17 08:26 UTC, nabinhait requested changes

2017-04-17 08:26 UTC, nabinhait commented on erpnext/patches.txt
> +execute:frappe.db.sql("update `tabSales Invoice Item` set serial_no = '' where parent in (select name from `tabSales Invoice` where update_stock = 0 and docstatus = 1)")
Put this patch in a separate file. Anything lengthy should be inside a file.

2017-04-17 10:51 UTC, rohitwaghchaure commented on erpnext/patches.txt
> +execute:frappe.db.sql("update `tabSales Invoice Item` set serial_no = '' where parent in (select name from `tabSales Invoice` where update_stock = 0 and docstatus = 1)")
Fixed!

2017-04-17 12:01 UTC, nabinhait approved these changes

2017-04-17 12:01 UTC, merged