Salutation and Gender in Lead and Customer
frappe/erpnext pull request #8351
Opened 2017-04-06 11:41 UTC by KanchanChauhan

Fixed https://github.com/frappe/erpnext/issues/8145

2017-04-06 11:54 UTC, rmehta requested changes

2017-04-06 11:54 UTC, rmehta commented on erpnext/crm/doctype/lead/lead.json
> +   "options": "\nMale\nFemale",
other?

2017-04-06 11:59 UTC, KanchanChauhan commented on erpnext/crm/doctype/lead/lead.json
> +   "options": "\nMale\nFemale",
If we do others, we need to give text box to mention the other gender. Blank field is better I think.

2017-04-06 12:01 UTC, rmehta commented on erpnext/crm/doctype/lead/lead.json
> +   "options": "\nMale\nFemale",
blank is unknown / not set ... other is other!

2017-04-06 12:05 UTC, KanchanChauhan commented on erpnext/crm/doctype/lead/lead.json
> +   "options": "\nMale\nFemale",
Done

2017-04-24 13:40 UTC, nabinhait commented
Closing this as it depends on https://github.com/frappe/frappe/pull/3079 which is closed.

2017-04-24 13:40 UTC, closed without merging