[fix] Vehicle expense report not working
frappe/erpnext pull request #8385
Opened 2017-04-10 06:39 UTC by rohitwaghchaure

2017-04-10 09:17 UTC, nabinhait requested changes

2017-04-10 09:17 UTC, nabinhait commented on erpnext/hr/report/vehicle_expenses/vehicle_expenses.js
> -			},
As you have removed from_date and to_date filters, there is no point of setting those filter values on change of fiscal _year.

2017-04-10 09:17 UTC, nabinhait commented on erpnext/hr/report/vehicle_expenses/vehicle_expenses.py
> +		vhcl.location as "Location",log.name as "Log",log.odometer as "Odometer",log.date as "Date",
Use space after comma. In this case, use separate line for each column.

2017-04-11 09:21 UTC, rohitwaghchaure commented on erpnext/hr/report/vehicle_expenses/vehicle_expenses.js
> -			},
fy = frappe.db.get_value('Fiscal Year', filters.get('fiscal_year'), ['year_start_date', 'year_end_date'], as_dict=True)
Fetched start date and end date from the fiscal year

2017-04-11 09:22 UTC, rohitwaghchaure commented on erpnext/hr/report/vehicle_expenses/vehicle_expenses.py
> +		vhcl.location as "Location",log.name as "Log",log.odometer as "Odometer",log.date as "Date",
Fixed

2017-04-11 13:24 UTC, merged