Fix for 8466
frappe/erpnext pull request #8470
Opened 2017-04-17 08:04 UTC by PawanMeh

Use Case

1. Track conversion ratios from Lead to Opportunity, Opportunity to Quotation, Quotation to Order and Order value generated by Leads. The analysis generally is done by Campaign and Lead Owner to determine efficiency of Campaigns and Leads.

![campaign_efficiency](https://cloud.githubusercontent.com/assets/20460498/25083054/66f23340-2372-11e7-8747-f61b70a8bcde.png)

![lead owner efficiency](https://cloud.githubusercontent.com/assets/20460498/25083059/6c193f30-2372-11e7-9424-e120c5766000.png)

2017-04-21 10:08 UTC, rmehta commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +										where lead in (select name from `tabLead` where campaign_name = %s)""",campaign)
style: can we have consistent tabbing for mulitline -- looks like hanging fruits in a tree. I think having a consistent whitespace will make the code look a lot cleaner.

2017-04-21 10:09 UTC, rmehta commented on erpnext/crm/report/lead_owner_efficiency/lead_owner_efficiency.js
> +frappe.require("assets/erpnext/js/financial_statements.js", function() {
i don't think this require is needed (if you are not using any special JS functions (?)).

2017-04-24 08:21 UTC, PawanMeh commented
Made changes requested

2017-04-24 13:49 UTC, nabinhait requested changes
@PawanMeh Please let me know if you need any kind of help.

2017-04-24 13:49 UTC, nabinhait commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +	where lead in (select name from `tabLead` where campaign_name = %s)""",campaign)
This sub-query has been called repeatedly in all the functions and those functions are called for campaign. You should create a dictionary like `{'campaign1': ['lead1', 'lead4'], 'campaign2': ['lead5', 'lead 7']}`, outside the `for` loop, then use it.

2017-04-24 13:49 UTC, nabinhait commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +	ordered_count_amount = frappe.db.sql("""select sum(base_net_amount) from `tabSales Order Item`
Do you want to show the amount without taxes? Otherwise, you should use `base_grand_total` value.

2017-04-24 13:49 UTC, nabinhait commented on erpnext/crm/report/lead_owner_efficiency/lead_owner_efficiency.py
> +	where lead in (select name from `tabLead` where lead_owner = %s)""",leadowner)
You should use the same approach as above.

2017-04-25 02:27 UTC, PawanMeh commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +	ordered_count_amount = frappe.db.sql("""select sum(base_net_amount) from `tabSales Order Item`
As these reports are for judging sales performance, taxes should not be in consideration. So I think the logic to use net amount is fine.

2017-04-25 02:31 UTC, PawanMeh commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +	where lead in (select name from `tabLead` where campaign_name = %s)""",campaign)
Executing a query in for loop repeatedly for each lead may reduce the performance benefit got from indexing using the in list. However, if you still think this needs to be changed, let me know, I can make the changes.

2017-04-25 07:24 UTC, nabinhait commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +	ordered_count_amount = frappe.db.sql("""select sum(base_net_amount) from `tabSales Order Item`
sorry! `base_net_amount` is correct

2017-04-25 07:29 UTC, nabinhait commented on erpnext/crm/report/campaign_efficiency/campaign_efficiency.py
> +	where lead in (select name from `tabLead` where campaign_name = %s)""",campaign)
You did not get my point, I am telling to do the query only once before the "for" loop. The query will give all the leads grouped by campaign. I can refactor the code if you want, after pulling your changes locally.

2017-04-25 10:35 UTC, merged