Pull non ordered material requests using supplier on purchase order
frappe/erpnext pull request #8474
Opened 2017-04-17 12:26 UTC by rohitwaghchaure

Re added the feature to pull the non ordered material requests using supplier on purchase order
Fixed https://github.com/frappe/erpnext/issues/8451

2017-04-17 14:06 UTC, nabinhait requested changes

2017-04-17 14:06 UTC, nabinhait commented on erpnext/buying/doctype/purchase_order/purchase_order.js
> +				erpnext.utils.map_current_doc({
There is already a function for this, just need to bind it to the custom button
https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order/purchase_order.js#L94

2017-04-18 05:10 UTC, rohitwaghchaure commented on erpnext/buying/doctype/purchase_order/purchase_order.js
> +				erpnext.utils.map_current_doc({
Fixed!

2017-04-18 05:43 UTC, nabinhait requested changes

2017-04-18 05:43 UTC, nabinhait commented on erpnext/buying/doctype/purchase_order/purchase_order.js
> +			source_doctype: "Supplier",
Why this? It needs `source_name` which is selected supplier in the PO, not `source_doctype`.

2017-04-18 06:24 UTC, rmehta requested changes

2017-04-18 06:24 UTC, rmehta commented on erpnext/buying/doctype/purchase_order/purchase_order.js
> +		cur_frm.add_custom_button(__('For Supplier'),
`cur_frm` !!!!

Should be a button below supplier field only shown when document is not saved (__islocal)

2017-04-18 06:36 UTC, closed without merging