[enhance] automatic batch creation, move and split
frappe/erpnext pull request #8509
Opened 2017-04-20 09:51 UTC by rmehta

2017-04-20 15:14 UTC, jof2jc commented
@rmehta, what about new incoming batches on purchase receipt/invoice and stock entry? Will the system auto-create it like serial no?

2017-04-21 04:45 UTC, nabinhait commented
@rmehta Should I check and test this PR now? Or I should wait for your pending task.

2017-04-21 12:58 UTC, nabinhait requested changes

2017-04-21 12:58 UTC, nabinhait commented on erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json
> +   "fieldname": "is_sample_item",
"is_sample_item" has been renamed to "allow_zero_valuation_rate" last week.

2017-04-22 11:50 UTC, rmehta commented on erpnext/stock/doctype/stock_entry_detail/stock_entry_detail.json
> +   "fieldname": "is_sample_item",
done! Good catch

2017-04-24 04:58 UTC, merged