Improving Item Price DocType (fixes #8456)
frappe/erpnext pull request #8511
Opened 2017-04-20 10:01 UTC by kickapoo

2017-04-20 10:03 UTC, kickapoo commented
![screenshot 2017-04-20 13 03 16](https://cloud.githubusercontent.com/assets/5064612/25225344/c36ffc3e-25c9-11e7-8957-6106ec5a8918.png)

2017-04-21 10:15 UTC, rmehta commented
- [ ] let us not keep 3 columns - we have not used it anywhere
- [ ] this should also impact selection of the price: https://github.com/frappe/erpnext/blob/8f3cc81302d9bde8aa4cbb8ff1c51074b0979fc2/erpnext/stock/get_item_details.py#L218

2017-04-21 13:35 UTC, kickapoo commented
![screenshot 2017-04-21 16 34 37](https://cloud.githubusercontent.com/assets/5064612/25279830/732ed00a-26b0-11e7-8b28-cfa055f6d6ca.png)

2017-04-21 13:37 UTC, kickapoo commented
![itemprice](https://cloud.githubusercontent.com/assets/5064612/25279854/89d7ad72-26b0-11e7-84f3-718da4b5ad7b.gif)

2017-04-25 03:51 UTC, rmehta requested changes

2017-04-25 03:51 UTC, rmehta commented on erpnext/stock/get_item_details.py
> +											  	  item_doc.name,
please use consistent indentation - not hanging in one corner

2017-04-25 03:51 UTC, rmehta commented on erpnext/stock/get_item_details.py
> +			and min_qty<=%s order by min_qty desc""",
date validation?

2017-04-25 03:51 UTC, rmehta commented on erpnext/stock/get_item_details.py
> +			and min_qty<=%s order by min_qty desc""",
Test cases missing for this - make a purchase order and see different prices are selected for different qtys

Also show UI screenshot to show it works from the UI

2017-05-11 08:05 UTC, nabinhait commented
Please resend the PR after completion, closing for now.

2017-05-11 08:05 UTC, closed without merging