Add option to skip material transfer for production orders
frappe/erpnext pull request #8515
Opened 2017-04-20 16:19 UTC by ishanloya

[Forum link](https://discuss.erpnext.com/t/production-order-with-bulk-stock-transfer/21641)

2017-04-21 10:10 UTC, rmehta commented
Screenshots and updated documentation please!

https://github.com/frappe/erpnext/wiki/Pull-Request-Guidelines

2017-04-21 10:15 UTC, ishanloya commented
I'll add screenshots and documentation. Didn't understand the status bit however.

2017-04-21 10:17 UTC, rmehta commented
If you are not tracking qty by Stock Entry, how do you complete the Production Order?

2017-04-21 10:22 UTC, ishanloya commented
The second Stock Entry (type- Manufacture) is still there, which completes the Production Order. It's only the first entry (type- Material Transfer for Manufacture) which isn't tracked against each Production Order. This is useful if a company transfers material in bulk and cannot track the transferred material for each Production Order. Maybe it will be clearer once I add the documentation.

2017-04-21 10:48 UTC, ishanloya commented
@rmehta Have updated the documentation. Thanks 🙂

2017-04-21 12:24 UTC, nabinhait requested changes

2017-04-21 12:24 UTC, nabinhait commented on erpnext/manufacturing/doctype/production_order/production_order.js
> +		} else if(this.frm.doc.skip_transfer){
else {
     var max = flt(this.frm.doc.qty) - flt(this.frm.doc.produced_qty);
}

2017-04-21 12:24 UTC, nabinhait commented on erpnext/manufacturing/doctype/production_order/production_order.js
> +			} else if(frm.doc.skip_transfer){
`else` is enough

2017-04-21 13:14 UTC, ishanloya commented
@nabinhait Thank you for reviewing

2017-04-24 05:14 UTC, nabinhait approved these changes

2017-04-24 05:14 UTC, merged