Add bank guarantee doctype with documentation
frappe/erpnext pull request #8544
Opened 2017-04-24 09:21 UTC by ishanloya

Add bank guarantee doctype to accounts module which lets a company track the bank guarantees (BG) given to customers

2017-04-24 13:55 UTC, rmehta commented
👍 please add screenshots to the documentation and also the PR too! Screenshots are very important to check if the fields have been labelled correctly etc.

2017-04-24 14:41 UTC, ishanloya commented
Ok. Thanks @rmehta 🙂. Here's a screenshot. Will update in documentation as well.
![screen shot 2017-04-24 at 8 09 18 pm](https://cloud.githubusercontent.com/assets/17540310/25342600/1a5f1e2c-292a-11e7-8656-5d2e1efc8b3e.png)

2017-04-24 14:53 UTC, ishanloya commented
Done. Thanks again.

2017-04-25 07:55 UTC, nabinhait requested changes
Add the document in config/accounts.py, to show it under Accounts module.

2017-04-25 07:55 UTC, nabinhait commented on erpnext/accounts/doctype/bank_guarantee/bank_guarantee.json
> +   "role": "System Manager",
Why system manager? I think it should permitted to Accounts User and Accounts Manager role.

2017-04-25 07:55 UTC, nabinhait commented on erpnext/accounts/doctype/bank_guarantee/bank_guarantee.json
> +   "fieldname": "account_name",
we always try to use same fieldname as doctype name for link field. In this case, would prefer `account` instead of `account_name` field.

2017-04-25 07:55 UTC, nabinhait commented on erpnext/accounts/doctype/bank_guarantee/bank_guarantee.json
> +}
Add another field for remarks/notes?

2017-04-25 08:05 UTC, ishanloya commented on erpnext/accounts/doctype/bank_guarantee/bank_guarantee.json
> +   "role": "System Manager",
Didn't realise that I hadn't changed permissions. Will keep in mind next time.

2017-04-25 08:06 UTC, ishanloya commented on erpnext/accounts/doctype/bank_guarantee/bank_guarantee.json
> +   "fieldname": "account_name",
Ok. Done.

2017-04-25 08:06 UTC, ishanloya commented on erpnext/accounts/doctype/bank_guarantee/bank_guarantee.json
> +}
Done

2017-04-25 08:42 UTC, nabinhait commented
@ishanloya Thanks for the doing requested changes so promptly. You forgot to add the document in config/accounts.py, to show it under Accounts module.

2017-04-25 09:19 UTC, ishanloya commented
Thanks @nabinhait

2017-04-25 10:38 UTC, merged