Merge the student group and student batch
frappe/erpnext pull request #8663
Opened 2017-05-03 03:58 UTC by manassolanki

- Change the student group doctype
- Delete the student batch doctype
- Patch to map the student batch data on the student group
- Changes in the linked doctype
- Cleanup for deprecated doctype

2017-05-05 12:04 UTC, nabinhait requested changes
Screenshot please

2017-05-08 12:27 UTC, nabinhait requested changes

2017-05-08 12:27 UTC, nabinhait commented on erpnext/patches/v8_0/merge_student_batch_and_student_group.py
> +		doc.save()
Why saving doc here? you can save after adding child records.

2017-05-08 12:27 UTC, nabinhait commented on erpnext/patches/v8_0/merge_student_batch_and_student_group.py
> +	student_batches = frappe.db.sql('''select name as student_group_name, student_batch_name as batch, program, academic_year, academic_term
use multilines after 80 chars

2017-05-08 12:27 UTC, nabinhait commented on erpnext/patches/v8_0/merge_student_batch_and_student_group.py
> +	# frappe.db.sql("drop table if exists `tabStudent Batch`")
remove commented lines

2017-05-08 12:27 UTC, nabinhait commented on erpnext/schools/doctype/course_schedule/course_schedule.py
> +		if self.student_group and frappe.db.get_value("Student Group", self.student_group, "group_based_on") == "Course":
Why 2 queries? It should be like this:

```
if self.student_group:
    group_based_on, course = frappe.db.get_value("Student Group", self.student_group, ["group_based_on", "course"])
    if group_based_on == "Course":
        self.course = course
```

2017-05-08 12:27 UTC, nabinhait commented on erpnext/schools/doctype/course_scheduling_tool/course_scheduling_tool.py
> +		if self.student_group and frappe.db.get_value("Student Group", self.student_group, "group_based_on") == "Course":
same as above

2017-05-08 12:41 UTC, manassolanki commented on erpnext/schools/doctype/course_schedule/course_schedule.py
> +		if self.student_group and frappe.db.get_value("Student Group", self.student_group, "group_based_on") == "Course":
Don't know this method

2017-05-09 10:02 UTC, merged