Update lead.py
frappe/erpnext pull request #8789
Opened 2017-05-12 05:25 UTC by hereabdulla

Import datetime to compare next contact date with now()

2017-05-13 04:26 UTC, rmehta commented
What is the use case?

2017-05-13 04:28 UTC, hereabdulla commented
resolves the below issue
https://discuss.erpnext.com/t/error-in-data-import-tool-while-uploading-lead/19626

2017-05-16 03:27 UTC, nabinhait requested changes

2017-05-16 03:27 UTC, nabinhait commented on erpnext/crm/doctype/lead/lead.py
> +		if self.contact_date and self.contact_date < datetime.now():
datetime.now() can create problem with user date format.

Instead use `nowdate()` function from `frappe.utils`

2017-05-19 09:45 UTC, merged