Batch entry modal
frappe/erpnext pull request #8848
Opened 2017-05-16 01:16 UTC by pratu16x7

Depends on frappe/frappe#3298

Model adds oldest batch by default, and prefills qty if less than available.
![batchmodal](https://cloud.githubusercontent.com/assets/5196925/26085568/f0c59f7a-3a02-11e7-8184-d2f3be6febf6.gif)

2017-05-24 07:57 UTC, pratu16x7 commented
Added warehouse selection:
![batch3](https://cloud.githubusercontent.com/assets/5196925/26392581/c2a8326e-4084-11e7-8439-2a95691cfc1f.gif)

2017-06-01 07:03 UTC, mbauskar requested changes
@pratu16x7,

Serial Nos can be added multiple times, also sometime after selection of serial number the serial number is added twice.

Also, on material receipt, serial number selection should be disabled

![stock-entry](https://cloud.githubusercontent.com/assets/11224291/26668090/c72c39ba-46c5-11e7-9507-9fef54b6df2b.gif)

Available Qty in batch does not reflect in child table

![batch](https://cloud.githubusercontent.com/assets/11224291/26668092/c8f31304-46c5-11e7-8bf4-619f7709794e.gif)

2017-06-07 05:17 UTC, pratu16x7 commented
- Added duplicate check for serial no (and removed serial no from material receipt)
![serial_no_check](https://user-images.githubusercontent.com/5196925/26863108-1e4d822e-4b6e-11e7-87a0-4e1a82c68e10.gif)

- fixed available qty re-update
![serial_no_check](https://user-images.githubusercontent.com/5196925/26863179-93e15d76-4b6e-11e7-98db-e3d10ca80428.gif)

2017-06-16 09:47 UTC, rmehta requested changes

2017-06-16 09:47 UTC, rmehta commented on erpnext/stock/doctype/stock_entry/stock_entry.py
> +			print type(float(item.qty))
print.....

2017-06-16 09:47 UTC, closed without merging