Issue 8842
frappe/erpnext pull request #8869
Opened 2017-05-16 13:21 UTC by tundebabzy

Fixes #8842. I also added a test for the issue and `encode_company_abbr`

2017-05-17 14:04 UTC, nabinhait requested changes

2017-05-17 14:04 UTC, nabinhait commented on requirements.txt
> +six
why another library? why not using python's inbuilt `range` or `xrange`?

2017-05-17 14:08 UTC, tundebabzy commented
I forgot to remove that while working on python 3 migration. I'm removing it now

2017-05-17 17:14 UTC, tundebabzy commented
I feel it's important to write python 3 compatible code since python 3 compatibility is in view. The swap of MySQLdb with mysqlclient passes all tests. It's much easier to maintain python 3 support with six

2017-05-18 07:07 UTC, rmehta commented
@tundebabzy since you have added six in frappe, you don't need to add it here again.

2017-05-18 07:10 UTC, rmehta requested changes

2017-05-18 07:10 UTC, rmehta commented on erpnext/tests/test_init.py
> +		    " - {a}".format(a=abbr), "ERPNext - Foundation - India",
whitespace (?)

2017-05-18 07:10 UTC, rmehta commented on erpnext/tests/test_init.py
> +			    "{enc} is not same as {exp}".format(enc=enc_name, exp=expected_names[i])
whitespace?

2017-05-18 08:30 UTC, tundebabzy commented
I'll reduce the whitespace

2017-05-19 06:12 UTC, merged