[Fix] Orders not creating from the POS for new customer if customer name is based on naming series
frappe/erpnext pull request #8933
Opened 2017-05-19 09:07 UTC by rohitwaghchaure

2017-05-24 12:11 UTC, nabinhait commented
@mbauskar Can you test this?

2017-05-25 06:38 UTC, mbauskar approved these changes

2017-05-25 08:34 UTC, mbauskar requested changes
while syncing Sales Invoice the same customer is synced multiple times.

2017-05-31 10:45 UTC, rohitwaghchaure commented
Fixed!

2017-05-31 13:02 UTC, mbauskar approved these changes

2017-06-02 07:41 UTC, nabinhait requested changes

2017-06-02 07:41 UTC, nabinhait commented on erpnext/selling/doctype/customer/customer.json
> +   "no_copy": 0,
no_copy=1

2017-06-02 07:41 UTC, nabinhait commented on erpnext/selling/doctype/customer/customer.json
> +   "print_hide": 0,
print_hide=1

2017-06-02 07:41 UTC, nabinhait commented on erpnext/selling/doctype/customer/customer.json
> +   "hidden": 0,
hidden=1

2017-06-05 05:58 UTC, mbauskar approved these changes

2017-06-07 06:34 UTC, merged