[minor] added filter for batch no field in purchase transaction
frappe/erpnext pull request #9038
Opened 2017-05-26 08:25 UTC by mbauskar

2017-05-30 10:03 UTC, nabinhait requested changes

2017-05-30 10:03 UTC, nabinhait commented on erpnext/public/js/controllers/transaction.js
> +				query : "erpnext.controllers.queries.get_batch_no",
`get_batch_no`  only returns batches if the batch has qty. But in Purchase receipt, we need to allow all batches, even if it has no qty.

https://github.com/frappe/erpnext/blob/master/erpnext/controllers/queries.py#L267

2017-06-01 12:30 UTC, mbauskar commented on erpnext/public/js/controllers/transaction.js
> +				query : "erpnext.controllers.queries.get_batch_no",
@nabinhait,

filtered the batch no based on item_code if doctype is Purchase Receipt

2017-06-02 08:59 UTC, nabinhait requested changes

2017-06-02 08:59 UTC, nabinhait commented on erpnext/public/js/controllers/transaction.js
> +		} else if (doc.doctype == "Purchase Receipt") {
also applicable to Purchase Invoice with update_stock checked.

2017-06-02 09:50 UTC, nabinhait approved these changes

2017-06-02 11:58 UTC, merged