updating serial no status from scheduler
frappe/erpnext pull request #9066
Opened 2017-05-29 08:02 UTC by manassolanki

#9061

2017-05-29 08:06 UTC, nabinhait requested changes

2017-05-29 08:06 UTC, nabinhait commented on erpnext/stock/doctype/serial_no/serial_no.py
> +	last_date = frappe.utils.add_days(frappe.utils.nowdate(), -1)
Why finding last_date? Instead use `<` sign in query

2017-05-29 09:13 UTC, manassolanki commented on erpnext/stock/doctype/serial_no/serial_no.py
> +	last_date = frappe.utils.add_days(frappe.utils.nowdate(), -1)
In the last logic, updating docs having the last date as expiry. Changed now.

2017-05-30 10:05 UTC, nabinhait approved these changes

2017-05-30 10:05 UTC, merged