Arabic language shows Errors onSubmit  in maintenance_schedule
frappe/erpnext pull request #9082
Opened 2017-05-30 09:44 UTC by ahmadRagheb

when trying to submit using arabic language error show up , 
i replace this way of formating arguments 
				description = frappe._("Reference: %s, Item Code: %s and Customer: %s") % \
					(self.name, d.item_code, self.customer)
to new one  :description = frappe._("Reference: %s, Item Code: %s and Customer: %s").format(self.name, d.item_code, self.customer)

and it solve the problem on my local

2017-05-30 09:46 UTC, ahmadRagheb commented
![error333](https://cloud.githubusercontent.com/assets/23044675/26577696/efeb0d86-4535-11e7-8852-bf47df97d579.png)
screenshot shows the error on my local

2017-05-30 09:46 UTC, ahmadRagheb commented
screenshot show the error on my local 
![eroror33333](https://cloud.githubusercontent.com/assets/23044675/26577736/0bb4d542-4536-11e7-8ccb-b0c08677e108.png)

2017-05-31 05:45 UTC, mbauskar requested changes

2017-05-31 05:45 UTC, mbauskar commented on erpnext/maintenance/doctype/maintenance_schedule/maintenance_schedule.py
> +				description = frappe._("Reference: %s, Item Code: %s and Customer: %s").format(self.name, d.item_code, self.customer)
frappe._("Reference: %s, Item Code: %s and Customer: %s").format(self.name, d.item_code, self.customer) should be frappe._("Reference: {0}, Item Code: {1} and Customer: {2}").format(self.name, d.item_code, self.customer)

2017-05-31 08:15 UTC, ahmadRagheb commented
@mbauskar   i change it

2017-05-31 09:45 UTC, mbauskar approved these changes

2017-06-01 13:36 UTC, merged