[Fix] Fieldtype in Serial No Rename
frappe/erpnext pull request #9103
Opened 2017-05-31 13:51 UTC by akshay83

In some DocTypes fieldtype for serial_no is "Small Text", in some it is "Text"

2017-06-01 12:41 UTC, mbauskar requested changes

2017-06-01 12:41 UTC, mbauskar commented on erpnext/stock/doctype/serial_no/serial_no.py
> +			where fieldname='serial_no' and fieldtype like '%%Text%%'"""):
@akshay83, can you add the `fieldtype in ('Text', 'Small Text')` condition instead?

2017-06-02 05:44 UTC, mbauskar commented
@akshay83, thanks for the PR, can you send the PR to hotfix branch ??

2017-06-02 08:25 UTC, akshay83 commented
Ok

2017-06-02 08:25 UTC, closed without merging