Add script report and print format for Assessment Result
frappe/erpnext pull request #9162
Opened 2017-06-06 14:17 UTC by crossxcell99

[Resolved merge conflicts from #9148 ]

Added the following fields to some of the doctypes:
In Assessment Result: Link for Academic term, Academic year and course, so the results can be filtered in the report (script report name = ResultsReport).
In Assessment Plan: Check box for multiple courses, a child table (doctype: Courses Table) and a button for the getting the courses automatically from program linked in student group (if possible).

Used a workaround for getting column names and removing extra fields ("_id" and "id") for the print format (resultsreport.html)

![resultsreport1](https://cloud.githubusercontent.com/assets/23179734/26833511/94644afa-4aca-11e7-9bcf-b0677dbd0855.png)
This report lists all the student results including the assessment criterias

![resultprint](https://cloud.githubusercontent.com/assets/23179734/26833512/948fcb9e-4aca-11e7-8bbe-8895bb26169b.png)
This is the print format of the results report

**Note**: This PR is an update on the suggestion I made in #8737

2017-06-07 11:20 UTC, manassolanki commented
Hi @crossxcell99 ,
Please squash your commits if possible and rebase your branch from upstream develop.
You don't need to merge develop branch into your branch.

2017-06-07 13:34 UTC, crossxcell99 commented
Commits have been squashed into one and branch rebased from upstream develop 
@manassolanki

2017-06-19 12:40 UTC, mbauskar requested changes
Also please remove the unnecessary whitespaces

2017-06-19 12:40 UTC, mbauskar commented on erpnext/schools/api.py
> +		results_obj.append({
indentation?

2017-06-19 12:40 UTC, mbauskar commented on erpnext/schools/doctype/assessment_plan/assessment_plan.js
> +                console.log(r.message);
remove console.log

2017-06-19 12:41 UTC, mbauskar commented
@crossxcell99,

Thanks for the PR, Please check and fix the Codacy issues, Closing this PR for now
Push the changes and reopen the PR

2017-06-19 12:41 UTC, closed without merging