Payment Entry - Latest Exchange Rate not fetched
frappe/erpnext pull request #9193
Opened 2017-06-08 20:40 UTC by tundebabzy

This fixes #8919, #9180

These two issues arise from the fact that "Pay" payment entries retrieve the average exchange rate used for transactions to the specified bank account. The side effect of this is that ERPNext can present different exchange rates for two different accounts with the same currency (#8919). Also, ERPNext will not be able to provide any exchange rate if the bank account balance is zero (#9180).

Technically, [IAS 21](https://www.iasplus.com/en/standards/ias/ias21#link8) does not allow for averaging exchange rates. Rather each transaction should be converted at the closing exchange rate on the day the transaction took place. Thus, the exchange rate automatically drawn should be the last saved exchange rate.

2017-06-09 06:08 UTC, tundebabzy commented
Here's the difference

### Before
![peek 2017-06-08 16-20](https://user-images.githubusercontent.com/818803/26963002-056ce766-4ce2-11e7-971b-c2055e4523f3.gif)

### After
![peek 2017-06-08 16-35](https://user-images.githubusercontent.com/818803/26963010-15d5da5e-4ce2-11e7-9e14-18c0bbfb0074.gif)

2017-06-14 10:04 UTC, nabinhait requested changes
The same issue is there in Journal Entry when bank account is credited, it takes average there as well.

2017-06-14 12:07 UTC, nabinhait requested changes

2017-06-14 12:07 UTC, nabinhait commented on erpnext/accounts/doctype/journal_entry/journal_entry.py
> +		elif account_currency and posting_date:
Why removed `not exchange_rate`? User will not be able to set exchange_rate manually.

2017-06-14 12:14 UTC, tundebabzy commented on erpnext/accounts/doctype/journal_entry/journal_entry.py
> +		elif account_currency and posting_date:
i'll ammend the commit

2017-06-15 07:04 UTC, merged

2017-06-16 05:09 UTC, addymuliady commented
Greetings @nabinhait 

Is it possible to merge this into hotfix as it is critical to my accounting. I cannot overwrite the average exchange rate and am stuck with my work until this fix is merged to master.

For your kind perusal please. Thanks!