Patch for the PR 8754, fixes #9011
frappe/erpnext pull request #9410
Opened 2017-06-21 11:34 UTC by manassolanki

patch for removing the address field from the company and creating an address doc.

2017-06-21 15:45 UTC, mbauskar requested changes

2017-06-21 15:45 UTC, mbauskar commented on erpnext/patches/v8_0/create_address_doc_from_address_field_in_company.py
> +	company_list = frappe.db.sql('''select name, address from `tabCompany` where address is not null''', as_dict=1)
@manassolanki,

Please check if the address column is available or not then use `frappe.db.sql`

2017-06-21 15:46 UTC, mbauskar commented
please push the changes and reopen the PR

2017-07-10 13:33 UTC, nabinhait commented
Create the address record only if there is already no address record for the same company.

To check address column in the table, you can use `if 'address' in frappe.db.get_table_columns('Company')`.

2017-07-11 05:42 UTC, manassolanki commented
@nabinhait ,
This is the patch for the PR https://github.com/frappe/erpnext/pull/8754

2017-07-11 06:05 UTC, merged