Setup wizard refactor
frappe/erpnext pull request #9441
Opened 2017-06-23 03:32 UTC by pratu16x7

Depends on frappe/frappe#3548

2017-06-23 14:00 UTC, mbauskar requested changes

2017-06-23 14:00 UTC, mbauskar commented on erpnext/public/js/setup_wizard.js
> +				if (year_start_date > get_today()) {
`get_today()` deprecated use `frappe.datetime.get_today()`

2017-06-23 14:01 UTC, mbauskar commented
push the changes and reopen the PR

2017-06-28 05:05 UTC, pratu16x7 commented
Frappe header:

![screen shot 2017-06-28 at 9 47 57 am](https://user-images.githubusercontent.com/5196925/27621308-83a8cd1a-5bed-11e7-937c-a6676b4da9b2.png)

2017-07-03 07:39 UTC, mbauskar commented
@pratu16x7,

Need to set the correct fiscal year for country ..

<img width="530" alt="screen shot 2017-07-03 at 12 37 55 pm" src="https://user-images.githubusercontent.com/11224291/27782597-c01545e2-5ff0-11e7-96e3-903570740f12.png">

2017-07-03 12:53 UTC, merged