Can't set Start and End Dates in Salary Slip - 1
frappe/erpnext pull request #9559
Opened 2017-06-30 22:31 UTC by tundebabzy

Reference - #9530, #9513 

Here is the first PR that creates Doctypes towards making creating Salary Slips and Process Payroll more flexible as well as fixing bugs like #9513 - Payroll Cycle, Payroll Period and Payroll Cycle Designation. Both Payroll Period and Payroll Cycle Designation are child tables of Payroll Cycle. I also added a test case. 

The target is that for each employee, ERPNext would check the Payment Cycle attached to the employee's designation to get pay period information needed for payroll runs.

2017-07-01 06:41 UTC, tundebabzy commented
### Screenccast

![peek 2017-06-30 23-33](https://user-images.githubusercontent.com/818803/27759760-9161bc6a-5e30-11e7-85d9-7de85bbf274a.gif)

2017-07-01 12:50 UTC, tundebabzy commented
### Completed task 4
![screenshot from 2017-07-01 13-43-40](https://user-images.githubusercontent.com/818803/27762155-f828d018-5e63-11e7-824d-c452c71796e3.png)

2017-07-03 09:56 UTC, rmehta requested changes

2017-07-03 09:56 UTC, rmehta commented on erpnext/hr/doctype/payroll_cycle/test_payroll_cycle.py
> +def get_document(dt, designatione):
put this in `def setUp` method of the test case

2017-07-03 09:56 UTC, rmehta commented on erpnext/hr/doctype/payroll_cycle/test_payroll_cycle.py
> +		payroll_cycle = frappe.get_doc(cycle_dict)
just add the dict here. its much more readable!

2017-07-06 11:27 UTC, tundebabzy commented
Trying another approach

2017-07-06 11:27 UTC, closed without merging

2017-08-24 09:09 UTC, magic-overflow commented
Have you been working on another approach?