Sales Goal by Company
frappe/erpnext pull request #9723
Opened 2017-07-07 18:32 UTC by pratu16x7

![screen shot 2017-07-07 at 11 50 51 pm](https://user-images.githubusercontent.com/5196925/27971420-46fdc9c6-6370-11e7-9cf6-0baf6d341d3d.png)

------------------------------------------------------
Settable in Company:
![screen shot 2017-07-07 at 11 51 16 pm](https://user-images.githubusercontent.com/5196925/27971435-5ba90660-6370-11e7-8633-7505081b4158.png)

------------------------------------------------------
Calculated by Invoices:
![screen shot 2017-07-07 at 11 53 12 pm](https://user-images.githubusercontent.com/5196925/27971482-77fa90c2-6370-11e7-8186-43691cfd89be.png)

------------------------------------------------------
Asked in Setup Wizard:
![screen shot 2017-07-07 at 10 50 35 pm](https://user-images.githubusercontent.com/5196925/27971496-88f187a0-6370-11e7-804b-0e310e24f831.png)

2017-07-10 06:29 UTC, rmehta commented
- [ ] Show line graph for last 12 months... daily sales makes no sense.
- [ ] keep consistent font size...

2017-07-12 05:48 UTC, pratu16x7 commented
![screen shot 2017-07-12 at 10 54 35 am](https://user-images.githubusercontent.com/5196925/28103468-82fc426e-66f3-11e7-99a6-5dff38b3dc9e.png)

Graph is shown regardless of goal setting; goal stats will be set to zero(no field value) by default.
Is a patch required to set a default goal based on past data?

2017-07-13 05:29 UTC, pratu16x7 commented
Travis fail due to frappe dependency

2017-07-14 05:18 UTC, rmehta requested changes

2017-07-14 05:18 UTC, rmehta commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +		update_company_monthly_sales(self.company)
don't call this after every submit - this will be expensive for large data steps... let targets be calculated only by the scheduler.

2017-07-14 05:18 UTC, rmehta commented on erpnext/setup/doctype/company/company_dashboard.py
> +		'graph_method': "frappe.utils.goal.get_monthly_goal_graph_data",
cache this!

2017-07-14 11:21 UTC, mbauskar requested changes

2017-07-14 11:21 UTC, mbauskar commented on erpnext/patches/v8_3/update_company_total_sales.py
> +	companies = [d['name'] for d in frappe.get_list("Company")]
@pratu16x7,

Need to reload the company doctype as `update_company_monthly_sales` update's the `total_monthly_sales` field in company

Also add the patch entry in patches.txt

2017-07-14 11:21 UTC, mbauskar commented on erpnext/setup/doctype/company/company.py
> +		filter_str = 'company = "_Test Company" and status != "Draft"'
_Test Company?

2017-07-14 11:21 UTC, mbauskar commented on erpnext/setup/doctype/company/company.py
> +		frappe.cache().hget("month_to_value_dict:Sales Invoice", "Company:" + company, month_to_value_dict)
hget is use to get the cache data it should be hset

2017-07-14 11:29 UTC, mbauskar requested changes

2017-07-14 11:29 UTC, mbauskar commented on erpnext/accounts/doctype/sales_invoice/sales_invoice.py
> +	''').format(monthly_total, company))
escape company name using `frappe.db.escape`

2017-07-17 07:18 UTC, pratu16x7 commented
Travis fail due to frappe dependency

2017-07-17 07:39 UTC, mbauskar approved these changes

2017-07-17 11:34 UTC, pratu16x7 commented
Now with frappe/frappe#3711

2017-07-18 04:27 UTC, pratu16x7 commented
Another fix: frappe/frappe#3720

2017-07-18 05:05 UTC, merged

2017-08-11 11:43 UTC, vladucoju commented
Hi, i like this feature. I would suggest to add fields for month goals for separate insert. Goals for each month doesn't have same value. Or maybe last year sales line to be option on check box. I also must say that i don't find graphs usable in ERPNEXT because we don't have option to have them on report. The good option will be when we print in PDF to have check option to include chart, like we have for print header, but that is not part of this topic.