Added Project Type new doctype to be added as link field for Project Type field in project instead of select field
frappe/erpnext pull request #9929
Opened 2017-07-18 12:13 UTC by KanchanChauhan

- patch to add select items in project_type field as "Project Type"

<img width="672" alt="screen shot 2017-07-18 at 5 41 54 pm" src="https://user-images.githubusercontent.com/16913064/28316416-6defe294-6be0-11e7-805e-c6b2ef6093e6.png">

Fixed https://github.com/frappe/frappe/issues/3691

2017-07-19 13:21 UTC, mbauskar commented
@KanchanChauhan,

Thanks for the PR,

Can you add the fixtures for project type for the new site the "External", "Internal", "Other" should be already created automatically (please check the install_fixture.py)

Also, project type **External** is used in Sales Order and email digest and user should not be able to delete **External** project type.

Closing the PR for now, You can reopen the PR once the changes are completed

2017-07-24 11:33 UTC, KanchanChauhan commented
@mbauskar Done. Can you check now please.

2017-07-26 11:39 UTC, mbauskar requested changes
Please see my comments,

Needs rebase !!

2017-07-26 11:39 UTC, mbauskar commented on erpnext/patches/v8_5/update_existing_data_in_project_type.py
> +	frappe.reload_doctype("Project Type")
use `frappe.reload_doc("projects", "doctype", "project_type")` instead

2017-07-26 11:39 UTC, mbauskar commented on erpnext/projects/doctype/project/project.json
> +   "options": "Project Type",
Please also update the modified date for project doctype

2017-07-26 11:59 UTC, mbauskar approved these changes

2017-07-26 12:25 UTC, merged